const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const origen='/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html',src=fs.readFileSync(origen,'utf8');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'ro270-'));fs.chmodSync(temp,0o700);let n=0;const check=(t,f)=>{f();n++;console.log('PASS',t);};
function funcion(nombre){const start=src.indexOf('function '+nombre+'(');assert.ok(start>=0,'Función original '+nombre);const fin=src.slice(start+1).search(/^function \w+\(/m);return fin<0?src.slice(start):src.slice(start,start+1+fin);}
function headers(nombre){return [...funcion(nombre).matchAll(/<th(?:\s[^>]*)?>([^<]*)<\/th>/g)].map(m=>m[1]);}
fs.writeFileSync(path.join(temp,'componentes.mjs'),`export class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.children=[];this.events=a.on||{};this.append(...xs);}addEventListener(k,v){this.events[k]=v;}get isConnected(){return this.connected===true||!!this.parent?.isConnected;}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x);}}replaceChildren(...xs){this.children.forEach(x=>{if(x instanceof N)x.parent=null;});this.children=[];this.append(...xs);}}export const h=(t,a,...xs)=>new N(t,a,xs);export const chipEstado=(e,v)=>h('span',{'data-estado':e},v);`);
fs.writeFileSync(path.join(temp,'accounts340.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_bandeja_accounts_340.js'),'utf8'));
fs.writeFileSync(path.join(temp,'meta285.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_meta_semantica_285.js'),'utf8'));
fs.writeFileSync(path.join(temp,'bandeja.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_operaciones_bandeja_270.js'),'utf8').replace("'../componentes.js'","'./componentes.mjs'").replace("'./_operaciones_feedback_273.js'","'./feedback.mjs'").replace("'./_meta_semantica_285.js'","'./meta285.mjs'").replace("'./_pedidos_account_local.js'","'./pedidos294.mjs'").replace("'./_bandeja_accounts_340.js'","'./accounts340.mjs'"));
fs.writeFileSync(path.join(temp,'mensaje330.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_mensaje_incidente_330.js'),'utf8'));
fs.writeFileSync(path.join(temp,'pedidos294.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_pedidos_account_local.js'),'utf8').replace("'../componentes.js'","'./componentes.mjs'").replace("'./_mensaje_incidente_330.js'","'./mensaje330.mjs'"));
fs.writeFileSync(path.join(temp,'feedback.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_operaciones_feedback_273.js'),'utf8').replace("'../componentes.js'","'./componentes.mjs'"));
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[];const text=n=>n&&typeof n==='object'?n.textContent??n.children.map(text).join(' '):String(n??'');
(async()=>{try{
 const {h}=await import('file://'+path.join(temp,'componentes.mjs')),M=await import('file://'+path.join(temp,'bandeja.mjs')),A=await import('file://'+path.join(temp,'accounts340.mjs'));
 const row=(pid,confianza='confirmada')=>({persona_id:pid,silla:'account',principal:true,confianza,desde:'2026-09-01',hasta:null});
 const persona=id=>({id,nombre:id,estado:'activo',puestos:['account']});
 const ctx=()=>({servidor:true,hoy:'2026-10-03',real:{id:'ops',estado:'activo',puestos:['operaciones']},persona:{id:'ops',estado:'activo',puestos:['operaciones']},clientesVisibles:[{id:'a',nombre:'Cliente A',detalle:true,activo_confirmado:true,equipo:{account:[row('acc-a')]}},{id:'b',nombre:'Cliente B',detalle:true,activo_confirmado:true,equipo:{account:[row('acc-b','alta')]}},{id:'c',nombre:'Cliente C',detalle:true,activo_confirmado:true,equipo:{account:[]}}],datos:{personas:[persona('acc-a'),persona('acc-b')],asignaciones:[]},veModulo:m=>m!=='captacion',ver:()=>({ok:true}),vigente:()=>true,nombre:id=>id,api:async()=>({}),datosModulo:async()=>B});
 const B={generado:'2026-10-03 03:26',fuentes:{desk:{hora:'2026-10-03 03:26',estado:'bien'}},correos:[{id:'r-a',cliente_id:'a',numero:'RA',horas:30,dias_laborables:2},{id:'h-a',cliente_id:'a',numero:'HA',horas:400,dias_laborables:30},{id:'r-b',cliente_id:'b',numero:'RB',horas:50,dias_laborables:3},{id:'r-c',cliente_id:'c',numero:'RC',horas:28,dias_laborables:1}],llamadas:[{id:'l-a',cliente_id:'a',ultima:'2026-10-02 08:00',dias_laborables:1,llamadas:1},{id:'l-b',cliente_id:'b',ultima:'2026-10-02 08:00',dias_laborables:1,llamadas:2}],triaje:[{id:'tr-a',cliente_id:'a',numero:'TR_A',propuesta:'dudoso'},{id:'tr-b',cliente_id:'b',numero:'TR_B',propuesta:'dudoso'},{id:'tr-sin',numero:'TR_SIN',propuesta:'sin_cliente'}]};
 check('original selector y grupos accounts presentes',()=>{const original=funcion('vBandeja');assert.match(original,/bandF.acc/);assert.match(original,/grupo-acc/);assert.match(original,/<label for="b-acc">Account/);});
 check('catálogo actual núcleo explícito con confianza separada',()=>{const d=A.catalogoAccounts340(ctx(),['a','b','c']);assert.equal(d.mapa.a.account_id,'acc-a');assert.equal(d.mapa.a.confirmado,true);assert.equal(d.mapa.b.confirmado,false);assert.equal(d.mapa.c.account_id,null);});
 check('cruce misma asignación de dos fuentes no duplica owner',()=>{const c=ctx();c.datos.asignaciones=[{...row('acc-a'),cliente_id:'a'}];assert.equal(A.catalogoAccounts340(c,['a']).mapa.a.account_id,'acc-a');});
 for(const [name,fn]of [['duplicados internos',c=>c.clientesVisibles[0].equipo.account.push(row('acc-a'))],['conflicto fuentes',c=>c.datos.asignaciones=[{...row('acc-b'),cliente_id:'a'}]],['persona duplicada',c=>c.datos.personas.push(persona('acc-a'))],['persona inactiva',c=>c.datos.personas[0].estado='baja'],['fecha futura',c=>c.clientesVisibles[0].equipo.account[0].desde='2026-10-04'],['duda/suplencia',c=>c.clientesVisibles[0].equipo.account[0].suplencia=true],['confianza baja',c=>c.clientesVisibles[0].equipo.account[0].confianza='baja']])check(name,()=>{const c=ctx();fn(c);assert.equal(A.catalogoAccounts340(c,['a']).mapa.a.account_id,null);});
 check('sin account específico no incorpora sin cliente',()=>{const d=A.catalogoAccounts340(ctx(),['a','c']);const xs=A.filtrarAccount340([...B.correos,{id:'sin'}],d,A.SIN_ACCOUNT340);assert.deepEqual(xs.map(x=>x.id),['r-b','r-c']);assert.equal(A.filtrarAccount340([{id:'sin'}],d,'').length,1);});
 const c=ctx(),cont=h('main',{});cont.connected=true;await M.renderBandeja270(cont,c);
 const selector=()=>walk(cont).find(x=>x.tag==='select'&&x.attrs['aria-label']==='Account');
 check('render selector accesible y conteos sin ocultar histórico',()=>{assert.ok(selector());assert.match(text(cont),/4 correos observados con el filtro · 3 recientes · 1 históricos/);assert.match(text(cont),/asignación por confirmar/);assert.match(text(cont),/TR_SIN/);});
 selector().events.change({target:{value:'acc-a'}});
 check('selección filtra reciente/histórico/llamadas/triaje por cliente',()=>{assert.match(text(cont),/2 correos observados con el filtro · 1 recientes · 1 históricos/);assert.match(text(cont),/HA/);assert.match(text(cont),/TR_A/);assert.doesNotMatch(text(cont),/TR_B|TR_SIN/);const links=walk(cont).filter(x=>x.tag==='a').map(x=>x.attrs.href);const llamadas=walk(cont).find(x=>x.tag==='section'&&text(x).startsWith('Llamadas de clientes'));assert.match(text(llamadas),/1 · 2026-10-02/);assert.doesNotMatch(text(llamadas),/2 · 2026-10-02/);assert(!links.includes('#/bandeja/r-b'));});
 selector().events.change({target:{value:A.SIN_ACCOUNT340}});
 check('sin asignación no elimina filas sin owner',()=>{assert.match(text(cont),/1 correos observados con el filtro/);assert.match(text(cont),/RC/);assert.doesNotMatch(text(cont),/TR_SIN/);});
 selector().events.change({target:{value:''}});
 check('volver todos recupera inventario observado',()=>{assert.match(text(cont),/4 correos observados con el filtro/);assert.match(text(cont),/TR_SIN/);});
 c.datos.personas[0].estado='baja';selector().events.change({target:{value:'acc-a'}});
 check('revocación de catálogo limpia vista previa',()=>assert.equal(walk(cont).filter(x=>x.tag==='table').length,0));
 let resolve;const deferred=new Promise(r=>resolve=r),loading=h('main',{});loading.connected=true;const cc=ctx();cc.datosModulo=()=>deferred;const request=M.renderBandeja270(loading,cc);cc.ver=()=>({ok:false});resolve(B);await request;
 check('cambio grant durante GET no expone grupos',()=>assert.equal(walk(loading).filter(x=>x.tag==='table').length,0));
 console.log(n+' grupos340 PASS modelo+render actual');
 }finally{fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
