const fs=require('fs'),vm=require('vm'),assert=require('assert');const s={Intl,Date,Number,Array,JSON,Set,Object};vm.createContext(s);vm.runInContext('(function(){'+fs.readFileSync(__dirname+'/modulos/_metricas_campanas_448.js','utf8').replace(/export /g,'')+';globalThis.metricasCampanas448=metricasCampanas448;})();',s);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_meta_diaria_386.js','utf8').replace(/^import .*;$/m,'').replace(/export /g,''),s);
const actor={id:'p',estado:'activo',activo:true,puestos:['trafficker']};const client={id:'ok',activo_confirmado:true,detalle:true};const ctx=()=>({servidor:true,vigente:()=>true,real:{...actor},persona:{...actor},datos:{personas:[{...actor}]},clientes:[{...client}],clientesVisibles:[{...client}],veModulo:()=>true,ver:()=>({ok:true})});
const dto={version:'385.1',cliente_id:'ok',estado:'copia_observada',medicion:{version:'384.1',cliente_id:'ok',nivel:'campaign_diario',cobertura:'filas_recibidas_no_censo',periodo:{desde:'2026-10-01',hasta:'2026-10-01',zona:'America/Los_Angeles'},paginas_completas:true,errores_tipados:[],contactos_unicos:null,leads_calificados:null,ventas:null,fecha_fuente:'2026-10-03T10:00:00+00:00',gasto_observado:2,moneda:'EUR',dias:[{dia:'2026-10-01',filas_recibidas:1,leads_observados:0,gasto_observado:2,impresiones_observadas:5,clics_observados:0}]}};
assert(s.ambitoMeta386(ctx(),'ok'));for(const change of [c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push({...client}),c=>c.clientes=[],c=>c.veModulo=()=>false,c=>c.datos.personas[0].puestos=[],c=>c.ver=()=>({ok:false})]){let c=ctx();change(c);assert.equal(s.ambitoMeta386(c,'ok'),null);}
assert.equal(s.modeloMeta386(dto,'ok').rows[0].leads,0);assert.equal(s.modeloMeta386(dto,'otro'),null);
let d=JSON.parse(JSON.stringify(dto));delete d.medicion.gasto_observado;delete d.medicion.moneda;delete d.medicion.dias[0].gasto_observado;assert.equal(s.modeloMeta386(d,'ok').gasto,false);
d=JSON.parse(JSON.stringify(dto));d.medicion.dias[0].filas_recibidas=0;assert.equal(s.modeloMeta386(d,'ok'),null);
d=JSON.parse(JSON.stringify(dto));d.medicion.secret='PRIVATE';d.medicion.dias[0].url='PRIVATE';assert(!JSON.stringify(s.modeloMeta386(d,'ok')).includes('PRIVATE'));
console.log('386 modelos/scope PASS: ACT canónico, unknown, cero explícito, inversión ausente y whitelist. UI real pendiente.');
