const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const src=fs.readFileSync(__dirname+'/modulos/horas.js','utf8').replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];\s*/g,'').replace(/export function/g,'function').replace('export async function','async function').replace('export default {','const modulo = {');
class El{constructor(tag,attrs={},...xs){this.tag=tag;this.attrs=attrs;this.style=attrs.style||{};this.children=[];this.isConnected=true;this.append(...xs)}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){if(typeof x==='object')x.parentNode=this;this.children.push(x)}}replaceChildren(...xs){this.children=[];this.append(...xs)}querySelectorAll(){return[]}addEventListener(){}getAttribute(k){return this.attrs[k]}}
const h=(...a)=>new El(...a);let tableConfig,folded=false;
const sandbox={console,Date,Intl,URL,Map,Set,S:[0,4,8,12,16,20,24],location:{hash:'#/horas'},MutationObserver:class{observe(){}},h,
fmt:{num:String},icono:x=>h('i',{},x),panel:(a,...xs)=>h('section',{},a.titulo,a.sub,...xs),vacio:x=>h('vacio',{},x.titulo),vacioLinea:x=>h('vacio',{},x),avisoParcial:x=>h('aviso',{},x),frescura:()=>null,
plegarConsejo:()=>{folded=true},lineaFuentes:()=>null,zonaTxt:x=>x||'Madrid',esMovil:()=>false,estadoTexto:(a,b)=>h('span',{},b),iniciales:x=>x,
chipsFiltro:o=>{const n=h('chips');n.valor=()=>o.valor||'';return n},tablaDensa:o=>{tableConfig=o;return h('table',{},o.filas.map(r=>h('tr',{},r.nombre)))},
pestanas:o=>{const n=h('tabs'),z=h('zona');o.pintar(o.activa||o.pestanas[0].id,z);n.append(z);n.activa=()=>o.activa||o.pestanas[0].id;n.elegir=id=>o.pintar(id,z);return n}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_horas_diarias_238.js','utf8').replace(/export function/g,'function'),sandbox);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_control_periodos_227.js','utf8').replace(/export function/g,'function'),sandbox);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_equipo_horas_254.js','utf8').replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];\s*/g,'').replace(/export function/g,'function'),sandbox);vm.runInContext(src+'\nglobalThis.modulo=modulo;',sandbox);
const D={ayer:'2026-10-02',hoy:'2026-10-03',meses:['2026-09','2026-10'],raras:[],fuentes:{horas:{hora:'2026-10-03 02:56'}},personas:['ana','bea'].map(id=>({persona_id:id,nombre:id,estado_persona:'activo',equipo:'Accounts',grupo:'Accounts',ayer:8,semana:40,meses:[{mes:'2026-09',imputadas:120,esperadas:128}]}))};
(async()=>{const root=h('main');const ctx={persona:{id:'ana',puestos:['operaciones']},real:{id:'ana'},datos:{personas:[]},soloLectura:false,servidor:false,hoy:'2026-10-03',params:[],ver:()=>({ok:true}),vigente:()=>true,titulo(){},indicador:()=>null,datosModulo:async()=>D};await sandbox.modulo.render(root,ctx);assert(folded);assert.equal(tableConfig.filas.length,2);assert.equal(tableConfig.filas[0].disponibilidad,null);const find=n=>n?.tag==='tabs'||(n?.children||[]).some(find);assert(find(root));console.log('182 PASS: render real Horas con dos personas y tabla inicial, sin TDZ ni capacidad inventada.');})().catch(e=>{console.error(e);process.exitCode=1});
