const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('modulos/panel_direccion.js','utf8'),components=fs.readFileSync('componentes.js','utf8');
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.a=a;this.style={...(a.style||{})};this.children=[];this.isConnected=true;this.append(...kids)}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){if(x instanceof N&&x.parent){x.parent.children=x.parent.children.filter(y=>y!==x)}if(x instanceof N)x.parent=this;this.children.push(x)}}querySelector(q){const c=q.split('.').pop();return this.children.find(n=>n instanceof N&&(n.a.class||'').split(' ').includes(c))||null}get textContent(){return this.children.map(n=>n instanceof N?n.textContent:String(n)).join(' ')}all(){return[this,...this.children.flatMap(n=>n instanceof N?n.all():[])]}}
const h=(t,a,...k)=>new N(t,a,k);const calls=[];const ctx={h,fmt:{num:(v,d=0)=>Number(v).toFixed(d)},_num:v=>typeof v==='number'&&Number.isFinite(v)?v:null,variacion:(a,b)=>b?100*(a-b)/Math.abs(b):null,limpiaTexto:t=>t,icono:()=>null,enlaceFuente:(url,t)=>h('a',{href:url},t),selloMedible:()=>null,frescura:()=>null,minilinea:(serie,o)=>{calls.push([serie,o]);return h('figure',{},'Tendencia '+serie.join(','))},NOMBRE_COMPARAR:{}};vm.createContext(ctx);
vm.runInContext(components.slice(components.indexOf('export function lineaComparacion('),components.indexOf('export function cascada(',components.indexOf('export function tarjetaKpi'))).replace(/export /g,''),ctx);
vm.runInContext(source.slice(source.indexOf('function indicadorDireccion246('),source.indexOf('async function pintarResumenV4(')),ctx);
let cases=0;
const opts={etiqueta:'Margen confirmado',valor:'10 %',num:10,comparar:'mes_ant',comparaciones:{mes_ant:{ref:5,texto:'frente al mes anterior',modo:'puntos'}},serie:[4,5,10],serieX:['a','b','c'],umbral:{texto:'Referencia propuesta, no contractual',colorea:false},fuente:{texto:'Fuente privada autorizada',href:'#/finanzas'},contexto:'Copia parcial',nota:'No confirma todos los gastos'};
const before=JSON.stringify(opts),old=ctx.tarjetaKpi(opts),row=ctx.indicadorDireccion246(opts);assert.equal(row.children.length,4);const leaves=n=>n instanceof N?n.children.flatMap(leaves):[String(n)];assert.deepEqual(leaves(row).filter(t=>t!=='Detalle').sort(),leaves(old).sort());assert.equal(row.children[0].a.scope,'row');assert(row.textContent.includes('▲ 5.0 puntos'));assert.equal(JSON.stringify(opts),before);cases++;
assert.equal(row.all().filter(n=>n.tag==='details').length,1);assert.equal(row.all().filter(n=>n.tag==='summary')[0].style.minHeight,'44px');assert.equal(row.all().filter(n=>n.tag==='figure').length,1);assert(row.textContent.includes('Copia parcial'));assert(row.textContent.includes('no contractual'));assert(row.textContent.includes('No confirma todos los gastos'));assert(row.all().some(n=>n.a.href==='#/finanzas'));assert.equal(row.children[1].children[0].style.fontSize,'14px');cases++;
const missing=ctx.indicadorDireccion246({...opts,valor:null,num:null,sinDato:'fuente pendiente'});assert(missing.textContent.includes('Sin dato · fuente pendiente'));assert(!missing.textContent.includes('▲'));cases++;
const different=ctx.indicadorDireccion246({...opts,comparar:'objetivo'});assert(different.textContent.includes('Sin comparación para esta cifra'));assert(!different.textContent.includes('▲'));cases++;
console.log(cases+' grupos246 tabla PASS: mismos nodos/textos, comparación real, fuente/límites/tendencia y null sin0.');
(async()=>{
const start=source.indexOf('async function pintarResumenV4('),end=source.indexOf('const MODULO',start);const fn=source.slice(start,end<0?source.indexOf('export default',start):end); // incluye sólo declaración hasta el siguiente contrato módulo
let safe=true,resolve,append=0,replace=0;const zone={isConnected:true,append:()=>append++,replaceChildren:()=>replace++};const persona={id:'tomas',estado:'activo',puestos:['direccion']};const c={real:{...persona},persona:{...persona},datos:{personas:[{...persona}]},vigente:()=>safe,veModulo:id=>id==='panel-direccion',datosModulo:async()=>null};
const b={JSON,esqueleto:()=>({}),leerFinanzas:()=>new Promise(r=>resolve=r)};vm.createContext(b);vm.runInContext(source.slice(source.indexOf('function panelNominal249('),source.indexOf('async function pintar(cont')),b);vm.runInContext(fn,b);
let p=b.pintarResumenV4(zone,c);safe=false;resolve({direccion:[{}]});await p;assert.equal(append,1);assert.equal(replace,0);
safe=true;p=b.pintarResumenV4(zone,c);c.real.id='otra';resolve({direccion:[{}]});await p;assert.equal(replace,0);
c.real.id='tomas';let allowed=true;c.veModulo=id=>allowed&&id==='panel-direccion';p=b.pintarResumenV4(zone,c);allowed=false;resolve({direccion:[{}]});await p;assert.equal(replace,0);
console.log('3 grupos246 async PASS: navegación/identidad cambiada tras lectura no publica.');
})().catch(e=>{console.error(e);process.exitCode=1});
