const fs=require('fs'),vm=require('vm'),assert=require('assert');
class N{};class T extends N{constructor(value){super();this.value=value;}}class E extends N{constructor(t){super();this.tag=t;this.children=[];this.events={};this.style={};this.isConnected=true;this.attrs={};}append(...xs){this.children.push(...xs.map(x=>x instanceof N?x:new T(String(x))));}replaceChildren(...xs){this.children=[];this.append(...xs);}addEventListener(k,f){this.events[k]=f;}setAttribute(k,v){this.attrs[k]=v;this[k]=v;}}
const s={document:{createElement:t=>new E(t),createTextNode:v=>new T(v)},Node:N,Date,JSON,Number,String,Array,Object,Set,Promise,urlSegura:x=>x};vm.createContext(s);const components=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(components.slice(components.indexOf('export function h('),components.indexOf('const svgNS')).replace('export ',''),s);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_decision_durable_382.js','utf8').replace(/export /g,''),s);
const p={id:'tomas',estado:'activo',activo:true,puestos:['direccion']},ctx=()=>({servidor:true,real:{...p,puestos:[...p.puestos]},persona:{...p,puestos:[...p.puestos]},datos:{personas:[{...p,puestos:[...p.puestos]}]},clientes:[{id:'ok',activo_confirmado:true,detalle:true}],clientesVisibles:[{id:'ok',activo_confirmado:true,detalle:true}],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true}),b=()=>({operacion:'nueva',cliente_id:'ok',tipo:'para_tomas',titulo:'Título operativo',problema:'Problema operativo',recomendacion:'Recomendación operativa'}),UUID='00000000-0000-4000-8000-000000000001',H='a'.repeat(64),receipt=(i,extra={})=>({version:'382.1',resultado:'guardado',recibo:{intencion_id:UUID,id:'db-1',operacion:i.payload.operacion,revision:H,autor:'tomas',guardado_local:true,envio_realizado:false,ejecucion_verificada:false,...extra}}),text=n=>n instanceof T?n.value:n.children.map(text).join(' ');let tests=0;
(async()=>{
let c=ctx(),i=s.prepararDecision382(c,b(),UUID),sent=[];await s.guardarDecision382(c,i,async p=>{sent.push(JSON.stringify(p));throw Error('lost');});assert.equal(i.estado,'sin_confirmar');await s.guardarDecision382(c,i,async p=>{sent.push(JSON.stringify(p));return receipt(i);});assert.equal(sent[0],sent[1]);assert.equal(i.recibo.guardado_local,true);assert.equal(i.recibo.ejecucion_verificada,false);tests++;
c=ctx();i=s.prepararDecision382(c,b(),UUID);await s.guardarDecision382(c,i,async()=>({ok:true}));assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');assert.equal(i.payload.titulo,b().titulo);tests++;
c=ctx();i=s.prepararDecision382(c,b(),UUID);let resolve,count=0;const send=async()=>{count++;return await new Promise(r=>resolve=r);};const first=s.guardarDecision382(c,i,send);assert.equal(await s.guardarDecision382(c,i,send),false);resolve(receipt(i));await first;assert.equal(count,1);tests++;
for(const mutate of [c=>c.real.id='other',c=>c.clientesVisibles[0].activo_confirmado=false,c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push({...c.clientes[0]}),c=>c.clientes[0].detalle=false,c=>c.ver=()=>({ok:false}),c=>c.datos.personas.push({...p}),c=>c.veModulo=()=>false]){c=ctx();i=s.prepararDecision382(c,b(),UUID);mutate(c);let sent=0;assert.equal(await s.guardarDecision382(c,i,async()=>{sent++;}),false);assert.equal(sent,0);}tests++;
c=ctx();i=s.prepararDecision382(c,b(),UUID);await s.guardarDecision382(c,i,async()=>{c.ver=()=>({ok:false});return receipt(i);});assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');tests++;
for(const mutate of [c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push({...c.clientes[0]}),c=>c.clientes[0].detalle=false,c=>c.clientes=[]]){c=ctx();i=s.prepararDecision382(c,b(),UUID);await s.guardarDecision382(c,i,async()=>{mutate(c);return receipt(i);});assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');}tests++;
c=ctx();i=s.prepararDecision382(c,b(),UUID);await s.guardarDecision382(c,i,async()=>{throw Error('lost');});for(const actor of [c.real,c.persona,c.datos.personas[0]])actor.puestos=['direccion','seo'];let payload;await s.guardarDecision382(c,i,async p=>{payload=p;return receipt(i);});assert.equal(payload.intencion_id,UUID);tests++;
for(const extra of [{intencion_id:'wrong'},{autor:'other'},{guardado_local:false},{envio_realizado:true},{ejecucion_verificada:true},{revision:'raw'},{id:'acc-1'}]){c=ctx();i=s.prepararDecision382(c,b(),UUID);assert.equal(s.reciboDecision382(receipt(i,extra),i),null);}tests++;
c=ctx();const res={operacion:'responder',id:'db-1',revision:H,decision:'Aprobar la recomendación',motivo:null,delegada_en:null};assert.throws(()=>s.prepararDecision382(c,res,UUID));i=s.prepararDecision382(c,res,UUID,'ok',{puede_responder:true,id:'db-1',revision:H,cliente_id:'ok',tipo:'para_tomas'});assert.equal(i.cliente_id,'ok');assert(!('cliente_id' in i.payload));assert.equal(s.reciboDecision382(receipt(i,{id:'db-2'}),i),null);tests++;
for(const mutate of [c=>c.soloLectura=true,c=>c.pilotoLectura=true,c=>c.persona.id='other',c=>c.real.puestos=['seo']]){c=ctx();mutate(c);assert.throws(()=>s.prepararDecision382(c,b(),UUID));}tests++;
c=ctx();i=s.prepararDecision382(c,b(),UUID);c.api=async()=>{throw Error('lost');};const root=s.botonDecision382({h:s.h,ctx:c,intento:i});const button=root.children[0];await button.events.click();assert(text(root).includes('Reintentar misma intención'));assert.equal(i.payload.intencion_id,UUID);c.ver=()=>({ok:false});await button.events.click();assert.equal(root.children.length,0);tests++;
c=ctx();assert.throws(()=>s.prepararDecision382(c,{...b(),datos:{secreto:'fixture'}},UUID));assert.throws(()=>s.prepararDecision382(c,b(),'not-uuid'));tests++;
console.log(tests+' grupos382 frontendPASS UUIDretry/NACK/scope/grants/receipt/hreal/botón.');
})().catch(e=>{console.error(e);process.exitCode=1;});
