const fs=require('fs'),vm=require('vm'),assert=require('assert');let src=fs.readFileSync(__dirname+'/modulos/_tendencias_operaciones_329.js','utf8').replace(/export /g,'');const c={};vm.createContext(c);vm.runInContext(src+';this.A={compararMediciones329,tendenciasFotos329,METRICAS329};',c);const A=c.A,scope='a'.repeat(64),opts={scopeHash:scope,actorId:'ops',ahora:'2026-10-03T18:00:00Z'};
const med=(valor,corte='2026-10-03T08:00:00Z')=>({version:'329.1',id:'rojas',valor,validado_servidor:true,origen:'medicion_copia',scope_hash:scope,cohorte_hash:'b'.repeat(64),definicion_hash:'c'.repeat(64),unidad:'alarmas',completa:false,corte,leido:'2026-10-03T10:00:00Z',periodo:{tipo:'stock'}});
let a=med(5,'2026-10-02T08:00:00Z'),b=med(3);let r=A.compararMediciones329(a,b,opts);assert.equal(r.delta,-2);assert.equal(r.estado,'comparacion_observada');assert.equal(r.parcial,true);
assert.equal(A.compararMediciones329({...a,valor:0},{...b,valor:0},opts).direccion,'igual');
for(const patch of [{cohorte_hash:'d'.repeat(64)},{definicion_hash:'d'.repeat(64)},{completa:true},{scope_hash:'d'.repeat(64)},{unidad:'clientes'},{origen:'declaracion'},{valor:null},{valor:NaN},{valor:Infinity},{corte:a.corte},{leido:'2026-10-04T10:00:00Z'},{corte:'2026-10-03 08:00'},{periodo:{tipo:'mes',desde:'2026-10-01'}}])assert.equal(A.compararMediciones329(a,{...b,...patch},opts).actual,null,JSON.stringify(patch));
function foto(id,m,extra={}){return {tipo:'foto',objeto:id,registrado_por:'ops',registrado_en:'2026-10-03T11:00:00Z',scope_hash:scope,cumplimiento:null,exhaustiva:false,metricas:A.METRICAS329.map(([id,et])=>({id,etiqueta:et,valor:id==='rojas'?m.valor:null,fecha_fuente:id==='rojas'?m.corte:null,estado:id==='rojas'?'observado_copia':'desconocido',detalle:'copia'})),...extra};}
let dto={version:'272.1',registros:[foto('f1',a),foto('f2',b)]};r=A.tendenciasFotos329(dto,opts);assert.equal(r.length,7);assert.equal(r[1].actual,null);assert.equal(r[1].referencias.length,2);assert.equal(r[2].referencias.length,0);
dto.registros[0].mediciones_329=[a];dto.registros[1].mediciones_329=[b];r=A.tendenciasFotos329(dto,opts);assert.equal(r[1].delta,-2);
r=A.tendenciasFotos329({...dto,registros:[foto('f1',a,{mediciones_329:[a]}),foto('f2',b,{mediciones_329:[{...b,cohorte_hash:'d'.repeat(64)}]})]},opts);assert.equal(r[1].actual,null);
for(const patch of [{registrado_por:'foreign'},{scope_hash:'d'.repeat(64)},{registrado_en:'2026-10-04T11:00:00Z'},{exhaustiva:true}])assert.equal(A.tendenciasFotos329({version:'272.1',registros:[foto('x',b,patch)]},opts)[1].referencias.length,0);
assert.equal(A.tendenciasFotos329({version:'272.1',registros:[foto('x',b),foto('x',b)]},opts)[1].referencias.length,0);
assert.equal(A.tendenciasFotos329(dto,{...opts,scopeHash:'d'.repeat(64)})[1].referencias.length,0);
assert.equal(A.tendenciasFotos329({version:'272.1',registros:[foto('x',{...b,valor:0})]},opts)[1].referencias[0].valor,0);
console.log('329: comparador y lector reales PASS;7indicadores, legacy no compara, contrato/cohorte/cortes/scope/cero cubiertos.');
