const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const b={Intl,URLSearchParams};vm.createContext(b);
const strip=s=>s.replace(/^import .*;\n/gm,'').replace(/export /g,'');
function load(file,names){vm.runInContext(`Object.assign(globalThis,(()=>{${strip(fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8'))};return {${names.join(',')}};})());`,b);}
load('control_cartera',['pautaHorasControl','prepararControlCartera']);load('_operaciones_equipo_262',['horasProyectoRango262','pautaProyectoRango262']);load('_horas_fuegos_341',['ambitoFuegos341','horasFuego341']);
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.attrs=a;this.children=[];this.append(...kids);}get isConnected(){return this.main||!!this.parent?.isConnected;}append(...ns){for(const n of ns.flat(Infinity).filter(x=>x!=null)){if(n instanceof N)n.parent=this;this.children.push(n);}}replaceChildren(...ns){for(const n of this.children)if(n instanceof N)n.parent=null;this.children=[];this.append(...ns);}get textContent(){return this.children.map(n=>n instanceof N?n.textContent:String(n)).join(' ');}}
b.h=(t,a,...ns)=>new N(t,a,ns);b.chipEstado=(e,t)=>b.h('span',{'data-estado':e},t);b.panelPlanFuego255=()=>b.h('p',{},'Plan fixture');b.metricasProyectoBaseline=()=>null;
load('_account_fuegos_346',['accountFuego346','firmaAccountFuegos346']);load('_meta_semantica_285',['semanticaMeta285']);load('_operaciones_fuegos_268',['renderFuegos268']);
const ctx=()=>({servidor:true,hoy:'2026-10-03',real:{id:'ops',estado:'activo',puestos:['operaciones']},persona:{id:'ops',estado:'activo',puestos:['operaciones']},datos:{personas:[{id:'ops',estado:'activo',puestos:['operaciones']}]},clientesVisibles:[{id:'c',nombre:'Fixture',activo_confirmado:true,detalle:true}],veModulo:()=>true,ver:x=>({ok:x.cliente_id==='c'}),verdad:()=>({cliente_id:'c',gravedad:'critico'}),nombre:()=>'',vigente:()=>true});
const P=()=>({hoy:'2026-10-03',proyectos:[{cliente_id:'c',horas_mes:14,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-10-03 02:56',cobertura:'parcial'}}]});
const D=()=>({generado:'2026-10-03 03:00',mes_cuota:'2026-10',clientes:[{cliente_id:'c',cuota_horas:{pautadas:10}}]});
let count=0;const t=(name,f)=>{f();count++;console.log('PASS',name)};

load('_viernes_accounts_347',['ambitoViernes347','filasViernes347']);load('_repartir_accounts_352',['ambitoRepartir352','atribuirReparto352']);load('_operaciones_rituales_264',['filasSaneamiento264','renderRituales264']);

const walk=n=>n instanceof N?[n,...n.children.flatMap(walk)]:[];
const fixture=()=>{const c=ctx();c.datos.personas.push({id:'actual',estado:'activo',puestos:['account']},{id:'responsable_seo347',estado:'activo',puestos:['seo']});c.datos.asignaciones=[{cliente_id:'c',silla:'account',persona_id:'actual',principal:true,confianza:'confirmada'}];c.clientesVisibles[0].equipo={account:[{persona_id:'actual',principal:true,confianza:'confirmada'}]};c.clientesVisibles[0].responsable_id='responsable_seo347';c.nombre=id=>id||'Sin nombre';c.datosModulo=async ruta=>ruta.startsWith('produccion')?PP():BB();return c;};
const PP=()=>({generado:'2026-10-03',revisiones:[{id:'t1',cliente_id:'c',tarea:'Tarea fixture',revisa:'account',account_id:'account_cache_inexacto'}]});
const BB=()=>({generado:'2026-10-03',correos:[{id:'k1',cliente_id:'c',horas:12,account_id:'account_cache_inexacto'}]});
const main=()=>{const x=new N('main');x.main=true;return x;};
(async()=>{
const c=fixture(),antes=b.filasSaneamiento264(c,PP(),BB());
t('reproduce filas fuente que atribuían responsableSEO general',()=>assert.equal(antes.tareas[0].account_id,'responsable_seo347'));
t('proyección canónica mantiene counts y sustituye sólo owner',()=>{const f=b.filasViernes347(c,antes);assert.equal(f.tareas.length,1);assert.equal(f.tickets.length,1);assert.equal(f.tareas[0].account_id,'actual');assert.equal(f.tickets[0].account_id,'actual');});
const v=main();await b.renderRituales264(v,c,'viernes');t('renderer realViernes muestra Accountactual y counts1/1',()=>{assert(!v.textContent.includes('responsable_seo347'));assert(!v.textContent.includes('account_cache_inexacto'));assert(v.textContent.includes('actual'));const row=walk(v).find(n=>n.tag==='tbody').children[0];assert.equal(row.children[1].textContent,'1');assert.equal(row.children[2].textContent,'1');assert(v.textContent.includes('no es una foto certificada'));assert.equal(walk(v).filter(n=>n.tag==='th').length,4);});
for(const [label,change]of [['ausente',x=>{x.datos.asignaciones=[];delete x.clientesVisibles[0].equipo;}],['duplicado',x=>x.datos.personas.push({...x.datos.personas[1]})],['baja',x=>x.datos.personas[1].estado='baja'],['otro puesto',x=>x.datos.personas[1].puestos=['seo']],['conflicto',x=>{x.datos.personas.push({id:'otro',estado:'activo',puestos:['account']});x.datos.asignaciones[0].persona_id='otro';}]]){const x=fixture();change(x);const box=main();await b.renderRituales264(box,x,'viernes');t('owner '+label+' conserva incidencias como porconfirmar',()=>{assert(box.textContent.includes('Account por confirmar'));assert.equal(walk(box).find(n=>n.tag==='tbody').children.length,1);assert(!box.textContent.includes('responsable_seo347'));});}
const alta=fixture();alta.datos.asignaciones[0].confianza='alta';alta.clientesVisibles[0].equipo.account[0].confianza='alta';const va=main();await b.renderRituales264(va,alta,'viernes');t('alta conserva IDactual con matizporconfirmar',()=>assert(va.textContent.includes('actual · asignación por confirmar')));
const extranjero=fixture();const pp=PP();pp.revisiones.push({id:'ajeno',cliente_id:'fuera',revisa:'account',tarea:'No mostrar'});extranjero.datosModulo=async r=>r.startsWith('produccion')?pp:BB();const vf=main();await b.renderRituales264(vf,extranjero,'viernes');t('cliente ajeno no entra en recuentos',()=>assert.equal(walk(vf).find(n=>n.tag==='tbody').children[0].children[1].textContent,'1'));
for(const [label,change]of [['asignación',x=>x.datos.asignaciones[0].persona_id='responsable_seo347'],['equipo',x=>x.clientesVisibles[0].equipo.account[0].persona_id='responsable_seo347'],['persona',x=>x.datos.personas[1].estado='baja'],['ACT',x=>x.clientesVisibles[0].activo_confirmado=false],['roles',x=>x.datos.personas[0].puestos=['seo']],['grant',x=>x.ver=()=>({ok:false})],['módulo',x=>x.veModulo=()=>false]]){const x=fixture();let resolve;const wait=new Promise(r=>resolve=r);x.datosModulo=()=>wait;const box=main(),pending=b.renderRituales264(box,x,'viernes');change(x);resolve(PP());await pending;t('cambio '+label+' duranteGET no publica',()=>assert.equal(box.textContent,''));}
for(const event of ['click','focusin','keydown']){const x=fixture(),box=main();await b.renderRituales264(box,x,'viernes');const root=walk(box).find(n=>n.attrs['data-viernes-347']);x.datos.asignaciones=[];root.attrs.on[event]();t('callback '+event+' tras revocación limpia atribución',()=>assert.equal(box.textContent,''));}
const ac=fixture();ac.real=ac.persona={...ac.datos.personas[1]};ac.carteraPorSilla={account:new Set()};const av=main();await b.renderRituales264(av,ac,'viernes');t('Account sin cartera no obtiene filas aunque cliente estévisible',()=>{assert(!av.textContent.includes('actual'));assert(av.textContent.includes('Sin filas observadas'));});
let reads=0;const denied=fixture();denied.datos.personas.push({...denied.real});denied.datosModulo=async()=>{reads++;return null;};await b.renderRituales264(main(),denied,'viernes');t('actor duplicado deniega antesGET',()=>assert.equal(reads,0));
const fallo=fixture();fallo.datosModulo=async()=>{throw Error('fixture');};const ve=main();await b.renderRituales264(ve,fallo,'viernes');t('error fuente no inventa cero',()=>assert(ve.textContent.includes('No se pudo leer')));
console.log(count+' grupos347 PASS · Viernes renderer264/ControlCartera reales, sin proveedores ni negocioPOST.');
})().catch(e=>{console.error(e);process.exitCode=1;});
