const fs=require('fs'),vm=require('vm'),assert=require('assert');
const fixture=fs.readFileSync(__dirname+'/probar_decision_durable_382.cjs','utf8').split('(async()=>{')[0];
const e=new Function('require','__dirname',fixture+';return {s,ctx,p,H,E,T,text,UUID};')(require,__dirname),{s,ctx,p,H,E,text,UUID}=e;
s.crypto={randomUUID:()=>UUID};
vm.runInContext('(function(){'+fs.readFileSync(__dirname+'/modulos/_operaciones_decisiones_387.js','utf8').replace(/^import .*;$/gm,'').replace(/export /g,'')+';globalThis.proyectarDecisiones387=proyectarDecisiones387;globalThis.renderDecisiones387=renderDecisiones387;globalThis.fechaRegistro387=fechaRegistro387;})();',s);
const all=n=>[n,...(n.children||[]).flatMap(all)].filter(n=>n instanceof E),tag=(n,t)=>all(n).filter(x=>x.tag===t),contains=(n,t)=>all(n).find(x=>text(x).includes(t)),row=()=>({id:'db-1',tipo:'para_tomas',cliente_id:'ok',quien:'tomas',titulo:'Revisión operativa',problema:'Problema de ejecución',recomendacion:'Revisar mañana',creada:'2026-10-03 22:10:00',respondida:null,respondida_por:null,respuesta:null,revision:H,puede_responder:true,origen:'registro_local',ejecucion_verificada:false,envio_realizado:false}),doc=()=>({version:'382.1',origen:'registro_local',envio_realizado:false,truncado:false,decisiones:[row()]}),ack=b=>({version:'382.1',resultado:'guardado',recibo:{intencion_id:b.intencion_id,id:'db-1',operacion:b.operacion,revision:H,autor:'tomas',guardado_local:true,envio_realizado:false,ejecucion_verificada:false}});
let tests=0;
async function mount(c,D=doc()){const out=new E('div');c.api=c.api|| (async()=>D);await s.renderDecisiones387(out,c);return out;}
(async()=>{
let c=ctx(),empty=doc();empty.decisiones=[];let emptyOut=await mount(c,empty);assert.equal(tag(emptyOut,'table').length,0);assert(text(emptyOut).includes('Sin decisiones en la colección autorizada.'));assert(text(emptyOut).includes('Nueva decisión'));tests++;
 c=ctx();let out=await mount(c);assert.equal(tag(out,'th').length,6);assert(text(out).includes('Problema de ejecución'));assert(text(out).includes('Revisar mañana'));assert(text(out).includes('Pendiente de decisión'));assert.equal(tag(out,'details')[0].open,undefined);assert.equal(tag(out,'textarea').length,3);tests++;
for(const mutate of [D=>D.version='raw',D=>D.decisiones.push(row()),D=>D.decisiones[0].cliente_id='foreign',D=>D.decisiones[0].revision='x'+H,D=>D.decisiones[0].envio_realizado=true]){c=ctx();const D=doc();mutate(D);assert.equal(s.proyectarDecisiones387(c,D),null);}tests++;
c=ctx();c.pilotoLectura=true;out=await mount(c);assert.equal(tag(out,'textarea').length,0);assert(text(out).includes('Revisión operativa'));tests++;
c=ctx();c.soloLectura=true;out=await mount(c);assert.equal(tag(out,'textarea').length,0);tests++;
c=ctx();let resolve;c.api=()=>new Promise(r=>resolve=r);const cont=new E('div'),pending=s.renderDecisiones387(cont,c);c.clientes[0].activo_confirmado=false;resolve(doc());await pending;assert(!text(cont).includes('Revisión operativa'));tests++;
c=ctx();out=await mount(c);const detail=tag(out,'details').find(x=>text(x).includes('Abrir detalle'));c.ver=()=>({ok:false});await detail.events.toggle();assert(!text(out).includes('Problema de ejecución'));tests++;
c=ctx();let posts=[],gets=0;c.api=async(path,opt)=>{if(!opt){gets++;return doc();}posts.push({...opt.cuerpo});if(posts.length===1)throw Error('lost');return ack(opt.cuerpo);};out=await mount(c);const newform=tag(out,'details')[0];tag(newform,'input')[0].value='Decidir';tag(newform,'textarea')[0].value='Problema';tag(newform,'textarea')[1].value='Recomendación';tag(newform,'select')[0].value='ok';const button=tag(newform,'button')[0];await button.events.click();assert.equal(posts.length,1);assert.equal(posts[0].tipo,'para_coti');assert(tag(newform,'input')[0].disabled);assert(text(newform).includes('Reintentar mismo contenido'));tag(newform,'input')[0].value='Cambio no autorizado';await button.events.click();assert.equal(JSON.stringify(posts[0]),JSON.stringify(posts[1]));assert.equal(gets,2);assert(!text(out).includes('Cambio no autorizado'));tests++;
c=ctx();let calls=0;c.api=async(path,opt)=>{if(!opt)return doc();calls++;return {ok:true};};out=await mount(c);const nf=tag(out,'details')[0];tag(nf,'input')[0].value='Título';tag(nf,'textarea').forEach(x=>x.value='Texto operativo');tag(nf,'select')[0].value='ok';await tag(nf,'button')[0].events.click();assert(text(nf).includes('Resultado sin confirmar'));assert(!text(nf).includes('Decisión guardada'));tests++;
c=ctx();posts=[];c.api=async(path,opt)=>{if(!opt)return doc();posts.push(opt.cuerpo);return ack(opt.cuerpo);};out=await mount(c);const rf=tag(out,'details').find(x=>text(x).includes('Abrir detalle'));const selects=tag(rf,'select');selects[0].value='Rechazar';tag(rf,'textarea')[0].value='Falta revisión';selects[1].value='';await tag(rf,'button')[0].events.click();assert.equal(posts[0].decision,'Rechazar');assert.equal(posts[0].revision,H);assert.equal(posts[0].operacion,'responder');assert(!('cliente_id' in posts[0]));tests++;
c=ctx();c.datos.personas.push({id:'delegate',nombre:'Persona destino',estado:'baja',puestos:['seo']});out=await mount(c);assert(!tag(out,'option').some(o=>o.value==='delegate'));tests++;
c=ctx();const D=doc();D.decisiones[0].respondida='2026-10-04 00:00:00';D.decisiones[0].puede_responder=false;D.decisiones[0].respuesta={decision:'Rechazar',motivo:'Verificación necesaria',delegada_en:null};out=await mount(c,D);assert(text(out).includes('Verificación necesaria'));assert(text(out).includes('Respuesta registrada'));assert.equal(tag(out,'textarea').length,2);tests++;
c=ctx();out=await mount(c);const n=tag(out,'details')[0];tag(n,'input')[0].value='Título';tag(n,'textarea').forEach(x=>x.value='Texto');tag(n,'select')[0].value='ok';c.datos.personas.push({...p});let count=0;c.api=async()=>{count++;};await tag(n,'button')[0].events.click();assert.equal(count,0);assert(!text(out).includes('Título'));tests++;
c=ctx();let done,pc=0;c.api=async(path,opt)=>opt?(pc++,await new Promise(r=>done=()=>r(ack(opt.cuerpo)))):doc();out=await mount(c);const nf2=tag(out,'details')[0];tag(nf2,'input')[0].value='Título';tag(nf2,'textarea').forEach(x=>x.value='Texto');tag(nf2,'select')[0].value='ok';const b2=tag(nf2,'button')[0],first=b2.events.click();await b2.events.click();assert.equal(pc,1);done();await first;tests++;
const actual=JSON.parse(require('child_process').execFileSync('python3',[__dirname+'/probar_decisiones_inline_387.py','--fixture'],{encoding:'utf8'}));c=ctx();c.datos.personas.push({id:'coti',nombre:'Coti',estado:'activo',puestos:['proyectos']});out=await mount(c,actual.antes);assert(text(out).includes('Coti · revisión de proyectos'));assert(tag(out,'textarea').length===3);delete c.api;out=await mount(c,actual.despues);assert(text(out).includes('Delegada en Coti'));assert(text(out).includes('registro, no notificación'));assert.equal(tag(out,'textarea').length,2);tests++;
assert(s.fechaRegistro387('2026-10-03 23:10:00').includes('04/10/2026'));assert(s.fechaRegistro387('2026-10-03 23:10:00').includes('01:10'));assert.equal(s.fechaRegistro387('2026-02-30 12:00:00'),'Sin fecha válida');assert.equal(s.fechaRegistro387('2026-10-03'),'Sin fecha válida');assert.equal(s.fechaRegistro387('2026-02-30T12:00:00Z'),'Sin fecha válida');assert.equal(s.fechaRegistro387('2026-10-03T24:00:00Z'),'Sin fecha válida');tests++;
c=ctx();const unknown=doc();unknown.decisiones[0].creada=null;unknown.decisiones[0].respondida=null;unknown.decisiones[0].respuesta_registrada=true;unknown.decisiones[0].puede_responder=false;out=await mount(c,unknown);assert(text(out).includes('Sin fecha válida'));assert(text(out).includes('Respuesta registrada'));assert(!text(out).includes('Pendiente de decisión'));assert.equal(tag(out,'textarea').length,2);tests++;
c=ctx();const pendingUnknown=doc();pendingUnknown.decisiones[0].creada=null;pendingUnknown.decisiones[0].respuesta_registrada=false;out=await mount(c,pendingUnknown);assert(text(out).includes('Pendiente de decisión'));assert.equal(tag(out,'textarea').length,3);tests++;
console.log(tests+' grupos387 DOM realPASS tabla/forms/UUID/receipt/ACT/revocación/readonly.');
})().catch(e=>{console.error(e);process.exitCode=1;});
