const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_coste_cita_299.js','utf8').replace(/export /g,'')+';Object.assign(globalThis,{normalizarCita299,referenciaCita299,textoMetaQuincenal299});',ctx);
const source=fs.readFileSync(__dirname+'/modulos/captacion.js','utf8');
function real(name){const a=source.indexOf('function '+name+'('),b=source.indexOf('\nfunction ',a+10);vm.runInContext(source.slice(a,b>0?b:undefined)+`;globalThis.${name}=${name};`,ctx);}
let n=0;const test=fn=>{fn();n++;};
test(()=>{const x={coste_por_cita_14d:250,alarma_100:true};const y=ctx.normalizarCita299(x);assert.equal(y.coste_por_cita_14d,null);assert.equal(y.coste_por_cita_referencia_14d,250);assert.equal(y.alarma_100,false);assert.equal(x.alarma_100,true);});
test(()=>{for(const x of [null,{},false,0,NaN,Infinity,-1,'200'])assert.equal(ctx.referenciaCita299({coste_por_cita_14d:x}),null);});
test(()=>{const x=ctx.normalizarCita299({coste_por_cita_14d:200});assert.equal(ctx.normalizarCita299(x).coste_por_cita_referencia_14d,200);});
test(()=>{ctx.mezclarTextos=(a,b)=>a;real('completarDinero');const c={quincenal:{coste_por_cita_14d:null}},f={fuentes:{captacion_ghl:{datos:{coste_por_cita:{coste_por_cita_14d:250,alarma_100:true}}}}};ctx.completarDinero(c,f);assert.equal(c.coste_por_cita.alarma_100,false);assert.equal(c.quincenal.coste_por_cita_14d,null);assert.equal(c.quincenal.coste_por_cita_referencia_14d,250);assert.equal(f.fuentes.captacion_ghl.datos.coste_por_cita.alarma_100,true);});
test(()=>{ctx.h=(t,a,...xs)=>({tag:t,attrs:a,children:xs});ctx.eur=v=>v+' €';ctx.chipEstado=(estado,text)=>({estado,text});ctx.candado=()=>({});real('celdaCita');const r=ctx.celdaCita({dinero:true,coste_por_cita:{coste_por_cita_14d:250}},{parametros:{alarma_cita:100,arranque_cita:20}});assert.equal(r.children[0].estado,'gris');assert.match(r.children[0].text,/ref\./);assert.match(ctx.celdaCita({dinero:true,ghl:{conectado:true}},{}).children[0],/Sin dato/);});
test(()=>{const lines=ctx.textoMetaQuincenal299({leads_14d:10,gasto_14d:200,cpl_14d:20,coste_por_cita_14d:250},true,v=>v+' €').join('\n');assert.match(lines,/≥10/);assert.match(lines,/Evento por confirmar/);assert.match(lines,/no es CPL acreditado/);assert.match(lines,/Sin cohorte enlazada/);assert(!lines.includes('Contactos de Meta'));});
test(()=>{for(const x of [0,true,NaN,Infinity,-1,'10',1.5])assert.match(ctx.textoMetaQuincenal299({leads_14d:x},false,String)[0],/Sin dato/);});
test(()=>{assert.equal(ctx.textoMetaQuincenal299({gasto_14d:500,cpl_14d:20},false,String).length,1);});
test(()=>{const nodes=[];ctx.h=(t,a,...xs)=>{const r={tag:t,attrs:a,children:xs};nodes.push(r);return r;};ctx.panel=(a,...xs)=>ctx.h('panel',a,...xs);ctx.icono=()=>null;ctx.botonConfirmar=()=>null;ctx.fDiaRO=String;ctx.num=String;ctx.pct=String;ctx.textoMot=String;ctx.medirEmbudoCRM=()=>({agendadas:null,celebradas:null,ausencias:null,asistencia:null,sinEstado:null,fecha:null});ctx.hoyMadrid=()=> '2026-10-03';real('tQuincenal');ctx.tQuincenal({append(){}},{hoy:'2026-10-03',soloLectura:true},{fuentes:[]},{nombre:'Fixture',dinero:true,ghl:{},quincenal:{periodo:['2026-09-19','2026-10-02'],leads_14d:10,cpl_14d:20,coste_por_cita_14d:250}});const pre=nodes.find(x=>x.tag==='pre').children.join('');assert.match(pre,/Resultados Meta · referencia/);assert.match(pre,/Citas creadas observadas: Sin dato/);assert(!pre.includes('Coste por cita:'));assert(!pre.includes('coste por contacto'));});
console.log(n+' pruebas299 PASS: fuente real de relleno, celda, quincenal y ausencia, sin mutación ni falsa alarma.');
