const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.append(...xs)}get isConnected(){return this.connected===true||!!this.parent?.isConnected}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x)}}set textContent(x){this.children=[];this.append(x)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}addEventListener(k,f){this.events[k]=f}}
const h=(t,a,...xs)=>new N(t,a,xs);let n=0;const check=f=>{f();n++};
(async()=>{const code=fs.readFileSync(__dirname+'/modulos/_revision_citas_334.js','utf8'),M=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));const x={ref:'r',cliente_id:'c',sub_id:'s',subcuenta:'Fixture',inicio:'2026-10-01T10:00Z',horas:50},base=[{sub_id:'s',cliente_id:'c'}];const a={tipo:'revisado_cita',objeto:'cita r',cliente_id:'c',id:1,texto:'Vino'};
check(()=>{const r=M.revisionCita334(x,new Map([['cita r',a]]));assert(r.registrada);assert.equal(r.asistencia_verificada,false);assert.equal(r.venta_verificada,false);assert.equal(M.citasPendientes334([x],base).length,1)});
check(()=>{for(const bad of [{...a,cliente_id:'foreign'},{...a,tipo:'revisado_lead'},{...a,objeto:'cita foreign'},{...a,id:null}])assert(!M.revisionCita334(x,new Map([['cita r',bad]])).registrada);assert.equal(M.citasPendientes334([x],[...base,...base]).length,0)});
const ctx=()=>({real:{id:'o',estado:'activo'},persona:{id:'o',estado:'activo'},datos:{personas:[{id:'o',estado:'activo'}]},servidor:true,soloLectura:false,clientesVisibles:[{id:'c',activo_confirmado:true,detalle:true}],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true});
let calls=[],retry=true;const c=ctx();c.accion=async b=>{calls.push(structuredClone(b));if(retry){retry=false;throw Error('sin respuesta')}return {ok:true,id:2,estado:'simulada',intencion_guardada:{id:b.intencion_id,accion_id:2}}};
const d={revisados:new Map()},root=h('main',{});root.connected=true;const badge=M.estadoRevisionCita334(h,x,d),widget=M.crearRevisionCita334(h,c,x,d,['Vino (lo confirma el despacho)']);root.append(badge,widget);const b=widget.children.find(x=>x.tag==='button');
check(()=>{assert.equal(calls.length,0);assert(!d.revisados.has('cita r'))});await b.events.click();check(()=>{assert(!d.revisados.has('cita r'));assert.match(widget.textContent,/reintenta/);assert(!root.hidden)});await b.events.click();check(()=>{assert.deepEqual(calls[0],calls[1]);assert(d.revisados.has('cita r'));assert.match(badge.textContent,/Revisión local registrada/);assert.match(widget.textContent,/resultado pendiente/);assert(!root.hidden)});
for(const alter of [c=>c.persona.id='other',c=>c.soloLectura=true,c=>c.clientesVisibles=[],c=>c.ver=()=>({ok:false}),c=>c.veModulo=()=>false,c=>c.datos.personas.push({...c.datos.personas[0]}),c=>c.datos.personas[0].estado='baja',c=>c.datos.personas[0].activo=false,c=>c.real.estado='baja',c=>c.persona.activo=false]){let count=0;const z=ctx();z.accion=async()=>{count++};alter(z);const w=M.crearRevisionCita334(h,z,x,{revisados:new Map()},['Prueba']);root.append(w);await w.children.find(x=>x.tag==='button').events.click();check(()=>assert.equal(count,0))}
let done;const z=ctx(),dd={revisados:new Map()};z.accion=b=>new Promise(r=>done=()=>r({ok:true,id:3,estado:'simulada',intencion_guardada:{id:b.intencion_id,accion_id:3}}));const w=M.crearRevisionCita334(h,z,x,dd,['Prueba']);root.append(w);const pending=w.children.find(x=>x.tag==='button').events.click();z.ver=()=>({ok:false});done();await pending;check(()=>assert.equal(dd.revisados.size,0));
for(const reply of [{ok:false},{ok:true,id:5,estado:'confirmado'},{ok:true,id:5,estado:'simulada',intencion_guardada:{id:'different',accion_id:5}}]){const c3=ctx(),d3={revisados:new Map()};c3.accion=async()=>reply;const w3=M.crearRevisionCita334(h,c3,x,d3,['Prueba']);root.append(w3);await w3.children.find(x=>x.tag==='button').events.click();check(()=>{assert.equal(d3.revisados.size,0);assert.match(w3.textContent,/No se confirmó/);assert(!root.hidden)})}
const c4=ctx(),d4={revisados:new Map()};let done4;c4.accion=b=>new Promise(r=>done4=()=>r({ok:true,id:9,estado:'simulada',intencion_guardada:{id:b.intencion_id,accion_id:9}}));const w4=M.crearRevisionCita334(h,c4,x,d4,['Prueba']);root.append(w4);const wait4=w4.children.find(x=>x.tag==='button').events.click();c4.datos.personas[0].activo=false;done4();await wait4;check(()=>assert.equal(d4.revisados.size,0));
// Renderer real de citas: el registro local no excluye la fila ni inventa eventos adicionales.
const src=fs.readFileSync(__dirname+'/modulos/crm.js','utf8'),start=src.indexOf('function pintarCitas('),end=src.indexOf('// ------------------------------------------------------------------',start+1);let options;
const note=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_nota_compacta_336.js','utf8')).toString('base64'));const env={h,...M,...note,MOVIL:()=>false,cuentagotas:()=>()=> 'gris',avisoParcial:()=>null,panel:(o,...xs)=>h('section',{},...xs),tablaDensa:o=>{options=o;return h('table',{})},tablaApilable:()=>null,botonRevisado:()=>null,logoCliente:()=>null,fDiaRO:x=>x,puntoEstado:()=>null,horasTxt:x=>x,masAcciones:()=>null,accionSim:()=>null,botonVerDatos:()=>null,abrirGHL:()=>null};vm.createContext(env);vm.runInContext(src.slice(start,end),env);const zone=h('main',{});const doc={subcuentas:base,revisados:new Map([['cita r',a]])};env.pintarCitas(zone,ctx(),doc,{base},[x]);check(()=>{assert.equal(options.filas.length,1);assert(options.columnas.some(c=>c.clave==='revision_ro'));assert.match(options.vacio.porque,/no acredita/)});
console.log(n+' grupos334 PASS: overlay, recibo/retry, vigencia y renderer real mantiene cita pendiente');})().catch(e=>{console.error(e);process.exitCode=1});
