const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(__dirname+'/fixture_harness_crm_677.cjs','utf8'),{e,h}=new Function('require',base+';return {e,h};')(require);
(async()=>{const M=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_contacto_observado_677.js','utf8')).toString('base64'));let count=0;
const d=Date.parse('2026-10-01T08:00:00Z'),cut=Date.parse('2026-10-03T10:00:00Z'),x={ref:'leadfixture',sub_id:'subfixture',cliente_id:'cliente-fixture',creado:'2026-10-01 10:00',creado_iso676:'2026-10-01T08:00:00Z',respondio:true},m={version:'676.1',fuente:'ghl_conversacion',estado:'observado_parcial',desde_ms:d,hasta_ms:cut,completa:false,entradas_observadas:1,ultima_entrada_ms:d+3600000,cliente_id:x.cliente_id,sub_id:x.sub_id,ref:x.ref,respuesta_humana_confirmada:null,resultado_comercial_confirmado:null};
const fuente={estado:'bien',hora:'2026-10-03 12:00'};const entrada=(x,hoy)=>M.entradaLead677(x,hoy,fuente);
let r=entrada({...x,respuesta_medicion676:m},'2026-10-04');assert.equal(r.texto,'Entrada obs.');assert.equal(r.fecha,'2026-10-01T09:00:00.000Z');assert.equal(r.estado,'gris');assert(r.detalle.includes('no confirma respuesta humana'));count++;
assert.equal(entrada(x,'2026-10-04').texto,'Por confirmar');assert.equal(entrada({...x,respondio:false},'2026-10-04').texto,'—');count++;
for(const [k,v] of Object.entries({cliente_id:'ajeno',sub_id:'otro',ref:'otro',version:'676.0',fuente:'arbitraria',estado:'completo',completa:true,desde_ms:d-1,hasta_ms:d-1,ultima_entrada_ms:cut+1,entradas_observadas:0,respuesta_humana_confirmada:true,resultado_comercial_confirmado:true})){assert.equal(entrada({...x,respuesta_medicion676:{...m,[k]:v}},'2026-10-04').texto,'Por confirmar',k);count++;}
for(const val of [null,'1',NaN,Infinity,true,10**30]){assert.equal(entrada({...x,respuesta_medicion676:{...m,entradas_observadas:val}},'2026-10-04').texto,'Por confirmar');count++;}
for(const hoy of ['',null,'2026-02-30','2026-10-02']){assert.equal(entrada({...x,respuesta_medicion676:m},hoy).texto,'Por confirmar');count++;}
const raw={cliente_id:x.cliente_id,sub_id:x.sub_id,velocidad:{en_1h:1,juzgables:1,pct_1h:100},sin_tocar_24h:0};assert.equal(M.primerIntento677(raw).texto,'1/1');assert(M.primerIntento677(raw).detalle.includes('No tasa vigente'));assert.equal(M.sinIntento677(raw).texto,'0');assert.equal(M.sinIntento677(raw).observado,false);count++;
const sf={estado:'bien',hora:'2026-10-04 12:00'},nowSin=Date.parse('2026-10-04T10:00:00Z');const typed={...raw,sin_tocar_medicion:{fuente:'ghl_conversacion',cobertura:'parcial',completa:false,leads_observados:2,leads_elegibles:5,version:'676.1',cliente_id:raw.cliente_id,sub_id:raw.sub_id,desde_ms:Date.parse('2026-09-03T22:00:00Z'),cohorte_hasta_ms:Date.parse('2026-10-03T22:00:00Z'),hasta_ms:Date.parse('2026-10-04T10:00:00Z'),hora_fuente:'2026-10-04 12:00'}};assert.equal(M.sinIntento677(typed,sf,'2026-10-04',nowSin).cobertura,'2/5');assert.equal(M.agregarSinIntento677([typed],sf,'2026-10-04',nowSin).cobertura,'2/5');assert.equal(M.agregarSinIntento677([typed,typed],sf,'2026-10-04',nowSin).cobertura,null);count++;
for(const v of [null,false,'1',NaN,Infinity,10**30]){assert.equal(M.primerIntento677({...raw,velocidad:{en_1h:v,juzgables:1}}).texto,'—');count++;}
const modern=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_crm_mediciones.js','utf8')).toString('base64'));Object.assign(e,modern,M);e.leadsPendientes369=a=>a;e.senalFilaCRM541=()=>({estado:'gris'});e.horasTxt=String;e.fDiaRO=String;e.estadoRevisionLead369=()=>null;e.botonRevisado=()=>null;e.botonVerDatos=()=>null;e.masAcciones=()=>null;e.accionSim=()=>null;e.tareaAccount=()=>null;e.revisionLead369=()=>null;
let options;e.tablaDensa=o=>{options=o;return h('table',{})};e.chipsFiltro=o=>Object.assign(h('div',{}),{valor:()=>''});vm.createContext(e);
function leads(source){vm.runInContext(source.slice(source.indexOf('function pintarLeads('),source.indexOf('// ------------------------------------------------------------------ pestaña: oportunidades paradas')),e);e.pintarLeads(h('main',{}),{hoy:'2026-10-04'},{subcuentas:[],fuentes:{ghl:fuente}},{base:[]},[x]);return options.columnas.find(c=>c.clave==='respondio').celda;}
const old=leads(fs.readFileSync(__dirname+'/fixturebaseline_crm_677.js','utf8'));assert.equal(old(x).textContent,'Sí, revisar');const fixed=leads(fs.readFileSync(__dirname+'/modulos/crm.js','utf8'));assert.equal(fixed(x).textContent,'Por confirmar');assert.equal(fixed({...x,respuesta_medicion676:m}).textContent,'Entrada obs.');count++;
for(const fuenteMala of [undefined,{estado:'bien',hora:'2026-10-03 12:01'},{estado:'bien',hora:'2026-02-30 12:00'},{estado:'bien',hora:'2026-10-03T12:00:00+02:99'},{estado:'error',hora:fuente.hora}]){assert.equal(M.entradaLead677({...x,respuesta_medicion676:m},'2026-10-04',fuenteMala).texto,'Por confirmar');count++;}
assert.equal(entrada({...x,creado_iso676:undefined,respuesta_medicion676:m},'2026-10-04').texto,'Por confirmar');count++;
function subs(source){vm.runInContext(source.slice(source.indexOf('function pintarSubcuentas('),source.indexOf('// ------------------------------------------------------------------ pestaña: leads sin tocar')),e);e.pintarSubcuentas(h('main',{}),{hoy:'2026-10-04',nivel:'suyo',vigente:()=>true},{fuentes:{ghl:sf},subcuentas:[raw]},{base:[raw],mias:[raw],jefatura:false});return options;}
const oldSub=subs(fs.readFileSync(__dirname+'/fixturebaseline_crm_677.js','utf8'));assert(oldSub.columnas.find(c=>c.clave==='v1h').celda(raw).textContent.includes('100%'));
const newSub=subs(fs.readFileSync(__dirname+'/modulos/crm.js','utf8'));const first=newSub.columnas.find(c=>c.clave==='v1h').celda(raw);assert.equal(first.textContent,'1/1');assert(!first.textContent.includes('%'));assert(first.attrs.title.includes('No tasa vigente'));const sin=newSub.columnas.find(c=>c.clave==='sin_tocar_24h').celda(typed);assert.equal(sin.textContent,'0');assert(sin.attrs.title.includes('2/5'));count+=2;
const sameDayCut=Date.parse('2026-10-04T12:00:00Z'),sameDay={...m,hasta_ms:sameDayCut,ultima_entrada_ms:sameDayCut-60000};assert.equal(M.entradaLead677({...x,respuesta_medicion676:sameDay},'2026-10-04',{estado:'bien',hora:'2026-10-04 14:00'},sameDayCut-300000).texto,'Por confirmar');assert.equal(M.entradaLead677({...x,respuesta_medicion676:sameDay},'2026-10-04',{estado:'bien',hora:'2026-10-04 14:00'},sameDayCut).texto,'Entrada obs.');count++;
assert.equal(M.sinIntento677({...typed,leads_30d:4},sf,'2026-10-04',nowSin).observado,false);assert.equal(M.sinIntento677({...typed,leads_30d:5},sf,'2026-10-04',nowSin).observado,true);count++;
const typedPositive={...typed,leads_30d:5,sin_tocar_24h:1},legacy={...raw,sub_id:'legacy-sid',sin_tocar_24h:7};const mixed=M.agregarSinIntento677([typedPositive,legacy],sf,'2026-10-04',nowSin);assert.equal(mixed.valor,1);assert.equal(mixed.cobertura,'2/5');assert(mixed.detalle.includes('referencias de filas sin descriptor excluidas'));count++;
const src=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');vm.runInContext(src.slice(src.indexOf('function sumar('),src.indexOf('const frescuraGHL')),e);const agregado=e.sumar([typedPositive,legacy],sf,'2026-10-04');assert.equal(agregado.sinTocar,1);assert.equal(agregado.sinIntentoLectura677.cobertura,'2/5');assert.equal(e.sumar([legacy],sf,'2026-10-04').sinTocar,7);assert.equal(e.sumar([legacy],sf,'2026-10-04').sinIntentoLectura677.cobertura,null);count++;
for(const alter of [{version:undefined},{hora_fuente:'2026-10-03 12:00'},{hasta_ms:nowSin+300000},{desde_ms:typed.sin_tocar_medicion.desde_ms+86400000},{cohorte_hasta_ms:typed.sin_tocar_medicion.cohorte_hasta_ms+3600000},{cliente_id:'ajeno'},{sub_id:'ajeno'}]){const legacyMeta={...typed,sin_tocar_medicion:{...typed.sin_tocar_medicion,...alter}};assert.equal(M.sinIntento677(legacyMeta,sf,'2026-10-04',nowSin).observado,false);assert.equal(M.agregarSinIntento677([legacyMeta],sf,'2026-10-04',nowSin).cobertura,null);count++;}
assert.equal(M.sinIntento677({...typed,sin_tocar_medicion:{fuente:'ghl_conversacion',cobertura:'parcial',leads_observados:2,leads_elegibles:5,completa:false}},sf,'2026-10-04',nowSin).cobertura,null);count++;
const bridge=JSON.parse(require('node:child_process').execFileSync('python3',[__dirname+'/puente_publico_crm_677.py'],{encoding:'utf8'}));const publico=M.entradaLead677(bridge.fl,bridge.hoy,bridge.fuentes.ghl,bridge.ahora_ms);assert.equal(publico.texto,'Entrada obs.');assert.equal(publico.fecha,new Date(bridge.fl.respuesta_medicion676.ultima_entrada_ms).toISOString());assert.equal(publico.estado,'gris');assert(!publico.detalle.includes('contactFixture'));assert(!publico.detalle.includes(bridge.fl.ref));count++;
const dBridge={subcuentas:[],fuentes:bridge.fuentes};e.pintarLeads(h('main',{}),{hoy:bridge.hoy},dBridge,{base:[]},[bridge.fl]);const realCelda=options.columnas.find(c=>c.clave==='respondio').celda(bridge.fl);assert.equal(realCelda.textContent,'Entrada obs.');assert(realCelda.attrs.title.includes(publico.fecha));assert(realCelda.attrs['aria-label'].includes('no confirma respuesta humana'));count++;
for(const alter of [{...bridge.fl,respuesta_medicion676:null},{...bridge.fl,respuesta_medicion676:{...bridge.fl.respuesta_medicion676,cliente_id:'ajeno'}},{...bridge.fl,creado_iso676:undefined}]){assert.equal(M.entradaLead677(alter,bridge.hoy,bridge.fuentes.ghl,bridge.ahora_ms).texto,'Por confirmar');count++;}
assert.equal(M.entradaLead677(bridge.fl,bridge.hoy,{...bridge.fuentes.ghl,hora:'2026-10-03 12:00'},bridge.ahora_ms).texto,'Por confirmar');count++;
const sinPublico=M.sinIntento677(bridge.fila,bridge.fuentes.ghl,bridge.hoy,bridge.ahora_ms);assert.equal(sinPublico.observado,true);assert.equal(sinPublico.cobertura,'1/1');assert.equal(sinPublico.texto,'1');assert.equal(M.agregarSinIntento677([bridge.fila],bridge.fuentes.ghl,bridge.hoy,bridge.ahora_ms).valor,1);count++;
assert.equal(M.sinIntento677(bridge.fila,{...bridge.fuentes.ghl,hora:'2026-10-03 12:00'},bridge.hoy,bridge.ahora_ms).observado,false);assert.equal(M.sinIntento677({...bridge.fila,sin_tocar_medicion:null},bridge.fuentes.ghl,bridge.hoy,bridge.ahora_ms).cobertura,null);count++;
const oldSource={estado:'bien',hora:'2026-10-03 12:00'},oldCut=Date.parse('2026-10-03T10:00:00Z'),oldRow={...typedPositive,motivos:[{clave:'sin_tocar',origen:'observacion_muestra'}],sin_tocar_medicion:{...typedPositive.sin_tocar_medicion,desde_ms:Date.parse('2026-09-02T22:00:00Z'),cohorte_hasta_ms:Date.parse('2026-10-02T22:00:00Z'),hasta_ms:oldCut,hora_fuente:oldSource.hora}};const historico=M.sinIntento677(oldRow,oldSource,'2026-10-04',nowSin);assert.equal(historico.observado,true);assert.equal(historico.vigente,false);assert.equal(historico.cobertura,'2/5');assert.equal(historico.valor,1);assert(historico.detalle.includes('2026-10-03T10:00:00.000Z'));assert.equal(M.agregarSinIntento677([oldRow],oldSource,'2026-10-04',nowSin).todoScope,false);assert.equal(M.agregarSinIntento677([oldRow],oldSource,'2026-10-04',nowSin).valor,1);assert.equal(M.sinIntento677(typedPositive,sf,'2026-10-04',nowSin).vigente,true);count++;
// Ejecuta el objeto tile real de detalle; ninguna llamada/API ni otros widgets simulados.
const detalleSrc=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');const tileStart=detalleSrc.indexOf("tile({ icono: 'phone', etiqueta: 'Sin intento registrado > 24 h', valor: f.sin_tocar_24h");const tileEnd=detalleSrc.indexOf('\n',tileStart);const tileExpr=detalleSrc.slice(tileStart,tileEnd).trim().replace(/,$/,'');e.tile=o=>h('article',{'data-color':o.estado},o.valor,o.unidad,h('small',{},o.contexto));e.f=oldRow;e.d={fuentes:{ghl:oldSource}};e.ctx={hoy:'2026-10-04'};e.sinDato=()=> '—';const oldTile=vm.runInContext(tileExpr,e);assert.equal(oldTile.attrs['data-color'],'gris');assert(oldTile.textContent.includes('2/5'));assert(!oldTile.textContent.includes('de 5 leads'));e.f={...typedPositive,motivos:oldRow.motivos};e.d={fuentes:{ghl:sf}};const currentTile=vm.runInContext(tileExpr,e);assert.equal(currentTile.attrs['data-color'],'ambar');count++;
const huge=M.agregarSinIntento677([{...legacy,sin_tocar_24h:Number.MAX_SAFE_INTEGER},{...legacy,sub_id:'legacy2',sin_tocar_24h:1}],sf,'2026-10-04',nowSin);assert.equal(huge.referencia,null);assert.equal(huge.todoScope,false);count++;
const catSource=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');const catOptions=[];e.fichaCatalogo=(i,o)=>{catOptions.push({i,...o});return h('span',{},o.valor)};e.plegable=(t,n)=>n;e.rejillaTarjetas=x=>h('div',{},x);e.pieFase2=()=>null;vm.runInContext(catSource.slice(catSource.indexOf('function indicadoresPuesto('),catSource.indexOf('// ------------------------------------------------------------------ detalle de una subcuenta')),e);e.indicadoresPuesto({indicador:x=>x,indicadores:()=>[]},{en1h:1,juzgables:1,asistencia:null,sinEstado14:null,sinTocar:1,sinIntentoLectura677:{todoScope:false},pctWa:null},{},{jefatura:false});const vel=catOptions.find(x=>x.i==='especialista_ghl.velocidad_del_despacho_con_el_lead');assert.equal(vel.valor,'1/1');assert.equal(vel.unidad,'');assert.equal(vel.estado,'gris');assert(vel.parcial.includes('no tasa vigente'));count++;
console.log(`${count} escenarios677 PASS · helper+rendererLeads real; baselineSí sin descriptor reproducido.`);
})().catch(x=>{console.error(x);process.exitCode=1});
