const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(tag,attrs,...children){this.tag=tag;this.attrs=attrs||{};this.children=children.flat().filter(x=>x!=null);this.style={};this.dataset={};this.isConnected=true;this.events={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x.filter(x=>x!=null);}addEventListener(k,f){this.events[k]=f;}querySelector(){return null;}querySelectorAll(){return [];}setAttribute(k,v){this.attrs[k]=v;}remove(){}focus(){} }
const h=(t,a,...c)=>new El(t,a,...c),txt=n=>n instanceof El?n.children.map(txt).join(' '):String(n??'');
const s={console,Date,Map,Set,JSON,Number,Array,String,Object,Promise,h,icono:()=>'',chipEstado:(c,t)=>h('span',{},t),vacio:o=>h('p',{},o.titulo,o.texto),esqueleto:()=>h('p',{},'Leyendo'),panel:(o,...c)=>h('section',{},o.titulo,...c),logoCliente:()=>'',iniciales:()=>'',fmt:x=>x,fechaCorta:x=>x,diaMes:x=>x,conTickets:x=>x,avisoFlotante:()=>{},copiar:async()=>{},requestAnimationFrame:()=>{},setTimeout,MutationObserver:class{observe(){}},window:{matchMedia:()=>({matches:false})},history:{replaceState(){}},document:{getElementById:()=>null},chipsFiltro:()=>({valor:()=>''})};vm.createContext(s);
function load(file){const raw=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8');const names=[...raw.matchAll(/^export (?:async )?(?:function|const) (\w+)/gm)].map(x=>x[1]);const src=raw.replace(/^import .*$/gm,'').replace(/export default /,'const modulo333=').replace(/export /g,'');if(raw.includes('export default'))names.push('modulo333');Object.assign(s,vm.runInContext('(()=>{'+src+'\nreturn {'+names.join(',')+'};})();',s));}
load('_alcance_asistente_333');load('ia_componentes');s.estilosIA=s.estilos;s.pestanas=o=>{const z=h('div',{});o.pintar(o.activa,z);z.elegir=id=>o.pintar(id,z);return z;};load('asistente_ia');
const persona={id:'mili',estado:'activo',puestos:['operaciones']},cliente={id:'c',nombre:'Nombre vigente',activo_confirmado:true,detalle:true};
function ctx(){return {real:{...persona},persona:{...persona},datos:{personas:[{...persona}]},clientesVisibles:[{...cliente}],servidor:true,veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,params:[],titulo(){},api:async route=>route==='ia/lista'?{copiloto:[],borradores:[],estado:{conectada:false}}:{ok:false,motivo:'Sin propuesta'}};}
const dto={copiloto:[{cliente_id:'c',nombre:'Nombre viejo',color:'rojo'},{cliente_id:'privado',nombre:'NO_EXPONER'}],borradores:[{cliente_id:'c',ticket:'RO-1',cliente:'Nombre viejo'}],estado:{}};
let count=0;const test=async f=>{await f();count++;};
(async()=>{
await test(()=>{const x=s.listaAsistente333(ctx(),dto);assert.equal(x.copiloto.length,1);assert.equal(x.copiloto[0].nombre,'Nombre vigente');assert.equal(x.borradores[0].cliente,'Nombre vigente');});
for(const mutate of [c=>c.real.estado='baja',c=>c.persona.activo=false,c=>c.datos.personas.push({...persona}),c=>c.datos.personas[0].activo=false,c=>c.veModulo=()=>false,c=>c.vigente=()=>false])await test(()=>{const c=ctx();mutate(c);assert.equal(s.listaAsistente333(c,dto),null);});
for(const mutate of [c=>c.clientesVisibles.push({...cliente}),c=>c.clientesVisibles[0].activo_confirmado=false,c=>c.ver=()=>({ok:false})])await test(()=>{const c=ctx();mutate(c);assert.equal(s.listaAsistente333(c,dto).copiloto.length,0);});
await test(()=>{const x=s.listaAsistente333(ctx(),{...dto,copiloto:[dto.copiloto[0],dto.copiloto[0]],borradores:[dto.borradores[0],dto.borradores[0]]});assert.equal(x.copiloto.length,0);assert.equal(x.borradores.length,0);});
await test(async()=>{const root=h('main',{});await s.modulo333.render(root,ctx());assert(txt(root).includes('0 clientes'));assert(txt(root).includes('Sin borradores disponibles'));assert(!txt(root).includes('40 correos'));assert(!txt(root).includes('11 clientes'));});
await test(async()=>{const c=ctx(),root=h('main',{});let release;c.api=()=>new Promise(r=>release=r);const pending=s.modulo333.render(root,c);c.clientesVisibles[0].activo_confirmado=false;release(dto);await pending;assert.equal(txt(root),'');});
await test(async()=>{let release;const c=ctx();c.api=()=>new Promise(r=>release=r);let valid=true;const box=s.panelCopiloto(c,'c',{vigente:()=>valid});valid=false;release({ok:true,diagnostico:['PRIVATE_PENDING'],acciones:[]});await new Promise(r=>setImmediate(r));assert(!txt(box).includes('PRIVATE_PENDING'));});
await test(async()=>{let release;const c=ctx();c.api=()=>new Promise(r=>release=r);let valid=true;const box=s.botonIA(c,{ticket:'RO-1',abierto:true,vigente:()=>valid});valid=false;release({ok:true,cuerpo:'PRIVATE_PENDING',asunto:'PRIVATE_PENDING'});await new Promise(r=>setImmediate(r));assert(!txt(box).includes('PRIVATE_PENDING'));});
await test(async()=>{const c=ctx();let calls=0;c.api=async()=>{calls++;return {};};s.panelCopiloto(c,'c',{vigente:()=>false});s.botonIA(c,{ticket:'RO-1',abierto:true,vigente:()=>false});assert.equal(calls,0);});
await test(async()=>{const c=ctx();c.api=async()=>({ok:true,origen:'precalculado',generado:'2026-10-02T18:00:00Z',color:'rojo',diagnostico:['Señal histórica'],acciones:[]});const box=s.panelCopiloto(c,'c',{vigente:()=>true});await new Promise(r=>setImmediate(r));assert(txt(box).includes('Propuesta histórica del'));assert(txt(box).includes('Comprueba los hechos y responsables actuales antes de actuar.'));assert(txt(box).includes('Señal histórica'));});
console.log(count+' grupos333 PASS: lista/ACT/duplicados/cambios durante lectura y propuestas/borradores async.');
})().catch(e=>{console.error(e);process.exitCode=1;});
