const fs=require('fs'),vm=require('vm'),assert=require('assert');
class E{constructor(tag,attrs,...cs){this.tag=tag;this.attrs=attrs||{};this.children=[];this.value='';this.events={};this.root=false;this.append(...cs.flat());}get isConnected(){return this.root||!!this.parent?.isConnected;}get childNodes(){return this.children;}append(...xs){for(const x of xs.flat().filter(x=>x!=null)){this.children.push(x);if(typeof x==='object')x.parent=this;}}replaceChildren(...xs){for(const x of this.children)if(typeof x==='object')x.parent=null;this.children=[];this.append(...xs);}addEventListener(k,f){this.events[k]=f;}set textContent(v){this.replaceChildren(String(v));}}
const h=(...args)=>new E(...args),text=n=>typeof n==='object'?(n.children||[]).map(text).join(' '):String(n??''),all=n=>typeof n==='object'?[n,...(n.children||[]).flatMap(all)]:[];
const s={h,Date,Intl,JSON,Array,Object,Number,String,RegExp,Map,Set,Promise,encodeURIComponent,console};vm.createContext(s);
function load(file,names){Object.assign(s,vm.runInContext('(()=>{'+fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\nreturn {'+names.join(',')+'};})()',s));}
load('_horas_diarias_238',['serieHorasDiaria238']);load('_historial_diario_364',['cargarHistorial364','historialVigente364']);load('_notas_horas_383',['ambitoNotasHoras383','cargarNotasHoras383','notasHorasVigentes383','serieNota383','semanaNota383','graficoNota383']);load('_operaciones_notas_equipo_281',['panelEquipoNotas281']);
const a={id:'m',estado:'activo',activo:true,puestos:['operaciones']},p={id:'p',estado:'activo',activo:true,puestos:['seo']},rows=[{persona_id:'p',nombre:'Persona sintética'}];
const ctx=()=>({real:{...a},persona:{...a},datos:{personas:[{...a},{...p}]},servidor:true,hoy:'2026-10-04',ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,api:async()=>dto()});
function raw(){const cut='2026-10-04',start=Date.parse(cut+'T00:00:00Z')-90*864e5;const dias=Array.from({length:90},(_,i)=>({fecha:new Date(start+i*864e5).toISOString().slice(0,10),estado:i===88?'observado':'sin_dato',horas:i===88?2:null,entradas:i===88?1:null}));return{version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona_confirmada:true,zona:'Europe/Madrid',corte_fecha:cut,fecha_fuente_utc:'2026-10-04T00:00:00Z',desde:dias[0].fecha,hasta:dias.at(-1).fecha,dias,atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true};}
function dto(){return{version:'362.1',estado:'copia_observada',generado:'2026-10-04T00:00:00Z',unidad:'h',cumplimiento:null,capacidad_contractual:null,fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',personas:[{persona_id:'p',historial_diario:raw()}]};}
const serie=()=>{const r=raw();return{persona_id:'p',dias:r.dias,desde:r.desde,hasta:r.hasta,corte:r.corte_fecha,zona:r.zona,fecha_fuente:r.fecha_fuente_utc};};let n=0;
(async()=>{
 const r=s.serieNota383(serie(),'2026-10-04');assert(r);assert.equal(r.dias.length,14);assert.equal(r.dias.filter(x=>x.horas===null).length,13);assert.equal(s.semanaNota383(serie(),'2026-10-04').valor,2);assert.equal(s.semanaNota383(serie(),'2026-10-04',true),null);n++;
 const tiny=serie();tiny.dias[88].horas=1e-8;assert(s.graficoNota383(h,s.serieNota383(tiny,'2026-10-04')).children.some(x=>x.attrs.title.includes('<0,001 h observadas')));n++;
 const z=serie();z.dias[88].horas=0;assert.equal(s.semanaNota383(z,'2026-10-04').valor,0);assert.equal(s.graficoNota383(h,s.serieNota383(z,'2026-10-04')).children.filter(x=>x.attrs.title.includes('0 h')).length,1);n++;
 for(const change of [x=>x.dias[0].fecha='2026-02-30',x=>x.dias[88].horas=-1,x=>x.dias[88].horas=Infinity,x=>x.dias[88].entradas=0,x=>x.dias[0].horas=0,x=>x.corte='2026-10-05',x=>x.zona='bad',x=>x.fecha_fuente='2026-02-30T00:00:00Z',x=>x.fecha_fuente='2026-10-05T00:00:00Z']){const z=serie();change(z);assert.equal(s.serieNota383(z,'2026-10-04'),null);}n++;
 let c=ctx(),reads=0;c.api=async path=>{reads++;assert.equal(path,'horas/historial-diario');return dto();};const root=h('main',{});root.root=true;const out=s.panelEquipoNotas281(root,c,rows,{hoy:c.hoy}),input=all(root).find(x=>x.tag==='input');input.value='Borrador humano';await out.listo;assert.equal(reads,1);assert.equal(all(root).filter(x=>x.tag==='th').length,7);assert.strictEqual(all(root).find(x=>x.tag==='input'),input);assert.equal(input.value,'Borrador humano');assert(all(root).some(x=>x.attrs['data-horas-nota-383']===''));assert(text(root).includes('2 h'));const holder=all(root).find(x=>x.events?.mouseenter);c.datos.personas[0].puestos=['seo'];holder.events.mouseenter();assert(!all(root).some(x=>x.attrs['data-horas-nota-383']===''));assert.strictEqual(all(root).find(x=>x.tag==='input'),input);n++;
 for(const change of [x=>x.ver=d=>({ok:d.tipo!=='horas_persona'}),x=>x.datos.personas[0].puestos=['seo'],x=>x.datos.personas.push({...p}),x=>x.servidor=false,x=>x.veModulo=()=>false,x=>{x.real.puestos=x.persona.puestos=['operaciones','operaciones'];x.datos.personas[0].puestos=['operaciones','operaciones'];},x=>{x.real.puestos=x.persona.puestos=[5];x.datos.personas[0].puestos=[5];}]){c=ctx();change(c);reads=0;c.api=async()=>{reads++;return dto();};await s.cargarNotasHoras383(c,rows);assert.equal(reads,0);}n++;
 c=ctx();c.api=async()=>{c.ver=()=>({ok:false});return dto();};const revoked=h('main',{});revoked.root=true;await s.panelEquipoNotas281(revoked,c,rows,{hoy:c.hoy}).listo;assert(!all(revoked).some(x=>x.attrs['data-horas-nota-383']===''));assert(!text(revoked).includes('Persona sintética'));n++;
 c=ctx();c.api=async()=>{throw {status:503};};const noData=h('main',{});noData.root=true;await s.panelEquipoNotas281(noData,c,rows,{hoy:c.hoy}).listo;assert.equal(all(noData).filter(x=>x.tag==='th').length,7);assert(!all(noData).some(x=>x.attrs['data-horas-nota-383']===''));assert(!text(noData).includes('0 h'));n++;
 c=ctx();const detached=h('main',{});detached.root=true;c.api=async()=>{detached.root=false;return dto();};await s.panelEquipoNotas281(detached,c,rows,{hoy:c.hoy}).listo;assert(!all(detached).some(x=>x.attrs['data-horas-nota-383']===''));n++;
 console.log(n+' grupos383 PASS: historial real364,14fechas,7columnas,permisos/revocación,unknown/zero y borrador preservado');
})().catch(e=>{console.error(e);process.exitCode=1});
