const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ro294-integrado-'));let n=0;const walk=x=>x&&typeof x==='object'?[x,...x.children.flatMap(walk)]:[];
fs.writeFileSync(path.join(tmp,'componentes.mjs'),`export class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.value=a.value||'';this.append(...xs);}get isConnected(){return this.connected===true||!!this.parent?.isConnected;}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x);}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs);}set textContent(v){this.replaceChildren(v);}get textContent(){return this.children.map(x=>typeof x==='object'?x.textContent:String(x)).join(' ');}addEventListener(t,f){this.events[t]=f;}}export const h=(t,a,...xs)=>new N(t,a,xs);export const chipEstado=(e,v)=>h('span',{},v);`);
for(const f of ['_bandeja_accounts_340','_mensaje_incidente_330','_operaciones_bandeja_270','_pedidos_account_local','_operaciones_feedback_273','_meta_semantica_285'])fs.writeFileSync(path.join(tmp,f+'.mjs'),fs.readFileSync(__dirname+'/modulos/'+f+'.js','utf8').replaceAll("'../componentes.js'","'./componentes.mjs'").replaceAll("'./_bandeja_accounts_340.js'","'./_bandeja_accounts_340.mjs'").replaceAll("'./_mensaje_incidente_330.js'","'./_mensaje_incidente_330.mjs'").replaceAll("'./_pedidos_account_local.js'","'./_pedidos_account_local.mjs'").replaceAll("'./_operaciones_feedback_273.js'","'./_operaciones_feedback_273.mjs'").replaceAll("'./_meta_semantica_285.js'","'./_meta_semantica_285.mjs'"));
const pause=()=>new Promise(r=>setImmediate(r));
(async()=>{const {h}=await import('file://'+tmp+'/componentes.mjs'),M=await import('file://'+tmp+'/_operaciones_bandeja_270.mjs');const cont=h('main',{});cont.connected=true;
 const B={generado:'2026-10-03T10:00:00Z',fuentes:{desk:{hora:'2026-10-03T09:00:00Z',estado:'bien'},zadarma:{hora:'2026-10-03T09:00:00Z',estado:'bien'}},correos:[{id:'t1',cliente_id:'c',horas:49},{id:'t2',cliente_id:'c',horas:50}],llamadas:[{id:'l',cliente_id:'c',ultima:'2026-10-02T10:00:00Z',dias_laborables:1,llamadas:2}],triaje:[]};let asks=0,queueReads=0,posts=0,record=null;
 const refs=[['t1','responder_correo'],['t2','responder_correo'],['l','devolver_llamada']];const ctx={hoy:'2026-10-03',servidor:true,real:{id:'o',estado:'activo',puestos:['operaciones']},persona:{id:'o',estado:'activo',puestos:['operaciones']},datos:{personas:[{id:'o',estado:'activo',puestos:['operaciones']},{id:'a',estado:'activo',puestos:['account']}],asignaciones:[{cliente_id:'c',persona_id:'a',silla:'account',principal:true,confianza:'confirmada',desde:'2026-01-01'}]},clientesVisibles:[{id:'c',nombre:'Fixture',activo_confirmado:true,detalle:true}],veModulo:()=>true,vigente:()=>true,ver:()=>({ok:true}),datosModulo:async p=>p.startsWith('bandeja/')?B:null,api:async(p,o)=>{
  if(p.startsWith('operaciones/feedback'))return {version:'273.1',cliente_id:'c',semana:'2026-09-28',revision:0,actual:null,historial:[],capacidades:{puede_registrar:false}};
  if(o){posts++;record={...o.cuerpo,revision:o.cuerpo.revision+1,autor:'o',receptor:'a',registrado_en:'2026-10-03T12:00Z',origen:'registro_equipo',declarado:true,envio_realizado:false,llamada_realizada:false,respuesta_verificada:false};return {version:'294.1',resultado:'guardado',recibo:record};}
  if(p.includes('?')){asks++;return {version:'294.1',cliente_id:'c',pedidos:record?[record]:[],capacidades:refs.map(([r,t])=>({cliente_id:'c',tipo:t,referencia_id:r,receptor:'a',revision:record?.referencia_id===r?1:0,revision_fuente:'a'.repeat(64),puede_registrar:true,actual:record?.referencia_id===r?record:null}))};}
  queueReads++;return {version:'294.1',cliente_id:null,pedidos:record?[record]:[],truncado:false};
 }};
 await M.renderBandeja270(cont,ctx);await pause();await pause();assert.equal(asks,1);assert.equal(posts,0);n++;
 const widgets=walk(cont).filter(x=>x.attrs['data-pedido-account']==='294');assert.equal(widgets.length,3);assert(widgets.every(x=>x.tag==='details'&&!x.attrs.open));n++;
 const q=walk(cont).find(x=>x.attrs['data-cola-pedidos']==='294');assert.equal(q.tag,'details');assert(!q.attrs.open);assert.match(q.textContent,/0 pendientes en RO/);n++;
 const btn=walk(widgets[0]).find(x=>x.tag==='button'&&x.textContent==='Guardar pedido en RO');assert(!btn.disabled);await btn.events.click();await pause();await pause();assert.equal(posts,1);assert.equal(asks,2);assert.match(q.textContent,/1 pendientes en RO/);assert(queueReads>=2);assert.match(q.textContent,/Pedido en RO/);n++;
 assert.doesNotMatch(cont.textContent,/llamada realizada correctamente|Respuesta enviada|Pedido enviado/);n++;
 ctx.persona.id='otro';await walk(widgets[1]).find(x=>x.tag==='button'&&x.textContent==='Guardar pedido en RO').events.click();assert.equal(posts,1);n++;
 const s=fs.readFileSync(__dirname+'/servir.py','utf8');assert(s.includes('OPERACIONES_PEDIDOS_ACCOUNT_294.enganchar(Manejador, sys.modules[__name__])'));assert(s.indexOf('OPERACIONES_PEDIDOS_ACCOUNT_294.enganchar')<s.indexOf('PILOTO_LECTURA.enganchar(Manejador)'));n++;
 console.log(n+' integración270+294 PASS: montaje, batching, cola, mutación fixture, identidad, hook');})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>fs.rmSync(tmp,{recursive:true,force:true}));
