const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ro294-'));let n=0;function check(f){f();n++}
fs.writeFileSync(path.join(tmp,'componentes.mjs'),`export class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.value=a.value||'';this.append(...xs);}get isConnected(){return this.connected===true||!!this.parent?.isConnected;}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x);}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs);}set textContent(v){this.replaceChildren(v);}get textContent(){return this.children.map(x=>typeof x==='object'?x.textContent:String(x)).join(' ');}addEventListener(t,f){this.events[t]=f;}}export const h=(t,a,...xs)=>new N(t,a,xs);`);fs.writeFileSync(path.join(tmp,'modulo.mjs'),fs.readFileSync(__dirname+'/modulos/_pedidos_account_local.js','utf8').replace("'../componentes.js'","'./componentes.mjs'").replace("'./_mensaje_incidente_330.js'","'./_mensaje_incidente_330.mjs'"));fs.writeFileSync(path.join(tmp,'_mensaje_incidente_330.mjs'),fs.readFileSync(__dirname+'/modulos/_mensaje_incidente_330.js','utf8'));const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[];
(async()=>{const {h}=await import('file://'+tmp+'/componentes.mjs'),M=await import('file://'+tmp+'/_mensaje_incidente_330.mjs'),P=await import('file://'+tmp+'/modulo.mjs');
const row={cliente_id:'c',tipo:'responder_correo',referencia_id:'t'},cap={...row,receptor:'a',revision:0,revision_fuente:'a'.repeat(64),puede_registrar:true};
const ctx=()=>({servidor:true,real:{id:'o'},persona:{id:'o'},clientesVisibles:[{id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true}],datos:{personas:[{id:'a',nombre:'Account fixture',estado:'activo'},{id:'o',nombre:'Operaciones fixture',estado:'activo'}]},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true});
check(()=>{const text=M.mensajeIncidencia330(ctx(),row,cap);assert.match(text,/Account fixture/);assert.match(text,/confirmar si requiere respuesta/);assert.doesNotMatch(text,/contrato|18:00|48 h|no tuvo reunión/);});
for(const alter of [c=>c.real.id='foreign',c=>c.soloLectura=true,c=>c.ver=()=>({ok:false}),c=>c.clientesVisibles=[],c=>c.clientesVisibles[0].activo_confirmado=false,c=>c.veModulo=()=>false])check(()=>{const c=ctx();alter(c);assert.equal(M.mensajeIncidencia330(c,row,cap),null);});
check(()=>assert.equal(M.mensajeIncidencia330(ctx(),row,{...cap,receptor:null}),null));
for(const alterar of [c=>c.datos.personas.push({...c.datos.personas[0]}),c=>c.datos.personas[0].estado='baja',c=>c.datos.personas[0].activo=false,c=>c.datos.personas[0].nombre='',c=>c.datos.personas=c.datos.personas.filter(p=>p.id!=='a'),c=>c.datos.personas[1].activo=false,c=>c.datos.personas.push({...c.datos.personas[1]})])check(()=>{const c=ctx();alterar(c);assert.equal(M.mensajeIncidencia330(c,row,cap),null)});

let copied=[],posts=0;Object.defineProperty(globalThis,'navigator',{value:{clipboard:{writeText:async x=>copied.push(x)}},configurable:true});
const c=ctx();c.api=async(u,o)=>{if(o)posts++;return {version:'294.1',cliente_id:'c',capacidades:[cap]}};
const widget=P.crearPedidoAccount294(c,row),parent=h('main',{});parent.connected=true;parent.append(widget.elemento);await widget.cargar();
const btn=walk(parent).find(x=>x.tag==='button'&&x.textContent==='Copiar mensaje'),area=walk(parent).find(x=>x.tag==='textarea');
check(()=>{assert(!btn.disabled);assert.equal(posts,0);assert.equal(copied.length,0)});area.value='Borrador editado';await btn.events.click();check(()=>{assert.equal(copied[0],'Borrador editado');assert.match(parent.textContent,/Copiado/);assert.equal(posts,0)});
navigator.clipboard.writeText=async()=>{throw Error('denied')};await btn.events.click();check(()=>{assert.match(parent.textContent,/No se pudo copiar/);assert(!btn.disabled)});
c.clientesVisibles=[];await btn.events.click();check(()=>{assert.equal(copied.length,1);assert(btn.disabled);assert.equal(area.value,'')});
let finish;const c2=ctx(),w=M.crearMensajeIncidencia330(h,c2,row,()=>cap,()=>true),p2=h('main',{});p2.connected=true;p2.append(w.elemento);w.actualizar();const b2=walk(p2).find(x=>x.tag==='button');navigator.clipboard.writeText=()=>new Promise(r=>finish=r);const waiting=b2.events.click();c2.ver=()=>({ok:false});finish();await waiting;check(()=>{assert(b2.disabled);assert.doesNotMatch(p2.textContent,/Copiado/);assert.equal(walk(p2).find(x=>x.tag==='textarea').value,'')});
console.log(n+' grupos330 PASS: borrador, grants, ACT, identidad, Clipboard éxito/fallo y revocación, cero POST');})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>fs.rmSync(tmp,{recursive:true,force:true}));
