// Audita fuente real 265 con h real; sin navegador/red/POST.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),cp=require('child_process');
class N{};class T extends N{constructor(t){super();this.value=t;}}
class E extends N{constructor(t){super();this.tag=t;this.children=[];this.events={};this.isConnected=true;this.open=false;this.style={};this.attrs={};}append(...xs){for(const x of xs)this.children.push(x instanceof N?x:new T(String(x)));}replaceChildren(...xs){this.children=[];this.append(...xs);}addEventListener(k,f){this.events[k]=f;}setAttribute(k,v){this.attrs[k]=v;}}
const document={createElement:t=>new E(t),createTextNode:t=>new T(t)},s={document,Node:N,Date,Intl,Map,Set,JSON,Number,String,Array,Object,Promise,console,urlSegura:x=>x};vm.createContext(s);
let component=fs.readFileSync(__dirname+'/componentes.js','utf8');component=component.slice(component.indexOf('export function h('),component.indexOf('const svgNS')).replace('export ','');vm.runInContext(component,s);
s.panel=(o,n)=>s.h('section',{},s.h('h2',{},o.titulo),o.sub,n);s.tablaDensa=()=>s.h('table',{});s.panelRituales269=async()=>{};s.chipEstado=()=>s.h('i',{});
// Dependencia real392 aislada: evita colisiones de declaraciones con265, sin mocks.
const declarativo392=fs.readFileSync(__dirname+'/modulos/_rastro_declarativo_392.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');
vm.runInContext('(function(){'+declarativo392+';globalThis.renderRastroDeclarativo392=renderRastroDeclarativo392;})();',s);
vm.runInContext(fs.readFileSync(__dirname+'/modulos/_operaciones_dia_direccion_265.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),s);
const all=n=>n instanceof E?[n,...n.children.flatMap(all)]:[],txt=n=>n instanceof T?n.value:n instanceof E?n.children.map(txt).join(' '):'',p={id:'mili',nombre:'Autor-fixture',estado:'activo',activo:true,puestos:['operaciones']},cli={id:'ok',nombre:'Cliente-fixture',activo_confirmado:true,detalle:true};
const ctx=()=>({real:{...p,puestos:[...p.puestos]},persona:{...p,puestos:[...p.puestos]},datos:{personas:[{...p,puestos:[...p.puestos]}]},clientes:[{...cli}],clientesVisibles:[{...cli}],ver:x=>({ok:x.cliente_id==='ok'}),veModulo:()=>true,vigente:()=>true,servidor:true,datosModulo:async()=>({}),api:async()=>({})});
const row=(extra={})=>({creada:'2026-10-03T22:10:00Z',quien:'mili',accion:'leer',coleccion:'tareas',datos:{cliente_id:'ok'},...extra}),now=Date.parse('2026-10-04T12:00:00Z');let tests=0;
const check=(n,fn)=>{fn();tests++;};
(async()=>{
check('SQL UTC y offset misma hora Madrid',()=>{for(const stamp of ['2026-10-02 23:10:00','2026-10-03T01:10:00+02:00','2026-10-02T23:10:00Z']){const d=s.porDia379(ctx(),[row({creada:stamp})],now)[0];assert.equal(d.dia,'2026-10-03');assert.equal(d.filas[0].cuando,'03/10/2026, 01:10 · Madrid');}});
check('Madrid transición DST sin cambiar fecha/hora',()=>{let d=s.porDia379(ctx(),[row({creada:'2026-03-29T01:10:00Z'})],now)[0];assert.equal(d.filas[0].cuando,'29/03/2026, 03:10 · Madrid');});
check('desconocidos no detalle/estado',()=>{for(const x of ['2026-04-31T12:00:00Z','2026-10-03T22:10:61Z','2026-10-03T22:10:00+99:99','2099-01-01']){const d=s.porDia379(ctx(),[row({creada:x,nota:'secret-marker',estado:'cumplido'})],now)[0];assert.equal(d.dia,'Fecha sin confirmar');assert.equal(d.filas.length,0);assert(!JSON.stringify(d).includes('secret-marker'));}});
check('contradicciones y tipo payload no llegan',()=>{for(const x of [{datos:{cliente_id:'foreign'}},{cliente_id:'foreign'},{datos:'[]'},{datos:'"ok"'},{datos:{cliente_id:23}}])assert.equal(s.porDia379(ctx(),[row(x)],now).length,0);const d=s.porDia379(ctx(),[row({datos:{cliente_id:'ok',nota:'secret-marker',start_url:'secret-marker'},nota:'secret-marker',estado:'cerrado',accion:'<script>secret-marker</script>'})],now);assert(!JSON.stringify(d).includes('secret-marker'));assert(!JSON.stringify(d).includes('cerrado'));});
check('sincliente explícito permanece sinatribuir',()=>{const d=s.porDia379(ctx(),[row({datos:{cliente:'Cliente-fixture'},cliente_id:null})],now);assert.equal(d[0].filas[0].cliente_id,null);});
for(const change of [c=>c.persona.puestos=['direccion'],c=>c.real.activo=false,c=>c.persona.estado='baja',c=>c.datos.personas.push({...p}),c=>c.real.puestos=['operaciones','operaciones'],c=>c.veModulo=x=>x!=='decisiones']){const c=ctx();change(c);let reads=0;c.api=c.datosModulo=async()=>{reads++;return{};};await s.renderDiaDireccion265(s.h('main',{}),c,'rastro');assert.equal(reads,0);}tests++;
for(const change of [c=>c.ver=()=>({ok:false}),c=>c.clientes.push({...cli}),c=>c.clientesVisibles=[],c=>c.persona.puestos=['seo'],c=>c.vigente=()=>false]){const c=ctx();c.api=async path=>{if(path==='rastro'){change(c);return{registro:[row()]};}return{};};const root=s.h('main',{});await s.renderDiaDireccion265(root,c,'rastro');assert(!txt(root).includes('Autor-fixture'));assert(!all(root).some(n=>n.tag==='details'));}tests++;
for(const change of [c=>c.clientes[0].activo_confirmado=false,c=>c.datos.personas[0].puestos=['seo'],c=>c.ver=()=>({ok:false}),c=>c.veModulo=x=>x!=='decisiones']){const c=ctx();c.api=async path=>path==='rastro'?{registro:[row()]}:{};const root=s.h('main',{});await s.renderDiaDireccion265(root,c,'rastro');const d=all(root).find(n=>n.tag==='details');assert(d);assert(!txt(root).includes('Autor-fixture'));d.open=true;d.events.toggle();assert(txt(root).includes('Autor-fixture'));assert(txt(root).includes('04/10/2026, 00:10 · Madrid'));assert(txt(root).includes('Cuándo Cliente Quién Qué Dónde'));change(c);d.open=false;d.events.toggle();assert(!txt(root).includes('Autor-fixture'));assert(!all(root).some(n=>n.tag==='details'));}tests++;
check('autor histórico incierto no identidadactual asumida',()=>{for(const mutate of [c=>c.datos.personas[0].estado='baja',c=>c.datos.personas.push({...p})]){const c=ctx();mutate(c);assert.equal(s.porDia379(c,[row()],now)[0].filas[0].quien,'Autor sin confirmar');}});
// Montaje265 con fuente392 real: DTO leído por300 sobre SQLite temporal, no inventado.
const dto392=JSON.parse(cp.execFileSync('python3',[__dirname+'/fixture_rastro_392.py'],{encoding:'utf8',cwd:__dirname}));
const integrado=()=>{const c=ctx(),actor={id:'ops',nombre:'Actor392-fixture',estado:'activo',puestos:['operaciones']},cliente={id:'c',nombre:'Cliente392-fixture',activo_confirmado:true,detalle:true};c.hoy='2026-10-03';c.real={...actor};c.persona={...actor};c.datos.personas=[actor];c.clientes=[{...cliente}];c.clientesVisibles=[cliente];c.ver=x=>({ok:x.cliente_id==='c'});return c;};
{
 const c=integrado(),calls=[];c.api=async path=>{calls.push(path);return path==='operaciones/prioridades'?JSON.parse(JSON.stringify(dto392)):path==='rastro'?{registro:[row({quien:'ops',datos:{cliente_id:'c'},creada:'2026-10-03T12:00:00Z'})]}:{};};const root=s.h('main',{});await s.renderDiaDireccion265(root,c,'rastro');assert.deepEqual(calls,['decisiones','rastro','operaciones/prioridades']);const cifras403=all(root).find(n=>n.attrs['data-resumen-rastro-403']!==undefined);assert(cifras403);assert.equal(all(cifras403).filter(n=>n.tag==='strong').map(txt).join(','),'2,2,1');const detalle=all(root).find(n=>n.tag==='details'&&txt(n).includes('2026-10-03 · 2 revisiones'));assert(detalle);detalle.open=true;detalle.events.toggle();assert.equal(all(detalle).filter(n=>n.tag==='th').length,5);assert(txt(detalle).includes('Comprobado por mí'));assert(txt(detalle).includes('Cliente392-fixture'));c.clientes[0].activo_confirmado=false;detalle.events.toggle();assert(!txt(root).includes('Comprobado por mí'));tests++;
}
{
 const c=integrado();let resolve,called;const started=new Promise(r=>called=r);c.api=async path=>{if(path==='operaciones/prioridades'){called();return new Promise(r=>resolve=r);}return path==='rastro'?{registro:[]}:{};};const root=s.h('main',{}),pending=s.renderDiaDireccion265(root,c,'rastro');await started;c.persona.id='revocada';resolve(dto392);await pending;assert(!txt(root).includes('Actor392-fixture'));assert(!txt(root).includes('Comprobado por mí'));assert(!all(root).some(n=>n.tag==='details'));tests++;
}
check('montaje declarativo limitado a Rastro en caller real',()=>{const source=fs.readFileSync(__dirname+'/modulos/_operaciones_dia_direccion_265.js','utf8');assert(source.includes("if(clave==='rastro')await renderRastroDeclarativo392(rastroDestino392,ctx,{vigente});"));});
console.log(tests+' grupos independientes379B PASS: h real, scope/grants, revocaciónlazy/await, Madrid/DST, whitelist y unknown.');
})().catch(e=>{console.error(e);process.exitCode=1;});
