const fsB=require('fs'),baseB=fsB.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];
new Function('require','__dirname',baseB+`
(async()=>{
let cases=0;const diaria={tipo:'diaria',observado:true,fuente:'ClickUp entradas',cobertura:'parcial',hoy:'2026-10-05',fecha:'2026-10-02',fecha_fuente:'2026-10-05T00:56:00Z',referencia_horas:8};
const ratio={...diaria,tipo:'porcentaje',desde:'2026-09-28',hasta:'2026-10-02',laborables:5,referencia_horas:40};
const parse=x=>Number(x.replaceAll('.','').replace(',','.'));
for(const [tipo,thresholds]of [['diaria',[6,8]],['porcentaje',[60,90]]])for(const t of thresholds)for(const eps of [.01,.00001,1e-8]){const shown=c.formatearBanda381(t-eps,tipo);assert(shown.startsWith('<')||parse(shown)<t,shown+' debe mantenerse debajo de '+t);assert.equal(c.formatearBanda381(t,tipo),String(t));}cases++;
for(const [v,nivel]of [[0,'baja'],[5.999,'baja'],[6,'media'],[7.999,'media'],[8,'alta']]){const b=c.bandaHoras381(v,diaria);assert.equal(b.nivel,nivel);assert(b.detalle.includes('No acredita jornada'));assert(b.etiqueta.startsWith('Ref.'));}cases++;
for(const [v,nivel]of [[23.999,'baja'],[24,'media'],[35.999,'media'],[36,'alta']]){const b=c.bandaHoras381(v,ratio);assert.equal(b.nivel,nivel);assert(b.detalle.includes('8h × 5 laborables'));}cases++;
for(const v of [null,undefined,false,'8',Infinity,NaN,-1]){assert.equal(c.formatearBanda381(v,'diaria'),null);assert.equal(c.bandaHoras381(v,diaria),null);}assert.equal(c.formatearBanda381(0,'diaria'),'0');assert.equal(c.formatearBanda381(0.0005,'diaria'),'<0,1');cases++;
for(const change of [m=>m.fuente='legado',m=>m.observado=false,m=>m.fecha_fuente='2026-10-06T00:00:00Z',m=>m.fecha='2026-10-06',m=>m.fecha='2026-02-30',m=>m.fecha_fuente='2026-10-03T24:00:00Z']){const m={...diaria};change(m);assert.equal(c.bandaHoras381(8,m),null);}for(const m of [{...ratio,laborables:0},{...ratio,referencia_horas:39},{...ratio,referencia_horas:null}])assert.equal(c.bandaHoras381(40,m),null);cases++;
assert.equal(c.bandaHoras381(1e308,{...ratio,laborables:1,referencia_horas:8}),null);cases++;
function dto(values){const cut='2026-10-05',start=Date.parse(cut+'T00:00:00Z')-90*864e5,dias=Array.from({length:90},(_,i)=>({fecha:new Date(start+i*864e5).toISOString().slice(0,10),estado:'sin_dato',horas:null,entradas:null}));for(const [i,fecha]of ['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'].entries())if(values[i]!==null)Object.assign(dias.find(x=>x.fecha===fecha),{estado:'observado',horas:values[i],entradas:1});return{version:'362.1',estado:'copia_observada',generado:'2026-10-05T05:00:00Z',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',unidad:'h',cumplimiento:null,capacidad_contractual:null,personas:[{persona_id:'p',historial_diario:{version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona:'Europe/Madrid',zona_confirmada:true,desde:dias[0].fecha,hasta:dias.at(-1).fecha,corte_fecha:cut,fecha_fuente_utc:'2026-10-05T00:56:00Z',atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,dias}}]};}
function context(values){const actor={id:'real',estado:'activo',activo:true,puestos:['operaciones']};return{...make(),servidor:true,hoy:'2026-10-05',real:actor,persona:{...actor},datos:{personas:[actor,{id:'p',estado:'activo',activo:true,puestos:['seo']}]},api:async()=>dto(values)};}
let n=new N('main');await c.renderEquipo262(n,context([5.999,7.999,8,0,null]),'equipo-dia');let cells=all(all(n,x=>x.tag==='tbody')[0],x=>x.tag==='span'&&x.attrs.class?.includes('banda381-'));assert.equal(cells.length,4);assert(text(cells[0]).includes('5,999'));assert(!text(cells[0]).includes('Ref. baja'));assert(cells[0].attrs.class.includes('banda381-rojo'));assert(text(cells[1]).includes('7,999'));assert(!text(cells[1]).includes('Ref. media'));assert(cells[1].attrs.class.includes('banda381-ambar'));assert(!text(cells[2]).includes('Ref. alta'));assert(cells[2].attrs.class.includes('banda381-verde'));assert(text(n).includes('Sin dato: gris'));cases++;
for(const hours of [23.99999,35.99999]){n=new N('main');await c.renderEquipo262(n,context([hours,null,null,null,null]),'horas');all(n,x=>x.tag==='button'&&text(x)==='Semana pasada')[0].events.click();const cell=all(all(n,x=>x.tag==='tbody')[0],x=>x.tag==='span'&&x.attrs.class?.includes('banda381-'))[0];assert(cell);const display=text(cell);assert(!display.includes(hours<24?'≥60 %':'≥90 %'));assert(!display.includes('Ref.'));assert(cell.attrs.class.includes(hours<24?'banda381-rojo':'banda381-ambar'));assert(cell.attrs.title.includes('no capacidad contractual'));}cases++;
console.log(cases+' grupos381B independientesPASS: bandas exactas,4bordes,unknown/cero yrender262 real.');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
