const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ro294-'));let n=0;function check(f){f();n++}
fs.writeFileSync(path.join(tmp,'componentes.mjs'),`export class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.value=a.value||'';this.append(...xs);}get isConnected(){return this.connected===true||!!this.parent?.isConnected;}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x);}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs);}set textContent(v){this.replaceChildren(v);}get textContent(){return this.children.map(x=>typeof x==='object'?x.textContent:String(x)).join(' ');}addEventListener(t,f){this.events[t]=f;}}export const h=(t,a,...xs)=>new N(t,a,xs);`);fs.writeFileSync(path.join(tmp,'modulo.mjs'),fs.readFileSync(__dirname+'/modulos/_pedidos_account_local.js','utf8').replace("'../componentes.js'","'./componentes.mjs'").replace("'./_mensaje_incidente_330.js'","'./_mensaje_incidente_330.mjs'"));fs.writeFileSync(path.join(tmp,'_mensaje_incidente_330.mjs'),fs.readFileSync(__dirname+'/modulos/_mensaje_incidente_330.js','utf8'));const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[];
(async()=>{const {h}=await import('file://'+tmp+'/componentes.mjs'),M=await import('file://'+tmp+'/modulo.mjs');const row={cliente_id:'c',tipo:'responder_correo',referencia_id:'t'},ctx=(api,extra={})=>({servidor:true,real:{id:'o'},persona:{id:'o'},clientesVisibles:[{id:'c',nombre:'Fixture',activo_confirmado:true,detalle:true}],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,api,...extra});const read=(x={})=>({version:'294.1',cliente_id:'c',capacidades:[{...row,receptor:'a',revision:0,revision_fuente:'a'.repeat(64),puede_registrar:true,actual:null,...x}]});const receipt=b=>({...b,revision:b.revision+1,autor:'o',receptor:'a',registrado_en:'2026-10-03',origen:'registro_equipo',declarado:true,envio_realizado:false,llamada_realizada:false,respuesta_verificada:false});function mount(c){const p=h('main',{});p.connected=true;p.append(c.elemento);return p;}async function init(api,extra){const c=M.crearPedidoAccount294(ctx(api,extra),row),p=mount(c);await c.cargar();return [c,p,walk(p).find(x=>x.tag==='button'),walk(p).find(x=>x.tag==='select')];}
 let calls=[],saved=null;const [c,p,btn,sel]=await init(async(u,o)=>{calls.push([u,o]);if(!o)return read(saved?{revision:1,actual:saved}:{});saved=receipt(o.cuerpo);return {version:'294.1',resultado:'guardado',recibo:saved}});
 check(()=>{assert(!btn.disabled);assert.match(p.textContent,/Sin pedido local/);assert.equal(calls.filter(x=>x[1]).length,0)});await btn.events.click();check(()=>{assert.equal(calls.filter(x=>x[1]).length,1);assert.match(p.textContent,/Pedido en RO/);assert(btn.disabled)});
 let posts=[];const [rc,rp,rb]=await init(async(u,o)=>{if(!o)return read();posts.push(o.cuerpo);if(posts.length===1)throw Error('Respuesta perdida');return {version:'294.1',resultado:'duplicado',recibo:receipt(o.cuerpo)}});await rb.events.click();await rb.events.click();check(()=>assert.deepEqual(posts[0],posts[1]));
 const [bad,bp,bb]=await init(async(u,o)=>o?{version:'294.1',resultado:'guardado',recibo:{...receipt(o.cuerpo),llamada_realizada:true}}:read());await bb.events.click();check(()=>assert.match(bp.textContent,/recibo coherente/));
 let writes=0;const [v,vp,vb]=await init(async(u,o)=>{if(o)writes++;return read()},{persona:{id:'a'}});await vb.events.click();check(()=>{assert(vb.disabled);assert.equal(writes,0)});
 const [pi,pip,pib]=await init(async()=>read(),{soloLectura:true});check(()=>assert(pib.disabled));
 const [unk,up,ub]=await init(async()=>read({revision_fuente:null}));check(()=>assert(ub.disabled));
 let live=true,resolve;const deferred=new Promise(r=>resolve=r),sc=M.crearPedidoAccount294(ctx(()=>deferred,{vigente:()=>live}),row),sp=mount(sc);const pending=sc.cargar();live=false;resolve(read());await pending;check(()=>assert(walk(sp).find(x=>x.tag==='button').disabled));
 let queries=0;const [foreign,fp,fb]=await init(async()=>{queries++;return read()},{clientesVisibles:[]});check(()=>{assert.equal(queries,0);assert(fb.disabled)});
 const [cf,cfp,cfb]=await init(async(u,o)=>{if(!o)return read();const e=Error('Cambió la copia');e.status=409;throw e});await cfb.events.click();check(()=>{assert(cfb.disabled);assert(walk(cfp).some(x=>x.tag==='button'&&x.textContent==='Recargar copia'&&!x.hidden))});
 check(()=>{const b={...row,estado:'pedido',revision:0,intencion_id:crypto.randomUUID()};assert(M.reciboPedido294({version:'294.1',resultado:'guardado',recibo:receipt(b)},b,'o','a'));assert(!M.reciboPedido294({version:'294.1',resultado:'guardado',recibo:{...receipt(b),cliente_id:'foreign'}},b,'o','a'))});
 console.log(n+' pruebas UI294 PASS');})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>fs.rmSync(tmp,{recursive:true,force:true}));
