const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const b={Intl,URLSearchParams};vm.createContext(b);
const strip=s=>s.replace(/^import .*;\n/gm,'').replace(/export /g,'');
function load(file,names){vm.runInContext(`Object.assign(globalThis,(()=>{${strip(fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8'))};return {${names.join(',')}};})());`,b);}
load('control_cartera',['pautaHorasControl','prepararControlCartera']);load('_operaciones_equipo_262',['horasProyectoRango262','pautaProyectoRango262']);load('_horas_fuegos_341',['ambitoFuegos341','horasFuego341']);
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.attrs=a;this.children=[];this.append(...kids);}get isConnected(){return this.main||!!this.parent?.isConnected;}append(...ns){for(const n of ns.flat(Infinity).filter(x=>x!=null)){if(n instanceof N)n.parent=this;this.children.push(n);}}replaceChildren(...ns){for(const n of this.children)if(n instanceof N)n.parent=null;this.children=[];this.append(...ns);}get textContent(){return this.children.map(n=>n instanceof N?n.textContent:String(n)).join(' ');}}
b.h=(t,a,...ns)=>new N(t,a,ns);b.chipEstado=(e,t)=>b.h('span',{'data-estado':e},t);b.panelPlanFuego255=()=>b.h('p',{},'Plan fixture');b.metricasProyectoBaseline=()=>null;
load('_account_fuegos_346',['accountFuego346','firmaAccountFuegos346']);load('_meta_semantica_285',['semanticaMeta285']);load('_operaciones_fuegos_268',['renderFuegos268']);
const ctx=()=>({servidor:true,hoy:'2026-10-03',real:{id:'ops',estado:'activo',puestos:['operaciones']},persona:{id:'ops',estado:'activo',puestos:['operaciones']},datos:{personas:[{id:'ops',estado:'activo',puestos:['operaciones']}]},clientesVisibles:[{id:'c',nombre:'Fixture',activo_confirmado:true,detalle:true}],veModulo:()=>true,ver:x=>({ok:x.cliente_id==='c'}),verdad:()=>({cliente_id:'c',gravedad:'critico'}),nombre:()=>'',vigente:()=>true});
const P=()=>({hoy:'2026-10-03',proyectos:[{cliente_id:'c',horas_mes:14,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-10-03 02:56',cobertura:'parcial'}}]});
const D=()=>({generado:'2026-10-03 03:00',mes_cuota:'2026-10',clientes:[{cliente_id:'c',cuota_horas:{pautadas:10}}]});
let count=0;const t=(name,f)=>{f();count++;console.log('PASS',name)};

load('_viernes_accounts_347',['ambitoViernes347','filasViernes347']);load('_repartir_accounts_352',['ambitoRepartir352','atribuirReparto352']);load('_operaciones_rituales_264',['filasSaneamiento264','filasRepartir326','renderRituales264','resumenRepartir354']);

const walk=n=>n instanceof N?[n,...n.children.flatMap(walk)]:[];
const fixture=()=>{const c=ctx();c.datos.personas.push({id:'actual',estado:'activo',puestos:['account']},{id:'responsable_seo347',estado:'activo',puestos:['seo']});c.datos.asignaciones=[{cliente_id:'c',silla:'account',persona_id:'actual',principal:true,confianza:'confirmada'}];c.clientesVisibles[0].equipo={account:[{persona_id:'actual',principal:true,confianza:'confirmada'}]};c.clientesVisibles[0].responsable_id='responsable_seo347';c.nombre=id=>id||'Sin nombre';c.datosModulo=async ruta=>ruta.startsWith('produccion')?PP():BB();return c;};
const PP=()=>({generado:'2026-10-03',revisiones:[{id:'t1',cliente_id:'c',tarea:'Tarea fixture',revisa:'account',account_id:'account_cache_inexacto'}]});
const BB=()=>({generado:'2026-10-03',correos:[{id:'k1',cliente_id:'c',horas:12,account_id:'account_cache_inexacto'}]});
const main=()=>{const x=new N('main');x.main=true;return x;};
(async()=>{
const prod=()=>({...PP(),cola:[{id:'blocked',cli:'c',tarea:'Bloqueada fixture',grupo:'bloqueada',estado_determinado:true,estado:'bloqueado',dias_estado:2}]}),band=()=>({...BB(),correos:[{...BB().correos[0],horas:31*24}]}),f=()=>{const c=fixture();c.datosModulo=async ruta=>ruta.startsWith('produccion')?prod():band();return c;};
const c=f(),rows=b.filasRepartir326(c,prod(),band());
t('proyección conservar revisión bloqueo ticket y sólo atribuciónactual',()=>{assert.equal(rows.tareas.length,2);assert.equal(rows.tickets.length,1);assert(rows.tareas.every(r=>r.account_id==='actual'));assert.equal(rows.tickets[0].account_id,'actual');assert(!JSON.stringify(rows).includes('responsable_seo347'));});
const v=main();await b.renderRituales264(v,c,'repartir');t('renderer realagrupa Accountactual no ownercache/generalSEO',()=>{assert(v.textContent.includes('· actual'));assert(v.textContent.includes('Tarea fixture'));assert(v.textContent.includes('Bloqueada fixture'));assert(!v.textContent.includes('account_cache_inexacto'));assert(!v.textContent.includes('responsable_seo347'));assert(v.textContent.includes('no atribuye autoría histórica'));});
for(const [label,change]of [['ausente',x=>{x.datos.asignaciones=[];delete x.clientesVisibles[0].equipo;}],['baja',x=>x.datos.personas[1].estado='baja'],['activo false',x=>x.datos.personas[1].activo=false],['duplicado',x=>x.datos.personas.push({...x.datos.personas[1]})],['otro departamento',x=>x.datos.personas[1].puestos=['seo']],['conflicto',x=>{x.datos.personas.push({id:'otro',estado:'activo',puestos:['account']});x.datos.asignaciones[0].persona_id='otro';}],['fecha futura',x=>{x.datos.asignaciones[0].desde='2026-10-04';x.clientesVisibles[0].equipo.account[0].desde='2026-10-04';}]]){const x=f();change(x);const box=main();await b.renderRituales264(box,x,'repartir');t('owner '+label+' conserva todas incidencias sin atribuirlas',()=>{assert(box.textContent.includes('Account por confirmar'));assert.equal(walk(walk(box).find(n=>n.attrs['data-repartir-detalle']==='354')).filter(n=>n.tag==='tbody').flatMap(n=>n.children).length,3);assert(box.textContent.includes('Tarea fixture'));assert(box.textContent.includes('Bloqueada fixture'));assert(!box.textContent.includes('responsable_seo347'));});}
const high=f();high.datos.asignaciones[0].confianza='alta';high.clientesVisibles[0].equipo.account[0].confianza='alta';const vh=main();await b.renderRituales264(vh,high,'repartir');t('alta muestra responsable registrado sin declarar confirmada',()=>{assert(vh.textContent.includes('actual · asignación por confirmar'));assert(b.filasRepartir326(high,prod(),band()).tareas.every(r=>r.account_confirmado===false));});
for(const [label,change]of [['ACT',x=>x.clientesVisibles[0].activo_confirmado=false],['grant',x=>x.ver=()=>({ok:false})],['roles',x=>x.datos.personas[0].puestos=['seo']],['identidad',x=>x.persona={...x.persona,id:'otro'}],['asignación',x=>x.datos.asignaciones[0].persona_id='otro'],['equipo',x=>x.clientesVisibles[0].equipo.account[0].persona_id='otro'],['módulo',x=>x.veModulo=()=>false]]){const x=f();let finish;const wait=new Promise(r=>finish=r);x.datosModulo=()=>wait;const box=main(),pending=b.renderRituales264(box,x,'repartir');change(x);finish(prod());await pending;t('scope '+label+' invalida lectura antespintar',()=>assert.equal(box.textContent,''));}
for(const event of ['click','focusin','keydown']){const x=f(),box=main();await b.renderRituales264(box,x,'repartir');const root=walk(box).find(n=>n.attrs['data-repartir-326']);x.datos.asignaciones=[];root.attrs.on[event]();t('callback '+event+' limpia atribución tras cambio fuente',()=>assert.equal(box.textContent,''));}
const denied=f();denied.datos.personas.push({...denied.real});let reads=0;denied.datosModulo=async()=>{reads++;return prod();};await b.renderRituales264(main(),denied,'repartir');t('actor duplicado deniega antesGET',()=>assert.equal(reads,0));
const ac=f();ac.real=ac.persona={...ac.datos.personas[1]};ac.carteraPorSilla={account:new Set()};const va=main();await b.renderRituales264(va,ac,'repartir');t('Accountsin cartera no obtiene incidencia visible enotrocontexto',()=>assert(!va.textContent.includes('Tarea fixture')));
const err=f();err.datosModulo=async()=>{throw Error('fixture');};const ve=main();await b.renderRituales264(ve,err,'repartir');t('error copia explícito no cero ni fuente anterior',()=>{assert(ve.textContent.includes('No se pudo leer'));assert(!ve.textContent.includes('Sin revisiones'));});
const antes354=JSON.stringify(rows),overview354=b.resumenRepartir354(rows.tareas,rows.tickets);
t('354 resumen cuenta sólo incidencias proyectadas y no muta filas',()=>{assert.equal(overview354.length,1);assert.equal(overview354[0].tareas,2);assert.equal(overview354[0].tickets,1);assert.equal(overview354[0].edad,2);assert.equal(JSON.stringify(rows),antes354);});
t('354 mayor edad desconocida no cero pero cero explícito se conserva',()=>{assert.equal(b.resumenRepartir354([{account_id:'a',dias:null}],[])[0].edad,null);assert.equal(b.resumenRepartir354([{account_id:'a',dias:0}],[])[0].edad,0);assert.equal(b.resumenRepartir354([],[]).length,0);});
const current354=f(),box354=main();await b.renderRituales264(box354,current354,'repartir');
const detail354=walk(box354).find(n=>n.attrs['data-repartir-detalle']==='354'),button354=walk(box354).find(n=>n.tag==='button'&&n.textContent==='actual');
t('354 detalle cerrado por defecto conserva tres incidencias completas',()=>{assert.equal(detail354.attrs.open,undefined);assert.equal(walk(detail354).filter(n=>n.tag==='tbody').flatMap(n=>n.children).length,3);assert(box354.textContent.includes('Pendientes observados por account'));});
button354.attrs.on.click();t('354 botón macro abre detalle de su account',()=>assert.equal(detail354.open,true));
current354.ver=()=>({ok:false});detail354.open=false;button354.attrs.on.click();t('354 botón macro tras revocación borra vista y no abre detalle',()=>{assert.equal(box354.textContent,'');assert.equal(detail354.open,false);});
const toggleCtx354=f(),toggleBox354=main();await b.renderRituales264(toggleBox354,toggleCtx354,'repartir');const toggleDetail354=walk(toggleBox354).find(n=>n.attrs['data-repartir-detalle']==='354');toggleCtx354.ver=()=>({ok:false});toggleDetail354.open=true;toggleDetail354.attrs.on.toggle();t('354 apertura de detalle por toggle revalida scope y borra datos revocados',()=>assert.equal(toggleBox354.textContent,''));
console.log(count+' grupos352/354 PASS · funciones/repartir264 reales, sin proveedores ni POST');
})().catch(e=>{console.error(e);process.exit(1);});
