const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
class N{constructor(t,a={},kids=[]){this.tag=t;this.attrs=a;this.children=kids.flat(Infinity).filter(x=>x!=null)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}desc(){return [this,...this.children.filter(x=>x instanceof N).flatMap(x=>x.desc())]}}
const h=(t,a,...xs)=>new N(t,a,xs);let n=0;const check=f=>{f();n++};
(async()=>{const helper=fs.readFileSync(__dirname+'/modulos/_nota_compacta_336.js','utf8');const {notaCompacta336}=await import('data:text/javascript;base64,'+Buffer.from(helper).toString('base64'));
const b=notaCompacta336(h,'Fuente · copia parcial',h('p',{},'Explicación disponible'));check(()=>{assert.equal(b.tag,'details');assert.equal(b.attrs.open,undefined);assert.equal(b.children[0].tag,'summary');assert.equal(b.children[0].attrs.style.minHeight,'44px');assert(b.desc().some(n=>n.attrs.role==='note'));assert.match(b.textContent,/Explicación disponible/)});
const seo=fs.readFileSync(__dirname+'/modulos/seo.js','utf8'),crm=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');const st=seo.indexOf('function lineaDatoSR('),end=seo.indexOf('\n}\n',st)+3;
const box={h,notaCompacta336,icono:()=>null,avisoParcial:(t,o)=>h('div',{role:'note','data-critical':true},o.titulo,t)};vm.createContext(box);vm.runInContext(seo.slice(st,end),box);
let out=box.lineaDatoSR({seo:{_meta:{seranking:{texto_dia:'Posiciones · 2-oct',creditos:{fuente:'https://fixture.invalid/docs'}}}}});check(()=>{assert.match(out.textContent,/2-oct/);assert.match(out.textContent,/automática local.*no está acreditada/);assert.doesNotMatch(out.textContent,/se lee cada día|no gasta créditos/);assert(out.desc().some(n=>n.tag==='a'&&n.attrs.href==='https://fixture.invalid/docs'));assert(out.desc().some(n=>n.tag==='details'))});
out=box.lineaDatoSR({seo:{_meta:{seranking:{texto_dia:'Copia · 2-oct',aviso:'Error de lectura fixture'}}}});check(()=>{assert(out.children.some(n=>n?.attrs?.['data-critical']===true));assert.match(out.textContent,/Error de lectura fixture/);assert.match(out.textContent,/2-oct/)});
let nodes=[];const c={h,notaCompacta336,d:{fuentes:{ghl:{hora:'2026-10-03 04:01'}}},contenedor:{append:x=>nodes.push(x)},cont:{append:x=>nodes.push(x)},zona:{append:x=>nodes.push(x)}};vm.createContext(c);
for(const [source,needle] of [[crm,'contenedor.append(notaCompacta336('],[crm,'zona.append(notaCompacta336('],[seo,'cont.append(notaCompacta336(']]){const line=source.split('\n').find(x=>x.includes(needle));vm.runInContext(line.trim(),c);}
check(()=>{assert.equal(nodes.length,3);assert(nodes.every(x=>x.tag==='details'&&x.attrs.open==null));assert.match(nodes[0].children[0].textContent,/04:01/);assert.match(nodes[0].textContent,/no demuestra.*contactado/);assert.match(nodes[0].textContent,/no evalúan.*garantía/);assert.match(nodes[1].textContent,/no marca asistencia ni envía/);assert.match(nodes[1].textContent,/propuestas en cola/);assert.match(nodes[2].textContent,/no todas son objetivos confirmados/);assert.match(nodes[2].textContent,/Google y Maps/)});
check(()=>{assert(crm.includes("if (f.errores_lectura?.length) cont.append(avisoParcial("));assert(seo.includes('if (d.seo._error || d.webs._error)'));assert(crm.includes("texto: 'Se presentó'"));assert(crm.includes("texto: 'No vino'"));assert(crm.includes("texto: 'Reprogramar'"));assert(fs.readFileSync(__dirname+'/modulos/_revision_citas_334.js','utf8').includes("tipo:'cliente_detalle'"));assert(seo.includes("texto: 'Crear tarea'"));});
console.log(n+' grupos336 PASS: details accesible, lectura visible, error visible, acciones/explicaciones conservadas y programación no prometida');})().catch(e=>{console.error(e);process.exitCode=1});
