const fs=require('fs'),path=require('path');
const prefix=fs.readFileSync(path.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
const old=fs.readFileSync(path.join(__dirname,'pruebas_planning_observado_360.cjs'),'utf8');
const fixtures=old.slice(old.indexOf('const SHA360='),old.indexOf('const render360='));
const code405=fs.readFileSync(path.join(__dirname,'pruebas_planning_405.cjs'),'utf8');
const fixtures405=code405.slice(code405.indexOf("load('_planning_observado_360.js'"),code405.indexOf('const render405='));
const tests=`
const open412=n=>{const d=all(n,x=>x.attrs['data-planning-proyectos-412']!==undefined)[0];d.open=true;d.events.toggle();return d;};
(async()=>{
await test('412 closed project section leaves account summary visible',async()=>{const n=new N('main');await c.panelPlanningObservado360(n,ctx405());const d=all(n,x=>x.attrs['data-planning-proyectos-412']!==undefined)[0];assert(d);assert.equal(d.open,false);assert.equal(all(d,x=>x.tag==='table').length,0);assert.equal(all(n,x=>x.tag==='table').length,1);assert(text(n).includes('Por account actual'));assert(text(n).includes('Por proyecto · inventario de planning'));});
await test('412 dash title and ARIA preserve unknown never zero',async()=>{const ctx=ctx405(),d=fixture405();d.filas=d.filas.filter(r=>r.estado==='diario');d.observaciones=1;ctx.api=async()=>d;const n=new N('main');await c.panelPlanningObservado360(n,ctx);const unknown=all(n,x=>x.tag==='td'&&text(x)==='—');assert.equal(unknown.length,4);for(const x of unknown){assert(x.attrs.title.includes('no equivale a cero'));assert(x.attrs['aria-label'].includes('sin observaciones'));}assert(!text(n).includes('Sin dato'));});
await test('412 compact hours coverage only in attributes',async()=>{const ctx=ctx405(),n=new N('main');await c.panelPlanningObservado360(n,ctx);open412(n);const cells=all(n,x=>x.tag==='td');assert(cells.some(x=>text(x)==='5 h'));assert(cells.some(x=>x.attrs.title?.includes('5/5 tareas con estimación observada')));assert(!text(n).includes('h observadas ·'));});
await test('412 opening and individual detail reuses one GET',async()=>{const ctx=ctx405(),n=new N('main');let reads=0;ctx.api=async()=>{reads++;return fixture405();};await c.panelPlanningObservado360(n,ctx);const overview=open412(n),detail=all(overview,x=>x.attrs['data-planning-cliente'])[0];detail.open=true;detail.events.toggle();assert.equal(all(detail,x=>x.tag==='th').length,7);assert.equal(reads,1);overview.open=false;overview.events.toggle();assert.equal(all(overview,x=>x.tag==='td').length,0);overview.open=true;overview.events.toggle();assert.equal(reads,1);assert(text(overview).includes('Cliente uno'));});
await test('412 overview revoked before opening clears all',async()=>{for(const mutate of [ctx=>ctx.clientes[0].activo_confirmado=false,ctx=>ctx.ver=()=>({ok:false}),ctx=>ctx.datos.personas[0].estado='baja']){const ctx=ctx405(),n=new N('main');await c.panelPlanningObservado360(n,ctx);const d=all(n,x=>x.attrs['data-planning-proyectos-412']!==undefined)[0];mutate(ctx);d.open=true;d.events.toggle();assert.equal(text(n),'');}});
await test('412 overview open state survives valid filtering',async()=>{const ctx=ctx405(),n=new N('main');await c.panelPlanningObservado360(n,ctx);open412(n);const client=all(n,x=>x.tag==='select')[0];client.value='c2';client.events.change();const d=all(n,x=>x.attrs['data-planning-proyectos-412']!==undefined)[0];assert.equal(d.open,true);assert(text(d).includes('Sin observaciones autorizadas'));client.value='';client.events.change();assert(text(n).includes('Cliente uno'));});
await test('412 unavailable remains explicit without zero metrics',async()=>{const ctx=ctx405(),n=new N('main');ctx.api=async()=>{throw Error('fixture');};await c.panelPlanningObservado360(n,ctx);assert(text(n).includes('Inventario no disponible'));assert.equal(all(n,x=>x.tag==='table').length,0);});
await test('412 legacy inventory also collapsed without losing five columns',async()=>{const n=new N('main');await c.panelPlanningObservado360(n,ctx360());assert.equal(all(n,x=>x.tag==='table').length,0);open412(n);assert.equal(all(n,x=>x.tag==='th').length,5);});
console.log(checks+' grupos412 PASS · renderer real, lazy, cobertura y revocación');
})().catch(e=>{console.error(e);process.exitCode=1;});
`;
new Function('require','__dirname',prefix+fixtures+fixtures405+tests)(require,__dirname);
