const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const box={Date,Intl,Map,Set,Number,Object,h:()=>({}),fmt:{num:n=>String(n),pct:n=>String(n)+'%',eur:n=>String(n)+'€'},REGLAS:{},FECHAS:{antiguedad:n=>n},hoyMadrid:()=> '2026-10-03'};vm.createContext(box);
for(const [file,names] of [['_meta_semantica_285','semanticaMeta285'],['_paid_mediciones','normalizarPaid,medirCplPaid'],['_crm_mediciones','normalizarFilaCRM,medirEmbudoCRM'],['_resultados_dia_314','clientesDia314,metaDia314,textoMetaDia314,totalMetaDia314,resultadosFilaDia314,crmDia314,fuenteCrmDia314']]){
 const s=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${names}})})()`,box);
}
const s=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{BLOQUES,NUMERO})})()`,box);
const ctx=()=>({hoy:'2026-10-03',servidor:true,persona:{id:'a',puestos:['account']},real:{id:'a'},carteraIds:new Set(['c']),carteraPorSilla:{account:new Set(['c']),trafficker:new Set(['c'])},clientesVisibles:[{id:'c',activo_confirmado:true,nombre:'Fixture'}],clientes:[{id:'c',activo_confirmado:true}],veModulo:()=>true,ver:()=>({ok:true}),datos:{personas:[]}});
const cap=()=>({ventanas:{ayer:'2026-10-02','7d':['2026-09-26','2026-10-02']},datos_hasta:'2026-10-02',clientes:[{cliente_id:'c',nombre:'Fixture',meta_activa:true,equipo:{account:'a',trafficker:'a'},leads:{'7d':8,ayer:0},serie:[{d:'2026-10-02',leads_meta:0}],severidad:'critico',cpl:{'7d':99},cpl_resumen:{ref:99,ref_base:'7d'},objetivo:{cpl_usado:35},motivos:[{texto:'CPL subió',nivel:'critico'}]}]});
const D=(c,crm=null)=>({dato:()=>c,opcional:()=>crm});let n=0;const test=(label,f)=>{f();n++;};
function typed(value=1){const c=cap();c.clientes[0].dinero=true;c.clientes[0].serie=[];for(let i=0;i<7;i++){const d=new Date(Date.parse('2026-09-26')+i*864e5).toISOString().slice(0,10);c.clientes[0].serie.push({d,leads_meta:value,gasto_meta:10,medicion:{version:'220.1',fuente:'meta_insights',nivel:'account',periodo_valido:true,desde:d,hasta:d,fecha_lectura:'2026-10-03T08:00:00Z',cohorte:'resultados_meta_sin_union_crm_ni_cualificacion_ro',campos_observados:['leads','gasto'],tipo_lead:'lead'}});}return c;}
test('Legacy positivo observado no lead y cero desconocido no alarma',()=>{const c=cap(),old=JSON.stringify(c),r=box.BLOQUES.resultados_mios.hacer(ctx(),D(c),{});assert.equal(r.valor,null);assert.equal(r.estado,'gris');assert.equal(r.primero.length,0);assert(r.filas[0].extra.includes('≥8 Resultados Meta'));assert(!JSON.stringify(r).includes('sin leads3'));assert.equal(JSON.stringify(c),old);assert.equal(box.NUMERO.resultados_cartera.hacer(ctx(),D(c)).valor,null);});
test('Cero exacto typed preservado sin juicio trabajo/cualificados',()=>{const c=typed(0),r=box.BLOQUES.resultados_mios.hacer(ctx(),D(c),{});assert.equal(r.valor,'0');assert.equal(r.estado,'gris');assert(r.filas[0].extra.includes('0 eventos lead Meta'));assert.equal(r.primero.length,0);});
test('Positivo exacto typed y totals misma unidad',()=>{const c=typed(2),r=box.BLOQUES.resultados_mios.hacer(ctx(),D(c),{});assert.equal(r.valor,'14');assert(r.filas[0].extra.includes('14 eventos lead Meta'));});
for(const mode of ['missing','duplicate','future','error','store','event'])test(mode+' failclosed',()=>{const c=typed();if(mode==='missing')c.clientes[0].serie.pop();if(mode==='duplicate')c.clientes[0].serie[1]=c.clientes[0].serie[0];if(mode==='future')c.clientes[0].serie[0].medicion.fecha_lectura='2026-10-04';if(mode==='error')c.clientes[0].cuenta_meta={error:'fixture'};if(mode==='store')c.clientes[0].tipo_negocio='tienda_online';if(mode==='event')c.clientes[0].serie[1].medicion.tipo_lead='purchase';assert.equal(box.BLOQUES.resultados_mios.hacer(ctx(),D(c),{}).valor,null);});
for(const mode of ['ACT','grant','duplicate','foreign'])test('scope '+mode,()=>{const c=ctx();if(mode==='ACT')c.clientesVisibles[0].activo_confirmado=false;if(mode==='grant')c.ver=()=>({ok:false});if(mode==='duplicate')c.clientesVisibles.push({...c.clientesVisibles[0]});if(mode==='foreign')c.clientesVisibles=[];assert.equal(box.BLOQUES.resultados_mios.hacer(c,D(typed()),{}).filas.length,0);});
test('TablaPaid no hereda semáforo legacy',()=>{const c=cap(),r=box.BLOQUES.tabla_cuentas.hacer(ctx(),D(c),{});assert.equal(r.estado,'gris');assert.equal(r.filas[0].estado,'gris');assert(r.filas[0].extra.includes('referencia'));});
test('CPL actual97 preservado sólo con descriptor y objetivo',()=>{const c=typed(2),f=c.clientes[0];f.leads['7d']=14;f.gasto={'7d':70};f.cpl_resumen={ref:5,ref_base:'7d',fiable:true,medicion:{...f.serie[0].medicion,desde:'2026-09-26',hasta:'2026-10-02'}};f.objetivo={cargado:true,cpl_objetivo:10,cuando:'2026-10-01',confirmado:true,vigente:true,fuente_generado:'2026-10-03',periodo:'2026-10'};const r=box.NUMERO.resultados_cartera.hacer(ctx(),D(c));assert.equal(r.valor,'100%');assert.equal(r.estado,'verde');f.objetivo.confirmado=false;assert.equal(box.NUMERO.resultados_cartera.hacer(ctx(),D(c)).valor,null);});
test('CRM cola vacía nunca ausencia confirmada',()=>{const crm={subcuentas:[{cliente_id:'c',tipo:'cliente'}],leads_sin_tocar:[],citas_sin_estado:[]};for(const id of ['leads_sin_tocar','citas_sin_estado']){const r=box.BLOQUES[id].hacer(ctx(),D(crm),{});assert.equal(r.valor,null);assert.equal(r.estado,'gris');assert(!JSON.stringify(r).includes('celebrar'));}});
test('Cliente crítico canónico independiente se conserva; ID no autorizado no fila',()=>{const c=cap();c.criticos_casa=['c','foreign'];const x=ctx();x.verdadPorId=new Map([['c',{gravedad:'critico',motivos:['Señal independiente']}]]);const r=box.BLOQUES.cuentas_problema.hacer(x,D(c),{alcance:'todo'});assert.equal(r.filas.length,1);assert.equal(r.filas[0].estado,'rojo');assert(!JSON.stringify(r).includes('foreign'));});
test('Ventana pasada no se presenta como ayer/semana actual',()=>{const c=ctx();c.hoy='2026-10-04';assert.equal(box.BLOQUES.resultados_mios.hacer(c,D(typed()),{}).valor,null);});
console.log(n+' grupos resultadosMiDia314 PASS: bloques reales, unidades/ventanas, legacy, ceros observados, roles/scope y objetivo97.');
