const fs=require('node:fs'),assert=require('node:assert/strict');
let code=fs.readFileSync(__dirname+'/pruebas_produccion_baseline.cjs','utf8');
const checks=`
test('442 headers reales12account/9proyecto completos abreviados',()=>{render();const ts=all(root,x=>x.tag==='table');const th=all(ts[0],x=>x.tag==='th');assert.deepEqual(th.map(text),['Account','Proyectos','Rev. account','+48 h','Rev. técnica','+48 h','Bloq.','En cliente','Sin tareas mes','Creadas sem.','No planif.','Cerradas sem.']);assert.equal(th[8].attrs.title,'Sin tareas este mes');assert.equal(th[9].attrs['aria-label'],'Creadas semana');assert.equal(th[11].attrs.title,'Cerradas semana');assert.equal(th[3].attrs.title,'Revisión account · +48 h');assert.equal(th[5].attrs.title,'Revisión técnica · +48 h');assert.ok(th.every(x=>x.attrs.title===x.attrs['aria-label']));assert.deepEqual(all(ts[1],x=>x.tag==='th').map(text),['Proyecto','Rev. account','Rev. técnica','Bloq.','En cliente','Creadas mes','Creadas sem.','No planif.','Cerradas sem.']);});
test('442 definición caller prioriza y callback queda intacto',()=>{let clicked=0;const col={titulo:'No planificadas',tituloCompleto:'No planificadas · corte de copia y cobertura parcial',valor:()=>7};const tab=c.tablaProduccionBaseline({h,titulo:'Test',columnas:[col],filas:[{}],alFila:()=>clicked++,vigente:()=>true});const th=all(tab,x=>x.tag==='th')[0];assert.equal(text(th),'No planif.');assert.equal(th.attrs.title,col.tituloCompleto);assert.equal(col.titulo,'No planificadas');all(tab,x=>x.tag==='button')[0].events.click();assert.equal(clicked,1);});
test('442 exactmatch no retitula otras ventanas ni valor observado',()=>{const tab=c.tablaProduccionBaseline({h,titulo:'Test',columnas:[{titulo:'Creadas semana anterior',valor:()=>({valor:0,detalle:'0 observado',referencia:false})},{titulo:'Bloqueadas externas',valor:()=>({valor:null,detalle:'Sin observación'})}],filas:[{}]});assert.deepEqual(all(tab,x=>x.tag==='th').map(text),['Creadas semana anterior','Bloqueadas externas']);const td=all(tab,x=>x.tag==='td');assert.equal(text(td[0]),'0');assert.equal(text(td[1]),'—');assert(!all(tab,x=>String(x.attrs.class||'').includes('verde')).length);});
`;
code=code.replace('console.log(`${total} grupos baseline252 PASS`);',checks+'\nconsole.log(`${total} grupos baseline252+442 PASS`);');
const run=require('node:child_process').spawnSync(process.execPath,['-e',code],{cwd:__dirname,encoding:'utf8'});process.stdout.write(run.stdout||'');process.stderr.write(run.stderr||'');assert.equal(run.status,0,'Renderer y h real de producción');
