const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const setup=fs.readFileSync('pruebas_revision_meta_diaria_386B.cjs','utf8').split('let checks=0;')[0],outer={require,console,__dirname:process.cwd()};vm.createContext(outer);vm.runInContext(setup+';globalThis.TEST448={s,h,text,all,ctx,dto,copy};',outer);const {s,h,text,all,ctx,dto,copy}=outer.TEST448;
let n=0;async function test(fn){await fn();n++;}
(async()=>{
await test(async()=>{const root=await s.renderMetaDiaria386(h,ctx(),'ok'),group=all(root,e=>e.attrs?.['data-metricas-campanas-448']!==undefined)[0];assert(group);assert(text(group).includes('CPM'));assert(text(group).includes('CTR tot.'));assert(group.attrs.title.includes('no total de cuenta'));assert(group.attrs.title.includes('2026-10-01'));assert(group.attrs.title.includes('America/Los_Angeles'));assert(text(root).includes('2026-10-01 → 2026-10-01'));assert.equal(all(root,e=>e.tag==='tbody')[0].children.length,1);const headers=all(root,e=>e.tag==='th');assert.deepEqual(Array.from(headers,text),['Día','Ev. lead','Impr.','Clics','Gasto · EUR']);assert.equal(headers[1].attrs['aria-label'],'Eventos lead, no leads calificados');assert.equal(headers[2].attrs.title,'Impresiones');});
await test(async()=>{const c=ctx();c.ver=a=>({ok:a.tipo!=='inversion'});const root=await s.renderMetaDiaria386(h,c,'ok'),group=all(root,e=>e.attrs?.['data-metricas-campanas-448']!==undefined)[0];assert(group);assert(!text(group).includes('CPM'));assert(!text(group).includes('Gasto'));assert(!text(root).includes('781,25'));assert(!text(root).includes('156.250'));assert(!text(root).includes('EUR'));assert(text(group).includes('CTR tot.'));});
await test(async()=>{const c=ctx();c.api=async()=>{const d=copy(dto);delete d.medicion.gasto_observado;delete d.medicion.moneda;delete d.medicion.dias[0].gasto_observado;return d;};const root=await s.renderMetaDiaria386(h,c,'ok'),group=all(root,e=>e.attrs?.['data-metricas-campanas-448']!==undefined)[0];assert(!text(group).includes('CPM'));assert(!text(root).includes('EUR'));});
await test(async()=>{const c=ctx();c.api=async()=>{const d=copy(dto);d.medicion.dias[0].impresiones_observadas=null;return d;};const root=await s.renderMetaDiaria386(h,c,'ok'),group=all(root,e=>e.attrs?.['data-metricas-campanas-448']!==undefined)[0];assert(group);const unknown=all(group,e=>e.tag==='b'&&text(e)==='—');assert.equal(unknown.length,3);assert(!text(group).includes('0 %'));});
await test(async()=>{const c=ctx();c.api=async()=>{c.clientes[0].activo_confirmado=false;return copy(dto);};assert.equal(text(await s.renderMetaDiaria386(h,c,'ok')),'');});
console.log(n+' grupos renderer448 PASS · periodo/cobertura, inversión denegada/ausente, unknown y scope revocado con render386 real.');
})().catch(e=>{console.error(e);process.exitCode=1;});
