// Auditoría/contrato futuro, NO habilita drag ni modifica código de producción.
const fs=require('node:fs');
const base=fs.readFileSync(__dirname+'/pruebas_tablero_mi_trabajo_181.cjs','utf8').split('const a=')[0];
new Function('require','__dirname',base+`
const t={id:'task-192',lista_id:'list-exacta',lista:'Lista sintética',cli:'cli-fixture',persona_id:'yo',tarea:'Tarea sintética',estado:'in progress',tipo_estado:'custom',grupo:'hoy',vence:null};
const cat={'list-exacta':[{estado:'in progress',tipo:'custom'},{estado:'complete',tipo:'closed'},{estado:'completado',tipo:'custom'}]};
let vivo=true,respuesta={ok:true,id:1,sincronia:{id:7,estado:'simulado',texto:'Guardado en RO; no enviado'}};
c.setTimeout=()=>1;
const E=()=>({D:{tareas:[t],estados_detalle:cat},V:{yo:'yo',cambios:[],personas:[{id:'yo'}],estados_detalle:cat},local:[],tableroLista:'list-exacta',ctx:{hoy:'2026-10-03',persona:{id:'yo'},servidor:true,nombre:id=>id,accion:async()=>respuesta},vigente:()=>vivo});
(async()=>{
 let e=E();let r;let b;await assert.rejects(c.actuar(e,t,'cambiar_estado',{a:'complete'},'Estado cambiado'),/intención durable/);assert.equal(e.local.length,0);assert.equal(c.tareasTableroTrabajo181(e,'mias').tareas[0].columna_tablero,'in progress');casos++;
 // 203 cierra el antiguo escape incluso ante respuestas ambiguas: nunca llama al transporte.
 for(const ambiguo of [{ok:true,id:1},{ok:false},{},null]){respuesta=ambiguo;e=E();let enviados=0;e.ctx.accion=async()=>{enviados++;return respuesta;};await assert.rejects(c.actuar(e,t,'cambiar_estado',{a:'complete'},'Estado cambiado'),/intención durable/);assert.equal(enviados,0);assert.equal(e.local.length,0);assert.equal(c.tareasTableroTrabajo181(e,'mias').tareas[0].columna_tablero,'in progress');casos++;}
 e=E();e.ctx.accion=async()=>{throw Error('No debe llamarse');};await assert.rejects(c.actuar(e,t,'marcar_hecha',{},'Hecha'),/intención durable/);assert.equal(e.local.length,0);casos++;
 e=E();vivo=false;await assert.rejects(c.actuar(e,t,'cambiar_estado',{a:'complete'},'Estado cambiado'),/intención durable/);assert.equal(e.local.length,0);vivo=true;casos++;
 e=E();assert.equal(c.resolverEstadoTrabajo(e,t,'complete',true).final_flujo,true);assert.equal(c.resolverEstadoTrabajo(e,t,'completado',true).final_flujo,false);assert.equal(c.resolverEstadoTrabajo(e,t,'Complete',true).estado,'indeterminado');casos++;
 e.V.estados_detalle={};assert.equal(c.resolverEstadoTrabajo(e,t,'complete',true).estado,'indeterminado');casos++;
 e=E();const original=JSON.stringify(e.D);const selected=c.tareasTableroTrabajo181(e,'mias');const vista=c.vistaTableroTrabajo181(e,selected,selected.tareas,()=>{});assert(!buscar(vista,n=>n.attrs?.draggable==='true').length);assert.equal(JSON.stringify(e.D),original);casos++;
 // Helpers DE PRODUCCIÓN 192 y recibo real193, sin prototipo duplicado.
 const revision='a'.repeat(64),uuid='f61a94b8-2091-453e-9299-43b5b1758192';
 c.crypto={randomUUID:()=>uuid};
 const operativo=()=>{const o=E();o.ctx.real={id:'yo'};o.ctx.persona={id:'yo'};o.ctx.soloLectura=false;o.ctx.pilotoLectura=false;o.V.capacidad_transicion={version:'191.1',activo:true};o.V.transiciones={[t.id]:{lista_id:t.lista_id,expected_estado:t.estado,revision,bloqueada:false}};return o;};
 const fila=o=>c.tareasTableroTrabajo181(o,'mias').tareas[0];
 const resolve=o=>(x,s=x.estado,l=false)=>c.resolverEstadoTrabajo(o,x,s,l);
 const recibo=(p,estado='simulado',remoto=false)=>({ok:true,id:1,intencion_guardada:{id:p.intencion_id,accion_id:1,repetida:false},cola_estado:estado,recibo_durable:true,confirmacion_remota:remoto,recibo:{accion_id:1,cambio_id:7,tarea_id:p.objeto,lista_id:p.vista_previa.lista_id,desde:p.vista_previa.expected_estado,hasta:p.vista_previa.a,intencion_id:p.intencion_id,estado_cola:estado,confirmacion_remota:remoto}});
 e=operativo();const row=fila(e);assert(c.permisoMovimiento192(e,row,resolve(e)).ok);const intento=c.crearIntentoMovimiento192(e,row,'complete',resolve(e),uuid);assert.equal(intento.payload.vista_previa.revision,revision);casos++;
 for(const estado of ['simulado','pendiente','enviado','confirmado','fallido','conflicto','descartado']){let r=recibo(intento.payload,estado,estado==='confirmado');const v=c.validarReciboMovimiento192(r,intento);assert(v.valido);assert(!v.mensaje.includes('tarea movida'));casos++;}
 for(const cambio of [{accion_id:2},{cambio_id:0},{cambio_id:1.5},{tarea_id:'ajena'},{lista_id:'otra'},{desde:'otro'},{hasta:'otro'},{intencion_id:'otro'},{estado_cola:'desconocido'},{confirmacion_remota:true}]){const r=recibo(intento.payload);r.recibo={...r.recibo,...cambio};assert.equal(c.validarReciboMovimiento192(r,intento).valido,false);casos++;}
 for(const cambio of [{ok:false},{recibo_durable:false},{id:0},{intencion_guardada:{id:'otra',accion_id:1}},{recibo:null},{cola_estado:'enviado'},{confirmacion_remota:true}])assert.equal(c.validarReciboMovimiento192({...recibo(intento.payload),...cambio},intento).valido,false);casos++;
 for(const cambiar of [o=>delete o.V.capacidad_transicion,o=>o.V.capacidad_transicion.activo=false,o=>o.V.capacidad_transicion.version='otra',o=>delete o.V.transiciones,o=>o.V.transiciones[t.id].bloqueada=true,o=>o.V.transiciones[t.id].lista_id='otra',o=>o.V.transiciones[t.id].revision='no-server-hash',o=>o.V.transiciones[t.id].expected_estado='complete',o=>o.ctx.pilotoLectura=true,o=>o.ctx.soloLectura=true,o=>o.ctx.real.id='otra',o=>o.V.solo_lectura=true,o=>o.V.estados_detalle={},o=>o.tableroLista='otra']){const o=operativo();cambiar(o);assert.equal(c.permisoMovimiento192(o,fila(operativo()),resolve(o)).ok,false);casos++;}
 assert.throws(()=>c.crearIntentoMovimiento192(e,row,'Complete',resolve(e),uuid));assert.throws(()=>c.crearIntentoMovimiento192(e,row,'complete',resolve(e),'not-uuid'));casos++;
 // Transporte aislado: timeout ambiguo + retry de mismo UUID/payload; no altera copia/columna.
 const originalMovimiento=JSON.stringify(e.D);let enviados=[];const copy=JSON.stringify(intento.payload);
 await c.guardarMovimiento192(e,row,intento,resolve(e),async p=>{enviados.push(JSON.stringify(p));throw Error('Respuesta perdida');});assert.equal(intento.estado,'sin_confirmar');assert.equal(c.tareasTableroTrabajo181(e,'mias').tareas[0].columna_tablero,t.estado);
 await c.guardarMovimiento192(e,row,intento,resolve(e),async p=>{enviados.push(JSON.stringify(p));return recibo(p);});assert.equal(intento.estado,'con_recibo');assert.equal(enviados[0],enviados[1]);assert.equal(enviados[0],copy);assert.equal(JSON.stringify(e.D),originalMovimiento);casos++;
 await c.guardarMovimiento192(e,row,intento,resolve(e),async()=>{throw Error('Debe evitar segundo POST');});assert.equal(enviados.length,2);casos++;
 let done;const pending=new Promise(r=>done=r);const waitIntent=c.crearIntentoMovimiento192(e,row,'complete',resolve(e),uuid);const flight=c.guardarMovimiento192(e,row,waitIntent,resolve(e),()=>pending);assert.equal(await c.guardarMovimiento192(e,row,waitIntent,resolve(e),()=>{throw Error('Dobleclick');}),false);vivo=false;done(recibo(waitIntent.payload));await flight;assert.equal(waitIntent.recibo,undefined);vivo=true;casos++;
 // Revocación/identidad/lista/tarea durante await no publica recibos tardíos.
 for(const invalidar of [o=>delete o.V.transiciones,o=>o.ctx.soloLectura=true,o=>o.tableroLista='otra',o=>o.D.tareas=[]]){const o=operativo(),rr=fila(o),ii=c.crearIntentoMovimiento192(o,rr,'complete',resolve(o),uuid);let finish;const hold=new Promise(r=>finish=r);const pp=c.guardarMovimiento192(o,rr,ii,resolve(o),()=>hold);invalidar(o);finish(recibo(ii.payload));assert.equal(await pp,false);assert.equal(ii.recibo,undefined);casos++;}
 // Render real de tablero: ausenciaDTO/consulta=>botón explicativo disabled.
 e=E();let tree=c.vistaTableroTrabajo181(e,c.tareasTableroTrabajo181(e,'mias'),[fila(operativo())],()=>{});let mover=buscar(tree,n=>n.attrs?.['aria-label']==='Mover tarea: '+t.tarea)[0];assert.equal(mover.attrs.disabled,true);assert(text(tree).includes('sólo lectura')||text(tree).includes('revisión vigente'));casos++;
 // Drag sólo prepara selector; teclado/móvil usa idéntico flujo GuardarRO y recibo193.
 e=operativo();let posted=0;e.ctx.accion=async p=>{posted++;return recibo(p);};const paint=()=>{const tab=c.tareasTableroTrabajo181(e,'mias');tree=c.vistaTableroTrabajo181(e,tab,tab.tareas,paint);};paint();assert(!text(tree).includes('Cambio guardado primero'));assert(text(tree).includes('El guardado en RO no confirma el envío'));assert(!text(tree).includes('Al guardar, se solicitará'),'200: aviso idle repetido eliminado; disclosure global permanece');casos++;let article=buscar(tree,n=>n.attrs?.['data-tablero-tarea']===t.id)[0];assert.equal(article.attrs.draggable,'true');
 const transfer={value:'',setData(_,v){this.value=v},getData(){return this.value}};article.attrs.on.dragstart({dataTransfer:transfer,preventDefault(){throw Error('Gated drag debería preparar');}});assert.equal(transfer.value,uuid);assert(!transfer.value.includes(t.id));let column=buscar(tree,n=>n.attrs?.['aria-label']==='Estado exacto: complete')[0];column.attrs.on.drop({dataTransfer:transfer,preventDefault(){}});assert.equal(posted,0);assert.equal(e.movimientos192.get(t.id).destino,'complete');assert(text(tree).includes('Guardar cambio en RO'));casos++;
 const save=buscar(tree,n=>n.tag==='button'&&text(n)==='Guardar cambio en RO')[0];await save.attrs.on.click();assert.equal(posted,1);assert.equal(e.movimientos192.get(t.id).intento.recibo.estado_cola,'simulado');assert(text(tree).includes('no enviado a ClickUp'));assert.equal(c.tareasTableroTrabajo181(e,'mias').tareas[0].columna_tablero,t.estado);casos++;
 e=operativo();paint();mover=buscar(tree,n=>n.attrs?.['aria-label']==='Mover tarea: '+t.tarea)[0];mover.attrs.on.click();const select=buscar(tree,n=>n.tag==='menu'&&n.attrs.config?.etiqueta==='Estado exacto')[0];select.attrs.config.alCambiar('complete');assert.equal(e.movimientos192.get(t.id).destino,'complete');assert.equal(posted,1,'botón Mover no hace POST');casos++;
 console.log(casos+' casos192 PASS: fuente readonly, estado exacto, errores/stale, escapelegacy cerrado203 y helpers/recibo193/render de movimiento gated de PRODUCCIÓN.');
})().catch(e=>{console.error(e);process.exitCode=1});
`)(require,__dirname);
