const fs=require('fs'),path=require('path'),vm=require('vm');
const base=fs.readFileSync(path.join(__dirname,'pruebas_produccion_baseline.cjs'),'utf8').replace(/console.log\(`\$\{total\} grupos baseline252 PASS`\);/,'');
const checks=`
const real360=fs.readFileSync(path.join(__dirname,'modulos/_planning_observado_360.js'),'utf8').replace(/^import[^;]+;\\s*/gm,'').replace(/export /g,'');c.panelPlanningObservado360=vm.runInContext('(function(){'+real360+';return panelPlanningObservado360;})()',c);
const datos405=()=>({version:'405.1',fuente_version:'395.1',sha256_candidato:'f0503e6e5edeaff1fabffb602e5a2bb80ed3e2c432c2bf9fad03ec25c0f8a292',corte_preparacion_utc:'2026-10-03T17:30:00Z',estados_incluidos:['backlog','diario','en curso','planning mensual','planning semanal'],estado:'copia_observada',fuente:'clickup_cache_local',generado:'2026-10-03T18:00:00Z',cobertura:'parcial',lectura_desde_utc:'2026-10-03T17:00:00Z',lectura_hasta_utc:'2026-10-03T17:00:00Z',observaciones:1,cliente_ids:['c'],disciplina:null,cumplimiento:null,filas:[{tarea_id:'task',cliente_id:'c',lista_id:'list',estado:'diario',tipo_estado:'custom',estado_fuente:'clickup',estado_leido_utc:'2026-10-03T17:00:00Z',asignados_persona_ids:['a'],asignacion_estado:'observada',asignados_sin_identidad_confirmada:0,inicio_utc:null,inicio_estado:'sin_dato',vence_utc:null,vence_estado:'sin_dato',estimacion:{valor:null,unidad:'milisegundos',estado:'sin_dato'},cobertura:'parcial',actor_historico:null,estado_inicial:null,rompe_semanal:null,fuego_confirmado:null}]});
const actor405={id:'ops',nombre:'Ops fixture',estado:'activo',puestos:['operaciones']};Object.assign(c.ctx,{servidor:true,hoy:'2026-10-03',real:actor405,persona:actor405,veModulo:()=>true,clientes:c.ctx.clientesVisibles.map(x=>({...x})),vigente:()=>live});c.ctx.datos.personas.push(actor405);for(const p of c.ctx.datos.personas)if(!p.puestos)p.puestos=['account'];
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{let reads=0;c.ctx.api=async route=>{assert.equal(route,'produccion/planning-observado');reads++;return datos405();};render();await tick();assert.equal(reads,1);const region=all(root,x=>x.attrs['data-inventario-produccion-405']!==undefined)[0];assert(text(region).includes('Diario'));assert(text(region).includes('≥1'));assert(text(root).includes('Leyenda de colores y datos'));const nodes=all(root,x=>x.tag==='h2').map(text);assert(nodes.indexOf('Por proyecto')<nodes.indexOf('Inventario de planificación · copia observada'));assert(nodes.indexOf('Inventario de planificación · copia observada')<nodes.indexOf('Disciplina de planificación'));
// Respuesta demorada: reemplazar actor en contexto original debe invalidar el contexto delegado.
let finish;c.ctx.api=()=>new Promise(r=>finish=r);render();await tick();c.ctx.persona={...actor405,id:'otra'};finish(datos405());await tick();const revoked=all(root,x=>x.attrs['data-inventario-produccion-405']!==undefined)[0];assert.equal(text(revoked),'');
console.log('2 grupos montaje real Producción405 PASS · lectura única, orden, leyenda409 y revocación');
})().catch(e=>{console.error(e);process.exitCode=1;});
`;
vm.runInNewContext(base+checks,{require,__dirname,console,setImmediate},{filename:__filename});
