const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_accounts_263.cjs','utf8').split('(async()=>{try{')[0];
const A=new Function('require','__dirname',prefix+';return {dir,walk,text,tables,heads};')(require,__dirname);
const ep=fs.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];
const E=new Function('require','__dirname',ep+';return {c,make,N,all,text};')(require,__dirname);
let groups=0;async function test(name,f){await f();groups++;console.log('PASS',name);}
(async()=>{try{
 const mod=await import('file://'+path.join(A.dir,'_cabeceras_operaciones_423.mjs'));
 const {h}=await import('file://'+path.join(A.dir,'componentes.mjs'));
 const {renderAccounts263}=await import('file://'+path.join(A.dir,'_operaciones_accounts_263.mjs'));
 await test('explicit shorthand preserves original metadata',()=>{for(const [original,short] of [['Sin responder','Sin resp.'],['Semáforo','Estado'],['Empujes de Mili','Emp. Mili'],['Reuniones semana','Reu. sem.']])assert.deepEqual(mod.cabeceraOperaciones423(original),{breve:short,completo:original});});
 await test('unknown dates and blank not inferred or truncated',()=>{for(const x of ['2026-10-01','Etiqueta desconocida larga',''])assert.equal(mod.cabeceraOperaciones423(x).breve,x);const node={tag:'button'};assert.equal(mod.cabeceraOperaciones423(node).breve,node);assert.equal(mod.cabeceraOperaciones423(node).completo,null);});
 for(const route of ['equipo-dia','horas','anomalias','planificacion'])await test('actual Equipo renderer '+route,async()=>{const n=new E.N('main');await E.c.renderEquipo262(n,E.make(),route);const ts=E.all(n,x=>x.tag==='table');assert.deepEqual(ts.map(t=>E.all(t,x=>x.tag==='th').length),Array.from(E.c.INVENTARIO_EQUIPO_262[route].map(x=>x.length)));for(const th of E.all(n,x=>x.tag==='th'))if(th.attrs.title){assert.equal(th.attrs['aria-label'],th.attrs.title);assert.equal(E.text(th),mod.cabeceraOperaciones423(th.attrs.title).breve);}assert(!E.text(n).includes('No autorizado'));});
 await test('daily width reduced scoped without shrinking typography or dropping columns',()=>{const src=fs.readFileSync(__dirname+'/modulos/_operaciones_equipo_262.js','utf8');assert(src.includes('.op-equipo262 .oe-daily{min-width:940px}'));assert(src.includes('.op-equipo262 .oe-daily th,.op-equipo262 .oe-daily td{padding-left:8px;padding-right:8px}'));assert(src.includes('font-size:13px'));assert(src.includes('min-width:135px'));assert.equal(E.c.INVENTARIO_EQUIPO_262['equipo-dia'][0].length,11);});
 const ps=[{id:'ops',estado:'activo',puestos:['operaciones']},{id:'acc',estado:'activo',puestos:['account']}];
 function ctx(){const cs=[{id:'ok',nombre:'Cliente fixture',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}];return {servidor:true,hoy:'2026-10-05',real:{...ps[0]},persona:{...ps[0]},datos:{personas:structuredClone(ps),asignaciones:[]},clientes:structuredClone(cs),clientesVisibles:structuredClone(cs),carteraPorSilla:{account:new Set(['ok'])},veModulo:()=>true,ver:()=>({ok:true}),nombre:x=>x,vigente:()=>true,api:async()=>null,datosModulo:async()=>null};}
 async function mount(route){const c=ctx(),n=h('main',{});n.connected=true;await renderAccounts263(n,c,route);return {c,n};}
 await test('actual Score retains full criterion and unknown score',async()=>{const {n}=await mount('accounts');const ts=A.tables(n);assert.deepEqual(ts.map(t=>A.heads(t).length),[10,11,11,6,9]);const hs=A.walk(ts[1]).filter(x=>x.tag==='th');assert.equal(A.text(hs[7]),'Estado');assert.equal(hs[7].attrs.title,'Semáforo al día');assert.equal(hs[7].attrs['aria-label'],'Semáforo al día');assert.equal(A.text(hs[10]),'Emp. Mili');assert.equal(hs[10].attrs.title,'Empujes de Mili');assert(A.walk(ts[1]).some(x=>x.attrs['aria-label']==='Nota de cumplimiento: —'));});
 await test('404 six columns retain exact accessible meanings',async()=>{const {n}=await mount('accounts');const th=A.walk(A.tables(n)[3]).filter(x=>x.tag==='th');assert.deepEqual(th.map(A.text),['Cliente','Reu. sem.','Seguim. 15d','Traf.','Últ. confirm.','Próx. rev.']);assert.deepEqual(th.map(x=>x.attrs.title),['Cliente','Reuniones semana','Seguimiento quincenal','Trafficker','Última confirmada','Próxima revisión']);});
 await test('real sort controls retain full labels and keys',async()=>{const {n}=await mount('clientes');const bs=A.walk(n).filter(x=>x.tag==='button'&&x.attrs['data-orden-clientes']);assert.equal(bs.length,6);const shortened=bs.find(x=>x.attrs.title?.startsWith('Última reunión.'));assert(shortened);assert(A.text(shortened).startsWith('Últ. reunión'));assert(shortened.attrs['aria-label'].includes('último registro histórico'));assert(shortened.attrs.title.startsWith('Última reunión.'));assert.equal(typeof shortened.events.click,'function');});
 await test('revoked detail still clears without changing grants',async()=>{const {c,n}=await mount('accounts');c.clientes[0].activo_confirmado=false;const fold=A.walk(n).find(x=>x.attrs['data-referencia-score']==='408');fold.open=true;fold.events.toggle();assert(!A.text(n).includes('Cliente fixture'));});
 console.log('PASS',groups,'grupos 423');
 }finally{fs.rmSync(A.dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
