const fs618=require('fs'),path618=require('path');
let f618=fs618.readFileSync(path618.join(__dirname,'pruebas_operaciones_accounts_263.cjs'),'utf8');
f618=f618.replace('prepararAccounts263,renderAccounts263,KPIS263','combinarInformesCartera617,prepararAccounts263,renderAccounts263,KPIS263');
const extra618=String.raw`
{
 const h615=await import('file://'+path.join(dir,'_informes_declarados_612.mjs'));
 const nota618='Declaraciones activas por mes del informe, no por fecha de envío. Cero no acredita ausencia de envío ni cumplimiento; no hay verificación externa.';
 const fila618=(cid,n)=>({cliente_id:cid,informes_declarados:n,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null});
 const dto618=(ns=[2,3])=>({version:'611.1',periodo_informe:'2026-09',clientes:ns.map((n,i)=>fila618('c'+(i+1),n)),source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null,cobertura:'parcial',nota:nota618});
 const cx618=()=>{const c=autorizado();c.datos={...c.datos,personas:[{...c.real},{id:'a1',estado:'activo',puestos:['account']}]};c.clientesVisibles.push({...c.clientesVisibles[0],id:'c2',nombre:'Segundo ficticio'});c.clientes=[...c.clientesVisibles];c.datos.asignaciones.push({...c.datos.asignaciones[0],cliente_id:'c2'});return c;};
 function modelo618(c,d){const s=h615.ambitoResumenInformes612(c,'2026-09');s.vigente=()=>c.vigente();return h615.proyectarResumenInformes612(c,d,s);}
 const macro618=r=>tables(r).find(t=>heads(t)[0]==='Account'&&heads(t)[1]==='Nota');
 async function render618(d,inf=null,c=cx618()){const r=h('main',{});r.connected=true;c.api=async ruta=>{if(ruta.startsWith('clientes/evidencias_kpi/informes?')){assert.equal(ruta,'clientes/evidencias_kpi/informes?periodo_informe=2026-09');if(d instanceof Error)throw d;return d;}return null};c.datosModulo=async ruta=>ruta==='informes/informes'?inf:null;await renderAccounts263(r,c,'accounts');return {r,c};}
 const sum618=await render618(dto618());check('618 macro real2clientes manual2+3 =5decl gris',()=>{const t=macro618(sum618.r);assert(t);assert.match(text(t),/5 decl\./);assert.equal(walk(t).some(n=>n.attrs['data-estado']==='verde'&&text(n)==='5 decl.'),false);const b=walk(t).find(n=>n.attrs['aria-label']==='Informe mensual: 5 decl.');assert(b);assert.match(b.attrs.title,/2\/2 filas explícitas/);assert.match(b.attrs.title,/no verifica envío, cumplimiento ni Score/)});
 const zero618=await render618(dto618([0,0]));check('618 cero explícito sumado sólodeclaraciones gris',()=>{assert.match(text(macro618(zero618.r)),/0 decl\./);const b=walk(macro618(zero618.r)).find(n=>n.attrs['aria-label']==='Informe mensual: 0 decl.');assert.match(b.attrs.title,/no ausencia de envío/)});
 for(const D of [Error('fixture'),null]){const x=await render618(D);check('618 sinAPI no fake0 ni desaparicióncartera',()=>{assert.doesNotMatch(text(macro618(x.r)),/0 decl\./);assert.match(text(x.r),/Cliente fixture/)});}
 const partial=await render618(dto618([2]));check('618 parcial1/2 conserva sumaobservada sin cumplimiento',()=>{const b=walk(macro618(partial.r)).find(n=>n.attrs['aria-label']==='Informe mensual: 2 decl.');assert(b);assert.match(b.attrs.title,/1\/2 filas explícitas/)});
 const dup=dto618();dup.clientes.push({...dup.clientes[0]});const bad=await render618(dup);check('618 duplicadosdecl noagrega ni0',()=>assert.doesNotMatch(text(macro618(bad.r)),/5 decl\.|0 decl\./));
 const over=await render618(dto618([Number.MAX_SAFE_INTEGER,1]));check('618 overflow suma segura unknown',()=>{assert.doesNotMatch(text(macro618(over.r)),/9007199254740992|0 decl\./)});
 const inf={_meta:{generado:'2026-10-03T10:00:00Z'},filas:[{cliente_id:'c1',mes:'2026-09',estado:'enviado',enviado:{fecha:'2026-10-02',ticket:'42',url:'https://desk.zoho.eu/support/tickets/42',asunto:'Informe mensual septiembre',pdf:true,metodo:'Desk en vivo'}}]};
 const both=await render618(dto618(),inf);check('618 Desk1observado principal manual5sólo detalle no6',()=>{const t=macro618(both.r);assert.match(text(t),/1 obs\./);assert.doesNotMatch(text(t),/6 obs\.|6 decl\.|5 decl\./);const b=walk(t).find(n=>n.attrs['aria-label']==='Informe mensual: 1 obs.');assert.match(b.attrs.title,/Registro manual separado: 5 decl\./);assert.match(b.attrs.title,/1\/2 proyectos/)});
 check('618 duplicadosdeproyecto no inventan sumaDesk',()=>{const fallback={valor:'—',estado:'gris'},r={cliente_id:'c1',kpis:[{medicion:{tipo:'envio_observado'}}]};assert.equal(combinarInformesCartera617([r,r],null,fallback),fallback)});
 check('618 agregación no cambiaScore modelo original',()=>{const c=cx618(),d=prepararAccounts263(c,{}),antes=JSON.stringify(d.groups.map(g=>[g.nota,g.kpis]));const m=modelo618(c,dto618());h615.agregarInformesDeclarados615(m,['c1','c2']);assert.equal(JSON.stringify(d.groups.map(g=>[g.nota,g.kpis])),antes)});
 const late=cx618(),rr=h('main',{});rr.connected=true;let done,start;const started=new Promise(r=>start=r);late.api=async ruta=>{if(ruta.startsWith('clientes/evidencias_kpi/informes?')){start();return new Promise(r=>done=r)}return null};const req=renderAccounts263(rr,late,'accounts');await started;late.clientes[1].activo_confirmado=false;done(dto618());await req;check('618 ACT revocado durante lectura no macro viejo',()=>{assert.equal(tables(rr).length,0);assert.doesNotMatch(text(rr),/5 decl\./)});
 const live=await render618(dto618());const old=walk(macro618(live.r)).find(n=>n.attrs['aria-label']==='Informe mensual: 5 decl.');live.c.ver=()=>({ok:false});old.events.click();check('618 callbackmacro grant revocado limpia cliente/detalle',()=>{assert.equal(tables(live.r).length,0);assert.doesNotMatch(text(live.r),/Cliente fixture|Segundo ficticio|5 decl\./)});
 for(const key of ['activo','estado']){const c=cx618();c.clientes=c.clientes.map(x=>({...x}));c.clientes[0][key]=key==='activo'?false:'baja';const x=await render618({...dto618(),clientes:[fila618('c2',3)]},inf,c);check('618 contradiccióninicial '+key+' noDesk ni proyecto revocado',()=>{assert.doesNotMatch(text(x.r),/Cliente fixture|1 obs\./);assert.match(text(x.r),/Segundo ficticio/)});}
 for(const key of ['activo','estado']){const c=cx618(),r=h('main',{});r.connected=true;let fin,inicio;const started=new Promise(a=>inicio=a);c.api=async ruta=>{if(ruta.startsWith('clientes/evidencias_kpi/informes?')){inicio();return new Promise(a=>fin=a)}return null};c.datosModulo=async ruta=>ruta==='informes/informes'?inf:null;const running=renderAccounts263(r,c,'accounts');await started;c.clientes[0][key]=key==='activo'?false:'baja';fin(dto618());await running;check('618 contradicción '+key+' duranteGET eliminaDeskviejo',()=>{assert.equal(tables(r).length,0);assert.doesNotMatch(text(r),/Cliente fixture|1 obs\.|5 decl\./)});}

}
`;
const anchor=" console.log(grupos+' grupos PASS";
if(!f618.includes(anchor)||!f618.includes('combinarInformesCartera617,prepararAccounts263'))throw Error('Adaptar harness real sin relajarcontratos');
f618=f618.replace(anchor,extra618+'\n'+anchor);
new Function('require','__dirname',f618)(require,__dirname);
