const fs=require('fs'),vm=require('vm'),assert=require('assert');
const s={Intl,Date,Number,Array,JSON,Set,Object};vm.createContext(s);vm.runInContext('(function(){'+fs.readFileSync(__dirname+'/modulos/_metricas_campanas_448.js','utf8').replace(/export /g,'')+';globalThis.metricasCampanas448=metricasCampanas448;})();',s);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_meta_diaria_386.js','utf8').replace(/^import .*;$/m,'').replace(/export /g,''),s);
class N{constructor(tag,attrs={},children=[]){this.tag=tag;this.attrs=attrs;this.children=[];this.events=attrs.on||{};this.append(...children);}append(...xs){for(const x of xs.flat(Infinity))if(x!==null&&x!==undefined&&x!==false)this.children.push(x);}replaceChildren(...xs){this.children=[];this.append(...xs);}}
const h=(t,a,...xs)=>new N(t,a||{},xs),text=n=>typeof n==='object'?n.children.map(text).join(' '):String(n),all=(n,f)=>typeof n!=='object'?[]:[...(f(n)?[n]:[]),...n.children.flatMap(x=>all(x,f))];
const actor={id:'p',estado:'activo',activo:true,puestos:['trafficker']},client={id:'ok',activo_confirmado:true,detalle:true};
const dto={version:'385.1',cliente_id:'ok',estado:'copia_observada',medicion:{version:'384.1',cliente_id:'ok',nivel:'campaign_diario',cobertura:'filas_recibidas_no_censo',periodo:{desde:'2026-10-01',hasta:'2026-10-01',zona:'America/Los_Angeles'},paginas_completas:true,errores_tipados:[],contactos_unicos:null,leads_calificados:null,ventas:null,fecha_fuente:'2026-10-03T10:00:00+00:00',gasto_observado:781.25,moneda:'EUR',dias:[{dia:'2026-10-01',filas_recibidas:1,leads_observados:0,gasto_observado:781.25,impresiones_observadas:5,clics_observados:0}]}};
const copy=x=>JSON.parse(JSON.stringify(x)),ctx=()=>({servidor:true,vigente:()=>true,real:copy(actor),persona:copy(actor),datos:{personas:[copy(actor)]},clientes:[copy(client)],clientesVisibles:[copy(client)],veModulo:()=>true,ver:()=>({ok:true}),api:async()=>copy(dto)});
let checks=0;async function test(label,f){await f();checks++;}
(async()=>{
 await test('render observado cero and source lazy mount',async()=>{const c=ctx(),r=await s.renderMetaDiaria386(h,c,'ok');assert.equal(all(r,x=>x.tag==='table').length,1);assert(text(r).includes('Ev. lead'));assert(text(r).includes('2026-10-01'));assert(text(r).includes('781,25'));assert(text(r).includes('no son leads calificados'));const row=all(r,x=>x.tag==='tbody')[0];assert.deepEqual(all(row,x=>x.tag==='td').map(text),['2026-10-01','0','5','0','781,25']);});
 await test('unknown fields no false zero',async()=>{const c=ctx();c.api=async()=>{const d=copy(dto);Object.assign(d.medicion.dias[0],{filas_recibidas:0,leads_observados:null,impresiones_observadas:null,clics_observados:null,gasto_observado:null});d.medicion.gasto_observado=null;return d;};const r=await s.renderMetaDiaria386(h,c,'ok'),ts=all(all(r,x=>x.tag==='tbody')[0],x=>x.tag==='td').map(text);assert.deepEqual(ts,['2026-10-01','—','—','—','—']);});
 await test('no API before canonical invalid scope',async()=>{for(const fn of [c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push(copy(client)),c=>c.datos.personas.push(copy(actor)),c=>c.real.puestos=['seo'],c=>c.veModulo=()=>false,c=>c.ver=()=>({ok:false})]){const c=ctx();let calls=0;c.api=async()=>{calls++;return dto};fn(c);assert.equal(text(await s.renderMetaDiaria386(h,c,'ok')),'');assert.equal(calls,0);}});
 await test('await revoke actual ACT without stale visible',async()=>{const c=ctx();c.api=async()=>{c.clientes[0].activo_confirmado=false;return dto};assert.equal(text(await s.renderMetaDiaria386(h,c,'ok')),'');});
 await test('await roles or route changes',async()=>{for(const f of [c=>c.datos.personas[0].puestos=['seo'],c=>c.vigente=()=>false,c=>c.ver=()=>({ok:false})]){const c=ctx();c.api=async()=>{f(c);return dto};assert.equal(text(await s.renderMetaDiaria386(h,c,'ok')),'');}});
 await test('details revoke clears already rendered',async()=>{const c=ctx(),r=await s.renderMetaDiaria386(h,c,'ok');c.clientes=[];all(r,x=>x.tag==='details')[0].events.toggle();assert.equal(text(r),'');});
 await test('foreign response and invalid number rejected',async()=>{for(const f of [d=>d.cliente_id='foreign',d=>d.medicion.dias[0].leads_observados=true,d=>d.medicion.dias[0].clics_observados=Infinity,d=>d.medicion.periodo.desde='2026-02-30',d=>d.medicion.fecha_fuente='invalid']){const c=ctx();c.api=async()=>{const d=copy(dto);f(d);return d};const r=await s.renderMetaDiaria386(h,c,'ok');assert.equal(all(r,x=>x.tag==='table').length,0);assert(text(r).includes('compatible'));}});
 await test('error still scoped and honest',async()=>{const c=ctx();c.api=async()=>{throw Error('opaque')};assert(text(await s.renderMetaDiaria386(h,c,'ok')).includes('pendiente'));c.api=async()=>{c.clientes=[];throw Error('opaque')};assert.equal(text(await s.renderMetaDiaria386(h,c,'ok')),'');});
 await test('surplus investment denied at renderer',async()=>{const c=ctx();c.ver=x=>({ok:x.tipo!=='inversion'});const r=await s.renderMetaDiaria386(h,c,'ok');assert(!text(r).includes('781,25'));assert(!text(r).includes('Gasto'));assert(text(r).includes('Ev. lead'));});
 console.log(checks+' grupos independientes386B PASS');
})().catch(e=>{console.error(e.message);process.exitCode=1;});
