const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(tag,a={},...children){this.tag=tag;this.attrs=a;this.children=children.flat(Infinity).filter(x=>x!=null);this.events=a.on||{};this.isConnected=true;this.value='';this.style={};}append(...ns){this.children.push(...ns);}replaceChildren(...ns){this.children=ns;}focus(){this.focused=true;}select(){this.selected=true;}}
const text=n=>typeof n==='object'&&n?[n.textContent||'',...(n.children||[]).map(text)].join(' '):String(n??'');
const find=(n,tag)=>{if(n?.tag===tag)return n;for(const c of n?.children||[]){const x=find(c,tag);if(x)return x;}return null;};
const h=(tag,a,...cs)=>new El(tag,a,...cs);const writes=[];
const b={console,Date,Map,Set,Number,JSON,String,Array,Object,Promise,h,navigator:{clipboard:{writeText:async x=>{writes.push(x);}}},panel:(o,n)=>h('section',{},h('h2',{},o.titulo),n),chipEstado:(c,t)=>h('span',{},t),tablaDensa:o=>h('table',{},o.filas.map(r=>h('tr',{},o.columnas.map(c=>c.celda(r))))),renderResumen274:async()=>{},panelEncargos272:()=>{},panelFotosControl272:()=>{},panelRituales269:()=>{}};vm.createContext(b);
for(const file of ['_informe_semanal_operaciones','_operaciones_dia_direccion_265'])vm.runInContext('(()=>{'+fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'')+'\nObject.assign(globalThis,{'+(file.startsWith('_informe')?'textoInformeSemanalOperaciones,panelInformeSemanalOperaciones,periodoInformeSemanalOperaciones':'puerta265,modelo265,renderDiaDireccion265')+'});})();',b);
const p={id:'fixture_ops',estado:'activo',puestos:['operaciones']};
function ctx(){return{real:{...p},persona:{...p},hoy:'2026-10-03',datos:{personas:[{...p}]},clientesVisibles:[{id:'allowed',nombre:'Cliente permitido',activo_confirmado:true,detalle:true},{id:'foreign',nombre:'NO_EXPOSE_FOREIGN',activo_confirmado:true,detalle:true}],veModulo:()=>true,ver:d=>({ok:d.cliente_id==='allowed'}),vigente:()=>true,nombre:id=>id,servidor:false,datosModulo:async()=>({})};}
function sources(){return{direccion:{informe_semanal:{corte:'02-10-2026 11:06',semana:'2026-09-28 → 2026-10-02',numeros:[{nombre:'Altas en plazo (encendidas el día 10, límite 12)',valor:'2 de 5',fuente:'Altas · copia parcial'},{nombre:'Horas por cuenta nueva (media al mes)',valor:'14,2 h',fuente:'Horas · registro parcial'},{nombre:'Compromisos vencidos sin aviso',valor:'0',fuente:'Snapshot sin descriptor'}]}},verdad:{clientes:[{cliente_id:'allowed',gravedad:'critico'},{cliente_id:'foreign',gravedad:'critico'}]},rastro:{registro:[{cliente_id:'allowed',creada:'2026-10-02T08:00:00Z'},{cliente_id:'foreign',creada:'2026-10-02T08:00:00Z'}]},decisiones:{decisiones:[{cliente_id:'foreign',creada:'2026-10-02',texto:'NO_EXPOSE_FOREIGN'},{cliente_id:'allowed',creada:'2026-10-02',texto:'Consultar entregable autorizado'}]}};}
let n=0;function t(name,f){f();n++;}
(async()=>{
 t('original has editor/copy/order',()=>{const o=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8');assert(o.includes('data-copiar-inf'));const c=ctx(),f=sources(),s=b.textoInformeSemanalOperaciones(c,b.modelo265(c,f),f);assert(s.indexOf('1. Altas')<s.indexOf('2. Horas'));assert(s.indexOf('2. Horas')<s.indexOf('3. Compromisos'));assert(s.includes('2 de 5'));assert(s.includes('14,2 h'));assert(s.includes('cero sin medición acreditada'));assert(!s.includes('NO_EXPOSE_FOREIGN'));assert(s.includes('≥1'));});
 t('future invalid period unknown',()=>{for(const edit of [q=>q.corte='04-10-2026',q=>q.semana='2026-09-28 → 2026-10-04',q=>q.semana='bad']){const c=ctx(),f=sources();edit(f.direccion.informe_semanal);const s=b.textoInformeSemanalOperaciones(c,b.modelo265(c,f),f);assert(!s.includes('2 de 5'));assert(s.includes('Sin dato confirmado'));}});
 t('zero measured versus missing',()=>{const c=ctx(),f=sources(),x=f.direccion.informe_semanal.numeros[2];x.medicion={estado:'medido',fuente:'Registro específico',desde:'2026-09-28',hasta:'2026-10-02',fecha:'2026-10-03'};assert(b.textoInformeSemanalOperaciones(c,b.modelo265(c,f),f).includes('3. Compromisos vencidos sin aviso: 0'));x.medicion.fecha='2026-10-04';assert(b.textoInformeSemanalOperaciones(c,b.modelo265(c,f),f).includes('cero sin medición acreditada'));});
 t('secrets money contacts excluded',()=>{const c=ctx(),f=sources();f.direccion.informe_semanal.numeros[0].fuente='API token=PRIVATE';f.decisiones.decisiones.push({cliente_id:'allowed',creada:'2026-10-02',texto:'Contrato 1800 € · PRIVATE'});let s=b.textoInformeSemanalOperaciones(c,b.modelo265(c,f),f);assert(!s.includes('PRIVATE'));assert(!s.includes('1800'));assert(!s.includes('€'));});
 t('empty no zero or absence credit',()=>{const c=ctx(),s=b.textoInformeSemanalOperaciones(c,b.modelo265(c,{}),{});assert(s.includes('Sin dato'));assert(!s.includes('no hay decisiones'));assert(!s.includes('ninguno'));});
 function panel(c=ctx(),f=sources()){return b.panelInformeSemanalOperaciones({h,ctx:c,modelo:b.modelo265(c,f),fuentes:f,vigente:()=>b.puerta265(c,'tomas')});}
 let c=ctx(),pane=panel(c),a=find(pane,'textarea'),btn=find(pane,'button');a.value+='\nMi nota editada';await btn.events.click();assert(writes.at(-1).includes('Mi nota editada'));assert(text(pane).includes('Copiado.'));assert(!text(pane).includes('Enviado'));assert(pane.attrs.open!==true);n++;
 for(const change of [c=>c.real.estado='baja',c=>c.persona.estado='baja',c=>c.persona.id='foreign',c=>c.veModulo=()=>false,c=>c.vigente=()=>false,c=>c.ver=()=>({ok:false}),c=>c.clientesVisibles=[]]){c=ctx();pane=panel(c);const old=writes.length;change(c);await find(pane,'button').events.click();assert.equal(writes.length,old);assert.equal(find(pane,'textarea').value,'');assert(text(pane).includes('ha cambiado'));n++;}
 c=ctx();pane=panel(c);find(pane,'textarea').isConnected=false;const beforeDetached=writes.length;await find(pane,'button').events.click();assert.equal(writes.length,beforeDetached);n++;
 c=ctx();c.persona.puestos=['account'];assert(!b.puerta265(c,'tomas'));n++;
 c=ctx();pane=panel(c);b.navigator.clipboard.writeText=async()=>{throw Error('CLIPBOARD_PRIVATE_ERROR');};await find(pane,'button').events.click();assert(find(pane,'textarea').selected);assert(text(pane).includes('Ctrl+C'));assert(!text(pane).includes('PRIVATE_ERROR'));n++;
 c=ctx();pane=panel(c);let resolve;b.navigator.clipboard.writeText=()=>new Promise(r=>resolve=r);const running=find(pane,'button').events.click();c.vigente=()=>false;resolve();await running;assert(!text(pane).includes('Copiado.'));n++;
 c=ctx();const f=sources();c.datosModulo=async path=>path==='decisiones/direccion'?f.direccion:path==='verdad/clientes'?f.verdad:{};const root=h('main',{});await b.renderDiaDireccion265(root,c,'tomas');assert(find(root,'textarea'));assert(text(root).includes('Editar y copiar'));assert(text(root).includes('Bajas con su motivo'));n++;
 console.log(`${n} grupos PASS: editor real265, originalorden, fuentes/unknown0/futuro/scopes/permisos/copyfallback/async.`);
})().catch(e=>{console.error(e);process.exit(1)});
