const fs=require('fs'),assert=require('assert/strict');
const p=fs.readFileSync(__dirname+'/pruebas_prioridades_300.cjs','utf8').split('(async()=>{')[0];
const P=new Function('require',p+';return {b,ctx,render,all,N,row};')(require);
const q=fs.readFileSync(__dirname+'/probar_operaciones_265.cjs','utf8').split('let casos=0;')[0];
const D=new Function('require','__dirname',q+';return {s,tables,ctx,text,El};')(require,__dirname);
let checks=0;async function test(name,f){await f();checks++;console.log('PASS',name);}
const rows=n=>Array.from({length:n},(_,i)=>({...P.row,id:'r'+i,titulo:'Prioridad '+i}));
(async()=>{
 await test('26 exact rows all present first6 next14 remaining6 closed',async()=>{const c=P.ctx();c.servidor=false;const n=await P.render(c,rows(26));const box=P.all(n,x=>x.attrs['data-prioridades-visibles']==='6')[0];assert.equal(P.all(box,x=>x.tag==='tbody')[0].children.length,6);const next=P.all(n,x=>x.attrs['data-prioridades-siguientes'])[0],rest=P.all(n,x=>x.attrs['data-prioridades-resto'])[0];assert.equal(P.all(next,x=>x.tag==='tbody')[0].children.length,14);assert.equal(P.all(rest,x=>x.tag==='tbody')[0].children.length,6);assert.equal(next.attrs.open,undefined);assert.equal(rest.attrs.open,undefined);assert.equal(P.all(n,x=>x.tag==='tr').length,29);assert(next.textContent.includes('primeras 20'));assert(rest.textContent.includes('6'));});
 await test('small lists no artificial extra section or lost rows',async()=>{for(const k of [0,1,6,7,20]){const c=P.ctx();c.servidor=false;const n=await P.render(c,rows(k));assert.equal(P.all(n,x=>x.attrs['data-prioridades-siguientes']).length,k>6?1:0);assert.equal(P.all(n,x=>x.attrs['data-prioridades-resto']).length,0);assert.equal(P.all(n,x=>x.tag==='tbody').reduce((a,t)=>a+t.children.length,0),k);}});
 await test('headers and missing marker compact with full semantics',async()=>{const c=P.ctx();c.servidor=false;const n=await P.render(c,rows(1));const hs=P.all(n,x=>x.tag==='th');assert.deepEqual(hs.map(x=>x.textContent),['Prioridad','Cliente / equipo','Rastro','Abrir']);assert.equal(hs[0].attrs.title,'Qué hay que empujar');assert.equal(hs[2].attrs['aria-label'],'Seguimiento local');const mark=P.all(n,x=>x.attrs.title==='Sin registro confirmado')[0];assert.equal(mark.textContent,'—');assert.equal(mark.attrs['aria-label'],'Sin registro confirmado');});
 await test('state and native summary share one44px row editor remains complete',async()=>{const c=P.ctx();c.servidor=false;const n=await P.render(c,rows(1));const summary=P.all(n,x=>x.tag==='summary'&&x.attrs.title==='Registrar avance · seguimiento local')[0];assert(summary);assert.equal(summary.style.minHeight,'44px');assert.equal(summary.style.display,'flex');assert(summary.textContent.includes('— Registrar avance'));assert.equal(P.all(summary,x=>x.attrs.title==='Sin registro confirmado').length,1);const cell=P.all(n,x=>x.tag==='tbody')[0].children[0].children[2];assert.equal(cell.children.length,1);assert.equal(cell.children[0].tag,'details');assert.equal(P.all(cell,x=>x.tag==='textarea').length,1);assert.equal(P.all(cell,x=>x.tag==='button').length,2);assert(P.all(cell,x=>x.tag==='summary'&&x.textContent==='Autor, fecha e historial').length===1);});
 await test('first20 denominator unchanged despite folded records',async()=>{const rs=rows(26),c=P.ctx(),tokens=await Promise.all(rs.map(r=>P.b.hashFuente300('ops',r)));c.api=async()=>({version:'300.1',propietario:'ops',dia:'2026-10-03',puede_registrar:false,prioridades:rs.map((r,i)=>({prioridad_id:r.id,cliente_id:'c',fuente_revision:tokens[i],revision:0,actual:null,historial:[]}))});const n=await P.render(c,rs);assert(n.textContent.includes('0 de 20 prioridades con rastro local · primeras 20'));assert.equal(P.b.progreso300(rs.slice(0,20),new Map([['r20',{actual:{estado:'resuelto'}}]])).registradas,0);});
 await test('fold callback after parent revocation clears instead of exposing hidden rows',async()=>{const c=P.ctx();c.servidor=false;let live=true;const n=new P.N('main');await P.b.renderPrioridades300(n,c,rows(26),()=> 'Cliente',()=>live);const fold=P.all(n,x=>x.attrs['data-prioridades-siguientes'])[0];live=false;fold.events.toggle();assert.equal(P.all(n,x=>x.tag==='tr').length,0);});
 await test('265 sources remain closed perindicator not lost or transformed',async()=>{const c=D.ctx(),n=new D.El('main',{});await D.s.renderDiaDireccion265(n,c,'dia');const t=D.tables.find(x=>x.columnas[0]?.titulo==='Indicador'&&x.columnas[1]?.titulo==='Medición');assert(t);assert.equal(t.filas.length,6);assert.equal(t.columnas[2].titulo,'Fuente');assert.equal(D.text(t.columnas[1].celda({valor:null})),'—');assert.equal(t.columnas[1].celda({valor:null}).attrs['aria-label'],'Sin dato confirmado');assert.equal(D.text(t.columnas[1].celda({valor:0})),'0');for(const r of t.filas){const x=t.columnas[2].celda(r);assert.equal(x.tag,'details');assert.equal(x.attrs.open,undefined);assert(D.text(x).includes(r.detalle));assert.equal(x.children[0].attrs.title,'Fuente y referencia del indicador');assert.equal(r.valor,null);}});
 await test('265 source toggle after revocation clears rendered panel',async()=>{const c=D.ctx(),n=new D.El('main',{});await D.s.renderDiaDireccion265(n,c,'dia');const t=D.tables.filter(x=>x.columnas[0]?.titulo==='Indicador'&&x.columnas[1]?.titulo==='Medición').at(-1),x=t.columnas[2].celda(t.filas[0]);c.vigente=()=>false;x.attrs.on.toggle();assert(!D.text(n).includes('Tus indicadores'));});
 console.log(checks,'grupos427 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
