const fs389=require('node:fs'),prefijo389=fs389.readFileSync(__dirname+'/pruebas_control_macro_138.cjs','utf8').split('const macros=root.desc()')[0];
new Function('require','__dirname',prefijo389+String.raw`
let casos389=0;const test389=(name,f)=>{f();casos389++;};
const copy389=x=>JSON.parse(JSON.stringify(x));
const fuente389=(n,z)=>{const x=copy389(fuentes);x.produccion.proyectos[0].rev_account=n;x.produccion.proyectos[0].rev_account_48=n;x.bandeja.clientes[0].sin_contestar=z;x.bandeja.clientes[0].mas_48=z;return x;};
const render389=(f)=>b.panelControlCartera(ctx,{opcional:name=>({'produccion/produccion':f.produccion,'bandeja/por_cliente':f.bandeja}[name]||null)},'operaciones',()=>true);
const macro389=(r)=>r.desc().find(n=>n.tag==='table').desc().find(n=>n.tag==='tbody').k.find(row=>row.desc().some(x=>x.tag==='button'&&x.attrs['aria-label']==='Ver proyectos de account'));
for(const [n,color]of [[0,'gris'],[1,'ambar'],[5,'ambar'],[6,'rojo']])test389('macro revision exact count '+n,()=>{const row=macro389(render389(fuente389(n,0))),cell=row.k[2].desc().find(x=>x.tag==='button');assert.equal(cell.textContent,String(n));assert(cell.attrs.class.includes(color));assert(cell.attrs['aria-label'].includes('clientes'));assert(!cell.textContent.includes('clientes'));});
for(const [n,color]of [[0,'gris'],[1,'rojo']])test389('macro tickets48 count '+n,()=>{const row=macro389(render389(fuente389(0,n))),cell=row.k[4].desc().find(x=>x.tag==='button');assert.equal(cell.textContent,String(n));assert(cell.attrs.class.includes(color));});
test389('unknown not fake zero or green',()=>{const r=render389({}),cells=r.desc().filter(n=>n.tag==='button'&&n.attrs.class?.includes('c250'));assert(cells.every(x=>x.textContent==='—'));assert(cells.every(x=>x.attrs.class.includes('gris')));assert(cells.every(x=>x.attrs['aria-label'].includes('Sin dato')));});
test389('unknown producer metrics despite legacy zero remains unknown',()=>{const f=fuente389(0,0);delete f.produccion.proyectos[0].revisiones_account;delete f.bandeja.fuentes;const row=macro389(render389(f));assert.equal(row.k[2].textContent,'—');assert.equal(row.k[4].textContent,'—');});
test389('lower cells compact but details keep sources and limits',()=>{const r=render389(fuente389(6,1)),t=r.desc().filter(n=>n.tag==='table')[1],summaries=t.desc().filter(n=>n.tag==='summary');assert(summaries.every(x=>x.textContent==='Ver detalle'));const visible=n=>typeof n!=='object'?String(n):n.tag==='details'?n.k.filter(x=>x.tag==='summary').map(visible).join(''):n.k.map(visible).join('');assert(!visible(t).includes('Registro histórico'));assert(!visible(t).includes('Objetivo por confirmar'));assert(r.textContent.includes('No hay evidencia')||r.textContent.includes('Sin evidencia')||r.textContent.includes('sin confirmar'));assert(r.textContent.includes('fecha no disponible'));assert(r.textContent.includes('no acredita'));});
test389('presentation never green for arbitrary numeric zero',()=>{const frame=b.pintarMapaControl250({h,filas:[{id:'x',nombre:'Account',celdas:{imputa:{valor:0,estado:'verde'}}}]});const cell=frame.desc().find(n=>n.tag==='button'&&n.attrs.class?.includes('c250'));assert.equal(cell.textContent,'0');assert(cell.attrs.class.includes('gris'));});
test389('compact macro source accessible via callback real guard',()=>{const r=render389(fuente389(6,1)),row=macro389(r),button=row.k[2].desc().find(n=>n.tag==='button');N.prototype.focus=function(){this.focused=true};button.listeners.click();assert(r.textContent.includes('umbral del mapa original'));const frame=r.desc().find(n=>n.attrs.class==='ro-control-artifact250');assert(frame.desc().some(n=>n.attrs.class==='detalle250'));});
function detalleFixture389(){const c={...ctx,servidor:true,real:{id:'account',estado:'activo'},persona:{id:'account',estado:'activo'},ver:q=>({ok:q.cliente_id==='uno'})},f=fuente389(6,1),source={opcional:name=>name==='dinero_cliente/dinero_cliente'?{generado:'2026-10-03 06:31',mes_cuota:'2026-10',mes_horas:'2026-09',clientes:[{cliente_id:'uno',cuota_horas:{pautadas:20}}]}:({'produccion/produccion':f.produccion,'bandeja/por_cliente':f.bandeja}[name]||null)};let active=true;const node=b.panelControlCartera(c,source,'account',()=>active),detail=node.desc().find(n=>n.tag==='details'&&n.desc().some(x=>x.tag==='summary'&&x.textContent==='Ver detalle'));return {c,node,detail,revocar:()=>active=false};}
for(const [name,change]of [['pauta',x=>x.c.ver=q=>({ok:q.tipo!=='horas_pautadas'&&q.cliente_id==='uno'})],['cliente',x=>x.c.ver=()=>({ok:false})],['vigencia',x=>x.revocar()]])test389('detail toggle revalidates '+name,()=>{const x=detalleFixture389();assert(x.detail.textContent.includes('20 h'));change(x);assert(x.detail.listeners.toggle);x.detail.listeners.toggle();assert(!x.detail.textContent.includes('20 h'));assert(!x.detail.textContent.includes('Fuente'));});
test389('live detail expansion preserves source content',()=>{const x=detalleFixture389(),before=x.detail.textContent;x.detail.listeners.toggle();assert.equal(x.detail.textContent,before);});
console.log(casos389+' grupos389 PASS · render real138/250 colores/compactación/unknown');
`)(require,__dirname);
