const fs=require('fs'),vm=require('vm'),assert=require('assert');
class N{constructor(tag,attrs={},...kids){this.tag=tag;this.attrs=attrs;this.disabled=!!attrs.disabled;this.kids=[];this.append(...kids)}append(...kids){this.kids.push(...kids.flat(Infinity).filter(k=>k!=null))}replaceChildren(...kids){this.kids=[];this.append(...kids)}get textContent(){return this.kids.map(k=>k instanceof N?k.textContent:String(k)).join(' ')}set textContent(t){this.kids=[t]}get isConnected(){return true}}
const walk=n=>[n,...n.kids.flatMap(k=>k instanceof N?walk(k):[])];
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function setup(){const calls=[];const h=(...args)=>new N(...args);const data={modo:'reglas',motivo:'Límite Console',llaves:{principal:true},topes:{mes_eur:150,dia_eur:10,aviso_pct:80,persona_dia_eur:5,respaldo_mes_eur:10,funcion_mes_eur:{},usd_a_eur:1},gasto:{mes:0,dia:0,prevision_mes:0,dias_mes:4},pct:{mes:0,dia:0},por_funcion:[],por_persona:[],ultimas:[],historial_topes:[],precios:{modelos:{},fecha:'fixture',fuente:'#'}};
const b={console,JSON,Set,Array,h,fmt:{eur:n=>String(n),num:n=>String(n),fecha:n=>n},tile:o=>h('tile',{},o.etiqueta),tiles:x=>h('tiles',{},x),panel:(o,x)=>h('panel',{},o.titulo,x),vacio:o=>h('vacio',{},o.titulo,o.texto),icono:()=>h('i'),tablaApilable:()=>h('table'),chipEstado:()=>h('chip'),avisoFlotante:()=>{throw Error('No se necesita confirmación flotante')}};
vm.createContext(b);vm.runInContext(fs.readFileSync('modulos/gasto_ia.js','utf8').replace(/^import .*;\n/gm,'').replace('export default {','globalThis.modulo={'),b);
const p={id:'tomas',estado:'activo',puestos:['direccion']};const ctx={real:{...p},persona:{...p},datos:{personas:[{...p}]},vigente:()=>true,veModulo:()=>true,soloLectura:false,pilotoLectura:false,api:async(r,op)=>{calls.push({r,op});return r.endsWith('reabrir')?{ok:true,...data}:data}};
const cont=h('main');return {b,ctx,cont,data,calls,render:()=>b.modulo.render(cont,ctx),button:()=>walk(cont).find(n=>n.tag==='button'&&n.textContent.includes('Reabrir')),root:()=>cont.kids[0]};}
let total=0;async function test(name,f){await f();total++;}
(async()=>{
await test('contrato real: ok+resumen registra local pero reglas no activada',async()=>{const x=setup();await x.render();await x.button().attrs.on.click();assert.match(x.cont.textContent,/Reapertura registrada en la app. La IA sigue en modo reglas/);assert.equal(x.calls.filter(c=>c.op?.metodo==='POST').length,1);assert.deepEqual(x.calls[1].op.cuerpo,{motivo:'Límite de la Console subido'})});
await test('doble clic durante await produce un solo POST',async()=>{const x=setup(),d=deferred();await x.render();let n=0;x.ctx.api=async()=>{n++;return d.promise};const bt=x.button(),p=bt.attrs.on.click();await bt.attrs.on.click();assert.equal(n,1);assert.equal(bt.disabled,true);d.resolve({ok:true,...x.data});x.ctx.api=async()=>x.data;await p});
await test('error visible y sin reenvío ni refresco automático',async()=>{const x=setup();await x.render();let n=0;x.ctx.api=async()=>{n++;throw Error('Respuesta perdida fixture')};await x.button().attrs.on.click();assert.match(x.cont.textContent,/No se confirmó la reapertura/);assert.match(x.cont.textContent,/Respuesta perdida fixture/);await x.button().attrs.on.click();assert.equal(n,1)});
await test('null, ok genérico, error y modo inválido no confirman',async()=>{for(const r of [null,{ok:true},{ok:true,...setup().data,error:'rechazado'},{ok:true,...setup().data,modo:'activada'}]){const x=setup();await x.render();x.ctx.api=async()=>r;await x.button().attrs.on.click();assert.match(x.cont.textContent,/No se confirmó/);assert.doesNotMatch(x.cont.textContent,/Reapertura registrada/)} });
await test('sólo lectura y piloto no escriben',async()=>{for(const key of ['soloLectura','pilotoLectura']){const x=setup();x.ctx[key]=true;await x.render();assert.equal(x.button().disabled,true);await x.button().attrs.on.click();assert.equal(x.calls.length,1)}});
await test('ver como nominal distinto no lee ni escribe',async()=>{const x=setup();x.ctx.persona.id='fixture';await x.render();assert.equal(x.calls.length,0);assert.equal(x.cont.textContent,'')});
await test('revocar módulo o catálogo antes clic no escribe ni conserva datos',async()=>{for(const change of [x=>x.ctx.veModulo=()=>false,x=>x.ctx.datos.personas[0].estado='baja',x=>x.ctx.datos.personas.push({...x.ctx.datos.personas[0]}),x=>x.ctx.datos.personas[0].puestos=['account'],x=>x.ctx.soloLectura=true]){const x=setup();await x.render();const bt=x.button();change(x);await bt.attrs.on.click();assert.equal(x.calls.length,1);assert.equal(x.cont.textContent,'')}});
await test('revocación durante GET no pinta resultado',async()=>{const x=setup(),d=deferred();x.ctx.api=()=>d.promise;const p=x.render();x.ctx.datos.personas[0].activo=false;d.resolve(x.data);await p;assert.equal(x.cont.textContent,'')});
await test('navegación o viewas durante POST no confirma ni refresca',async()=>{for(const change of [x=>x.ctx.vigente=()=>false,x=>x.ctx.persona.id='fixture',x=>x.ctx.datos.personas[0].estado='baja']){const x=setup(),d=deferred();await x.render();let n=0;x.ctx.api=()=>{n++;return d.promise};const p=x.button().attrs.on.click();change(x);d.resolve({ok:true,...x.data});await p;assert.equal(n,1);assert.equal(x.cont.textContent,'')}});
await test('denegación explícita del servidor limpia el gasto previo',async()=>{const x=setup();await x.render();x.ctx.api=async()=>{throw Object.assign(Error('Denegado fixture'),{status:403})};await x.button().attrs.on.click();assert.match(x.cont.textContent,/No se permite reabrir/);assert.doesNotMatch(x.cont.textContent,/Gastado este mes/)});
await test('modo ia tampoco acredita límite externo',async()=>{const x=setup();await x.render();x.ctx.api=async(r)=>r.endsWith('reabrir')?{ok:true,...x.data,modo:'ia'}:x.data;await x.button().attrs.on.click();assert.match(x.cont.textContent,/límite externo no se ha comprobado/)});
await test('fallo lectura posterior no anuncia éxito ni desaparece el error',async()=>{const x=setup();await x.render();x.ctx.api=async(r)=>{if(r.endsWith('reabrir'))return {ok:true,...x.data};throw Object.assign(Error('Consulta fallida fixture'),{status:503})};await x.button().attrs.on.click();assert.match(x.cont.textContent,/Consulta fallida fixture/);assert.doesNotMatch(x.cont.textContent,/Reapertura registrada/)});
console.log(`${total} grupos 601 PASS: módulo render real, DOM y transporte ficticios.`);
})().catch(e=>{console.error(e);process.exitCode=1});
