const fs=require('fs'),vm=require('vm'),assert=require('assert');
const b={Date,Number,JSON,Object};vm.createContext(b);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_kpis_compactos_396.js','utf8').replace(/export /g,''),b);
let n=0;const test=(name,f)=>{f();n++;},cell=(valor,estado='gris')=>({valor,estado,detalle:'Fuente exacta · cobertura parcial · periodo2026-09',fuente:'fixture',fecha:'2026-10-03',_firma:'guard-current'}),fmt=(c,tabla='proyecto',indice=0)=>b.celdaKpiCompacta396(c,{tabla,indice});
test('account coverage not compliance',()=>{const r=fmt(cell('3/8 registros','ambar'),'account',4);assert.equal(r.valor,'3/8');assert.equal(r.estado,'ambar');assert(r.detalle.includes('3/8 registros'));assert(!r.valor.includes('%'));});
test('observed zero not missing',()=>{assert.equal(fmt(cell('Sin dato'),'proyecto',6).valor,'—');assert(fmt(cell('Sin dato'),'proyecto',6).detalle.includes('Sin dato')); assert.equal(fmt(cell('0/8 registros'),'account',0).valor,'0/8');assert.equal(fmt(cell('—'),'account',0).valor,'—');});
test('other formats literal',()=>{for(const v of ['3/8 cumplidos','3 de 8 registros','1/4 ref.','≥3 registros'])assert.equal(fmt(cell(v),'account',0).valor,v);});
test('report period retained no acceptance',()=>{for(const [v,w]of [['Envío 2026-09','Envío'],['en_curso · 2026-09','En curso'],['hecho · 2026-09','Tarea hecha'],['no_aplica · 2026-09','No aplica'],['sin_tarea · 2026-09','Sin tarea']]){const r=fmt(cell(v));assert.equal(r.valor,w);assert(r.detalle.includes(v));assert(!r.valor.includes('Entregado'));}});
test('invalid month untouched',()=>{for(const v of ['Envío 2026-13','hecho · 2026-00','pendiente · 2026-09'])assert.equal(fmt(cell(v)).valor,v);});
test('short registered date no celebration',()=>{const r=fmt(cell('2026-09-29'),'proyecto',1);assert.equal(r.valor,'29/09/26');assert(r.detalle.includes('2026-09-29'));});
test('invalid date unknown preserved',()=>{for(const v of ['2026-02-30','Fecha por confirmar','—'])assert.equal(fmt(cell(v),'proyecto',1).valor,v);});
test('local declaration0 remains gray',()=>{for(const v of ['0 declarado','2 declarados']){const r=fmt(cell(v),'proyecto',2);assert(r.valor.endsWith(' decl.'));assert(r.detalle.includes(v));assert.equal(r.estado,'gris');}});
test('partial and tiny hours units preserved',()=>{for(const [v,w]of [['≥14,2 h registradas','≥14,2 h'],['0 h registradas','0 h'],['<0,1 h registradas','<0,1 h'],['2.3 h registradas','2.3 h']])assert.equal(fmt(cell(v),'proyecto',6).valor,w);});
test('no parsing ratios or nonfinite',()=>{for(const v of ['2 h / 40h ref.','≥14 h · oct','Infinity h registradas','-1 h registradas'])assert.equal(fmt(cell(v),'proyecto',6).valor,v);});
test('tickets review retain colors',()=>{for(const i of [3,4]){const c=cell('4 · 2 >48h','rojo');assert.strictEqual(fmt(c,'proyecto',i),c);}});
test('guards metadata unchanged immutable',()=>{const c=cell('3/8 registros');c.modelo={firma:'scope'};c.cliente_ids=['c'];Object.freeze(c);const r=fmt(c,'account',0);assert.equal(c.valor,'3/8 registros');assert.strictEqual(r.modelo,c.modelo);assert.strictEqual(r.cliente_ids,c.cliente_ids);for(const k of ['_firma','fuente','fecha','estado'])assert.equal(r[k],c[k]);});
test('idempotent no duplicate detail',()=>{const r=fmt(cell('3/8 registros'),'account',0);assert.strictEqual(fmt(r,'account',0),r);});
test('inherited enum never mapped',()=>{for(const v of ['constructor','__proto__'])assert.equal(fmt(cell(v)).valor,v);});
test('invalid no fake zero',()=>{for(const c of [null,undefined,[],{},cell(null),cell(NaN),cell(Infinity)])assert.strictEqual(fmt(c),c);});
test('unsupported dimensions unchanged',()=>{const c=cell('3/8 registros');assert.strictEqual(fmt(c,'macro',0),c);assert.strictEqual(fmt(c,'account',8),c);assert.strictEqual(fmt(c,'account',-1),c);assert.equal(fmt(cell('3 declarados'),'proyecto',7).valor,'3 declarados');});
console.log(`${n} grupos396 PASS: presentación pura, cobertura/unknown/colores/guardas conservados.`);
