const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const base=fs.readFileSync(__dirname+'/pruebas_resumen_274.cjs','utf8').split('(async()=>{')[0];
const init=new Function('require','__dirname',base+';return {tmp,walk};')(require,__dirname);const {tmp,walk}=init,path=require('path');
(async()=>{try{const M=await import('file://'+path.join(tmp,'_operaciones_resumen_274.mjs'));const HH=await import('file://'+path.join(tmp,'_historial_diario_364.mjs'));const {h}=await import('file://'+path.join(tmp,'componentes.mjs'));
const actor={id:'ops',estado:'activo',puestos:['operaciones']},person={id:'p',estado:'activo',puestos:['account']};const H={personas:[{persona_id:'ops'},{persona_id:'p'}]};
function ctx(hoy='2026-10-03'){return {hoy,servidor:true,real:{...actor},persona:{...actor},datos:{personas:[{...actor},{...person}]},clientes:[],clientesVisibles:[],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,nombre:id=>id,datosModulo:async()=>null,api:async()=>null};}
function raw(values=[2,0],cut='2026-10-03',day='2026-10-02'){const dates=Array.from({length:90},(_,i)=>new Date(Date.parse(cut+'T00:00:00Z')-(90-i)*864e5).toISOString().slice(0,10));return {version:'362.1',generado:cut+'T10:00:00Z',unidad:'h',cumplimiento:null,capacidad_contractual:null,estado:'copia_observada',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',personas:['ops','p'].map((pid,i)=>({persona_id:pid,historial_diario:{version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona_confirmada:true,zona:'Europe/Madrid',corte_fecha:cut,fecha_fuente_utc:cut+'T00:56:00Z',atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,desde:dates[0],hasta:dates.at(-1),dias:dates.map(fecha=>({fecha,estado:fecha===day&&values[i]!==null?'observado':'sin_dato',horas:fecha===day?values[i]:null,entradas:fecha===day&&values[i]!==null?1:null}))}}))};}
const model=(c,r=raw())=>HH.modeloHistorial364(c,r,H,HH.ambitoHistorial364(c,H));let n=0;const test=async(name,f)=>{await f();n++;console.log('PASS '+name);};
await test('Historial real validado suma2h/2personas sin8h ni%',()=>{const c=ctx(),x=M.horasResumen517(c,H,model(c));assert.equal(x.valor,'≥2 h');assert(x.detalle.includes('2/2 personas'));assert(x.detalle.includes('2026-10-02'));assert.equal(x.estado,'gris');assert(!x.valor.includes('%'));});
await test('Cero observado conserva0; ausencia no lo fabrica',()=>{const c=ctx();assert.equal(M.horasResumen517(c,H,model(c,raw([0,0]))).valor,'≥0 h');assert.equal(M.horasResumen517(c,H,model(c,raw([null,null]))).valor,'—');assert.equal(M.horasResumen517(c,H,null).valor,'—');});
await test('Suma parcial y dato mínimo conservados; overflow desconocido',()=>{const c=ctx();assert.equal(M.horasResumen517(c,H,model(c,raw([3,null]))).valor,'≥3 h');assert(M.horasResumen517(c,H,model(c,raw([3,null]))).detalle.includes('1/2 personas'));assert.equal(M.horasResumen517(c,H,model(c,raw([0.0005,null]))).valor,'<0,1 h obs.');assert.equal(M.horasResumen517(c,H,model(c,raw([1e308,1e308]))).valor,'—');});
await test('Borne ≥ nunca redondea hacia arriba ni desborda al multiplicar',()=>{const c=ctx();assert.equal(M.horasResumen517(c,H,model(c,raw([1.06,null]))).valor,'≥1 h');assert.equal(M.horasResumen517(c,H,model(c,raw([0.099,null]))).valor,'<0,1 h obs.');assert.equal(M.horasResumen517(c,H,model(c,raw([0.9999999999999999,null]))).valor,'≥0,9 h');const grande=M.horasResumen517(c,H,model(c,raw([1e308,null])));assert(grande.valor.startsWith('≥'));assert(!grande.valor.includes('∞'));assert.equal(grande.estado,'gris');});
await test('Domingo/lunes mantienen últimoL–V viernes, no cambio para cobertura',()=>{for(const hoy of ['2026-10-04','2026-10-05']){const c=ctx(hoy),r=M.horasResumen517(c,H,model(c));assert(r.detalle.includes('2026-10-02'));assert.equal(r.valor,'≥2 h');}});
await test('CambioDST no resta24h ni selecciona domingo',()=>{const c=ctx('2026-03-30'),r=M.horasResumen517(c,H,model(c,raw([4,null],'2026-03-28','2026-03-27')));assert.equal(r.valor,'≥4 h');assert(r.detalle.includes('2026-03-27'));});
await test('Día del sello aún incompleto no se usa comoayer',()=>{const c=ctx('2026-10-06');assert.equal(M.horasResumen517(c,H,model(c,raw())).valor,'—');});
for(const mode of ['grant','duplicate','inactive','roles','module','hoy'])await test('Revocación actual '+mode,()=>{const c=ctx(),hist=model(c);if(mode==='grant')c.ver=()=>({ok:false});if(mode==='duplicate')c.datos.personas.push({...person});if(mode==='inactive')c.real.estado='baja';if(mode==='roles')c.real.puestos=['operaciones','seo'];if(mode==='module')c.veModulo=id=>id!=='horas';if(mode==='hoy')c.hoy='invalid';assert.equal(M.horasResumen517(c,H,hist).valor,'—');});
await test('RendererGET una vez,0POST y scope revocado al abrirfuentes limpia',async()=>{const c=ctx(),main=h('main',{});main.connected=true;let gets=0;c.api=async route=>{assert.equal(route,'horas/historial-diario');gets++;return raw();};await M.renderResumen274(main,c,{fuentes:{horas:H}});assert.equal(gets,1);assert(main.textContent.includes('≥2 h'));const source=walk(main).find(x=>x.tag==='details'&&x.children[0]?.textContent==='Fuentes y alcance de los once indicadores');c.ver=()=>({ok:false});source.attrs.on.toggle();assert.equal(main.children[0].children.length,0);});
await test('Revocación duranteGET no deja cifra vieja o revive238',async()=>{const c=ctx(),main=h('main',{});main.connected=true;c.api=async()=>{c.ver=()=>({ok:false});return raw();};await M.renderResumen274(main,c,{fuentes:{horas:H}});assert(!main.textContent.includes('≥2 h'));assert(!main.textContent.includes('% ref.'));});
await test('GETdenegado/503 preservanunknown sin fallback',async()=>{for(const status of [403,503]){const c=ctx(),main=h('main',{});main.connected=true;c.api=async()=>{throw {status};};await M.renderResumen274(main,c,{fuentes:{horas:H}});assert(!main.textContent.includes('≥2 h'));assert(main.textContent.includes('Sin historial personal válido'));}});
console.log(n+' grupos517 PASS · historial364 y renderer274 reales, fixtures sin POST');
}finally{fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
