const fs=require('node:fs'),assert=require('node:assert/strict');
class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.children=[];this.append(...xs)}append(...xs){this.children.push(...xs.flat(Infinity).filter(x=>x!=null))}replaceChildren(...xs){this.children=[];this.append(...xs)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}desc(){return this.children.filter(x=>x instanceof N).flatMap(x=>[x,...x.desc()])}}
const h=(t,a,...xs)=>new N(t,a,xs),src=fs.readFileSync(__dirname+'/modulos/crm.js','utf8'),part=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
(async()=>{const M=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_crm_mediciones.js')).toString('base64'));let n=0;const test=(label,f)=>{f();n++};
const fuente={hora:'2026-10-03T12:00:00Z',estado:'bien'},hoy='2026-10-04',raw={cliente_id:'c',sub_id:'s',nombre:'Fixture',nombre_sub:'Fixture',tipo:'cliente',estado:'rojo',motivos:[{clave:'integracion',nivel:'rojo'}],errores_lectura:[],enlaces:{},leads_30d:10,citas_14d:{sin_estado:0},whatsapp:{enviados:10,fallidos:0}};
const norm=x=>M.normalizarFilaCRM(x,fuente,hoy),base=[norm(raw)];
test('legacy red or green never made current by global timestamp',()=>{for(const estado of ['rojo','ambar','verde']){const f=norm({...raw,estado});assert.equal(f.estado,'gris');assert.equal(f.estado_referencia,estado);assert.equal(f.motivos[0].nivel,'dato');assert(f.motivos[0].texto.includes('Señal anterior'));}});
test('positive sample preserved without contract or green',()=>{const f=norm({...raw,sin_tocar_24h:2,citas_14d:{sin_estado:1},whatsapp:{enviados:10,fallidos:1}});assert.equal(f.estado,'ambar');assert.equal(f.sin_tocar_24h,2);assert.equal(f.motivos.filter(x=>x.origen==='observacion_muestra').length,3);assert.equal(f.motivos.find(x=>x.clave==='integracion').nivel,'dato');});
test('explicit zero partial and absent not complete',()=>{for(const x of [raw,{...raw,sin_tocar_24h:0},{...raw,sin_tocar_24h:null}]){const f=norm(x);assert.equal(f.estado,'gris');assert.equal(f._medicionCRM.cobertura,'registros_observados_no_exhaustivos')}});
test('errors missing inventory and malformed positive not colored',()=>{for(const x of [{...raw,error:'red',sin_tocar_24h:3},{...raw,errores_lectura:['mensajes'],sin_tocar_24h:3},{...raw,errores_lectura:undefined,sin_tocar_24h:3},{...raw,cliente_id:{},sin_tocar_24h:3},{...raw,sub_id:null,sin_tocar_24h:3},{...raw,sin_tocar_24h:true},{...raw,sin_tocar_24h:Infinity}])assert.equal(norm(x).estado,'gris')});
test('source stale future bad offset no current sample',()=>{for(const hora of ['2020-01-01T12:00:00Z','2099-01-01T12:00:00Z','2026-10-03T12:00:00+02:99','2026-10-03T12:00:00+15:00','2026-02-30T12:00:00Z'])assert.equal(M.normalizarFilaCRM({...raw,sin_tocar_24h:2},{...fuente,hora},hoy).estado,'gris')});
test('producer naive Madrid cut explicit and DST ambiguous unknown',()=>{assert.equal(M.corteCRM541('2026-10-03 14:00',hoy),Date.parse('2026-10-03T12:00:00Z'));assert.equal(M.corteCRM541('2026-03-29 02:30',hoy),null);assert.equal(M.corteCRM541('2026-02-03T12:00:00Z','2026-02-30'),null)});
const cita={cliente_id:'c',sub_id:'s',ref:'r',inicio:'2026-10-01T12:00:00Z',estado_ghl:'confirmed',horas:999};
test('cita48 exact amber and >48 red not rounded hours',()=>{assert.equal(M.senalFilaCRM541('cita',cita,fuente,hoy,base).estado,'ambar');const x={...cita,inicio:'2026-10-01T11:59:59Z',horas:48};assert.equal(M.senalFilaCRM541('cita',x,fuente,hoy,base).estado,'rojo')});
test('cancelled attended missing or future not missing-result alert',()=>{for(const x of [{...cita,estado_ghl:'showed'},{...cita,estado_ghl:'cancelled'},{...cita,estado_ghl:undefined},{...cita,inicio:'2026-10-03T13:00:00Z'},{...cita,inicio:null}])assert.equal(M.senalFilaCRM541('cita',x,fuente,hoy,base).estado,'gris')});
test('unknown duplicate or foreign dimension never colored',()=>{for(const b of [[],[base[0],base[0]],[base[0],{...base[0],cliente_id:'otro'}],[{...base[0],cliente_id:'otro'}],[{...base[0],errores_lectura:['calendar']}]] )assert.equal(M.senalFilaCRM541('cita',cita,fuente,hoy,b).estado,'gris')});
test('opportunity unknown origin date neutral and lead creation not red',()=>{assert.equal(M.senalFilaCRM541('oportunidad',{...cita,horas:999},fuente,hoy,base).estado,'gris');assert.equal(M.senalFilaCRM541('lead',{...cita,creado:'2026-09-29T12:00:00Z',horas:999},fuente,hoy,base).estado,'ambar')});
test('observations outside producer closed windows remain references',()=>{assert.equal(M.senalFilaCRM541('cita',{...cita,inicio:'2026-09-01T12:00:00Z'},fuente,hoy,base).estado,'gris');assert.equal(M.senalFilaCRM541('lead',{...cita,creado:'2026-08-01T12:00:00Z'},fuente,hoy,base).estado,'gris');assert.equal(M.senalFilaCRM541('cita',{...cita,inicio:'2026-10-03T01:00:00Z'},fuente,hoy,base).estado,'gris')});
test('inputs immutable',()=>{const before=JSON.stringify(raw);norm(raw);assert.equal(JSON.stringify(raw),before)});
const gota=new Function(part('function cuentagotas(','const pesoSub')+';return cuentagotas;')();
test('actual no quota stable same row across filter sort pagination',()=>{const rows=Array.from({length:6},(_,i)=>({id:i,estado:'rojo',peso:i}));for(const xs of [rows,[rows[0]],[...rows].reverse(),rows.slice(0,2)])assert.equal(gota(xs,x=>x.estado,x=>x.peso)(rows[0]),'rojo')});
let tables=[],filter='activas',lastChips,configs=[];
const deps={...M,h,semaforo:()=>'gris',ID:'salud-crm',JEFA:'Fixture',JEFATURA:['operaciones'],EST:{rojo:{o:0,t:'Señal observada'},ambar:{o:1,t:'Revisar muestra'},verde:{o:2,t:'Verde'},gris:{o:3,t:'Referencia'}},ICO_MOT:{},QUIEN_MOT:{},ETAPAS:[],fmt:{num:x=>x==null?'—':String(x)},pc:x=>x+'%',pesoSub:()=>0,cuentagotas:gota,MOVIL:()=>false,logoCliente:()=>null,icono:()=>null,iniciales:()=>'',chipEstado:(e,t)=>h('span',{'data-color':e},t),puntoEstado:(e,t)=>h('span',{'data-color':e},t),chipsFiltro:o=>{lastChips=o;return Object.assign(h('div',{}),{valor:()=>filter})},panel:(o,...xs)=>h('section',{},o.titulo,...xs),notaCompacta336:(h,t,...xs)=>h('details',{},t,...xs),tablaDensa:o=>{tables.push(o);return h('table',{})},tablaApilable:o=>{tables.push(o);return h('table',{})},numFuerte:x=>x==null?'—':String(x),horasTxt:x=>String(x),fDiaRO:x=>x,botonRevisado:()=>null,botonVerDatos:()=>null,estadoRevisionCita334:()=>null,estadoRevisionLead369:()=>null,citasPendientes334:x=>x,leadsPendientes369:x=>x,masAcciones:()=>null,accionSim:()=>null,abrirGHL:()=>null,tareaAccount:()=>null,selectorCliente:o=>{configs.push(o);return null;},rejillaTarjetas:x=>h('div',{},x),tile:o=>{configs.push(o);return h('div',{'data-color':o.estado},o.etiqueta,o.valor)},sinDato:()=> '—',vacioLinea:x=>h('span',{},x),listaLoPrimero:xs=>h('ul',{},xs.map(x=>h('li',{'data-color':x.estado},x.motivo))),panelEmbudo469:()=>null,acciones:()=>null,avisoParcial:()=>null,plegable:()=>null};
const functions=part('function vista(', 'function sumar(')+part('function pintarSubcuentas(', '// ------------------------------------------------------------------ pestaña: leads sin tocar')+part('function pintarLeads(', '// ------------------------------------------------------------------ pestaña: oportunidades')+part('function pintarCitas(', '// ------------------------------------------------------------------ pestaña: por especialista')+part('function pintarFlujos(', '// ------------------------------------------------------------------ pestaña: montajes')+part('function pintarDetalle(', 'function acciones(');
// Dependencias de presentación, helpers de medición y funciones fuente reales.
const real=new Function('deps','with(deps){'+functions+';return{pintarSubcuentas,pintarLeads,pintarCitas,pintarFlujos,pintarDetalle};}')(deps);
const c={hoy,nivel:'todo',persona:{puestos:['operaciones']},ver:()=>({ok:true}),vigente:()=>true,titulo:()=>{},carteraIds:new Set(['c']),navegar:()=>{}},doc={subcuentas:base,fuentes:{ghl:fuente},leads_sin_tocar:[],citas_sin_estado:[cita],oportunidades_paradas:[],revisados:new Map()},vis={jefatura:true,base,mias:base,resumen:false};
test('actual default filter retains gray reference, columns stable',()=>{tables=[];real.pintarSubcuentas(h('main',{}),c,doc,vis);assert.equal(tables[0].filas.length,1);assert.equal(tables[0].columnas.length,8);assert.equal(tables[0].columnas.find(x=>x.clave==='estado').celda(base[0]).attrs['data-color'],'gris');filter='gris';lastChips.alCambiar();assert.equal(tables.at(-1).filas[0].sub_id,'s')});
test('actual Flujos not hidden when global gray, numeric zero retained neutral',()=>{tables=[];real.pintarFlujos(h('main',{}),c,doc,vis);assert.equal(tables[0].filas.length,1);const cell=tables[0].columnas.find(x=>x.clave==='wa').celda(base[0]);assert.equal(cell.attrs['data-color'],'gris');assert(cell.textContent.includes('0 de 10'))});
test('actual citas table same color after single row and bad hours999',()=>{tables=[];real.pintarCitas(h('main',{}),c,doc,vis,[cita]);let cell=tables[0].columnas.find(x=>x.clave==='horas');assert.equal(cell.celda(cita).desc()[0].attrs['data-color'],'ambar');tables=[];real.pintarCitas(h('main',{}),c,doc,vis,[{...cita,inicio:'2026-10-01T11:59:59Z'}]);cell=tables[0].columnas.find(x=>x.clave==='horas');assert.equal(cell.celda(tables[0].filas[0]).desc()[0].attrs['data-color'],'rojo');assert(cell.celda(tables[0].filas[0]).textContent.includes('>48 h'));assert(cell.celda(tables[0].filas[0]).attrs.title.includes(fuente.hora))});
test('actual detail preserves gray reference and same citas criterion',()=>{tables=[];configs=[];const root=h('main',{});real.pintarDetalle(root,c,doc,'s');const table=tables.find(t=>t.columnas.some(col=>col.clave==='inicio'));assert(table);assert.equal(table.columnas.find(col=>col.clave==='horas').celda(cita).desc()[0].attrs['data-color'],'ambar');assert(root.desc().some(x=>x.attrs['data-color']==='gris'&&x.textContent.includes('Señal anterior')));assert(configs.every(x=>x.estado!=='verde'));assert.equal(configs.find(x=>x.etiqueta==='Cambiar de subcuenta').clientes.length,1)});
test('real counter source never turns empty sample green or legacy into red',()=>{
 const counters=part('const franja = franjaCifras([','  cont.append(pantallaAncha(');
 const get=(cs,ls)=>new Function('deps','with(deps){'+counters+';return franja;}')({...deps,franjaCifras:x=>x,vis:{...vis},S:{ambar:0,pctWa:null},leads:ls,citas:cs,paradas:[{horas:999}],rev:new Map(),d:doc,ctx:c,pest:{elegir:()=>{}}});
 let a=get([],[]);assert.equal(a[0].estado,'gris');assert.equal(a[1].estado,'gris');assert.equal(a[3].estado,'gris');
 a=get([{...cita,inicio:'2026-10-01T11:59:59Z'}],[{...cita,creado:'2026-09-29T12:00:00Z'}]);assert.equal(a[0].estado,'ambar');assert.equal(a[1].estado,'rojo');assert.equal(a[3].estado,'gris');
});
console.log(n+' grupos541 PASS · normalizador, colores invariantes y tablas/ficha reales; sin API ni cambios de datos');
})().catch(e=>{console.error(e);process.exitCode=1});
