const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(__dirname+'/probar_operaciones_265.cjs','utf8').split('(async()=>{')[0];
const E=new Function('require','__dirname',base+';return {s,El,ctx,text};')(require,__dirname),{s,El,ctx,text}=E;
// h auténtico: eventos sólo on:{toggle}, atributos accesibles y textos sin HTML.
El.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(El.prototype,'className',{set(v){this.attrs.class=v;}});
s.Node=El;s.document={createElement:t=>{const n=new El(t,{});n.style={};return n;},createTextNode:t=>String(t)};
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function urlSegura('),comp.indexOf('const svgNS =')).replace(/export /g,''),s);
const all=n=>n instanceof El?[n,...n.children.flat(Infinity).flatMap(all)]:[],pick=(n,tag)=>all(n).filter(x=>x.tag===tag),copy=x=>JSON.parse(JSON.stringify(x));
let checks=0;const test=async(l,f)=>{await f();checks++;console.log('PASS '+l);};
const columns=[];s.tablaDensa=o=>{columns.push(o);return s.h('table',{},s.h('thead',{},s.h('tr',{},o.columnas.map(c=>s.h('th',{scope:'col'},c.titulo)))),s.h('tbody',{},o.filas.map(r=>s.h('tr',{},o.columnas.map(c=>s.h('td',{},c.celda?c.celda(r):r[c.clave]))))));};

async function mount({n=9,visto=false,fallo=false,empty=false,change=null}={}){
 const x=ctx();x.clientesVisibles=Array.from({length:n},(_,i)=>({id:'c'+i,nombre:'Cliente '+i,activo_confirmado:true,detalle:true}));x.clientes=x.clientesVisibles.map(c=>({id:c.id}));x.ver=()=>({ok:true});x.datos.personas.push({id:'constanza',estado:'activo',puestos:['proyectos']});
 let posts=0;x.accion=async()=>{posts++;throw Error('POST prohibido');};
 x.datosModulo=async path=>path==='verdad/clientes'?{generado:'2026-10-02',clientes:x.clientesVisibles.map(c=>({cliente_id:c.id,gravedad:'critico',motivo:empty?'':'Primera razón '+c.id,motivos:empty?[]:['Segunda razón íntegra '+c.id,'Tercera razón íntegra '+c.id]}))}:{};
 x.api=async(r,op)=>{assert(!op?.metodo||op.metodo==='GET');if(r.startsWith('en-rojo/planes?')){if(change)change(x);if(fallo)throw Error('fallo privado');const id=r.split('=').pop();return {cliente_id:id,version:visto?2:0,plan:visto?{version:1,que:'Plan privado',responsable_id:'account',plazo:'2026-10-12'}:null,revision:visto?{version:2,plan_version:1,actor_id:'constanza',estado:'visto'}:null,historial:[],capacidades:{},origen:'local'};}return {};};
 const root=s.h('main',{});await s.renderDiaDireccion265(root,x,'tomas');return {root,x,block:all(root).find(n=>n.attrs['data-planes-pendientes-500']!==undefined),posts};
}
(async()=>{
 await test('9 clientes y rutas exactas sin POST; vista previa compacta',async()=>{const {block,posts}=await mount();assert(block);assert.equal(pick(block,'tbody')[0].children.length,9);const ds=pick(block,'details');assert.equal(ds.length,9);assert(ds.every(d=>!d.open));assert(!text(block).includes('Segunda razón'));assert.deepEqual(pick(block,'a').slice(0,9).map(a=>a.attrs.href),Array.from({length:9},(_,i)=>'#/en-rojo/c'+i));assert.equal(posts,0);const span=pick(ds[0],'span')[0];assert.equal(span.style.whiteSpace,'nowrap');assert.equal(span.style.textOverflow,'ellipsis');assert.equal(pick(ds[0],'summary')[0].style.minHeight,'44px');});
 await test('Motivos completos y fuente preservados en disclosure nativo',async()=>{const {block}=await mount();const d=pick(block,'details')[0],summary=pick(d,'summary')[0];assert(summary.attrs.title.includes('Tercera razón íntegra c0'));assert.equal(summary.attrs['aria-label'],'Motivos completos de Cliente 0');d.open=true;d.events.toggle();for(const t of ['Primera razón c0','Segunda razón íntegra c0','Tercera razón íntegra c0','verdad operativa · 2026-10-02','no acreditan ejecución'])assert(text(d).includes(t),t);d.open=false;d.events.toggle();assert(!text(d).includes('Segunda razón'));});
 await test('Sin motivos no inventa razón',async()=>{const {block}=await mount({empty:true});assert.equal(text(pick(block,'summary')[0]),'—');assert.equal(pick(block,'summary')[0].attrs.title,'Sin motivo registrado');});
 await test('Lectura fallida permanece desconocida, no falta de plan',async()=>{const {block}=await mount({fallo:true,n:1});assert(text(block).includes('Plan / revisión no comprobados'));assert(!text(block).includes('Sin plan local registrado'));});
 await test('Plan vigente visto queda excluido según política original',async()=>{const {block,root}=await mount({visto:true,n:1});assert.equal(pick(block,'tbody')[0].children.length,0);assert(text(root).includes('1 con plan vigente visto por Coti'));});
 for(const mode of ['grant','ACT','duplicate','roles','identity','module','disconnected'])await test('Revocación al abrir detalle '+mode,async()=>{const {block,x}=await mount();const d=pick(block,'details')[0];if(mode==='grant')x.ver=()=>({ok:false});if(mode==='ACT')x.clientes[0].activo=false;if(mode==='duplicate')x.clientes.push({...x.clientes[0]});if(mode==='roles')x.persona.puestos=['direccion','seo'];if(mode==='identity')x.persona.id='other';if(mode==='module')x.veModulo=id=>id!=='en-rojo';if(mode==='disconnected')block.isConnected=false;d.open=true;d.events.toggle();assert.equal(block.children.length,0);});
 await test('Enlace bloqueado tras revocación y limpia motivos',async()=>{const {block,x}=await mount();const a=pick(block,'a')[0];x.ver=()=>({ok:false});let prevented=false;a.events.click({preventDefault(){prevented=true;}});assert(prevented);assert.equal(block.children.length,0);});
 await test('Cambio durante await no publica lista antigua',async()=>{const {block,root}=await mount({change:x=>{x.ver=()=>({ok:false});}});assert.equal(block,undefined);assert(!text(root).includes('Primera razón'));assert(!text(root).includes('Segunda razón'));});
 console.log(checks+' grupos motivos500 PASS · renderer265 y h reales');
})().catch(e=>{console.error(e);process.exitCode=1;});
