const fs360=require('fs'),path360=require('path');
const prefix360=fs360.readFileSync(path360.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
const body360=`
const SHA360='be7ff0dcc533d283d7fb2f02cc556b0fc0d9e39f080e5eb1b95ddde02818a7a4';
const fixture360=()=>({version:'356.1',fuente_version:'355.1',sha256_candidato:SHA360,estado:'copia_observada',fuente:'clickup_cache_local',generado:'2026-10-03T18:00:00Z',cobertura:'parcial',lectura_desde_utc:'2026-10-03T17:00:00Z',lectura_hasta_utc:'2026-10-03T17:00:00Z',observaciones:2,cliente_ids:['c1','c2'],disciplina:null,cumplimiento:null,filas:['c1','c2'].map((cliente_id,i)=>({tarea_id:'task'+i,cliente_id,lista_id:'list',estado:i?'backlog':'planning mensual',tipo_estado:'custom',estado_fuente:'clickup',estado_leido_utc:'2026-10-03T17:00:00Z',asignados_persona_ids:['a'],asignacion_estado:'observada',asignados_sin_identidad_confirmada:0,inicio_utc:null,inicio_estado:'sin_dato',vence_utc:'2026-11-03T08:00:00Z',vence_estado:'observada',estimacion:{valor:i?null:3600000,unidad:'milisegundos',estado:i?'sin_dato':'observada'},cobertura:'parcial',actor_historico:null,estado_inicial:null,rompe_semanal:null,fuego_confirmado:null}))});
const ctx360=()=>{const people=[{id:'ops',nombre:'Ops fixture',estado:'activo',puestos:['operaciones']},{id:'a',nombre:'Persona actual',estado:'activo',puestos:['account']}];const clientes=[{id:'c1',nombre:'Cliente uno',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'a',principal:true,confianza:'confirmada'}]}},{id:'c2',nombre:'Cliente dos',activo_confirmado:true,detalle:true}];return {clientes,servidor:true,hoy:'2026-10-03',real:people[0],persona:people[0],datos:{personas:people,asignaciones:[{cliente_id:'c1',persona_id:'a',silla:'account',principal:true,confianza:'confirmada'}]},clientesVisibles:[{id:'c1',nombre:'Cliente uno',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'a',principal:true,confianza:'confirmada'}]}},{id:'c2',nombre:'Cliente dos',activo_confirmado:true,detalle:true}],carteraPorSilla:{account:new Set(['c1'])},veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,api:async route=>{assert.equal(route,'produccion/planning-observado');return fixture360();},datosModulo:async()=>({personas:[],proyectos:[]})};};
const render360=async(node,ctx)=>{const result=await c.panelPlanningObservado360(node,ctx);const d=all(node,n=>n.attrs['data-planning-proyectos-412']!==undefined)[0];if(d){d.open=true;d.events.toggle();}return result;};
(async()=>{
 await test('360strict canonical contract',()=>{const ctx=ctx360(),d=fixture360();const out=c.proyectarPlanning360(ctx,d,c.ambitoPlanning360(ctx));assert.equal(out.filas.length,2);assert.equal(out.filas[0].vence,'2026-11-03');assert(!JSON.stringify(out).includes('disciplina'));});
 for(const [key,value] of [['version','wrong'],['sha256_candidato','a'.repeat(64)],['generado','2026-10-04T18:00:00Z'],['generado','2026-10-03T25:00:00Z'],['cumplimiento',true],['observaciones',0]])await test('360reject '+key+value,()=>{const ctx=ctx360();assert.equal(c.proyectarPlanning360(ctx,{...fixture360(),[key]:value},c.ambitoPlanning360(ctx)),null);});
 await test('360scope unknown foreign duplicate rows',()=>{for(const change of [d=>d.cliente_ids.push('foreign'),d=>d.filas.push({...d.filas[0]}),d=>d.filas[0].tipo_estado='closed',d=>d.filas[0].estado_leido_utc='2026-10-03T19:00:00Z',d=>d.filas[0].estimacion.unidad='euros']){const ctx=ctx360(),d=fixture360();change(d);assert.equal(c.proyectarPlanning360(ctx,d,c.ambitoPlanning360(ctx)),null);}});
 await test('360real renderer compacttable andclosed details',async()=>{const ctx=ctx360(),node=new N('main');await render360(node,ctx);assert.equal(all(node,n=>n.tag==='table')[0].children[0].children[0].children.length,5);assert(text(node).includes('≥1'));assert(text(node).includes('1 h'));assert(all(node,n=>n.tag==='td').some(n=>String(n.attrs.title).includes('1/1 tareas con estimación observada')));assert(!text(node).includes('0 tareas'));assert(all(node,n=>n.attrs['data-planning-cliente']).every(d=>!d.open));assert(text(node).includes('2/2 clientes con observaciones'));assert.equal(all(node,n=>n.tag==='table').length,1);const details=all(node,n=>n.attrs['data-planning-cliente'])[0];details.open=true;details.events.toggle();assert(text(node).includes('2026-11-03'));});
 await test('360nativeclient andassignedfilters',async()=>{const node=new N('main'),ctx=ctx360();await render360(node,ctx);const client=all(node,n=>n.tag==='select')[0];client.value='c1';client.events.change();assert.equal(all(node,n=>n.attrs['data-planning-cliente']).length,1);assert(!text(all(node,n=>n.tag==='table')[0]).includes('Cliente dos'));const assigned=all(node,n=>n.tag==='select')[1];assigned.value='__unknown';assigned.events.change();assert(text(node).includes('Sin observaciones autorizadas'));assert(!text(node).includes('0 tareas'));});
 for(const [label,change]of [['ACT',ctx=>ctx.clientesVisibles[0].activo_confirmado=false],['grant',ctx=>ctx.ver=()=>({ok:false})],['role',ctx=>ctx.datos.personas[0].puestos=['seo']],['identity',ctx=>ctx.persona={id:'other'}],['module',ctx=>ctx.veModulo=()=>false]])await test('360revoked duringawait '+label,async()=>{const ctx=ctx360(),node=new N('main');let finish;ctx.api=()=>new Promise(r=>finish=r);const p=c.panelPlanningObservado360(node,ctx);change(ctx);finish(fixture360());await p;assert.equal(text(node),'');});
 await test('360toggle andfilter revoke clear visiblefields',async()=>{const ctx=ctx360(),node=new N('main');await render360(node,ctx);const detail=all(node,n=>n.attrs['data-planning-cliente'])[0];ctx.clientesVisibles[0].activo_confirmado=false;detail.open=true;detail.events.toggle();assert.equal(text(node),'');});
 await test('363Account ownreadgrant othersrejected',async()=>{const ctx=ctx360();ctx.real=ctx.persona=ctx.datos.personas[1];const d=fixture360();d.filas=d.filas.filter(r=>r.cliente_id==='c1');d.cliente_ids=['c1'];d.observaciones=1;ctx.api=async()=>d;const node=new N('main');await render360(node,ctx);assert(text(node).includes('Cliente uno'));assert(!text(node).includes('Cliente dos'));ctx.datos.asignaciones[0].confianza='alta';ctx.clientesVisibles[0].equipo.account[0].confianza='alta';assert.deepEqual(Array.from(c.ambitoPlanning360(ctx).ids),['c1']);ctx.ver=()=>({ok:false});assert.equal(c.ambitoPlanning360(ctx).ids.length,0);});
 await test('360snapshotempty neverfullzero',async()=>{const ctx=ctx360(),d=fixture360();d.filas=[];d.observaciones=null;d.lectura_desde_utc=d.lectura_hasta_utc=null;ctx.api=async()=>d;const node=new N('main');await render360(node,ctx);assert(text(node).includes('Sin observaciones'));assert(!text(node).includes('0 tareas'));});
 await test('360missing service visibly honest',async()=>{const ctx=ctx360();ctx.api=async()=>{throw Error('fixture')};const node=new N('main');await render360(node,ctx);assert(text(node).includes('Inventario no disponible'));});
 await test('360tinyestimates do notroundpositive tozero',async()=>{const ctx=ctx360(),d=fixture360();d.filas[0].estimacion.valor=1;ctx.api=async()=>d;const node=new N('main');await render360(node,ctx);assert(text(node).includes('<0,1 h'));assert(!text(node).includes('0 h observadas'));});
 await test('360integratedactualplanbranch retainsdiscipline andcomparison',async()=>{const node=new N('main'),ctx=ctx360();await c.renderEquipo262(node,ctx,'planificacion');assert(text(node).includes('Disciplina de planificación'));assert(all(node,q=>q.tag==='th'&&q.attrs.title==='Rompen el semanal').length===1);assert(text(node).includes('Inventario de planificación'));assert(text(node).includes('Cliente uno'));});
 console.log(checks+' grupos360 PASS · helpers/componentes/render262 reales, sin POST/proveedores');
})().catch(e=>{console.error(e);process.exitCode=1;});
`;
new Function('require','__dirname',prefix360+body360)(require,__dirname);
