const fs=require('fs'),vm=require('vm'),assert=require('assert');
const box={};vm.createContext(box);vm.runInContext(fs.readFileSync('modulos/_informes_declarados_612.js','utf8').replace(/export /g,'')+'\nthis.ambito=ambitoResumenInformes612;this.proyectar=proyectarResumenInformes612;this.sumar=agregarInformesDeclarados615;',box);
const nota='Declaraciones activas por mes del informe, no por fecha de envío. Cero no acredita ausencia de envío ni cumplimiento; no hay verificación externa.';
const row=(cliente_id,n)=>({cliente_id,informes_declarados:n,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null});
function fixture(rows=[row('c1',2),row('c2',3)]){const p={id:'actor',nombre:'Fixture',estado:'activo',puestos:['operaciones']};const cs=['c1','c2','c3'].map(id=>({id,activo_confirmado:true,detalle:true}));const ctx={real:p,persona:p,servidor:true,periodoSeleccionado:'2026-09',hoy:'2026-10-04',datos:{personas:[p]},clientes:cs,clientesVisibles:cs,vigente:()=>true,veModulo:()=>true,ver:()=>({ok:true})};let alive=true;const scope={...box.ambito(ctx,'2026-09'),vigente:()=>alive&&ctx.periodoSeleccionado==='2026-09'};const dto={version:'611.1',periodo_informe:'2026-09',clientes:rows,nota,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null,cobertura:'parcial'};return {ctx,p,cs,scope,dto,modelo:box.proyectar(ctx,dto,scope),revoke:()=>alive=false};}
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name)};
test('sumas seguras filas explícitas 2/2 grises',()=>{const q=fixture(),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'5 decl.');assert.equal(r.estado,'gris');assert.equal(r.cobertura.observados,2);assert.equal(r.cobertura.total,2);assert.equal(r.cobertura.parcial,true);assert(r.detalle.includes('2026-09'));assert(r.detalle.includes('no mes de envío'));assert(r.detalle.includes('no verifica envío, cumplimiento ni Score'));assert(r.vigente())});
test('missing no0, subtotal observado1/2',()=>{const q=fixture([row('c1',2)]),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'2 decl.');assert.equal(r.cobertura.observados,1);assert.equal(r.cobertura.total,2);assert(r.detalle.includes('1/2'));});
test('0 explícito entre missing válido sólesa fila',()=>{const q=fixture([row('c1',0)]),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'0 decl.');assert.equal(r.cobertura.observados,1);assert(r.detalle.includes('sólo incluye esas filas'));});
test('todas filas explícitas0 no desempeño',()=>{const q=fixture([row('c1',0),row('c2',0)]),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'0 decl.');assert.equal(r.cobertura.observados,2);assert.equal(r.estado,'gris')});
test('ausencia todas es unknown 0/2coverage',()=>{const q=fixture([]),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'—');assert.equal(r.informes_declarados,null);assert.equal(r.cobertura.observados,0);assert(r.detalle.includes('0/2'))});
test('ids inválidos duplicados sin selección ajenos',()=>{const q=fixture();for(const ids of [null,{},[],['c1','c1'],['c1',null],['c1',{}],['c1','c2@email'],['c1','ajeno']]){const r=box.sumar(q.modelo,ids);assert.equal(r.valor,'—');assert.equal(r.vigente(),false)}});
test('safeoverflow unknown no mínimo incompleto',()=>{const q=fixture([row('c1',Number.MAX_SAFE_INTEGER),row('c2',1)]),r=box.sumar(q.modelo,['c1','c2']);assert.equal(r.valor,'—');assert.equal(r.informes_declarados,null);assert.equal(r.cobertura.observados,null)});
test('maxsafe permitido y no redondeo suma',()=>{const q=fixture([row('c1',Number.MAX_SAFE_INTEGER),row('c2',0)]);assert.equal(box.sumar(q.modelo,['c1','c2']).informes_declarados,Number.MAX_SAFE_INTEGER)});
for(const [name,mut] of Object.entries({epoch:q=>q.revoke(),actorBaja:q=>q.p.estado='baja',actorDup:q=>q.ctx.datos.personas.push({...q.p}),roles:q=>q.p.puestos.push('seo'),clienteACT:q=>q.cs[0].activo_confirmado=false,clienteDup:q=>q.ctx.clientes.push({...q.cs[0]}),grant:q=>q.ctx.ver=()=>({ok:false}),modulo:q=>q.ctx.veModulo=()=>false,periodo:q=>q.ctx.periodoSeleccionado='2026-10'}))test('revoca subtotal/callback '+name,()=>{const q=fixture(),prev=box.sumar(q.modelo,['c1','c2']);mut(q);assert.equal(box.sumar(q.modelo,['c1','c2']).valor,'—');assert.equal(prev.vigente(),false)});
test('captura copia deids frente a mutación caller',()=>{const q=fixture(),ids=['c1','c2'],r=box.sumar(q.modelo,ids);ids.push('ajeno');assert(r.vigente());assert.equal(r.valor,'5 decl.');assert.equal(r.cobertura.total,2)});
test('modelo desconocido no suma ni datosprivados',()=>{const r=box.sumar({periodo_informe:'PRIVATE'},['c1']);assert.equal(r.valor,'—');assert(!r.detalle.includes('PRIVATE'));assert(!JSON.stringify(r).includes('autor'))});
test('revocación durante agregación no sumamixed',()=>{const q=fixture();let calls=0;const orig=q.ctx.ver;q.ctx.ver=x=>{calls++;if(calls===6)q.cs[0].activo_confirmado=false;return orig(x)};assert.equal(box.sumar(q.modelo,['c1','c2']).valor,'—')});
console.log(n+' grupos PASS615; sin API/POST/DB');
