const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const setup=fs.readFileSync('pruebas_triaje_durable_432.cjs','utf8').split('let count=0;')[0];
const outer={require,console,process};vm.createContext(outer);vm.runInContext(setup+';globalThis.E440=e;globalThis.F440=fixture;globalThis.H440=h;globalThis.ALL440=all;globalThis.ST440=storage;',outer);
const e=outer.E440,f=outer.F440,h=outer.H440,all=outer.ALL440,storage=outer.ST440;
const dto=()=>({version:'437.1',ticket_id:'desk1',cliente_id:'cid',objeto:'RO123',origen:'ledger_local',lectura_exacta:true,confirmacion_desk:false,tipos:{asignar:{cantidad:0,ultima:null},cerrar:{cantidad:0,ultima:null}}});
const prev=(id=null,propia=false)=>({cantidad:1,ultima:{accion_id:1,estado_registro:'simulada',intencion_id:id,propia}});
let groups=0;async function test(fn){await fn();groups++;}
(async()=>{
await test(async()=>{const {ctx,S,t}=f();let path;ctx.api=async p=>(path=p,dto());await e.consultarTriaje440(ctx,S,t,'asignar');assert.equal(path,'bandeja/triaje-intenciones?ticket_id=desk1&cliente_id=cid');assert.equal(storage.size,0);assert.equal(S.intencionesTriaje432,undefined);});
for(const modify of [d=>d.version='437.0',d=>d.ticket_id='other',d=>d.cliente_id='other',d=>d.objeto='other',d=>d.origen='provider',d=>d.lectura_exacta=false,d=>d.confirmacion_desk=true,d=>delete d.tipos.cerrar,d=>d.tipos.extra={},d=>d.tipos.asignar.cantidad=-1,d=>d.tipos.asignar.cantidad=0.5,d=>d.tipos.asignar.ultima={},d=>d.tipos.asignar={cantidad:1,ultima:null},d=>d.tipos.asignar=prev('invalid',true),d=>d.tipos.asignar=prev('00000000-0000-4000-8000-000000000001',false)])await test(async()=>{const {ctx,S,t}=f(),d=dto();modify(d);ctx.api=async()=>d;await assert.rejects(e.consultarTriaje440(ctx,S,t,'cerrar'));assert.equal(storage.size,0);});
for(const tipo of ['asignar','cerrar'])await test(async()=>{const {ctx,S,t}=f(),d=dto();d.tipos[tipo]=prev();ctx.api=async()=>d;let writes=0;ctx.accion=async()=>{writes++;};const root=h('main',{});e.pintarTriaje(root,ctx,S);await assert.rejects(all(root,x=>x.config&&x.textContent==='Solicitar cierre')[0].on.click());assert.equal(writes,0);assert.equal(storage.size,0);assert(root.textContent.includes(t.asunto));assert(root.textContent.includes('Envíos'));});
await test(async()=>{const {ctx,S,t}=f();ctx.api=async()=>{throw Error('503');};await assert.rejects(e.consultarTriaje440(ctx,S,t,'cerrar'));assert.equal(storage.size,0);});
await test(async()=>{const {ctx,S,t}=f();ctx.api=async()=>{ctx.clientes[0].activo_confirmado=false;return dto();};await assert.rejects(e.consultarTriaje440(ctx,S,t,'cerrar'));assert.equal(storage.size,0);});
await test(async()=>{const {ctx,S,t}=f();const intention=e.intencionTriaje432(ctx,S,t,'asignar'),d=dto();d.tipos.asignar=prev(intention.payload.intencion_id,true);ctx.api=async()=>d;await e.consultarTriaje440(ctx,S,t,'asignar');assert.equal(e.intencionTriaje432(ctx,S,t,'asignar').payload.intencion_id,intention.payload.intencion_id);d.tipos.asignar.cantidad=2;await assert.rejects(e.consultarTriaje440(ctx,S,t,'asignar'));d.tipos.asignar.cantidad=1;d.tipos.asignar.ultima.estado_registro='pendiente';await assert.rejects(e.consultarTriaje440(ctx,S,t,'asignar'));});
await test(async()=>{const {ctx,S,t}=f(),d=dto();d.tipos.asignar=prev('00000000-0000-4000-8000-000000000999',true);ctx.api=async()=>d;await assert.rejects(e.consultarTriaje440(ctx,S,t,'asignar'));assert.equal(storage.size,0);});
await test(async()=>{const {ctx,S,t}=f();const i=e.intencionTriaje432(ctx,S,t,'cerrar'),reload=f(false),d=dto();d.tipos.cerrar=prev(i.payload.intencion_id,true);reload.ctx.api=async()=>d;await e.consultarTriaje440(reload.ctx,reload.S,reload.t,'cerrar');assert.equal(e.intencionTriaje432(reload.ctx,reload.S,reload.t,'cerrar').payload.intencion_id,i.payload.intencion_id);});
await test(async()=>{const {ctx,S,t}=f();let resolve,writes=0;ctx.api=()=>new Promise(r=>resolve=r);ctx.accion=async()=>{writes++;};const root=h('main',{});e.pintarTriaje(root,ctx,S);const pending=all(root,x=>x.config&&x.textContent==='Solicitar cierre')[0].on.click();assert.equal(storage.size,0);ctx.vigente=()=>false;resolve(dto());await assert.rejects(pending);assert.equal(writes,0);assert.equal(storage.size,0);assert.equal(root.children.length,0);});
console.log(groups+' grupos440 PASS · preflight real previoUUID, ledger antiguo, retry/mismoUUID, legacy/desconocido, revocación; sin POST real');
})().catch(error=>{console.error(error);process.exitCode=1;});
