const fs=require('fs'),vm=require('vm'),A=require('assert');
const clean=s=>s.replace(/^import\s[\s\S]*?;\s*/gm,'').replace(/export default \{/g,'globalThis.moduloAlertas={').replace(/export (const|function|class)/g,'$1');
class N {constructor(tag,attrs={},...kids){this.tag=tag;this.attrs=attrs;this.kids=[];this.listeners={};this.append(...kids)}append(...ks){for(const k of ks.flat(Infinity)){if(k==null)continue;if(k instanceof N)k.parent=this;this.kids.push(k)}}replaceChildren(...ks){this.kids=[];this.append(...ks)}remove(){if(this.parent)this.parent.kids=this.parent.kids.filter(k=>k!==this)}addEventListener(k,f){(this.listeners[k]??=[]).push(f)}click(){this.attrs.on?.click?.({currentTarget:this});for(const f of this.listeners.click||[])f({currentTarget:this})}get textContent(){return this.kids.map(k=>k instanceof N?k.textContent:String(k)).join('')}get isConnected(){return true}focus(){}querySelector(sel){return walk(this).find(x=>sel==='.tostada'?(x.attrs.class||'').includes('tostada'):x.tag===sel)||null}}
const walk=n=>n.kids.flatMap(k=>k instanceof N?[k,...walk(k)]:[]);
function setup(){const timers=new Map();let ti=0;const notices=[],calls=[],events={};const body=new N('body');const h=(...a)=>new N(...a);
const b={console,Date,Map,Set,JSON,Number,Intl,h,ico:()=>h('i'),icono:()=>h('i'),setTimeout:(f,ms)=>{timers.set(++ti,{f,ms});return ti},clearTimeout:i=>timers.delete(i),setInterval:()=>++ti,clearInterval:()=>{},document:{body,querySelector:s=>body.querySelector(s),addEventListener:(k,f)=>events[k]=f,visibilityState:'visible'},window:{addEventListener:(k,f)=>events[k]=f},fechaCortaRO:s=>s,sumarDiasRO:(d,n)=>new Date(Date.parse(d+'T12:00Z')+n*864e5).toISOString().slice(0,10),avisoFlotante:s=>notices.push(s),fmt:{plural:(n,s)=>`${n} ${s}`}};
vm.createContext(b);vm.runInContext(clean(fs.readFileSync('_fechas_ro.js','utf8'))+'\nglobalThis.FECHAS_RO={instante:instanteRO,dia:diaRO,hora:horaRO,fechaCivil:fechaCivilRO,horasHasta:horasHastaRO,horasDesde:horasDesdeRO};',b);
vm.runInContext('(function(){'+clean(fs.readFileSync('modulos/_deshacer.js','utf8'))+';globalThis.conDeshacer=conDeshacer;})()',b);vm.runInContext(clean(fs.readFileSync('modulos/alertas.js','utf8'))+'\nglobalThis.api594={S,marcar,lote,posponer,fechaVuelta,vigenteDecision594};',b);
const p={id:'p-fixture',puestos:['operaciones'],estado:'activo',activo:true};const ctx={real:p,persona:p,datos:{personas:[p]},clientes:[{id:'c-fixture',activo_confirmado:true,activo:true}],servidor:true,soloLectura:false,vigente:()=>true,veModulo:()=>true,ver:()=>({ok:true}),accion:async x=>{calls.push(x);return {ok:true,id:1,estado:'simulada'}}};const a={id:'web_caida:c-fixture',cliente_id:'c-fixture',motivo:'Señal sintética',departamento:'web',escalado_cadena:['p-fixture']},a2={...a,id:'segunda:c-fixture'};
Object.assign(b.api594.S,{ctx,D:{generado:'2026-10-04T10:00Z',posponer_max_dias:31},ahora:new Date('2026-10-04T10:00Z'),local:new Map(),sel:new Set(),porId:new Map([[a.id,a],[a2.id,a2]]),refrescar:()=>{}});
return {b,ctx,a,a2,calls,notices,body,events,S:b.api594.S,run:async()=>{for(const [id,t] of [...timers])if(t.ms===8000){timers.delete(id);await t.f()}await Promise.resolve()}}}
let count=0;async function test(n,f){await f();count++;console.log('PASS '+n)}
(async()=>{
await test('individual espera y Deshacer no POST',async()=>{const x=setup();const t=await x.b.api594.marcar(x.a,'resuelta');A.equal(x.calls.length,0);A.equal(x.S.local.get(x.a.id).pendiente,true);A.match(x.body.textContent,/pendiente de guardar/);t.deshacer();await x.run();A.equal(x.calls.length,0);A.equal(x.S.local.has(x.a.id),false)});
await test('plazo sólo una escritura con acuse local',async()=>{const x=setup();await x.b.api594.marcar(x.a,'lo_tengo');await x.run();A.equal(x.calls.length,1);A.equal(x.calls[0].tipo,'alerta_lo_tengo');A.equal(x.S.local.get(x.a.id).pendiente,false);A.match(x.notices[0],/local guardada/)});
await test('lote usa una acción y cancelar restaura selección exacta',async()=>{const x=setup();x.S.sel.add(x.a.id);x.S.sel.add(x.a2.id);const t=await x.b.api594.lote('resuelta');A.equal(x.S.sel.size,0);t.deshacer();await x.run();A.equal(x.calls.length,0);A.equal(x.S.sel.size,2);A.equal(x.S.local.size,0)});
await test('lote no divide aceptación en varios POST',async()=>{const x=setup();x.S.sel.add(x.a.id);x.S.sel.add(x.a2.id);await x.b.api594.lote('resuelta');await x.run();A.equal(x.calls.length,1);A.equal(x.calls[0].tipo,'alerta_lote');A.deepEqual(Array.from(x.calls[0].vista_previa.ids),[x.a.id,x.a2.id]);A.equal(x.S.local.size,2)});
await test('error lote restaura valores previos y selección',async()=>{const x=setup();const previo={estado:'vista'};x.S.local.set(x.a.id,previo);x.S.sel.add(x.a.id);x.S.sel.add(x.a2.id);x.ctx.accion=async()=>{throw Error('fixture')};await x.b.api594.lote('lo_tengo');await x.run();A.strictEqual(x.S.local.get(x.a.id),previo);A.equal(x.S.local.has(x.a2.id),false);A.equal(x.S.sel.size,2);A.match(x.body.textContent,/No se pudo/)});
await test('null y ok genérico no confirman guardado',async()=>{for(const r of [null,{ok:true},{ok:true,id:1,estado:'enviada'}]){const x=setup();x.ctx.accion=async()=>r;await x.b.api594.marcar(x.a,'resuelta');await x.run();A.equal(x.S.local.size,0);A.match(x.body.textContent,/No se confirmó el registro local/);A.equal(x.notices.length,0)}});
await test('sólo lectura y permiso inexistente no programan',async()=>{for(const alter of [x=>x.ctx.soloLectura=true,x=>x.ctx.veModulo=()=>false,x=>x.ctx.ver=()=>({ok:false})]){const x=setup();alter(x);await A.rejects(x.b.api594.marcar(x.a,'resuelta'));A.equal(x.S.local.size,0);A.equal(x.calls.length,0)}});
await test('revocación antes plazo cancela escritura',async()=>{const x=setup();await x.b.api594.marcar(x.a,'resuelta');x.ctx.veModulo=()=>false;await x.run();A.equal(x.calls.length,0);A.equal(x.S.local.size,0)});
await test('revocación tras await no confirma ni pisa otra decisión',async()=>{const x=setup();let finish;x.ctx.accion=async()=>new Promise(r=>finish=r);await x.b.api594.marcar(x.a,'resuelta');const running=x.run();await Promise.resolve();const posterior={estado:'vista'};x.S.local.set(x.a.id,posterior);x.ctx.vigente=()=>false;finish({ok:true,id:1,estado:'simulada'});await running;A.strictEqual(x.S.local.get(x.a.id),posterior);A.equal(x.notices.length,0)});
await test('posponer inválido no abre Deshacer ni escribe',async()=>{const x=setup();await x.b.api594.posponer(x.a,'fecha','2026-10-03');A.equal(x.S.local.size,0);A.equal(x.calls.length,0);A.match(x.notices[0],/fecha válida/)});
await test('posponer válido conserva fecha Madrid y Deshacer',async()=>{const x=setup();const t=await x.b.api594.posponer(x.a,'fecha','2026-10-05');A.equal(x.S.local.get(x.a.id).hasta,'2026-10-05 09:00');A.equal(x.calls.length,0);/* posponer delega; se pulsa botón nativo */x.body.querySelector('button').click();await x.run();A.equal(x.calls.length,0);A.equal(x.S.local.size,0)});
await test('segundo cambio guarda anterior y fallo no revierte posterior',async()=>{const x=setup();let finish;x.ctx.accion=()=>new Promise(r=>finish=r);await x.b.api594.marcar(x.a,'vista');await x.b.api594.marcar(x.a,'lo_tengo');finish(null);await new Promise(setImmediate);A.equal(x.S.local.get(x.a.id).estado,'lo_tengo')});
await test('error previo y Deshacer posterior no recuperan estado pendiente huérfano',async()=>{const x=setup();let finish;x.S.sel.add(x.a.id);x.ctx.accion=()=>new Promise(r=>finish=r);await x.b.api594.marcar(x.a,'vista');const siguiente=await x.b.api594.marcar(x.a,'lo_tengo');finish(null);await new Promise(setImmediate);siguiente.deshacer();A.equal(x.S.local.has(x.a.id),false);A.equal(x.S.sel.has(x.a.id),true)});
await test('dos decisiones aceptada y fallida no revierten la aceptada',async()=>{const x=setup();let n=0;x.ctx.accion=async()=>{if(++n===1)return {ok:true,id:1,estado:'simulada'};throw Error('segunda')};await x.b.api594.marcar(x.a,'vista');await x.b.api594.marcar(x.a2,'resuelta');await new Promise(setImmediate);await x.run();A.equal(n,2);A.equal(x.S.local.get(x.a.id).estado,'vista');A.equal(x.S.local.get(x.a.id).pendiente,false);A.equal(x.S.local.has(x.a2.id),false)});
console.log(count+' grupos Alertas594 PASS; helper Deshacer real, reloj/DOM/transporte sintéticos.');
})().catch(e=>{console.error(e);process.exitCode=1});
