const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_metadatos_tarea_225.js','utf8').replace(/export function /g,'function '),c);
class Nodo{constructor(tag,props,children){this.tag=tag;this.props=props;this.children=children.flat().filter(x=>x!=null);this.events=props.on||{};this.isConnected=true;this.disabled=props.disabled;}append(...xs){this.children.push(...xs.flat().filter(x=>x!=null));}replaceChildren(...xs){this.children=xs.flat().filter(x=>x!=null);}}
const h=(tag,props,...xs)=>new Nodo(tag,props||{},xs),texto=x=>typeof x==='string'?x:typeof x==='number'?String(x):(x?.children||[]).map(texto).join(' ');
const data=()=>({tarea_id:'task-fixture',cliente_id:'client-fixture',lista_id:'list-fixture',fuente:'copia_local_clickup',estado_leido_utc:'2026-10-03T10:00:00+00:00',checklists:{estado:'observado',total_confirmado:2,resueltos_observados:1,items_observados:2,listas:[{id:'list-check',cobertura:'observado',items:[{id:'item-a',resuelto:true},{id:'item-b',resuelto:false}]}]},entregable:{estado:'sin_dato',url:null},adjuntos:{estado:'sin_dato',cantidad:null}});
let groups=0;
function fixture(patch={}){const ctx={servidor:true,real:{id:'owner'},persona:{id:'owner'},vigente:()=>true,...patch};const E={ctx,vigente:()=>true};const t={id:'task-fixture',cli:'client-fixture',lista_id:'list-fixture'};let calls=[];ctx.api=ctx.api|| (async ruta=>{calls.push(ruta);return data()});const box=c.renderMetadatosTarea225(E,t,h);const btn=box.children[2];return {ctx,E,t,box,btn,calls};}
(async()=>{
 let f=fixture();assert.equal(f.calls.length,0);await f.btn.events.click();assert.equal(f.calls[0],'mi_trabajo/metadatos?tarea=task-fixture');assert.match(texto(f.box),/1 de 2 elementos/);assert.match(texto(f.box),/ID item-a/);assert.match(texto(f.box),/Lista sin título conservado/);assert.match(texto(f.box),/no acredita entrega ni aceptación/);assert.match(texto(f.box),/Adjuntos sin dato/);groups++;
 f=fixture({soloLectura:true,real:{id:'ops'},persona:{id:'owner'}});await f.btn.events.click();assert.equal(f.calls.length,1);assert.match(texto(f.box),/1 de 2/);groups++;
 f=fixture({pilotoLectura:true});assert(f.btn.disabled);await f.btn.events.click();assert.equal(f.calls.length,0);assert.match(texto(f.box),/piloto de lectura/);groups++;
 f=fixture({servidor:false});assert(f.btn.disabled);await f.btn.events.click();assert.equal(f.calls.length,0);groups++;
 for(const field of ['tarea_id','cliente_id','lista_id','fuente']){f=fixture({api:async()=>({...data(),[field]:'foreign'})});await f.btn.events.click();assert.match(texto(f.box),/No se pudo consultar/);assert(!texto(f.box).includes('item-a'));groups++;}
 let d=data();d.checklists={estado:'sin_dato',listas:[],items_observados:null,total_confirmado:null};f=fixture({api:async()=>d});await f.btn.events.click();assert.match(texto(f.box),/Checklist sin dato/);assert(!/0 de 0/.test(texto(f.box)));groups++;
 d=data();d.checklists={estado:'observado',listas:[],items_observados:0,total_confirmado:0,resueltos_observados:0};f=fixture({api:async()=>d});await f.btn.events.click();assert.match(texto(f.box),/0 de 0 elementos observados/);assert.match(texto(f.box),/no acredita entrega/);groups++;
 d=data();d.checklists.estado='parcial';d.checklists.total_confirmado=null;f=fixture({api:async()=>d});await f.btn.events.click();assert.match(texto(f.box),/Checklist parcial: 2/);assert.match(texto(f.box),/Total sin confirmar/);groups++;
 f=fixture({api:async()=>{throw Error('token=private reason')}});await f.btn.events.click();assert.match(texto(f.box),/No se pudo consultar/);assert(!texto(f.box).includes('token='));assert.equal(f.btn.disabled,false);groups++;
 let finish,count=0;f=fixture({api:()=>{count++;return new Promise(res=>finish=res)}});let p=f.btn.events.click();await f.btn.events.click();assert.equal(count,1);assert(f.btn.disabled);finish(data());await p;groups++;
 for(const mode of ['ruta','identidad','nodo']){f=fixture({api:()=>new Promise(res=>finish=res)});p=f.btn.events.click();const before=texto(f.box);if(mode==='ruta')f.E.vigente=()=>false;if(mode==='identidad')f.ctx.persona={id:'other'};if(mode==='nodo')f.box.isConnected=false;finish(data());await p;assert.equal(texto(f.box),before);assert(!texto(f.box).includes('item-a'));groups++;}
 d=data();d.checklists.listas[0].items=Array.from({length:21},(_,i)=>({id:'item-'+i,resuelto:false}));f=fixture({api:async()=>d});await f.btn.events.click();assert.match(texto(f.box),/20 de 21/);assert(!texto(f.box).includes('ID item-20'));groups++;
 const src=fs.readFileSync(__dirname+'/modulos/mi_trabajo.js','utf8');assert(src.includes('renderMetadatosTarea225(E,t,h)'));assert(!src.includes('checklists, adjuntos y menciones de ClickUp aún no están disponibles'));assert(!fs.readFileSync(__dirname+'/modulos/_metadatos_tarea_225.js','utf8').includes('ctx.accion'));groups++;
 console.log(groups+' grupos225 PASS: render real, GET exclusivo, scope, unknown/0, límites, stale, permiso readonly y piloto.');
})().catch(e=>{console.error(e);process.exitCode=1});
