const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const APP=__dirname,b={};vm.createContext(b);vm.runInContext(fs.readFileSync(path.join(APP,'modulos/control_cartera.js'),'utf8').replace(/export /g,''),b);
const cli=[{id:'uno',nombre:'Cliente uno',activo_confirmado:true,servicios:{publicidad:'sí',seo:'no',crm_ghl:'sí',cuota:'NO MOSTRAR'}},{id:'dos',nombre:'Cliente dos',activo_confirmado:true,servicios:{seo:'sí'}},{id:'ajeno',nombre:'Cliente ajeno',activo_confirmado:true}];
const base={clientes:cli,persona_id:'account',esOps:false,carteraIds:['uno'],hoy:'2026-10-03',asignaciones:[{cliente_id:'uno',persona_id:'account',silla:'account',principal:true,desde:'2026-01-01'},{cliente_id:'dos',persona_id:'otro',silla:'account',principal:true,desde:'2026-01-01'}]};
const fuentes={produccion:{hoy:'2026-10-03',fuentes:{horas:{hora:'2026-10-02 23:00'},tareas:{hora:'2026-10-03'},flujo:{hora:'2026-10-03'}},proyectos:[{cliente_id:'uno',horas_mes:2.5,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-10-02 23:00'},rev_account:0,rev_account_48:0,revisiones_account:{estado:'medido',fuente:'flujo',fecha:'2026-10-03'}}],cola:[{id:'t1',cli:'uno',vence:'2026-10-04',persona_id:'a'},{id:'t1',cli:'uno',vence:'2026-10-04',persona_id:'b'},{id:'t2',cli:'uno',vence:'2026-10-02'},{id:'t3',cli:'uno',vence:null},{id:'otro',cli:'ajeno',vence:'2026-01-01'}]},bandeja:{generado:'2026-10-03 09:00',fuentes:{desk:{hora:'2026-10-02 17:12',estado:'bien'}},clientes:[{cliente_id:'uno',sin_contestar:0,mas_48:0,entre_24_48:0}]}};
let count=0;
const row=b.prepararControlCartera({...base,fuentes})[0];assert.equal(row.pendientes.total_visible,3);assert.equal(row.pendientes.fechas_pasadas,1);assert.equal(row.pendientes.proxima_fecha,'2026-10-04');assert.equal(row.pendientes.sin_fecha,1);assert.deepEqual(Array.from(row.servicios_lista),['Paid','CRM']);assert.equal(row.presupuesto.valor,'Sin presupuesto confirmado');count++;
let groups=b.resumirAccountsControl([row]);assert.equal(groups[0].horas.valor,2.5);assert.equal(groups[0].horas.periodo,'2026-10');assert.equal(groups[0].tickets48.valor,0);assert.equal(groups[0].contacto_sin_dato,1);count++;
const ops=b.prepararControlCartera({...base,esOps:true,fuentes});assert.equal(ops.length,3);const otro=b.resumirAccountsControl(ops).find(g=>g.account_id==='otro');assert.equal(otro.horas.valor,null);assert.equal(otro.horas.sin_dato,1);assert.equal(otro.tickets.valor,null);count++;
for(const hora of ['2026-10-04','2026-02-30','no-fecha']){const doc={...fuentes.produccion,fuentes:{...fuentes.produccion.fuentes,tareas:{hora},horas:{hora}}};const r=b.prepararControlCartera({...base,fuentes:{produccion:doc}})[0];assert.equal(r.pendientes.valor,'Sin dato');assert.equal(r.horas.valor,'Sin dato');count++;}
for(const cola of [[{id:'t1',cli:'uno',vence:'2026-02-30'}],[{id:'t1',cli:'uno',vence:'2026-10-03'},{id:'t1',cli:'uno',vence:'2026-10-04'}],[{id:null,cli:'uno',vence:null}]]){const r=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,cola}}})[0];assert.equal(r.pendientes.valor,'Por contrastar');assert.equal(r.pendientes.total_visible,undefined);count++;}
const sinPeriodo=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,hoy:null}}})[0];assert.equal(b.resumirAccountsControl([sinPeriodo])[0].horas.valor,null);count++;
const otraFecha={...row,horas:{...row.horas,medicion:{total:4,periodo:'2026-09'}}};assert.equal(b.resumirAccountsControl([row,otraFecha])[0].horas.valor,null);count++;
const fraccion=b.prepararControlCartera({...base,fuentes:{bandeja:{clientes:[{cliente_id:'uno',sin_contestar:1.5,mas_48:0,entre_24_48:0}]}}})[0];assert.equal(fraccion.tickets.valor,'Sin dato');count++;
assert(!JSON.stringify(row).includes('NO MOSTRAR'));assert(!JSON.stringify(row).includes('Cliente ajeno'));count++;
const equipoCli=[{...cli[0],equipo:{account:[{persona_id:'account',principal:true,confianza:'confirmada',suplencia:false}]}}];
const equipoBase={...base,clientes:equipoCli,asignaciones:[],personas:[{id:'account',estado:'activo',activo:true}]};
assert.equal(b.prepararControlCartera(equipoBase)[0].account_id,'account');assert.equal(b.prepararControlCartera(equipoBase)[0].owner_confirmado,true);count++;
const alta=b.prepararControlCartera({...equipoBase,clientes:[{...equipoCli[0],equipo:{account:[{...equipoCli[0].equipo.account[0],confianza:'alta'}]}}]})[0];assert.equal(alta.account_id,'account');assert.equal(alta.owner_confirmado,false);assert.equal(b.resumirAccountsControl([alta])[0].asignaciones_por_confirmar,1);count++;
for(const cambio of [{hasta:'2026-10-02'},{desde:'2026-10-04'},{confianza:1},{confianza:'pendiente'},{suplencia:true},{principal:false},{desde:'2026-02-30'}]){assert.equal(b.prepararControlCartera({...equipoBase,clientes:[{...equipoCli[0],equipo:{account:[{...equipoCli[0].equipo.account[0],...cambio}]}}]})[0].account_id,null);count++;}
assert.equal(b.prepararControlCartera({...equipoBase,personas:[{id:'account',estado:'baja'}]})[0].account_id,null);count++;
assert.equal(b.prepararControlCartera({...equipoBase,asignaciones:[{...base.asignaciones[0],persona_id:'otra'}]})[0].account_id,null);count++;
for(const hm of [undefined,{}, {estado:'medido',fuente:'flujo',periodo:'2026-10',fecha:'2026-09-30 23:00'},{estado:'medido',fuente:'horas',periodo:'2026-09',fecha:'2026-09-30 23:00'},{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-10-03'}]){const r=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,proyectos:[{cliente_id:'uno',horas_mes:0,horas_medicion:hm}]}}})[0];assert.equal(r.horas.valor,'Sin dato');assert.equal(b.resumirAccountsControl([r])[0].horas.valor,null);count++;}
const lecturaAnterior=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,fuentes:{...fuentes.produccion.fuentes,horas:{hora:'2026-09-30 23:00'}},proyectos:[{cliente_id:'uno',horas_mes:0,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-09-30 23:00'}}]}}})[0];assert.equal(lecturaAnterior.horas.valor,'Sin dato');assert.equal(lecturaAnterior.horas.medicion,undefined);count++;
const ceroMedido=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,proyectos:[{cliente_id:'uno',horas_mes:0,horas_medicion:fuentes.produccion.proyectos[0].horas_medicion}]}}})[0];assert.equal(ceroMedido.horas.valor,'0 h registradas');assert.equal(b.resumirAccountsControl([ceroMedido])[0].horas.valor,0);count++;
const legacyPos=b.prepararControlCartera({...base,fuentes:{produccion:{...fuentes.produccion,proyectos:[{cliente_id:'uno',horas_mes:3}]}}})[0];assert.equal(legacyPos.horas.valor,'3 h observadas');assert.equal(b.resumirAccountsControl([legacyPos])[0].horas.valor,null);count++;
// Render de la función real con DOM sintético: cada callback verifica vigencia.
class N{constructor(tag,attrs={},kids=[]){this.tag=tag;this.isConnected=true;this.attrs=attrs;this.k=[];this.listeners=attrs.on||{};this.value=attrs.value||'';this.checked=false;this.append(...kids);}append(...ks){this.k.push(...ks.flat(Infinity).filter(k=>k!=null));}replaceChildren(...ks){this.k=[];this.append(...ks);}addEventListener(e,f){this.listeners[e]=f;}get textContent(){return this.k.map(k=>k instanceof N?k.textContent:String(k)).join('');}set textContent(v){this.replaceChildren(String(v));}desc(){return this.k.filter(k=>k instanceof N).flatMap(k=>[k,...k.desc()]);}}
vm.runInContext("Object.assign(globalThis,(()=>{"+fs.readFileSync(path.join(APP,'modulos/_control_artifact_250.js'),'utf8').replace(/export /g,'')+";return {pintarMapaControl250,COLUMNAS_CONTROL_250};})())",b);
vm.runInContext("Object.assign(globalThis,(()=>{"+fs.readFileSync(path.join(APP,'modulos/_imputa_personal_390.js'),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'')+";return {celdaImputa390,imputaVigente390};})())",b);
const utilDias390=fs.readFileSync(path.join(APP,'modulos/mi_dia_bloques.js'),'utf8');Object.assign(b,vm.runInContext('(()=>{'+utilDias390.slice(utilDias390.indexOf('const hoyISO'),utilDias390.indexOf('const horaCorta')).replace(/export /g,'')+';return {diaCorto};})()',b));
const h=(t,a,...k)=>new N(t,a,k);Object.assign(b,{h,chipEstado:(e,t)=>h('span',{},t),vacioLinea:t=>h('p',{},t),hoyMadrid:()=>base.hoy});const md=fs.readFileSync(path.join(APP,'modulos/mi_dia.js'),'utf8');vm.runInContext(fs.readFileSync(path.join(APP,'modulos/_evidencias_resumen.js'),'utf8').replace(/export /g,''),b);vm.runInContext(md.slice(md.indexOf('function semanaDeclaracionesControl'),md.indexOf('// ================================================================== el número que manda')),b);
let vigente=true;const ctx={persona:{id:'account'},clientesVisibles:cli,carteraPorSilla:{account:new Set(['uno'])},datos:{asignaciones:base.asignaciones},veModulo:()=>true,nombre:id=>id};const D={opcional:name=>({'produccion/produccion':fuentes.produccion,'bandeja/por_cliente':fuentes.bandeja}[name]||null)};
const root=b.panelControlCartera(ctx,D,'operaciones',()=>vigente);assert.equal(root.desc().filter(n=>n.tag==='table').length,2);assert(root.textContent.includes('Mapa de control por persona'));assert(root.textContent.includes('Sin presupuesto confirmado'));assert(root.desc().some(n=>n.tag==='a'&&n.attrs.href==='#/ficha/uno/resumen'));count++;
const macros=root.desc().filter(n=>n.tag==='button'&&n.attrs['aria-label']?.startsWith('Ver proyectos'));assert.equal(macros.length,3);macros.find(n=>n.attrs['aria-label']==='Ver proyectos de otro').listeners.click();assert(root.textContent.includes('Cliente dos'));assert(!root.textContent.includes('Cliente uno'));count++;
const servicio=root.desc().find(n=>n.tag==='select'&&n.attrs['aria-label']==='Filtrar por servicio confirmado');const selector=root.desc().find(n=>n.tag==='select'&&n.attrs['aria-label']==='Filtrar cartera por account');selector.value='';servicio.value='SEO';servicio.listeners.change();assert(root.textContent.includes('Cliente dos'));assert(!root.textContent.includes('Cliente uno'));count++;
const floats={...fuentes,produccion:{...fuentes.produccion,proyectos:[{cliente_id:'uno',horas_mes:110.69999999999999,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-10',fecha:'2026-10-02 23:00'}}]}};const formatRoot=b.panelControlCartera(ctx,{opcional:name=>name==='produccion/produccion'?floats.produccion:null},'operaciones',()=>true);assert(formatRoot.textContent.includes('110,7 h'));assert(!formatRoot.textContent.includes('999999999'));count++;
const before=root.textContent;vigente=false;macros[0].listeners.click();servicio.value='';servicio.listeners.change();assert.equal(root.desc().filter(n=>n.tag==='table').length,1);assert(!root.textContent.includes('Cliente dos'));assert(root.textContent.includes('Mapa de control por persona'));count++;
vigente=true;const propio=b.panelControlCartera(ctx,D,'account',()=>vigente);assert.equal(propio.desc().filter(n=>n.tag==='table').length,1);assert(!propio.textContent.includes('Cliente ajeno'));assert(!propio.textContent.includes('Cliente dos'));count++;
console.log(`${count} grupos138 pasan: agregación parcial, períodos, dedup, fuente inválida, privacidad, tablas reales y filtros con identidad vigente.`);
// Consejo global real: se descubre en #main y se mueve bajo la matriz, no se busca sólo dentro del módulo.
let observado=null,disconnect=0,movido=0,plegado=0,actual=true;const nnum={textContent:''};const li={hidden:false,querySelector:q=>q==='.n'?nnum:q==='b'?{textContent:'Revisar registro'}:null};
const consejo={dataset:{},hidden:false,querySelectorAll:()=>[li],querySelector:()=>null};const padre={querySelector:()=>consejo};const modulo={closest:()=>padre,parentElement:padre,isConnected:true,compareDocumentPosition:()=>2,after:c=>{assert.equal(c,consejo);movido++;}};const loMio={isConnected:true,querySelectorAll:()=>[]};const despuesDe={parentElement:modulo,isConnected:true,compareDocumentPosition:()=>2,after:c=>{assert.equal(c,consejo);movido++;}};
Object.assign(b,{filtroConsejo:()=>()=>true,objetoDe:()=>'',Node:{DOCUMENT_POSITION_PRECEDING:2},MutationObserver:class{constructor(fn){this.fn=fn;observado=this;}observe(node){this.node=node;}disconnect(){disconnect++;}},clearTimeout:()=>{},setTimeout:f=>f(),plegarConsejo:()=>{plegado++;}});
vm.runInContext(md.slice(md.indexOf('function vigilarConsejo('),md.indexOf('/** Verbo + objeto',md.indexOf('function vigilarConsejo('))),b);
b.vigilarConsejo(modulo,loMio,despuesDe,{ctx:{vigente:()=>actual},puesto:'operaciones'});assert.equal(movido,1);assert.equal(plegado,1);assert.equal(nnum.textContent,'1');actual=false;observado.fn();assert.equal(disconnect,1);assert.equal(movido,1);console.log('1 grupo138 adicional pasa: consejo de carcasa plegado/reubicado con identidad vigente.');
