// Source263+404 actuales, DOM/ESM temporal; no HTTP ni DB/proveedores.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_accounts_263.cjs','utf8').split('(async()=>{try{')[0];
const {dir}=new Function('require','__dirname',prefix+';return {dir};')(require,__dirname);
for(const f of ['_metodo_cohorte_305']){fs.writeFileSync(path.join(dir,f+'.mjs'),fs.readFileSync(__dirname+'/modulos/'+f+'.js','utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'"));}
const clone=x=>JSON.parse(JSON.stringify(x)),walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
function ctx(){const ps=[{id:'ops',estado:'activo',puestos:['operaciones']},{id:'acc',estado:'activo',puestos:['account']},{id:'paid',nombre:'Especialista fixture',estado:'activo',puestos:['trafficker']}],cs=[{id:'ok',nombre:'Cliente fixture',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}];return {servidor:true,hoy:'2026-10-05',real:clone(ps[0]),persona:clone(ps[0]),datos:{personas:clone(ps),asignaciones:[]},clientes:clone(cs),clientesVisibles:clone(cs),carteraPorSilla:{account:new Set(['ok'])},veModulo:()=>true,ver:()=>({ok:true}),nombre:x=>x,vigente:()=>true,api:async()=>null,datosModulo:async()=>null};}
const row=()=>({cliente_id:'ok',reunion_historica:{fecha_registro:'2026-09-29',celebrada_confirmada:false}});
const declared=n=>new Map([['ok',{cliente_id:'ok',estado:'declarado',source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null,reuniones_declaradas:n,contactos_declarados:2}]]);
const method=()=>({hoy:'2026-10-05',cobertura_reuniones:{completa:false},sugerencias:[{cliente_id:'ok',regla_id:'seguimiento_quincenal_especialista',cadencia_dias:15,responsable_role:'trafficker',responsable_id:'paid',responsables_ids:['paid'],ultima_confirmada:'2026-09-28',proxima_revision:'2026-10-13',estado:'en_cadencia',incumplimiento:null,fuentes_operativas:[{tipo:'reunion_celebrada',fecha:'2026-09-28'}],contrato:'PRIVATE_CONTRACT',precio:987654,recomendacion:'PRIVATE_SOURCE'}]});
let groups=0;async function test(name,f){try{await f();groups++;}catch(e){throw Error(name+': '+e.message)}}
(async()=>{try{
 const {h,N}=await import('file://'+path.join(dir,'componentes.mjs'));N.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(N.prototype,'className',{get(){return this.attrs.class||'';},set(v){this.attrs.class=v;}});
 const M=await import('file://'+path.join(dir,'_seguimiento_accounts_404.mjs')),{renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 const project=(c=ctx(),o={})=>M.proyectarSeguimiento404(c,[row()],{semana:'2026-10-05',declaraciones:declared(0),metodo:method(),...o});
 await test('sixcolumns/order and neutral typed DTO no15counter',async()=>{assert.deepEqual(M.COLUMNAS_SEGUIMIENTO_404,['Cliente','Reuniones semana','Seguimiento quincenal','Trafficker','Última confirmada','Próxima revisión']);const d=project()[0];assert.equal(d.celdas[0].valor,'0');assert.equal(d.celdas[1].valor,'En cadencia');assert.equal(d.celdas[3].valor,'28/09/26');assert.equal(d.celdas[4].valor,'13/10/26');assert(d.celdas.every(c=>c.estado==='gris'&&c.cumplimiento===null));});
 await test('unknown isnotzero and declarationnotcelebration',async()=>{const d=project(ctx(),{declaraciones:new Map()})[0];assert.equal(d.celdas[0].valor,'—');const z=project()[0].celdas[0];assert(z.detalle.includes('no ausencia'));assert(z.detalle.includes('No confirma celebración'));});
 await test('weeklyinvalid/source/verification/count rejected',async()=>{for(const mutate of [f=>f.reuniones_declaradas=-1,f=>f.reuniones_declaradas=Infinity,f=>f.reuniones_declaradas=1.5,f=>f.cumplimiento=true,f=>f.verificacion_externa=true,f=>f.source_kind='external',f=>f.cliente_id='foreign']){const map=declared(1);mutate(map.get('ok'));assert.equal(project(ctx(),{declaraciones:map})[0].celdas[0].valor,'—');}for(const semana of ['2026-02-30','2026-10-06','2026-10-12','2026-09-28'])assert.equal(project(ctx(),{semana})[0].celdas[0].valor,'—');});
 await test('wrongday/ambiguous/rule/role15policy failclosed',async()=>{for(const mutate of [m=>m.hoy='2026-10-04',m=>m.sugerencias.push(clone(m.sugerencias[0])),m=>m.sugerencias[0].regla_id='other',m=>m.sugerencias[0].cadencia_dias='15',m=>m.sugerencias[0].responsable_role='account',m=>m.sugerencias[0].estado='unknown',m=>m.sugerencias[0].incumplimiento=true]){const m=method();mutate(m);assert(project(ctx(),{metodo:m})[0].celdas.slice(1).every(c=>c.valor==='—'));}});
 await test('datesnotderived and invaliddatefuture/pairinconsistent rejected',async()=>{for(const mutate of [s=>s.ultima_confirmada='2026-02-30',s=>s.ultima_confirmada='2026-10-06',s=>s.proxima_revision='2026-10-14',s=>s.ultima_confirmada=null]){const m=method();mutate(m.sugerencias[0]);assert(project(ctx(),{metodo:m})[0].celdas.slice(1).every(c=>c.valor==='—'));}const m=method();m.sugerencias[0].ultima_confirmada=null;m.sugerencias[0].proxima_revision=null;m.sugerencias[0].estado='sin_dato';const d=project(ctx(),{metodo:m})[0];assert.equal(d.celdas[1].valor,'—');assert(d.celdas[1].detalle.includes('Confirmar evidencia'));assert.equal(d.celdas[3].valor,'—');assert.equal(d.celdas[4].valor,'—');});
 await test('ownercanonicalactiveunique actualrole notaccountfallback',async()=>{for(const mutate of [c=>c.datos.personas[2].estado='baja',c=>c.datos.personas[2].puestos=[],c=>c.datos.personas.push(clone(c.datos.personas[2])),c=>c.datos.personas[2].puestos=['trafficker','trafficker']]){const c=ctx();mutate(c);assert.equal(project(c)[0].celdas[2].valor,'—');}const m=method();m.sugerencias[0].responsables_ids=['paid','paid'];assert.equal(project(ctx(),{metodo:m})[0].celdas[2].valor,'—');});
 await test('puesto no trafficker no acredita el especialista de la regla305',async()=>{const c=ctx();c.datos.personas[2].puestos=['jefa_publicidad'];assert(project(c)[0].celdas.slice(1).every(x=>x.valor==='—'));});
 await test('historicalrecord preservedonlydetail no substitution lastconfirmed',async()=>{const d=project()[0];assert.equal(d.celdas[3].valor,'28/09/26');assert(d.celdas[3].detalle.includes('2026-09-29'));assert(d.celdas[3].detalle.includes('no confirma celebración'));assert.equal(d.celdas[4].valor,'13/10/26');assert(d.celdas[4].detalle.includes('No es cita'));});
 await test('privacy minfields ignore sourcecontractpricefreedescription',async()=>{const d=JSON.stringify(project());assert(!d.includes('PRIVATE_'));assert(!d.includes('987654'));assert(!d.includes('recomendacion'));});
 await test('actorclientcanonicalfreshscope denies priorandafter',async()=>{for(const mutate of [c=>delete c.clientes,c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push(clone(c.clientes[0])),c=>c.ver=()=>({ok:false}),c=>c.datos.personas[0].estado='baja',c=>c.datos.personas[0].puestos=['account'],c=>c.datos.personas.push(clone(c.datos.personas[0]))]){const c=ctx(),before=M.ambitoSeguimiento404(c);mutate(c);assert.equal(project(c).length,0);assert.equal(M.seguimientoVigente404(c,[row()],before.firma),false);}});
 await test('account own and realview intersection noforeign row',async()=>{const c=ctx();c.real=clone(c.datos.personas[1]);c.persona=clone(c.real);assert.equal(project(c).length,1);c.carteraPorSilla.account=new Set();assert.equal(project(c).length,0);c.persona=clone(c.datos.personas[0]);assert.equal(project(c).length,0);});
 const summary=()=>({semana_inicio:'2026-10-05',cobertura:'parcial',verificacion_externa:false,cumplimiento:null,clientes:[{cliente_id:'ok',contactos_declarados:2,reuniones_declaradas:0,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null}]});
 const configure=c=>{c.api=async route=>route==='metodo/sugerencias'?method():route.startsWith('clientes/evidencias_kpi/resumen?')?summary():null;c.datosModulo=async route=>route==='reuniones/reuniones'?{generado:'2026-10-05T10:00:00Z',clientes:[{cliente_id:'ok',mes:'2026-09',ultima:'2026-09-29'}]}:null;return c;};
 const mount=async c=>{const root=h('main',{});root.connected=true;await renderAccounts263(root,c,'accounts');return root;};
 const table=root=>walk(root).find(n=>n.attrs['data-seguimiento-accounts']==='404');
 await test('renderer actualsixcols onceeachsource monthlyretainedand0visiblegray',async()=>{const c=configure(ctx());let methodCalls=0,summaryCalls=0;const api=c.api;c.api=async r=>{if(r==='metodo/sugerencias')methodCalls++;if(r.startsWith('clientes/evidencias_kpi/resumen?'))summaryCalls++;return api(r);};const root=await mount(c),t=table(root);assert.equal(walk(t).filter(n=>n.tag==='th').length,6);assert.equal(methodCalls,1);assert.equal(summaryCalls,1);assert(text(t).includes('28/09/26'));assert(text(t).includes('13/10/26'));const b=walk(t).find(n=>n.tag==='button'&&n.attrs['aria-label']?.startsWith('Reuniones semana'));assert.equal(text(b),'0');assert.equal(b.children[0].attrs['data-estado'],'gris');assert(text(root).includes('29/09/26'));b.events.click();assert(text(root).includes('no ausencia de actividad'));});
 await test('method module revoked nofetch/sourcecells weeklystillshown',async()=>{const c=configure(ctx());c.veModulo=m=>m!=='reuniones';let n=0;const api=c.api;c.api=async r=>{if(r==='metodo/sugerencias')n++;return api(r);};const root=await mount(c);assert.equal(n,0);assert(!text(table(root)).includes('Especialista fixture'));assert.equal(text(walk(table(root)).find(n=>n.tag==='button'&&n.attrs['aria-label']?.startsWith('Reuniones semana'))),'0');});
 await test('late method response afterACTrevocation no publication',async()=>{const c=configure(ctx());let done,entered;const p=new Promise(r=>done=r),started=new Promise(r=>entered=r),api=c.api;c.api=async r=>{if(r==='metodo/sugerencias'){entered();return p;}return api(r);};const root=h('main',{});root.connected=true;const req=renderAccounts263(root,c,'accounts');await started;c.clientes[0].activo_confirmado=false;done(method());await req;assert(!text(root).includes('Cliente fixture'));assert(!text(root).includes('Especialista fixture'));});
 await test('revoked client/owner scope beforeclick clears prior policydetails',async()=>{for(const mutate of [c=>c.clientes[0].activo_confirmado=false,c=>c.datos.personas[2].estado='baja',c=>c.ver=()=>({ok:false}),c=>c.persona.id='acc']){const c=configure(ctx()),root=await mount(c),b=walk(table(root)).find(n=>n.tag==='button'&&n.attrs['aria-label']?.startsWith('Trafficker'));b.events.click();assert(text(root).includes('Trafficker actual canónico'));mutate(c);b.events.click();assert(!text(root).includes('Trafficker actual canónico'));assert(!text(root).includes('Especialista fixture'));}});
 await test('detached stale button cannot open details afterrepaint',async()=>{const c=configure(ctx()),root=await mount(c),old=walk(table(root)).find(n=>n.tag==='button'&&n.attrs['aria-label']?.startsWith('Trafficker'));walk(root).find(n=>n.tag==='button'&&text(n)==='Restablecer filtros').events.click();assert.equal(old.isConnected,false);old.events.click();const detail=walk(root).find(n=>n.attrs['aria-label']==='Evidencia del indicador');assert(detail.hidden);});
 console.log(groups+' grupos404 PASS · fuente y renderer reales, fixtures aislados.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e.message);process.exitCode=1});
