const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(t){this.tag=t;this.children=[];this.attrs={};this.style={};}append(...x){this.children.push(...x.flat(Infinity).filter(x=>x!=null));}setAttribute(k,v){this.attrs[k]=String(v);}addEventListener(){}}
const text=x=>x instanceof N?x.children.map(text).join(' '):String(x??'');
const b={Node:N,document:{createElement:t=>new N(t),createTextNode:x=>String(x)},L:x=>x,fmt:{num:String},chipEstado:(e,t)=>t,selloMedible:(m,p)=>[m,p],frescura:x=>x,cifraPrincipal:x=>Object.values(x).join(' '),vacioLinea:x=>x,panel:(o,x)=>x,colorCifra:()=>''};vm.createContext(b);
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function h('),comp.indexOf('const svgNS =')).replace('export ',''),b);
const source=fs.readFileSync(__dirname+'/modulos/mi_dia.js','utf8');vm.runInContext(source.slice(source.indexOf('function heroNumero('),source.indexOf('// ================================================================== A1'))+';this.render=heroNumero;',b);
const legacy={nombre:'Subcuentas con el CRM en verde',umbral:'≥80% verde; ≥60% ámbar',formula:'Cumplen3condiciones÷encendidas Meta',medible:'hoy',medible_porque:'asistencia≥75%',fuente:'Legacy',frecuencia:'diaria'};
const cfg={calculo:'crm_verde',indicador:'legacy',titulo:'Subcuentas con el CRM en verde',meta:'Verde ≥80%'};
let n=0;const test=(l,f)=>{f();n++;};
test('Render real título/details/fuentes sin legacy targets',()=>{const original=JSON.stringify([cfg,legacy]);const r=text(b.render({indicador:()=>legacy},cfg,{valor:37,unidad:'37 autorizadas',estado:'gris',contexto:'Copia parcial'},'jefa_crm'));for(const no of ['Subcuentas con el CRM en verde','80%','60%','75%','Cumplen3condiciones','Umbral:','Verde / ámbar / rojo'])assert(!r.includes(no),no);assert(r.includes('Cobertura de lectura CRM'));assert(r.includes('Número de subcuentas cliente autorizadas'));assert(r.includes('sin umbral de rendimiento'));assert.equal(JSON.stringify([cfg,legacy]),original);});
test('Ausente y falta no revive catálogo/fase2 oldmetadata',()=>{for(const valor of [{valor:null,contexto:'Sin lectura suficiente'},{falta:{titulo:'Fuente pendiente',texto:'Copia pendiente'}},{fase2:true}]){const r=text(b.render({indicador:()=>legacy},cfg,valor,'jefa_crm'));assert(r.includes('Cobertura de lectura CRM'));assert(!r.includes('80%'));assert(!r.includes('75%'));}});
test('Otro indicador idéntico catálogo y umbral intactos',()=>{const r=text(b.render({indicador:()=>legacy},{...cfg,calculo:'otro'},{valor:90,estado:'verde'},'otro'));assert(r.includes('Subcuentas con el CRM en verde'));assert(r.includes('80%'));assert(r.includes('Cumplen3condiciones'));assert(r.includes('Verde / ámbar / rojo'));});
console.log(n+' grupos metadatosCRM319A PASS');
