const fs=require('fs'),assert=require('assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];
const {c,N,all,text}=new Function('require','__dirname',prefix+';return {c,N,all,text};')(require,__dirname);
const PIN='23ace1eb937926c13c18a05c6ac0e42e4b2a7b40585de0be606f19efa474696d';
function ctx(){const actor={id:'ops',nombre:'Actor fixture',estado:'activo',puestos:['operaciones']},worker={id:'p',nombre:'Persona fixture',estado:'activo',puestos:['seo']},clients=[{id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true}];return {servidor:true,hoy:'2026-10-04',real:{...actor},persona:{...actor},datos:{personas:[actor,worker],asignaciones:[]},clientes:clients.map(x=>({...x})),clientesVisibles:clients.map(x=>({...x})),carteraPorSilla:{account:new Set()},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,api:async()=>dto()};}
function row(i=1){return {tarea_id:'t'+i,cliente_id:'c',lista_id:'l',persona_id:'p',creada_utc:'2026-10-01T08:00:00Z',estado_observado:'planning semanal',tipo_estado:'custom',estado_leido_utc:'2026-10-03T13:00:00Z',titulo_saneado:'Ejemplo '+i};}
function dto(){return {version:'438.1',estado:'copia_observada',sha256_candidato:PIN,generado:'2026-10-04T05:00:00Z',corte_preparacion_utc:'2026-10-04T04:13:17Z',fuente:'clickup_cache_local',cobertura:'parcial',persona_ids:['p'],cliente_ids:['c'],filas:[row()],atribucion:'creador_ID_exacto',creacion_no_es_planificacion:true,cumplimiento:null};}
let checks=0;async function test(label,f){await f();checks++;console.log('PASS',label);}
(async()=>{
 await test('exactcreator DTO not assigned/history and malformed denied',()=>{const x=ctx(),before=c.ambitoEjemplos438(x);assert.equal(c.modeloEjemplos438(x,dto(),before).filas[0].persona_id,'p');for(const fn of [d=>d.filas[0].persona_id='foreign',d=>d.filas[0].cliente_id='foreign',d=>d.filas.push({...d.filas[0],cliente_id:'foreign'}),d=>d.filas[0].creada_utc='2026-02-30T08:00:00Z',d=>d.filas[0].estado_leido_utc='2026-10-03T13:00:00+14:01',d=>d.filas[0].creador_usuario_id='1',d=>d.filas[0].titulo_saneado='password=private_fixture',d=>d.filas[0].creada_utc='2026-10-04T05:00:00Z']){const d=dto();fn(d);assert.equal(c.modeloEjemplos438(x,d,before),null);}});
 await test('missing grant module canonical duplicate noGET',async()=>{for(const mutate of [x=>x.ver=()=>({ok:false}),x=>x.veModulo=m=>m!=='horas',x=>x.datos.personas.push({...x.real}),x=>x.clientes.push({...x.clientes[0]}),x=>x.real.estado='baja']){const x=ctx();mutate(x);let calls=0;x.api=async()=>{calls++;return dto();};await c.panelEjemplosCreador438(new N('main'),x);assert.equal(calls,0);}});
 await test('closed creator details lazy five examples pagination linksonlysafeIDs',async()=>{const x=ctx(),d=dto();d.filas=Array.from({length:8},(_,i)=>row(i+1));let calls=0;x.api=async(path,opts)=>{calls++;assert.equal(path,'produccion/ejemplos-creador');assert.equal(opts,undefined);return d;};const n=new N('main');await c.panelEjemplosCreador438(n,x);assert.equal(calls,1);assert.equal(all(n,z=>z.tag==='a').length,0);const fold=all(n,z=>z.tag==='details')[0];fold.open=true;fold.events.toggle();assert.equal(all(n,z=>z.tag==='th').length,5);assert.equal(all(n,z=>z.tag==='a').length,5);assert(all(n,z=>z.tag==='a').every(a=>/^https:\/\/app\.clickup\.com\/t\/t\d+$/.test(a.attrs.href)));all(n,z=>z.tag==='button'&&text(z)==='Siguiente')[0].events.click();assert.equal(all(n,z=>z.tag==='a').length,3);assert(text(n).includes('No mide rendimiento ni cumplimiento'));});
 await test('revocation while GET clears nooldtitle',async()=>{const x=ctx(),n=new N('main');x.api=async()=>{x.clientes[0].activo_confirmado=false;return dto();};await c.panelEjemplosCreador438(n,x);assert(!text(n).includes('Ejemplo 1'));assert.equal(all(n,z=>z.tag==='details').length,0);});
 await test('revocation onfold/page/link clears and prevents navigation',async()=>{for(const action of ['fold','page','link']){const x=ctx(),d=dto();d.filas=Array.from({length:8},(_,i)=>row(i+1));x.api=async()=>d;const n=new N('main');await c.panelEjemplosCreador438(n,x);const fold=all(n,z=>z.tag==='details')[0];fold.open=true;fold.events.toggle();const link=all(n,z=>z.tag==='a')[0],next=all(n,z=>z.tag==='button'&&text(z)==='Siguiente')[0];x.ver=()=>({ok:false});let prevented=false;if(action==='fold')fold.events.toggle();else if(action==='page')next.events.click();else link.events.click({preventDefault:()=>prevented=true});assert(!text(n).includes('Ejemplo 1'));if(action==='link')assert(prevented);}});
 await test('source unavailable/unknown nozero or stale scope',async()=>{const x=ctx(),n=new N('main');x.api=async()=>{throw Error('not configured');};await c.panelEjemplosCreador438(n,x);assert(text(n).includes('no acredita ausencia'));assert.equal(all(n,z=>z.tag==='table').length,0);const y=ctx(),m=new N('main');y.api=async()=>({...dto(),filas:[]});await c.panelEjemplosCreador438(m,y);assert(text(m).includes('no equivale a cero tareas'));});
 console.log(checks,'grupos438 UI PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
