const fs=require('fs'),vm=require('vm'),assert=require('assert'),cp=require('child_process'),crypto=require('crypto');
class N{constructor(t){this.tag=t;this.children=[];this.attrs={};this.events={};this.style={};this.isConnected=true;}append(...xs){for(const x of xs.flat(Infinity))if(x!==null&&x!==undefined&&x!==false)this.children.push(x);}replaceChildren(...xs){this.children=[];this.append(...xs);}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}addEventListener(k,v){this.events[k]=v;}set textContent(v){this.children=[v];}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}}
const b={Date,Number,Map,Set,Node:N,TextEncoder,crypto:crypto.webcrypto,document:{createElement:t=>new N(t),createTextNode:s=>String(s)},urlSegura:x=>x,chipEstado:(color,t)=>newText(t)};
function newText(t){const n=new N('span');n.append(t);return n;}
vm.createContext(b);const comps=fs.readFileSync('componentes.js','utf8');vm.runInContext(comps.slice(comps.indexOf('export function h('),comps.indexOf('const svgNS =')).replace('export ',''),b);
vm.runInContext(fs.readFileSync('modulos/_operaciones_prioridades_300.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,''),b);
const row={id:'exacta',cliente_id:'c',titulo:'Comprobar respuesta',detalle:'Acción concreta'};
const token=cp.execFileSync('python3',['-c',"import operaciones_prioridades_300 as M;print(M.hash_(['300.1','ops',{'id':'exacta','cliente_id':'c','titulo':'Comprobar respuesta','detalle':'Acción concreta'}]))"],{encoding:'utf8'}).trim();
const dto=()=>({version:'300.1',propietario:'ops',dia:'2026-10-03',puede_registrar:true,prioridades:[{prioridad_id:'exacta',cliente_id:'c',fuente_revision:token,revision:0,actual:null,historial:[]}]});
const ctx=()=>({real:{id:'ops'},persona:{id:'ops'},servidor:true,vigente:()=>true,ver:()=>({ok:true}),clientesVisibles:[{id:'c',activo_confirmado:true,detalle:true}],api:async()=>dto()});
const all=(n,p)=>[...(n instanceof N&&p(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,p)):[])];
const render=async(c=ctx(),rs=[row])=>{const n=new N('main');await b.renderPrioridades300(n,c,rs,()=> 'Cliente fixture');return n;};
let count=0;const test=async(name,f)=>{await f();count++;};
(async()=>{
 await test('canonical source matches real Python hash',async()=>assert.equal(await b.hashFuente300('ops',row),token));
 await test('empty not one hundred',async()=>{const p=b.progreso300([],new Map());assert.equal(p.porcentaje,null);const n=await render(ctx(),[]);assert(n.textContent.includes('no acredita'));assert(!n.textContent.includes('100'));});
 await test('actual render four compact columns and closed editor',async()=>{const n=await render();assert.equal(all(n,x=>x.tag==='th').length,4);assert(all(n,x=>x.tag==='details').every(x=>x.attrs.open===undefined));assert(n.textContent.includes('0 de 1'));assert(!all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].disabled);});
 await test('source content changed disables edit',async()=>{const n=await render(ctx(),[{...row,detalle:'Otra acción'}]);assert(all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].disabled);assert(n.textContent.includes('Referencia exacta no disponible'));});
 await test('viewas cannot POST even fake cap true',async()=>{const c=ctx();c.real.id='otro';const n=await render(c);const button=all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0];assert(button.disabled);let calls=0;c.api=async()=>calls++;await button.events.click();assert.equal(calls,0);});
 await test('ACT revoked callback no POST',async()=>{const c=ctx(),n=await render(c);c.clientesVisibles[0].activo_confirmado=false;let calls=0;c.api=async()=>calls++;await all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].events.click();assert.equal(calls,0);});
 await test('stale identity pending GET no sensitive repaint',async()=>{const c=ctx();let resolve;c.api=()=>new Promise(r=>resolve=r);const n=new N('main');const p=b.renderPrioridades300(n,c,[row],()=> 'Cliente fixture');c.persona.id='otro';resolve(dto());await p;assert(!n.textContent.includes('0 de 1'));assert(all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].disabled);});
 await test('failed response retry same exact intention receipt local',async()=>{const c=ctx(),n=await render(c),button=all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0],nota=all(n,x=>x.tag==='textarea')[0],bodies=[];nota.value='Contacto declarado';let fail=true;
 c.api=async(path,opt)=>{bodies.push(JSON.parse(JSON.stringify(opt.cuerpo)));if(fail){fail=false;throw Error('Lost response');}const q=opt.cuerpo;return {version:'300.1',resultado:'duplicado',recibo_durable:true,recibo:{...q,actor:'ops',revision:q.revision+1,registrado_en:'2026-10-03T15:00:00Z',origen:'local',declarado:true,envio_realizado:false,ejecucion_verificada:false}};};
 await button.events.click();assert(n.textContent.includes('Sin recibo confirmado'));await button.events.click();assert.deepEqual(bodies[0],bodies[1]);assert(n.textContent.includes('1 de 1'));assert(n.textContent.includes('sin envío ni ejecución confirmados'));});
 await test('incompatible receipt never advance',async()=>{const c=ctx(),n=await render(c);c.api=async()=>({version:'300.1',resultado:'guardado',recibo_durable:true,recibo:{actor:'foreign'}});await all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].events.click();assert(n.textContent.includes('0 de 1'));assert(n.textContent.includes('Sin recibo confirmado'));});
 await test('GET failure visible priorities not green',async()=>{const c=ctx();c.api=async()=>{throw Error('Unavailable');};const n=await render(c);assert(n.textContent.includes(row.titulo));assert(n.textContent.includes('Rastro no disponible'));assert(all(n,x=>x.tag==='button'&&x.textContent==='Guardar en RO')[0].disabled);});
 await test('duplicates not double denominator or progress',async()=>{const p=b.progreso300([row,row],new Map());assert.equal(p.total,0);assert.equal(p.porcentaje,null);});
 console.log(`${count} grupos UI300 PASS: renderer/h reales, Python hash, fixture DOM/promesas/retry.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
