const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const DIR=__dirname;
function localizarApp(){if(process.env.RO_APP_688){const p=path.resolve(process.env.RO_APP_688);assert(fs.existsSync(path.join(p,'modulos/crm.js')),'APP explícita válida');return p;}let p=DIR;while(true){if(fs.existsSync(path.join(p,'modulos/crm.js')))return p;const q=path.join(p,'30_APP_PROTOTIPO');if(fs.existsSync(path.join(q,'modulos/crm.js')))return q;const up=path.dirname(p);if(up===p)return null;p=up;}}
const APP=localizarApp();
const appHelper=APP&&path.join(APP,'modulos/_crm_mediciones.js');
const INTEGRADO=!!appHelper&&fs.readFileSync(appHelper,'utf8').includes('const tiempoValido=');
const AFTER=INTEGRADO?appHelper:path.join(path.dirname(DIR),'_crm_mediciones_candidato.js');
assert(fs.existsSync(AFTER),'Fuente integrada o candidato presente');
function rendererActual(){if(APP){const s=fs.readFileSync(path.join(APP,'modulos/crm.js'),'utf8'),a=s.indexOf('function pintarSubcuentas('),b=s.indexOf('// ------------------------------------------------------------------ pestaña: leads sin tocar',a);assert(a>=0&&b>a,'renderer vigente extraíble');return s.slice(a,b);}return fs.readFileSync(path.join(path.dirname(DIR),'fixture_renderer_subcuentas_688.js'),'utf8');}
const NOW=Date.parse('2026-10-04T12:00:00Z'),HOY='2026-10-04';
class Clock extends Date{static now(){return NOW;}}
class N{constructor(tag,attrs={},kids=[]){this.tag=tag;this.attrs=attrs;this.children=[];this.append(...kids);}append(...kids){this.children.push(...kids.flat(Infinity).filter(x=>x!=null));}replaceChildren(...kids){this.children=[];this.append(...kids);}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}}
const h=(t,a,...kids)=>new N(t,a,kids);
function load(file){const e={Date:Clock,Intl,Map,Set,Object,Number,JSON,Array};vm.createContext(e);vm.runInContext(fs.readFileSync(file==='APP_AFTER'?AFTER:path.join(DIR,file),'utf8').replace(/export /g,''),e);return e;}
const before=load('_crm_mediciones_baseline.js'),after=load('APP_AFTER');
const source={hora:'2026-10-04T10:00:00Z',estado:'bien'};
const clone=x=>JSON.parse(JSON.stringify(x));
function row(){return{cliente_id:'fixtureClient',sub_id:'fixtureSub',nombre:'Cliente sintético',tipo:'cliente',estado:'gris',errores_lectura:[],leads_30d:5,citas_14d:{sin_estado:2},citas_30d:{celebradas:2,no_presentadas:1,futuras:4,agendadas:3},velocidad:{juzgables:4,en_1h:1,auto_5min:2,juzgables_72h:2,cuatro_en_72h:1},whatsapp:{enviados:2,fallidos:0},sms:{enviados:1,fallidos:0},correo:{enviados:3,fallidos:1}};}
const norm=(m,f,src=source)=>m.normalizarFilaCRM(f,src,HOY);
let groups=0;function test(name,fn){fn();groups++;}
test('before reproduce velocidad error publica positivos',()=>{const f=row();f.velocidad.error='fallo sintético';assert.equal(norm(before,f).velocidad.auto_5min,2);assert.equal(norm(before,f).velocidad.pct_1h,25);const n=norm(after,f);for(const k of ['auto_5min','juzgables','en_1h','pct_1h','juzgables_72h','cuatro_en_72h','pct_4en72'])assert.equal(n.velocidad[k],null);assert.equal(n.citas_30d.celebradas,2);assert.equal(n.leads_30d,5);});
test('before reproduce cita fallida futuras revived',()=>{const f=row();f.citas_30d.error='fallo sintético';assert.equal(norm(before,f).citas_30d.futuras,4);const n=norm(after,f);assert.equal(n.citas_30d.futuras,null);assert.equal(n.citas_30d.asistencia_pct,null);assert.equal(n.citas_14d.sin_estado,2);assert.equal(n.velocidad.auto_5min,2);});
test('before reproduce fuente futura same day asistencia',()=>{const future={...source,hora:'2026-10-04T23:59:00Z'},f=row();assert.equal(norm(before,f,future).citas_30d.asistencia_pct,2/3*100);const n=norm(after,f,future);assert.equal(n.citas_30d.asistencia_pct,null);assert.equal(n.leads_30d,null);assert.equal(n.whatsapp.enviados,null);assert.equal(n._medicionCRM.fechaValida,false);});
test('invalid offset DST/future boundary',()=>{for(const stamp of ['2026-10-04T10:00:00+15:00','2026-10-04T10:00:00+02:99','2026-02-31T10:00:00Z','2026-03-29 02:30:00','2026-10-04T12:00:00.001Z'])assert.equal(norm(after,row(),{...source,hora:stamp}).citas_30d.asistencia_pct,null);assert.equal(norm(after,row(),{...source,hora:'2026-10-04T14:00:00+02:00'}).citas_30d.asistencia_pct,2/3*100);});
test('datos_hasta future/error and missing read',()=>{for(const src of [{...source,datos_hasta:'2026-10-04T22:00:00Z'},{...source,error:'fallo'}, {...source,estado:'error'}, {...source,hora:null}])assert.equal(norm(after,row(),src).citas_30d.asistencia_pct,null);});
test('valid zero preserved no fake missing zero',()=>{const f=row();f.velocidad={juzgables:2,en_1h:0,auto_5min:0};f.citas_30d={celebradas:0,no_presentadas:2,futuras:0};const n=norm(after,f);assert.equal(n.citas_30d.asistencia_pct,0);assert.equal(n.citas_30d.futuras,0);assert.equal(n.velocidad.pct_1h,0);assert.equal(n.velocidad.auto_5min,0);f.velocidad={};f.citas_30d={};const missing=norm(after,f);assert.equal(missing.citas_30d.asistencia_pct,null);assert.equal(missing.citas_30d.futuras,null);assert.equal(missing.velocidad.auto_5min,null);});
test('resource error fields all current helper contracts',()=>{for(const key of ['error','errores','errores_lectura']){const f=row();f.velocidad[key]=key==='error'?'x':['x'];f.citas_30d[key]=key==='error'?'x':['x'];const n=norm(after,f);assert.equal(n.velocidad.en_1h,null);assert.equal(n.citas_30d.futuras,null);assert.equal(n.citas_14d.sin_estado,2);}});
test('no mutate input no qualification sale fabricated',()=>{const f=row(),copy=clone(f),n=norm(after,f);assert.deepEqual(f,copy);const e=after.medirEmbudoCRM({embudo:{contactos_90d:2,funnel:{cerrado:1}}},source,HOY);assert.equal(e.ventas,null);assert.equal(e.conversiones,null);assert.equal(n.respondio,undefined);});
function renderer(model){let options,changed,live=true,nav=0;const e={h,ID:'salud-crm',EST:{gris:{o:3,t:'Sin dato'},ambar:{o:1,t:'Vigilar'},verde:{o:2,t:'Bien'},rojo:{o:0,t:'Crítico'}},pc:x=>x+'%',logoCliente:()=>null,chipsFiltro:o=>{changed=o.alCambiar;return Object.assign(h('div',{}),{valor:()=>''});},cuentagotas:()=>f=>f.estado,pesoSub:()=>0,tablaDensa:o=>{options=o;return h('table',{},o.filas.map(f=>h('tr',{},f.nombre)));},puntoEstado:(_,t)=>h('span',{},t),numFuerte:x=>String(x),MOVIL:()=>false,panel:(o,...kids)=>h('section',{},...kids)};vm.createContext(e);vm.runInContext(rendererActual(),e);const z=h('main',{}),ctx={vigente:()=>live,navegar:()=>nav++},d={subcuentas:[model],fuentes:{ghl:source}};e.pintarSubcuentas(z,ctx,d,{jefatura:false,base:[model],mias:[model]});return{cell:()=>options.columnas.find(c=>c.clave==='se').celda(model),revoke:()=>{live=false;options.alPulsar(model);changed();return{nav,privado:z.textContent.includes(model.nombre)};},columns:options.columnas.length};}
test('real renderer before after future source and preserved periods',()=>{const src={...source,hora:'2026-10-04T23:59:00Z'};const b=renderer(norm(before,row(),src)),a=renderer(norm(after,row(),src));assert(b.cell().textContent.includes('%'));assert.equal(a.cell().textContent,'—  ·  —');assert(a.cell().attrs['aria-label'].includes('Sin dato'));assert(a.cell().attrs.title.includes('Sólo resultados registrados'));assert.equal(a.columns,8);assert.deepEqual(a.revoke(),{nav:0,privado:false});});
test('real renderer confirmedzero remains visible',()=>{const f=row();f.citas_30d={celebradas:0,no_presentadas:2};f.citas_14d={sin_estado:0};const r=renderer(norm(after,f));assert(r.cell().textContent.includes('0%'));assert(r.cell().attrs.title.includes('no todas las citas ni ventas'));});
console.log(groups+' grupos688 PASS (fuente/recurso + renderer real antes/después).');
