const fs=require('fs'),vm=require('vm'),assert=require('assert');
class N{constructor(tag,a={},...k){this.tag=tag;this.attrs=a;this.style={};this.dataset={};this.classList={add:()=>{}};this.isConnected=true;this.disabled=!!a.disabled;this.kids=[];this.append(...k)}append(...k){this.kids.push(...k.flat(Infinity).filter(x=>x!=null))}replaceChildren(...k){this.kids=[];this.append(...k)}setAttribute(k,v){this.attrs[k]=v}get textContent(){return this.kids.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}set textContent(s){this.kids=[s]}querySelector(){return null}}
const walk=n=>[n,...n.kids.flatMap(x=>x instanceof N?walk(x):[])];
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function setup(){const d=defer(),notes=[],traces=[];let prints=0;const h=(...a)=>new N(...a);const source=fs.readFileSync('modulos/informe.js','utf8');const real=source.slice(source.indexOf('function ambitoPdf609'),source.indexOf('const FUENTE_DE ='));
const s={h,MOD:'informe-cliente',Set,JSON,Number,Array,Date,Map,Intl,console,SIN_CORTE:{},PILA:()=>({}),SELLOS:[],BLOQUES:[],SELLO_BLOQUE:{},ESTADO_FUENTE:{},textoComparar:()=>'',analisisDe:()=>({actual:null}),avisosDe:()=>[],equipoDe:()=>[],enlacePeriodo:()=>null,fRango:()=>'',rangoComparar:()=>'',fDia:x=>x,estadoInforme:()=>({}),textoEstadoInforme:()=>'',borrador:()=>({}),enP:()=>'',vacioLinea:x=>h('p',{},x),barraAcciones:(o)=>h('div',{},o.acciones),soloPapel:x=>x,icono:()=>'',rc:(n,...x)=>n.replaceChildren(...x),avisoFlotante:x=>notes.push(x),window:{print:()=>prints++}};
vm.createContext(s);vm.runInContext(fs.readFileSync('modulos/_informe_evidencia.js','utf8').replace(/export /g,'')+'\n'+real+'\nglobalThis.pintar=pintarCliente;',s);
const p={id:'p',estado:'activo',puestos:['account']},c={id:'c',nombre:'Cliente ficticio',activo_confirmado:true,detalle:true,logo:'logos/c.png'},P={id:'2026-09',desde:'2026-09-01',hasta:'2026-09-30',texto:'Septiembre 2026'};
const ctx={real:{...p},persona:{...p},datos:{personas:[{...p}]},clientes:[c],params:['c'],vigente:()=>true,veModulo:()=>true,ver:q=>({ok:q.tipo!=='responder_cliente'}),servidor:true,pilotoLectura:false,titulo:()=>{},rastro:x=>traces.push(x),api:()=>d.promise};const root=h('main');s.pintar(root,ctx,{c,f:{},P,P0:[P],cmp:'no',acc:[],bloques:new Set()});const bt=()=>walk(root).find(n=>n.tag==='button'&&n.textContent.trim()==='Descargar PDF');const loadLogo=()=>{const img=walk(root).find(n=>n.tag==='img');img.naturalWidth=2;img.attrs.on.load()};const doc={cliente_id:'c',desde:P.desde,hasta:P.hasta,cobertura:'parcial',fuente:'Fuente ficticia',tareas:[{id:'t',cliente_id:'c',nombre:'Trabajo ficticio',fecha_ejecucion:'2026-09-12',fuente_evidencia:'Cierre de flujo ficticio',tipo_evidencia:'finalizacion_flujo'}]};return {d,root,ctx,c,P,bt,loadLogo,doc,notes,traces,prints:()=>prints};}
const tick=()=>new Promise(setImmediate);let total=0;async function test(f){await f();total++}
(async()=>{
await test(async()=>{const x=setup();x.loadLogo();assert.equal(x.bt().disabled,true);x.bt().attrs.on.click();assert.equal(x.prints(),0);assert.match(x.notes[0],/Espera/);assert.equal(x.root.attrs['data-export-bloqueada'],'si')});
await test(async()=>{const x=setup();x.loadLogo();x.d.resolve(x.doc);await tick();assert.equal(x.bt().disabled,false);x.bt().attrs.on.click();assert.equal(x.prints(),1);assert.match(x.root.textContent,/Trabajo ficticio/);assert.match(x.root.textContent,/Copia parcial/);assert.match(x.root.textContent,/aceptación no acreditada/)});
await test(async()=>{const x=setup();x.d.resolve(x.doc);await tick();x.bt().attrs.on.click();assert.equal(x.prints(),0);assert.match(x.notes[0],/logo real/)});
await test(async()=>{const x=setup();x.loadLogo();x.d.reject(Error('Fixture'));await tick();assert.equal(x.bt().disabled,true);x.bt().attrs.on.click();assert.equal(x.prints(),0);assert.match(x.root.textContent,/Esto no significa que no se haya trabajado/);assert.doesNotMatch(x.root.textContent,/0 tareas/)});
await test(async()=>{for(const mutation of [d=>d.cliente_id='ajeno',d=>d.hasta='2026-08-31',d=>d.tareas=null]){const x=setup();x.loadLogo();mutation(x.doc);x.d.resolve(x.doc);await tick();assert.equal(x.bt().disabled,true);x.bt().attrs.on.click();assert.equal(x.prints(),0)}});
await test(async()=>{for(const revoke of [x=>x.ctx.vigente=()=>false,x=>x.ctx.ver=()=>({ok:false}),x=>x.c.activo_confirmado=false,x=>x.ctx.datos.personas[0].estado='baja',x=>x.ctx.clientes.push({...x.c}),x=>x.ctx.persona.id='otro',x=>x.ctx.params=['otro']]){const x=setup();x.loadLogo();revoke(x);x.d.resolve(x.doc);await tick();assert.equal(x.root.textContent,'');assert.equal(x.prints(),0)}});
await test(async()=>{const x=setup();x.loadLogo();x.d.resolve(x.doc);await tick();const bt=x.bt();x.ctx.ver=()=>({ok:false});bt.attrs.on.click();assert.equal(x.prints(),0);assert.equal(x.root.textContent,'')});
await test(async()=>{const x=setup();x.loadLogo();x.doc.tareas=[];x.d.resolve(x.doc);await tick();assert.equal(x.bt().disabled,false);x.bt().attrs.on.click();assert.equal(x.prints(),1);assert.match(x.root.textContent,/no aporta tareas con evidencia válida/);assert.match(x.root.textContent,/Copia parcial/)});
await test(async()=>{const x=setup();x.loadLogo();x.d.resolve(x.doc);await tick();const bt=x.bt();x.ctx.rastro=()=>{x.ctx.vigente=()=>false};bt.attrs.on.click();assert.equal(x.prints(),0)});
await test(async()=>{const x=setup();assert(walk(x.root).some(n=>n.tag==='button'&&n.textContent.includes('Preparar Word')));const img=walk(x.root).find(n=>n.tag==='img');img.attrs.on.error();x.d.resolve(x.doc);await tick();assert.equal(x.bt().disabled,true);x.bt().attrs.on.click();assert.equal(x.prints(),0);assert.match(x.notes[0],/no se pudo cargar/)});
console.log(total+' grupos609 PASS: renderer real, PDF ficticio, fuente local y guardia de contexto.');
})().catch(e=>{console.error(e);process.exitCode=1});
