const fs=require('fs'),assert=require('assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];
const {c,N,all,text,H,PR,docs,make}=new Function('require','__dirname',prefix+';return {c,N,all,text,H,PR,docs,make};')(require,__dirname);
const copy=x=>JSON.parse(JSON.stringify(x)),r={desde:'2026-10-01',hasta:'2026-10-03'},hoy=r.hasta;
const row=(id,v)=>{const m={valor:v,periodo:'2026-10',parcial:true,fecha:'2026-10-03T00:56:00Z',fuente:'ClickUp entradas'},p=c.pautaProporcional306({horas:42,periodo:'2026-10',fecha:'2026-10-03 06:31',fuente:'Pauta mensual · copia autorizada',cobertura:'parcial',origen:'referencia_economica',presupuesto_confirmado:false},r,hoy,m);return {proyecto:{cliente_id:id},medicion:m,pauta:p,autorizada:true};};
const ids=o=>Array.from(o.filas,x=>x.proyecto.cliente_id),sort=xs=>c.ordenarHorasCliente555(xs,r,hoy);let n=0;const test=async(s,f)=>{await f();n++;};
function fixture(){const actor={id:'ops',estado:'activo',activo:true,puestos:['operaciones']},person={id:'p',estado:'activo',activo:true,puestos:['account']},clientes=['low','unknown','high','zero'].map(id=>({id,nombre:id,activo_confirmado:true,detalle:true})),prod=copy(PR);prod.proyectos=clientes.map(x=>({cliente_id:x.id,cliente:x.id,horas_mes:{high:9,low:2,zero:0}[x.id]??null,horas_medicion:x.id==='unknown'?null:{estado:'medido',fuente:'ClickUp entradas',periodo:'2026-10',fecha:H.generado,cobertura:'parcial'}}));const pauta={generado:'2026-10-03 06:31',mes_cuota:'2026-10',clientes:clientes.map(x=>({cliente_id:x.id,cuota_horas:{pautadas:42}}))};const ctx={...make(),servidor:true,real:actor,persona:{...actor},clientes,clientesVisibles:copy(clientes),datos:{personas:[actor,person]},api:async()=>{throw Error('fuente90d no configurada en fixture');},datosModulo:async p=>p==='produccion/produccion'?prod:p==='dinero_cliente/dinero_cliente'?pauta:docs[p]};return {ctx,prod,pauta};}
const clienteTable=node=>all(node,x=>x.tag==='table')[1];const names=node=>all(clienteTable(node),x=>x.tag==='tbody')[0].children.map(tr=>text(tr.children[0]));
(async()=>{
 await test('Descendente estable unknownfinal0 observado inputinmutable',()=>{const a=[row('low',2),row('unknown',null),row('high',9),row('zero',0),row('tie',2)],original=JSON.stringify(a),o=sort(a);assert.equal(o.ordenado,true);assert.deepEqual(ids(o),['high','low','tie','zero','unknown']);assert.equal(JSON.stringify(a),original);});
 await test('Sin ratios conserva orden fuente',()=>{const a=[row('a',null),row('b',null)];assert.deepEqual(ids(sort(a)),['a','b']);assert.equal(sort(a).ordenado,false);});
 for(const [nombre,cambiar] of [
  ['cortehoras',x=>x.medicion.fecha='2026-10-03T01:56:00Z'],['cortepauta',x=>x.pauta.fecha='2026-10-03 06:32'],['fuentehoras',x=>x.medicion.fuente='Otra fuente'],['fuentepauta',x=>x.pauta.fuente='Otra pauta']
 ])await test('Cohortes incompatibles '+nombre,()=>{const a=[row('low',2),row('high',9)];cambiar(a[1]);const o=sort(a);assert.equal(o.ordenado,false);assert.deepEqual(ids(o),['low','high']);});
 await test('Duplicado y missingID no ordenar ni borrar',()=>{for(const id of ['a',null]){const a=[row('a',2),row(id,9)],o=sort(a);assert.equal(o.filas.length,2);assert.equal(o.ordenado,false);assert.deepEqual(ids(o),['a',id]);}});
 for(const [nombre,cambiar] of [
  ['unidad',x=>x.medicion.unidad='EUR'],['grant',x=>x.autorizada=false],['legacysindescriptor',x=>delete x.medicion.fecha],['mes',x=>x.medicion.periodo='2026-09'],['referenciaconfirmada',x=>x.pauta.presupuesto_confirmado=true],['cobertura',x=>x.pauta.cobertura='completa'],['denominador0',x=>x.pauta.horas=0],['ratioforjado',x=>x.pauta.porcentaje=999],['laborables',x=>x.pauta.laborables=3],['future',x=>x.medicion.fecha='2026-10-04T00:00:00Z'],['invalidfecha',x=>x.medicion.fecha='2026-02-30T00:00:00Z'],['offsetinvalid',x=>x.medicion.fecha='2026-10-03T00:00:00+02:99'],['bool',x=>x.medicion.valor=true],['overflow',x=>{x.medicion.valor=1e308;x.pauta.horas=1e-308;x.pauta.porcentaje=Infinity;}]
 ])await test('No ranking desde '+nombre,()=>{const a=[row('a',9)];cambiar(a[0]);assert.equal(sort(a).ordenado,false);assert.equal(sort(a).filas.length,1);});
 await test('Rango distintomes/invalid/futuro mantiene source',()=>{for(const range of [{desde:'2026-09-30',hasta:hoy},{desde:'2026-10-02',hasta:'2026-10-01'},{desde:'2026-10-01',hasta:'2026-10-04'}])assert.equal(c.ordenarHorasCliente555([row('a',2)],range,hoy).ordenado,false);});
 await test('Rendererreal cuatrocolumnas filas/0/pauta/banda intactas',async()=>{const {ctx}=fixture(),node=new N('main');await c.renderEquipo262(node,ctx,'horas');const input=all(node,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0];input.events.change({target:{value:r.desde}});assert.deepEqual(names(node),['high','low','zero','unknown']);assert.equal(all(clienteTable(node),x=>x.tag==='th').length,4);assert.equal(all(clienteTable(node),x=>x.tag==='tbody')[0].children.length,4);assert(text(node).includes('Mayor → menor porcentaje observado')); const zero=all(clienteTable(node),x=>x.tag==='tbody')[0].children[2];assert.equal(text(zero.children[1]),'0');assert(text(zero.children[3]).includes('0 %'));assert(text(clienteTable(node)).includes('225 %'));assert(text(clienteTable(node)).includes('—'));});
 await test('Sin pauta grant conserva filas/horas sin ordenar porlegacy',async()=>{const {ctx}=fixture(),node=new N('main');ctx.ver=q=>({ok:q.tipo!=='horas_pautadas'});await c.renderEquipo262(node,ctx,'horas');all(node,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0].events.change({target:{value:r.desde}});assert.deepEqual(names(node),['low','unknown','high','zero']);assert(!text(clienteTable(node)).includes('225 %'));});
 await test('Scope propio nofilasajenas',async()=>{const {ctx}=fixture(),node=new N('main');ctx.clientes=ctx.clientes.filter(x=>x.id==='low');ctx.clientesVisibles=copy(ctx.clientes);await c.renderEquipo262(node,ctx,'horas');all(node,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0].events.change({target:{value:r.desde}});assert.deepEqual(names(node),['low']);});
 await test('Revocacióncliente duranteawait no fuentecliente pintada',async()=>{const {ctx}=fixture(),node=new N('main'),read=ctx.datosModulo;ctx.datosModulo=async p=>{const doc=await read(p);ctx.clientesVisibles.forEach(x=>x.detalle=false);return doc;};await c.renderEquipo262(node,ctx,'horas');assert(!names(node).some(x=>['low','high','zero','unknown'].includes(x)));assert(!text(clienteTable(node)).includes('225 %')); });
 await test('Callback revocador no nuevaorden ni datos',async()=>{const {ctx}=fixture(),node=new N('main');await c.renderEquipo262(node,ctx,'horas');const input=all(node,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0];ctx.datos.personas[0].estado='baja';input.events.change({target:{value:r.desde}});assert(!text(node).includes('high'));assert(!text(node).includes('low'));});
 await test('Renderer porcentaje mínimo1.06 y positivo0.099 sininflar ni perderfuente',async()=>{const {ctx,prod}=fixture(),node=new N('main');prod.proyectos.find(x=>x.cliente_id==='high').horas_mes=0.0424;prod.proyectos.find(x=>x.cliente_id==='low').horas_mes=0.00396;await c.renderEquipo262(node,ctx,'horas');all(node,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0].events.change({target:{value:r.desde}});const table=clienteTable(node);assert(text(table).includes('≥1 %'));assert(text(table).includes('≥0,099 %'));assert(!text(table).includes('<0,1 %')); assert(!text(table).includes('≥1,1 %'));assert(all(table,x=>x.tag==='span'&&x.attrs['aria-label']==='Porcentaje mínimo observado sobre pauta económica mensual proporcional de referencia, no capacidad ni cumplimiento contractual.').length>=2);assert(all(table,x=>x.tag==='span'&&String(x.attrs.title||'').includes('no acredita consumo total')).length>=2);});
 await test('Mínimos noinflados y positivopequeño',()=>{assert.equal(c.porcentajeMinimo555(1.06),'≥1 %');assert.equal(c.porcentajeMinimo555(0.099),'≥0,099 %');assert.equal(c.porcentajeMinimo555(Number.MIN_VALUE),'≥5e-324 %');assert.equal(c.porcentajeMinimo555(0),'≥0 %');assert.equal(c.porcentajeMinimo555(Infinity),'—');assert(!c.porcentajeMinimo555(Number.MAX_VALUE).includes('∞'));});
 console.log(n+' grupos555 PASS: helper/renderer real, ratios/cortes, cero/unknown,4cols,scope y revocación.');
})().catch(e=>{console.error(e);process.exitCode=1;});
