const fs370=require('node:fs');
const base370=fs370.readFileSync(__dirname+'/pruebas_tablero_mi_trabajo_181.cjs','utf8').split('const a=')[0];
new Function('require','__dirname',base370+String.raw`
const source370=fs.readFileSync(__dirname+'/modulos/mi_trabajo.js','utf8');vm.runInContext(source370.slice(source370.indexOf('function lineaDia('),source370.indexOf('function grupos('))+source370.slice(source370.indexOf('function bloqueTuDia('),source370.indexOf('function coberturaTrabajo(')),c);
let count=0;function check(name,fn){fn();count++;}
const make=()=>({ctx:{persona:{id:'p'},hoy:'2026-10-03',nombre:x=>x,clientes:[],servidor:true},D:{tareas:[]},V:{yo:'p',hoy:'2026-10-03',dias:{p:{}},jornada:[{persona_id:'p',horas_dia:5.8,horas_mes:128,dias_lab_mes:22}],raras:[],ve_equipo:true},local:[]});
check('missing real header and day panel',()=>{const e=make();assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,null);const a=text(c.lineaDia(e)),b=text(c.bloqueTuDia(e,()=>{}));assert(a.includes('Sin registros'));assert(b.includes('Sin registros'));assert(!a.includes('0 h'));assert.equal(buscar(c.bloqueTuDia(e,()=>{}),n=>n.tag==='barra').length,0);assert(b.includes('jornada no confirmada'));});
check('explicit zero preserved',()=>{const e=make();e.V.dias.p['2026-10-03']={cu:0,app:null,cu_observado:true,app_observado:false};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,0);assert(text(c.bloqueTuDia(e,()=>{})).includes('0 h observadas'));});
check('partial positive and RO separate',()=>{const e=make();e.V.dias.p['2026-10-03']={cu:2,app:0.5};e.local=[{campo:'horas',dia:'2026-10-03',quien:'p',minutos:15},{campo:'horas',dia:'2026-10-03',quien:'other',minutos:60}];const x=c.horasDiaTrabajo370(e,'p','2026-10-03');assert.equal(x.valor,2.75);assert.equal(x.ro,.75);const t=text(c.bloqueTuDia(e,()=>{}));assert(t.includes('≥'));assert(t.includes('declaraciones RO'));assert(t.includes('RO no confirma llegada'));});
check('invalid and tiny values',()=>{const e=make();e.V.dias.p['2026-10-03']={cu:NaN,app:undefined};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,null);e.V.dias.p['2026-10-03']={cu:0.0005};assert(c.textoHorasTrabajo370(c.horasDiaTrabajo370(e,'p','2026-10-03')).includes('<0,1'));});
check('team legacy/new missing counts neutral',()=>{const e=make();e.V.raras=[{persona_id:'other',regla:'sin_registros_copia',dia:'2026-10-02'},{persona_id:'third',regla:'sin_horas',dia:'2026-10-02'}];const t=text(c.bloqueRarasEquipo(e));assert(t.includes('Fechas sin registros'));assert(!t.includes('Sin horas en un laborable'));assert(!t.includes('laborables sin horas'));assert(t.includes('calendario no confirmado'));});
check('personal inherited warning neutral',()=>{const e=make();assert(text(c.avisoAmable(e,{regla:'sin_registros_copia',dia:'2026-10-02'})).includes('no acredita ausencia de trabajo'));});
check('no reference does not hide observed hours',()=>{const e=make();e.V.jornada=[];e.V.dias.p['2026-10-03']={cu:2,app:0};assert(text(c.lineaDia(e)).includes('2 h observadas'));assert(text(c.bloqueTuDia(e,()=>{})).includes('2 h observadas'));});
check('source presence flags prevent phantom source zero',()=>{const e=make();e.V.dias.p['2026-10-03']={cu:null,app:1,cu_observado:false,app_observado:true};let x=c.horasDiaTrabajo370(e,'p','2026-10-03');assert.equal(x.cu,null);assert.equal(x.valor,1);e.V.dias.p['2026-10-03']={cu:2,app:null,cu_observado:true,app_observado:false};x=c.horasDiaTrabajo370(e,'p','2026-10-03');assert.equal(x.ro,null);assert.equal(x.valor,2);e.V.dias.p['2026-10-03']={cu:null,app:0};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,null);e.V.dias.p['2026-10-03']={cu:0,app:1};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').cu,null);});
check('explicit RO zero and overflow safe',()=>{const e=make();e.V.dias.p['2026-10-03']={cu:null,app:0,cu_observado:false,app_observado:true};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,0);e.V.dias.p['2026-10-03']={cu:1e308,app:1e308};const x=c.horasDiaTrabajo370(e,'p','2026-10-03');assert.equal(x.valor,null);assert(!c.textoHorasTrabajo370(x).includes('∞'));e.V.dias.p['2026-10-03']={cu:2,app:Infinity};assert.equal(c.horasDiaTrabajo370(e,'p','2026-10-03').valor,null);e.V.dias.p['2026-10-03']={cu:2};e.local=[{campo:'horas',dia:'2026-10-03',quien:'p',minutos:Number.MAX_VALUE},{campo:'horas',dia:'2026-10-03',quien:'p',minutos:Number.MAX_VALUE}];assert(Number.isFinite(c.horasDiaTrabajo370(e,'p','2026-10-03').valor));});
console.log(count+' grupos370 VM real PASS');
`)(require,__dirname);
