const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const e={Intl,Date,Number,Array,JSON,Set,Object};vm.createContext(e);vm.runInContext(fs.readFileSync('modulos/_metricas_campanas_448.js','utf8').replaceAll('export ',''),e);
const ahora=Date.parse('2026-10-04T00:00:00Z');
const fixture=()=>({version:'385.1',cliente_id:'cid',estado:'copia_observada',medicion:{version:'384.1',cliente_id:'cid',nivel:'campaign_diario',cobertura:'filas_recibidas_no_censo',fecha_fuente:'2026-10-03T22:14:08Z',periodo:{desde:'2026-10-01',hasta:'2026-10-02',zona:'America/Los_Angeles'},moneda:'EUR',gasto_observado:102,paginas_completas:true,errores_tipados:[],dias:[{dia:'2026-10-01',filas_recibidas:1,impresiones_observadas:100,clics_observados:10,gasto_observado:2},{dia:'2026-10-02',filas_recibidas:1,impresiones_observadas:10000,clics_observados:100,gasto_observado:100}]}});
let n=0;function test(fn){fn();n++;}
test(()=>{const m=e.metricasCampanas448(fixture(),ahora);assert.equal(m.impresiones,10100);assert.equal(m.clics,110);assert(Math.abs(m.ctr-110/10100*100)<1e-12);assert(Math.abs(m.cpm-102/10100*1000)<1e-12);assert(m.ctr!==5.5);assert(m.cpm!==15);assert.equal(m.cobertura,'filas_recibidas_no_censo');assert.equal(m.periodo.zona,'America/Los_Angeles');});
for(const change of [d=>d.medicion.nivel='account',d=>d.medicion.cobertura='censo',d=>d.medicion.cliente_id='other',d=>d.medicion.fecha_fuente='2026-10-03T24:00:00Z',d=>d.medicion.fecha_fuente='2026-10-03T22:00:00+14:01',d=>d.medicion.fecha_fuente='2026-02-30T22:00:00Z',d=>d.medicion.fecha_fuente='2026-10-05T00:00:00Z',d=>d.medicion.periodo.hasta='2026-10-03',d=>d.medicion.dias[1].dia='2026-10-01',d=>d.medicion.dias.pop(),d=>d.medicion.dias[0].clics_observados=-1,d=>d.medicion.dias[0].impresiones_observadas=0.5,d=>d.medicion.dias[0].gasto_observado=Infinity,d=>d.medicion.gasto_observado=1,d=>d.medicion.dias[0].filas_recibidas=0])test(()=>{const d=fixture();change(d);assert.equal(e.metricasCampanas448(d,ahora),null);});
test(()=>{const d=fixture();d.medicion.dias[0].impresiones_observadas=null;let m=e.metricasCampanas448(d,ahora);assert.equal(m.impresiones,null);assert.equal(m.ctr,null);assert.equal(m.cpm,null);assert.equal(m.clics,110);assert.equal(m.gasto,102);});
test(()=>{const d=fixture();d.medicion.dias[0].clics_observados=null;let m=e.metricasCampanas448(d,ahora);assert.equal(m.clics,null);assert.equal(m.ctr,null);assert.equal(m.impresiones,10100);assert(Math.abs(m.cpm-102/10100*1000)<1e-12);});
test(()=>{const d=fixture();for(const r of d.medicion.dias){r.impresiones_observadas=0;r.clics_observados=0;r.gasto_observado=0;}d.medicion.gasto_observado=0;const m=e.metricasCampanas448(d,ahora);assert.equal(m.impresiones,0);assert.equal(m.gasto,0);assert.equal(m.ctr,null);assert.equal(m.cpm,null);});
test(()=>{const d=fixture();delete d.medicion.gasto_observado;delete d.medicion.moneda;for(const r of d.medicion.dias)delete r.gasto_observado;const m=e.metricasCampanas448(d,ahora);assert.equal(m.permiteImporte,false);assert.equal(m.gasto,null);assert.equal(m.cpm,null);assert.equal(m.moneda,null);assert.equal(m.impresiones,10100);});
test(()=>{const d=fixture();d.medicion.dias[0].gasto_observado=0;d.medicion.dias[1].gasto_observado=0;d.medicion.gasto_observado=0;assert.equal(e.metricasCampanas448(d,ahora).cpm,0);});
test(()=>{const d=fixture();d.medicion.dias[0].impresiones_observadas=Number.MAX_SAFE_INTEGER;assert.equal(e.metricasCampanas448(d,ahora).impresiones,null);});
test(()=>{const d=fixture();d.medicion.paginas_completas=false;assert.equal(e.metricasCampanas448(d,ahora).parcial,true);});
console.log(n+' grupos448 PASS · cocientes de totales, cobertura campañas/fecha/zona, missing/0, importes ausentes y fechas inválidas.');
