const fs381=require('node:fs'),path381=require('node:path'),base381=fs381.readFileSync(path381.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
new Function('require','__dirname',base381+`
const copy=x=>JSON.parse(JSON.stringify(x));
const meta={tipo:'diaria',observado:true,fuente:'ClickUp entradas',cobertura:'parcial',hoy:'2026-10-05',fecha:'2026-10-02',fecha_fuente:'2026-10-05T00:56:00Z',referencia_horas:8};
function dto381(values=[0,5.9,6,7.9,8]){const cut='2026-10-05',dates=Array.from({length:90},(_,i)=>({fecha:new Date(Date.parse(cut+'T00:00Z')-(90-i)*864e5).toISOString().slice(0,10),horas:null,entradas:null,estado:'sin_dato'}));for(const [i,f]of ['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'].entries())if(values[i]!==null)Object.assign(dates.find(x=>x.fecha===f),{horas:values[i],entradas:1,estado:'observado'});return {version:'362.1',estado:'copia_observada',generado:'2026-10-05T05:00:00Z',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',unidad:'h',cumplimiento:null,capacidad_contractual:null,personas:[{persona_id:'p',historial_diario:{version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona:'Europe/Madrid',zona_confirmada:true,desde:dates[0].fecha,hasta:dates.at(-1).fecha,corte_fecha:cut,fecha_fuente_utc:'2026-10-05T00:56:00Z',atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,dias:dates}}]};}
function ctx381(values){const x=make(),p={id:'real',estado:'activo',activo:true,puestos:['operaciones']};Object.assign(x,{hoy:'2026-10-05',servidor:true,real:p,persona:{...p},datos:{personas:[p,{id:'p',estado:'activo',puestos:['seo']}]},api:async()=>dto381(values)});return x;}
(async()=>{
await test('original thresholds independently verified',()=>{const src=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8'),d=src.slice(src.indexOf('function vEquipoDia()'),src.indexOf('function vProduccion()')),r=src.slice(src.indexOf('function vHoras()'),src.indexOf('/* ===== Encargos'));assert(d.includes("h>=8?"));assert(d.includes("h>=6?"));assert(r.includes("p>=90?"));assert(r.includes("p>=60?"));});
await test('daily six eight exact observed',()=>{for(const [h,level]of [[0,'baja'],[5.999,'baja'],[6,'media'],[7.999,'media'],[8,'alta'],[40,'alta']])assert.equal(c.bandaHoras381(h,meta).nivel,level);});
await test('60 90 percent exact with denominator',()=>{const m={...meta,tipo:'porcentaje',desde:'2026-09-28',hasta:'2026-10-02',referencia_horas:40,laborables:5};for(const [h,level]of [[0,'baja'],[23.999,'baja'],[24,'media'],[35.999,'media'],[36,'alta']])assert.equal(c.bandaHoras381(h,m).nivel,level);});
await test('unknown malformed no falseband',()=>{for(const h of [null,undefined,'8',true,NaN,Infinity,-1])assert.equal(c.bandaHoras381(h,meta),null);for(const change of [m=>m.observado=false,m=>m.fuente='legacy',m=>m.fecha_fuente='2026-10-06T00:00:00Z',m=>m.fecha_fuente='2026-99-99T00:00:00Z',m=>m.fecha_fuente='2026-10-03T25:00:00Z',m=>m.fecha='2026-10-06',m=>m.referencia_horas=null]){const m={...meta};change(m);assert.equal(c.bandaHoras381(8,m),null);}});
await test('percent missing zero inconsistent denominator',()=>{for(const [h,n]of [[null,5],[0,0],[41,5],[40,null]])assert.equal(c.bandaHoras381(36,{...meta,tipo:'porcentaje',desde:'2026-09-28',hasta:'2026-10-02',referencia_horas:h,laborables:n}),null);});
await test('overflow percent neutral',()=>assert.equal(c.bandaHoras381(1e308,{...meta,tipo:'porcentaje',desde:'2026-09-28',hasta:'2026-10-02',referencia_horas:8,laborables:1}),null));
await test('immutable and no compliance claim',()=>{const m=copy(meta),b=c.bandaHoras381(8,m);assert.deepEqual(m,meta);assert.equal(b.etiqueta,'Ref. alta');assert(b.detalle.includes('No acredita jornada'));});
await test('real day table typed colors labels and source',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381(),'equipo-dia');const tbody=all(n,x=>x.tag==='tbody')[0],cells=all(tbody,x=>/banda381-(rojo|ambar|verde)/.test(x.attrs.class||''));assert.deepEqual(cells.map(x=>x.attrs.class.split(' ').at(-1)),['banda381-rojo','banda381-rojo','banda381-ambar','banda381-ambar','banda381-verde']);assert(!text(tbody).includes('Ref. baja'));assert(!text(tbody).includes('Ref. alta')); assert(cells.every(x=>x.attrs.title.includes('copia parcial')));assert(text(n).includes('no jornada ni cumplimiento'));});
await test('real unknown day never coloredzero',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381([null,null,null,null,null]),'equipo-dia');assert.equal(all(all(n,x=>x.tag==='tbody')[0],x=>x.attrs.class?.includes('banda381-')).length,0);});
await test('real range percent amber reference not HR',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381(),'horas');all(n,x=>x.tag==='button'&&text(x)==='Semana pasada')[0].events.click();const row=all(n,x=>x.tag==='tbody')[0];assert(!text(row).includes('Ref. media'));assert(all(row,x=>x.attrs.class?.includes('banda381-ambar')).length);assert(!text(row).includes('cumplido'));});
await test('legacy monthly unknown descriptor stays neutral',async()=>{const x=make(),n=new N('main');await c.renderEquipo262(n,x,'horas');all(n,x=>x.tag==='button'&&text(x)==='Mes pasado')[0].events.click();const tbody=all(n,x=>x.tag==='tbody')[0];assert(text(tbody).includes('14'));assert.equal(all(tbody,x=>x.attrs.class?.includes('banda381-')).length,0);});
await test('revoked callbacks clear private colors',async()=>{const x=ctx381(),n=new N('main');await c.renderEquipo262(n,x,'horas');x.datos.personas[1].estado='baja';all(n,z=>z.tag==='button'&&text(z)==='Semana pasada')[0].events.click();assert.equal(all(n,z=>z.tag==='table').length,0);assert(!text(n).includes('Persona fixture'));});
await test('rounding cannot cross threshold six eight sixty ninety',()=>{for(const [v,t,w]of [[5.99,'diaria','5,99'],[7.99,'diaria','7,99'],[59.99,'porcentaje','59,99'],[89.99,'porcentaje','89,99'],[6,'diaria','6'],[8,'diaria','8'],[60,'porcentaje','60'],[90,'porcentaje','90'],[7.999999999,'diaria','<8'],[89.999999999,'porcentaje','<90'],[3.14,'diaria','3,1']])assert.equal(c.formatearBanda381(v,t),w);});
await test('real day near boundary retains precision and band',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381([5.99,7.99,6,8,null]),'equipo-dia');const cells=all(all(n,x=>x.tag==='tbody')[0],x=>/banda381-(rojo|ambar|verde)/.test(x.attrs.class||''));assert.equal(text(cells[0]),'5,99');assert.equal(text(cells[1]),'7,99');});
await test('real percent near boundary visible before label',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381([4.7992,4.7992,4.7992,4.7992,4.7992]),'horas');all(n,x=>x.tag==='button'&&text(x)==='Semana pasada')[0].events.click();const cell=all(all(n,x=>x.tag==='tbody')[0],x=>x.attrs.class?.includes('banda381-rojo'))[0];assert(text(cell).includes('59,99 %'));assert(!text(cell).includes('Ref. baja'));assert(!text(cell).includes('60 %'));});
console.log(checks+' grupos381 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
