const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(__dirname+'/probar_operaciones_265.cjs','utf8').split('(async()=>{')[0];
const E=new Function('require','__dirname',base+';return {s,El,ctx,text};')(require,__dirname),{s,El,ctx,text}=E;
// h auténtico: eventos sólo on:{toggle}, atributos accesibles y textos sin HTML.
El.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(El.prototype,'className',{set(v){this.attrs.class=v;}});
s.Node=El;s.document={createElement:t=>{const n=new El(t,{});n.style={};return n;},createTextNode:t=>String(t)};
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function urlSegura('),comp.indexOf('const svgNS =')).replace(/export /g,''),s);
const all=n=>n instanceof El?[n,...n.children.flat(Infinity).flatMap(all)]:[],pick=(n,tag)=>all(n).filter(x=>x.tag===tag),copy=x=>JSON.parse(JSON.stringify(x));
let checks=0;const test=async(l,f)=>{await f();checks++;console.log('PASS '+l);};
const columns=[];s.tablaDensa=o=>{columns.push(o);return s.h('table',{},s.h('thead',{},s.h('tr',{},o.columnas.map(c=>s.h('th',{scope:'col'},c.titulo)))),s.h('tbody',{},o.filas.map(r=>s.h('tr',{},o.columnas.map(c=>s.h('td',{},c.celda?c.celda(r):r[c.clave]))))));};
const sample=[{nombre:'Altas en plazo (encendidas el día 10, límite 12)',valor:'8/17 · 47 %',detalle:'Explicación original A'},
{nombre:'Compromisos vencidos sin aviso',valor:0,detalle:'Explicación original B'},
{nombre:'Horas por cuenta nueva (media al mes)',valor:'45,7 h/mes',detalle:'Explicación original C'}];
async function mount(rs=sample,change=null,role='direccion'){const x=ctx();x.real.puestos=[role];x.persona.puestos=[role];x.datos.personas[0].puestos=[role];let calls=0;x.accion=async()=>{calls++;throw Error('POST prohibido');};x.datosModulo=async path=>{if(change)change(x);return path==='decisiones/direccion'?{informe_semanal:{corte:'2026-10-02',semana:'28sep→4oct2026',numeros:rs.map(r=>({...r})).concat([{nombre:'EXTRA PRIVADA',valor:999,detalle:'SECRET'}])}}:{};};const root=s.h('main',{});await s.renderDiaDireccion265(root,x,'tomas');return {root,x,block:all(root).find(n=>n.attrs['data-informe-semanal-498']!==undefined),calls};}
(async()=>{
await test('2 columnas y3 indicadores conservan exactamente valores fuente',async()=>{const {root,block,calls}=await mount();assert(block);assert.deepEqual(pick(block,'th').map(text),['Indicador','Valor']);const rs=pick(block,'tbody')[0].children;assert.equal(rs.length,3);assert.deepEqual(rs.map(r=>text(r.children[1])),['8/17 · 47 %','0','45,7 h/mes']);assert(!text(root).includes('EXTRA PRIVADA'));assert(text(root).includes('Fuente histórica de Dirección · 2026-10-02'));assert(text(root).includes('no son métricas actuales'));assert(text(root).includes('borrador editable'));assert.equal(calls,0);});
await test('Detalles cerrados sin texto repetido conservan explicación completa al abrir',async()=>{const {block}=await mount(),ds=pick(block,'details');assert.equal(ds.length,3);assert(ds.every(d=>!d.open));assert(!text(block).includes('Explicación original'));ds.forEach(d=>{d.open=true;d.events.toggle();});for(const l of ['Explicación original A','Explicación original B','Explicación original C','Día 12','48 h','45 h/mes','fuente histórica 2026-10-02'])assert(text(block).includes(l),l);assert(ds.every(d=>pick(d,'summary')[0].attrs['aria-label'].startsWith('Fuente y criterio de ')));});
await test('Valores desconocidos no0 niNaN ycriterios permanecen',async()=>{const {block}=await mount([]);assert.deepEqual(pick(block,'tbody')[0].children.map(r=>text(r.children[1])),['—','—','—']);const ds=pick(block,'details');ds.forEach(d=>{d.open=true;d.events.toggle();});assert(text(block).includes('Falta ventana y evidencia suficiente'));assert(pick(block,'span').filter(n=>text(n)==='—').every(n=>n.attrs.title.includes('no equivale a cero')));});
await test('Valor0 finito conservado; NaN/boolean/infinity son desconocidos',async()=>{const rs=copy(sample);rs[0].valor=true;rs[1].valor=Infinity;rs[2].valor=NaN;const x=await mount(rs);assert(pick(x.block,'tbody')[0].children.every(r=>text(r.children[1])==='—'));});
for(const role of ['direccion','operaciones'])await test('Rol vigente autorizado '+role,async()=>{assert((await mount(sample,null,role)).block);});
await test('Account fuera de puerta no recibe informe',async()=>{const {root,block}=await mount(sample,null,'account');assert.equal(block,undefined);assert(!text(root).includes('8/17'));});
for(const mode of ['grant','actor','ACT','roles'])await test('Revocación al abrir detalle '+mode,async()=>{const {block,x}=await mount();const d=pick(block,'details')[0];if(mode==='grant')x.veModulo=id=>id!=='decisiones';if(mode==='actor')x.datos.personas.push(copy(x.datos.personas[0]));if(mode==='ACT')x.clientes.push({id:'other',activo_confirmado:false});if(mode==='roles')x.persona.puestos=['direccion','seo'];d.open=true;d.events.toggle();assert.equal(block.children.length,0);});
await test('Fuente permiso revocado durante await no publica cifras antiguas',async()=>{const {block}=await mount(sample,x=>{x.veModulo=id=>id!=='decisiones';});assert(block);assert.equal(block.children.length,0);});
console.log(checks+' grupos informe498 PASS · renderer265/componentes.h reales');
})().catch(e=>{console.error(e);process.exitCode=1;});
