const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
class N{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.events={};this.style={};this.isConnected=true;}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){this.children.push(x);if(x instanceof N)x.parent=this;}}replaceChildren(...xs){this.children=[];this.append(...xs);}setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}set className(v){this.attrs.class=v;}addEventListener(k,fn){this.events[k]=fn;}focus(){}querySelectorAll(){return[];}}
const c={Date,Intl,Number,Map,Set,Promise,Node:N,document:{createElement:t=>new N(t),createTextNode:s=>String(s)}};vm.createContext(c);
const component=fs.readFileSync(path.join(__dirname,'componentes.js'),'utf8');vm.runInContext(component.slice(component.indexOf('export function urlSegura('),component.indexOf('export function h(')).replace('export ',''),c);vm.runInContext(component.slice(component.indexOf('export function h('),component.indexOf('const svgNS =')).replace('export ',''),c);
function load(file,exports){const s=fs.readFileSync(path.join(__dirname,'modulos',file),'utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');Object.assign(c,vm.runInContext(`(()=>{${s}\nreturn {${exports.join(',')}}})()`,c));}
load('_cabeceras_operaciones_423.js',['cabeceraOperaciones423']);load('_pauta_proporcional_306.js',['pautaProporcional306']);load('control_cartera.js',['pautaHorasControl','prepararControlCartera']);load('_operaciones_registros_269.js',['filaAvisado269']);load('_operaciones_anomalias_276.js',['controlAnomalia276']);load('_horas_diarias_238.js',['serieHorasDiaria238']);load('_operaciones_notas_equipo_281.js',['panelEquipoNotas281','observacionesSemana281']);load('_produccion_baseline.js',['planificacionBaseline']);load('_produccion_creadas_287.js',['creadasSemana287','panelComparacionSemanal296','modeloComparacionSemanal296']);load('_planning_comparacion_320.js',['comparacionCreadores320']);load('_account_fuegos_346.js',['accountFuego346']);load('_planning_observado_360.js',['ambitoPlanning360','proyectarPlanning360','panelPlanningObservado360']);load('_bandas_horas_381.js',['bandaHoras381','formatearBanda381','cssBandas381','leyendaHoras381']);load('_ejemplos_creador_438.js',['ambitoEjemplos438','modeloEjemplos438','panelEjemplosCreador438']);load('_operaciones_equipo_262.js',['renderEquipo262','INVENTARIO_EQUIPO_262','diasLaborables262','horasRango262','referenciaHoras262','horasProyectoRango262','pautaProyectoRango262']);
const all=(n,p)=>[...(n instanceof N&&p(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,p)):[])],text=n=>n instanceof N?n.children.map(text).join(' '):String(n??'');
const cp=require('child_process');
const dto=JSON.parse(cp.execFileSync('python3',['-c',"import json;import probar_integracion_comparacion_296 as F;import evidencia_produccion_287 as M;print(json.dumps(M.aplicar296({'proyectos':[{'cliente_id':'a','cliente':'Cliente fixture'}],'personas':[{'persona_id':'p','nombre':'Persona fixture'}]},F.fixture(),{'a'},{'p'},M.SHA296,M.SHA296)))"],{encoding:'utf8'}));
const clone=x=>JSON.parse(JSON.stringify(x));
const ctx=()=>({hoy:'2026-10-03',real:{id:'ops'},persona:{id:'ops'},clientes:[{id:'a',activo_confirmado:true,detalle:true}],clientesVisibles:[{id:'a',activo_confirmado:true,detalle:true}],datos:{personas:[{id:'p',estado:'activo',nombre:'Persona fixture'}]},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,datosModulo:async()=>clone(dto)});
let n=0;const test=async(l,f)=>{await f();n++;};
(async()=>{
 await test('Canonicalcreator exactweekobserved scope',()=>{const r=c.comparacionCreadores320(ctx(),dto).get('p');assert.equal(r.valor,1);assert.equal(r.desde,'2026-09-21');assert.equal(r.hasta_exclusiva,'2026-09-28');assert(r.detalle.includes('no mide rupturas'));});
 for(const mode of ['oldweek','grantclient','grantperson','module','revoked','ACT','duplicate','foreignscope','hash','future'])await test('Failclosed '+mode,()=>{const x=ctx(),d=clone(dto);if(mode==='oldweek')x.hoy='2026-10-05';if(mode==='grantclient')x.ver=q=>({ok:q.tipo!=='cliente_detalle'});if(mode==='grantperson')x.ver=q=>({ok:q.tipo!=='horas_persona'});if(mode==='module')x.veModulo=()=>false;if(mode==='revoked')x.vigente=()=>false;if(mode==='ACT')x.clientes[0].activo_confirmado=false;if(mode==='duplicate')d.personas.push(clone(d.personas[0]));if(mode==='foreignscope')d.personas[0]._comparacion_semanal_296.cliente_ids_scope.push('foreign');if(mode==='hash')d.personas[0]._comparacion_semanal_296.sha256_candidato='0'.repeat(64);if(mode==='future')d.personas[0]._comparacion_semanal_296.corte_utc='2099-10-03T13:08:00Z';assert.equal(c.comparacionCreadores320(x,d).size,0);});
 await test('Zeroobservationsno0count',()=>{const d=clone(dto),a=d.personas[0]._comparacion_semanal_296.creadas.anterior;a.valor=null;a.observaciones=0;assert.equal(c.comparacionCreadores320(ctx(),d).get('p').valor,null);});
 await test('Realrenderer additionalcell preservesoriginalSemanaPasadaUnknown',async()=>{const x=ctx(),root=new N('main');await c.renderEquipo262(root,x,'planificacion');const heads=all(root,q=>q.tag==='thead')[0],labels=all(heads,q=>q.tag==='th').map(text);assert.equal(labels.length,8);assert.equal(labels[5],'Sem. ant.');assert.equal(labels[6],'Creadas sem. ant.');assert.equal(all(heads,q=>q.tag==='th')[5].attrs.title,'Semana pasada');assert.equal(all(heads,q=>q.tag==='th')[6].attrs.title,'Creadas semana pasada');const row=all(root,q=>q.tag==='tbody')[0].children[0];assert.equal(text(row.children[5]),'—');assert(text(row.children[6]).includes('≥1'));const tips=all(row.children[5],q=>q.attrs.title);assert(tips.some(q=>q.attrs.title.includes('Rupturas')));assert.equal(text(row.children[2]),'—');assert.equal(text(row.children[3]),'—');assert.equal(text(row.children[4]),'—');});
 await test('Absentcomparison retainsoriginal7columns',async()=>{const x=ctx();x.datosModulo=async()=>({personas:[{persona_id:'p'}]});const root=new N('main');await c.renderEquipo262(root,x,'planificacion');assert.equal(all(all(root,q=>q.tag==='thead')[0],q=>q.tag==='th').length,7);});
 await test('Asyncgrantrevokedbeforeattach no rows',async()=>{const x=ctx();let alive=true;x.vigente=()=>alive;x.datosModulo=async()=>{alive=false;return clone(dto);};const root=new N('main');await c.renderEquipo262(root,x,'planificacion');assert.equal(root.children.length,0);});
 await test('Header distinguishes measuredperiods+cuts and legacy',async()=>{const d=clone(dto);d.lunes='2026-09-28';d.planificacion={};d.personas[0]._evidencia_equipo_275={version:'275.1',sha256_candidato:'f2e568ced88d880a9df5aedde752d51d5d982ac52d7cb7b190fc9bf299bc49a2',fuente:'clickup_cache_local',cobertura:'parcial',zona:'Europe/Madrid',persona_id:'p',criterio:'creador_ID_canonico+clientes_del_DTO',cierres_ayer:null,al_planning:null,rompen_semanal:null,corte:'2026-10-03T13:08:00Z',lunes:'2026-09-28',creadas_semana:1,creadas_semana_observaciones:1};const x=ctx();x.datosModulo=async()=>d;const root=new N('main');await c.renderEquipo262(root,x,'planificacion');const header=text(all(root,q=>q.tag==='header')[0]);assert(header.includes('Creadas actuales 2026-09-28 → 2026-10-03 · corte 2026-10-03T13:08:00Z'));assert(header.includes('Creadas anteriores 2026-09-21 → 2026-09-28 (fin exclusivo) · corte 2026-10-03T13:08:00Z'));assert(header.includes('Legado planificación'));assert(header.includes('no es el corte de creaciones'));});
 await test('No descriptor header not certifyfreshcreations',async()=>{const x=ctx();x.datosModulo=async()=>({lunes:'2026-09-28',personas:[{persona_id:'p'}]});const root=new N('main');await c.renderEquipo262(root,x,'planificacion');const header=text(all(root,q=>q.tag==='header')[0]);assert(header.includes('Legado planificación'));assert(!header.includes('Creadas actuales'));assert(!header.includes('Creadas anteriores'));});
 console.log(n+' grupos planning320 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
