const fs=require('node:fs');
const base=fs.readFileSync(__dirname+'/pruebas_tablero_mi_trabajo_181.cjs','utf8').split('const a=')[0];
new Function('require','__dirname',base+String.raw`
(async()=>{
const a={id:'task-a',lista_id:'list-1',cli:'cliente-1',persona_id:'yo',tarea:'Visible A',estado:'in progress',tipo_estado:'custom',grupoV:'hoy',capa:{cambios:[]}};
const uuid='f61a94b8-2091-453e-9299-43b5b1758192';c.crypto={randomUUID:()=>uuid};
const E=()=>({D:{tareas:[{...a}],fuentes:{}},V:{yo:'yo',personas:[{id:'yo'}],cambios:[],estados_detalle:{'list-1':[{estado:'in progress',tipo:'custom'},{estado:'complete',tipo:'closed'}]},capacidad_transicion:{version:'191.1',activo:true},transiciones:{'task-a':{lista_id:'list-1',expected_estado:'in progress',revision:'a'.repeat(64),bloqueada:false}},dias:{},jornada:[],raras:[]},local:[],tableroLista:'list-other',ctx:{hoy:'2026-10-03',persona:{id:'yo'},real:{id:'yo'},servidor:true,nombre:x=>x},vigente:()=>true});
const receipt=p=>({ok:true,id:1,intencion_guardada:{id:p.intencion_id,accion_id:1,repetida:false},cola_estado:'simulado',recibo_durable:true,confirmacion_remota:false,recibo:{accion_id:1,cambio_id:7,tarea_id:p.objeto,lista_id:p.vista_previa.lista_id,desde:p.vista_previa.expected_estado,hasta:p.vista_previa.a,intencion_id:p.intencion_id,estado_cola:'simulado',confirmacion_remota:false}});
const button=n=>buscar(n,x=>x.tag==='button')[0];const menu=n=>buscar(n,x=>x.tag==='menu')[0]?.attrs.config;
let e=E(),tree;const paint=()=>tree=c.cambioEstadoDetalle200(e,a,paint);paint();assert(menu(tree));assert.equal(e.tableroLista,'list-other');assert.equal(e.movimientos192.size,0);assert(button(tree).attrs.disabled);casos++;
const requests=[];e.ctx.accion=async p=>{requests.push(JSON.stringify(p));throw Error('timeout');};menu(tree).alCambiar('complete');await button(tree).attrs.on.click();assert.equal(requests.length,1);assert(text(tree).includes('Reintentar la misma intención'));let p=JSON.parse(requests[0]);assert.equal(p.intencion_id,uuid);assert.equal(p.vista_previa.transicion_tablero,true);assert.equal(p.vista_previa.expected_estado,a.estado);assert.equal(p.vista_previa.lista_id,a.lista_id);assert.equal(p.vista_previa.revision,'a'.repeat(64));assert.equal(e.local.length,0);assert.equal(e.D.tareas[0].estado,'in progress');assert.equal(e.tableroLista,'list-other');casos++;
e.ctx.accion=async p=>{requests.push(JSON.stringify(p));return receipt(p);};await button(tree).attrs.on.click();assert.equal(requests[0],requests[1]);assert(button(tree).attrs.disabled);assert(text(tree).includes('no enviado a ClickUp'));await button(tree).attrs.on.click();assert.equal(requests.length,2);assert.equal(e.local.length,0);casos++;
for(const mutate of [e=>delete e.V.transiciones,e=>e.ctx.soloLectura=true,e=>e.ctx.pilotoLectura=true,e=>e.ctx.real.id='otra',e=>e.V.transiciones[a.id].bloqueada=true,e=>e.V.capacidad_transicion.activo=false,e=>e.D.tareas.push({...a,cli:'foreign'}),e=>e.D.tareas=[]]){e=E();mutate(e);let count=0;e.ctx.accion=async()=>{count++;};tree=c.cambioEstadoDetalle200(e,a,()=>{});assert(button(tree).attrs.disabled);await button(tree).attrs.on.click();assert.equal(count,0);casos++;}
// Revocación después del render y antes del clic: ningún envío.
e=E();paint();menu(tree).alCambiar('complete');const click=button(tree).attrs.on.click;e.ctx.persona.id='otra';let calls=0;e.ctx.accion=async()=>{calls++;};await click();assert.equal(calls,0);casos++;
// Revocación mientras espera: no recibo ni confirmación se pinta.
e=E();paint();menu(tree).alCambiar('complete');let resolve;let payload;e.ctx.accion=p=>{payload=p;return new Promise(r=>resolve=r);};const pending=button(tree).attrs.on.click();e.D.tareas=[];resolve(receipt(payload));await pending;assert(!e.movimientos192.get(a.id).intento.recibo);assert.equal(e.local.length,0);casos++;
// Doble clic: la misma intención y un único transporte.
e=E();paint();menu(tree).alCambiar('complete');calls=0;e.ctx.accion=p=>{calls++;payload=p;return new Promise(r=>resolve=r);};const first=button(tree).attrs.on.click();await button(tree).attrs.on.click();assert.equal(calls,1);resolve(receipt(payload));await first;casos++;
assert(!source.includes("actuar(E, t, 'cambiar_estado', { a: estadoNuevo }"));assert(source.includes("actuar(E, t, 'cambiar_fecha'"));assert(source.includes("panelComentario366(E,t,h)"));casos++;
// UX separada del contrato: detalle ancho fuera de columnas, cierre y teclado.
e=E();e.ctx.soloLectura=true;e.ctx.pilotoLectura=true;e.cont=h('main');e.abierta='yo:task-a';const tab={lista_disponible:true};const row={...a,coherente:true,asignados:['yo'],columna_tablero:'in progress',resolucion_estado:{estado:'verificado'}};e.tableroLista='list-1';tree=c.vistaTableroTrabajo181(e,tab,[row],()=>{});const wide=buscar(tree,n=>n.attrs?.['data-detalle-tablero-200']!==undefined)[0];assert(wide);assert.equal(wide.attrs.tabindex,'-1');assert.equal(wide.attrs.style.width,'100%');assert.equal(buscar(buscar(tree,n=>n.attrs?.['data-tablero-tarea'])[0],n=>n.attrs?.['data-detalle-197']!==undefined).length,0);wide.attrs.on.keydown({key:'Escape',preventDefault(){}});assert.equal(e.abierta,null);casos++;
// Todos los avisos quedan accesibles, plegados; sin cortar a los primeros cuatro.
vm.runInContext('bloqueTuDia='+source.slice(source.indexOf('function bloqueTuDia('),source.indexOf('/** Varias horas')),c);
e=E();e.ctx.soloLectura=true;e.V.raras=Array.from({length:7},(_,i)=>({persona_id:'yo',regla:'sin_horas',dia:'2026-10-'+String(i+1).padStart(2,'0')}));tree=c.bloqueTuDia(e,()=>{});const d=buscar(tree,n=>n.tag==='details')[0];assert(d);assert(text(d).includes('Registros por contrastar · 7'));assert(!d.attrs.open);assert.equal(buscar(d,n=>n.attrs.role==='note').length,7);casos++;
console.log(casos+' pruebas200 PASS: detalle CAS191/194/193, retry durable, scopedstale/doble clic, sin escape legacy y UX ancho/avisos completos plegados.');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
