const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const fuente=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8');
const funcs={},nums={};
const box={Date,Number,Set,Map,def:(id,usa,f)=>funcs[id]=f,num:(id,usa,f)=>nums[id]=f,
 verdad:(c,id)=>c.verdad(id),saludV:(c,id)=>c.verdad(id)?.salud,
 fresco:(fuente,d)=>({fuente,d}),fmt:{num:String},hoyDia:()=>new Date('2026-10-04T12:00:00'),hoyISO:()=> '2026-10-04',
 GRAV_TXT:{bien:'Bien',critico:'Crítico',atencion:'Atención'},GRAV_EST:{bien:'verde',critico:'rojo',atencion:'ambar'},hrefCliente:(c,id)=>'#/ficha/'+id,
 altasNuevos:(c,D)=>({n:D.dato(),l:D.dato().altas}),ordenEstado:(a,b)=>({rojo:0,verde:2}[a.estado]??3)-({rojo:0,verde:2}[b.estado]??3),ir:(c,r,id)=>'#/'+r+'/'+id};
vm.createContext(box);
for(const [inicio,fin] of [["def('ronda_mili'","def('clientes_esperando'"],["def('clientes_tarjetas'","/** R12 (A4)"],["def('nuevos_resumen'","def('produccion_ops'"],["num('cartera_salud'","function citaObjetivo"]])vm.runInContext(fuente.slice(fuente.indexOf(inicio),fuente.indexOf(fin,fuente.indexOf(inicio))),box);
let n=0;const test=(nombre,f)=>{f();n++;};
const ctx=(vs)=>({clientes:vs.map((v,i)=>({id:'c'+i,nombre:'Fixture '+i,enCartera:true})),verdad:id=>vs[Number(id.slice(1))]});const D={opcional:()=>({}),dato:()=>({})};
test('Índice100 no convierte gravedad desconocida en verde',()=>{const r=funcs.clientes_tarjetas(ctx([{salud:100}]),D);assert.equal(r.estado,'gris');assert.equal(r.filas[0].estado,'gris');assert(r.filas[0].texto.includes('índice registrado 100'));assert(!JSON.stringify(r).includes('salud ≥'));});
test('Estado independiente crítico sobrevive índicealto',()=>{const c=ctx([{salud:100,gravedad:'critico',motivos:['Señal independiente']},{salud:0,gravedad:'bien'}]),r=funcs.clientes_tarjetas(c,D);assert.equal(r.valor,2);assert.equal(r.estado,'rojo');assert.equal(r.filas[0].extra,'Señal independiente');assert(r.filas[1].texto.includes('índice registrado 0'));assert.equal(nums.cartera_salud(c,D).estado,'gris');assert.equal(nums.cartera_salud(c,D).valor,2);});
for(const v of [null,NaN,Infinity,-1,'100',undefined])test('Índiceinválido no dato '+String(v),()=>{const c=ctx([{salud:v}]);assert.equal(nums.cartera_salud(c,D).valor,0);assert(!funcs.clientes_tarjetas(c,D).filas[0].texto.includes('índice registrado'));});
test('Estado bien legítimo no se borra poríndice0',()=>{assert.equal(funcs.clientes_tarjetas(ctx([{salud:0,gravedad:'bien'}]),D).estado,'verde');assert.equal(funcs.clientes_tarjetas(ctx([]),D).estado,'gris');});
const original={id:'r1',donde:'equipo',f:'Cada día',que:'Que nadie del equipo se quede sin imputar: quien ayer no llegó a 8 h, avisado.',prueba:'Casilla histórica'};
test('Ronda referenciaexacta neutral sinmutar fuente ni Hecho automático',()=>{const raw={items:[original,{...original,id:'r2'}]},prev=JSON.stringify(raw),r=funcs.ronda_mili({}, {dato:()=>raw},{},{acciones:[]});assert.equal(r.ronda.items.length,2);assert(r.ronda.items[0].que.startsWith('Revisar los registros'));assert.equal(r.ronda.items[0].referencia547,original.que);assert.equal(r.ronda.items[1].que,original.que);assert.equal(r.valor,'0/2');assert.equal(JSON.stringify(raw),prev);});
test('MismoID futura política diferente no se reescribe',()=>{const r=funcs.ronda_mili({}, {dato:()=>({items:[{...original,que:'Otro punto'}]})},{},{acciones:[]});assert.equal(r.ronda.items[0].que,'Otro punto');assert.equal(r.ronda.items[0].referencia547,undefined);});
const src=fs.readFileSync(__dirname+'/modulos/mi_dia.js','utf8');
const node=(tag,attrs,...children)=>({tag,attrs:attrs||{},children:children.flat(Infinity).filter(x=>x!==null&&x!==undefined)});
box.h=node;box.unidadDe=(n,s)=>s;box.nombreModulo=x=>x;box.icono=x=>x;box.TEXTO_FILA={};box.chipEstado=(s,t)=>node('chip',{estado:s},t);box.botonDeshacer=p=>node('button',p,p.texto);box.fmt={num:String};
vm.runInContext(src.slice(src.indexOf('function objetoBloque('),src.indexOf('/** Mapa de control',src.indexOf('function objetoBloque(')))+';this.objetoBloque=objetoBloque;this.masEn=masEn;this.ronda=ronda;',box);
const texto=x=>typeof x==='object'?x.children.map(texto).join(' '):String(x);const buscar=(x,tag)=>typeof x==='object'?[...(x.tag===tag?[x]:[]),...x.children.flatMap(v=>buscar(v,tag))]:[];
test('17altas5fuera no etiqueta12fuera restantes',()=>{const altas=Array.from({length:17},(_,i)=>({cliente_id:'x'+i,nombre:'Alta '+i,dia:i,plazo:{estado:i<5?'rojo':'verde'}})),r=funcs.nuevos_resumen({verdad:()=>null},{dato:()=>({altas})},{});assert.equal(r.valor,5);assert.equal(r.filas.length,17);assert.equal(r.unidad,'fuera de plazo de 17 altas');const more=box.masEn(r.filas.length-5,box.objetoBloque({id:'nuevos_resumen'},r),'Nuevos','clientes-nuevos');assert(texto(more).includes('y 12 altas más'));assert(!texto(more).includes('fuera'));assert.equal(box.objetoBloque({id:'reuniones_ciclo'},{}).join('|'),'caso de seguimiento|casos de seguimiento');});
test('Ronda realrender mantiene referencia y acción sólo callback explícito',()=>{let llamadas=0;const r=funcs.ronda_mili({}, {dato:()=>({items:[original]})},{},{acciones:[]}),out=box.ronda({soloLectura:true,accion:()=>{llamadas++;}},r.ronda,5);assert.equal(llamadas,0);assert.equal(buscar(out,'details').length,1);assert(texto(out).includes('Referencia histórica'));assert(texto(out).includes(original.que));assert(texto(out).includes('sin jornada confirmada'));assert.equal(buscar(out,'button')[0].attrs.soloLectura,true);});
console.log(n+' grupos547 PASS: bloques/proxy reales, universoaltas y ronda renderizada sin POST.');
