const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ro349-'));fs.chmodSync(dir,0o700);const mod=path.join(__dirname,'modulos'),harness=fs.readFileSync(path.join(__dirname,'pruebas_operaciones_accounts_263.cjs'),'utf8');
const stub=harness.match(/fs.writeFileSync\(path.join\(dir,'componentes.mjs'\),`([\s\S]*?)`\);/)[1].replace('replaceChildren(...xs){','replaceChildren(...xs){if(xs.some(Array.isArray))throw Error("Array en replaceChildren nativo");');fs.writeFileSync(path.join(dir,'componentes.mjs'),stub);
for(const name of ['_llamadas_historicas_353','_horas_cartera_349','_orden_clientes_348','_operaciones_accounts_263','_pedidos_macro_344','_mensaje_alarma_345','_alarmas_operaciones_342','_top_alarmas_388','control_cartera','_control_artifact_250','_control_cartera_ruta_239','_imputa_personal_390','_historial_diario_364','_bandas_horas_381','_horas_diarias_238','_evidencias_resumen'])fs.writeFileSync(path.join(dir,name+'.mjs'),fs.readFileSync(path.join(mod,name+'.js'),'utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'").replace("from '../componentes.js'","from './componentes.mjs'"));
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');let n=0;const test=(label,f)=>{f();n++;console.log('PASS',label);};
(async()=>{try{
const {ambitoLlamadas353:scope,proyectarLlamadas353:project,celdaLlamadas353:cell,celdaLlamadasVigente353:alive}=await import('file://'+path.join(dir,'_llamadas_historicas_353.mjs')),{renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs')),{h}=await import('file://'+path.join(dir,'componentes.mjs'));
const hoy='2026-10-03',stamp=hoy+'T09:00:00+00:00',HASH='4afc61a142faadf9631141c3a33109712cfd9ecfdf832a99e469731e970f5bc2';
function ctx(){const ops={id:'ops',estado:'activo',puestos:['operaciones']},acc={id:'acc',estado:'activo',puestos:['account']};return {real:{...ops},persona:{...ops},hoy,servidor:true,veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,datos:{personas:[ops,acc],asignaciones:[]},clientesVisibles:['a','b','c'].map(id=>({id,nombre:id,activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}})),carteraPorSilla:{account:new Set(['a','b','c'])},nombre:id=>id,verdad:cid=>({cliente_id:cid,gravedad:'atencion'}),api:async()=>null,datosModulo:async()=>null};}
const row=(cliente_id,count)=>({cliente_id,periodo:'2026-09',llamadas_30s:count,unidad:'llamadas_respondidas_30s',estado:count===null?'sin_dato':'copia_historica',actor_id:null,direccion:null,registro:'historico',verificacion_externa:false,cumplimiento:null});
const dto=()=>({version:'350.1',generado:stamp,periodo:'2026-09',estado:'copia_historica',cobertura:'parcial',fuente:'Zadarma · agregado histórico local',sha256_candidato:HASH,filas:[row('a',4),row('b',3),row('c',null)],nota:'NO copiar nota importada ni contactos'}),get=(c,d)=>project(c,d,scope(c));
const c=ctx(),m=get(c,dto());
test('contrato350 parcial positivo sin actor ni dirección mantiene mínimo',()=>{assert.ok(m);const x=cell(c,m,['a','b','c']);assert.equal(x.total,7);assert.equal(x.medidos,2);assert.match(x.valor,/≥7 · sep2026/);assert.equal(x.estado,'gris');assert.match(x.detalle,/no atribuye.*account actual/);assert.doesNotMatch(JSON.stringify(m),/nota|NO copiar/);});
test('fila nula y fila ausente no ceros',()=>{assert.equal(cell(c,m,['c']).total,null);const d=dto();d.filas=d.filas.slice(0,1);const x=get(c,d);assert.equal(cell(c,x,['b']).valor,'—');});
for(const [label,modify]of [['version',d=>d.version='350.2'],['periodo',d=>d.periodo='2026-10'],['hash',d=>d.sha256_candidato='0'.repeat(64)],['fuente',d=>d.fuente='API actual'],['cobertura',d=>d.cobertura='completa'],['sin zona',d=>d.generado='2026-10-03T09:00:00'],['fecha futura',d=>d.generado='2026-10-04T00:00:00Z'],['hora inválida',d=>d.generado='2026-10-03T25:00:00Z'],['fecha inválida',d=>d.generado='2026-02-30T09:00:00Z'],['offset inválido',d=>d.generado='2026-10-03T09:00:00+15:00'],['estado global',d=>d.estado='sin_dato']]){test('rechaza '+label,()=>{const d=dto();modify(d);assert.equal(get(ctx(),d),null);});}
for(const [label,modify]of [['cero',r=>r.llamadas_30s=0],['negativo',r=>r.llamadas_30s=-1],['fracción',r=>r.llamadas_30s=1.1],['texto',r=>r.llamadas_30s='4'],['unidad',r=>r.unidad='llamadas_salientes'],['actor',r=>r.actor_id='acc'],['dirección',r=>r.direccion='saliente'],['verificación',r=>r.verificacion_externa=true],['cumplimiento',r=>r.cumplimiento=true],['estado',r=>r.estado='sin_dato'],['mesfila',r=>r.periodo='2026-10'],['registro',r=>r.registro='actual']]){test('rechaza fila '+label,()=>{const d=dto();modify(d.filas[0]);assert.equal(get(ctx(),d),null);});}
test('duplicados y clientes ajenos nunca selecciona primero',()=>{for(const modify of [d=>d.filas.push({...d.filas[0]}),d=>d.filas[0].cliente_id='ajeno']){const d=dto();modify(d);assert.equal(get(ctx(),d),null);}});
test('fuente ausente permitida sólo unknown todas filas',()=>{const d=dto();d.estado='sin_dato';d.cobertura='desconocida';d.fuente=d.sha256_candidato=null;d.filas=d.filas.map(r=>row(r.cliente_id,null));assert.ok(get(c,d));assert.equal(cell(c,get(c,d),['a']).total,null);d.filas[0]=row('a',2);assert.equal(get(c,d),null);});
test('catálogos/ACT/grants/roles/propia se validan actualmente',()=>{for(const modify of [x=>x.datos.personas.push({...x.real}),x=>x.datos.personas[0].activo=false,x=>x.real.puestos=['direccion'],x=>x.veModulo=()=>false]){const x=ctx();modify(x);assert.equal(scope(x),null);}const x=ctx();x.clientesVisibles[0].activo_confirmado=false;assert.equal(get(x,dto()),null);x.clientesVisibles[0].activo_confirmado=true;x.ver=()=>({ok:false});assert.equal(get(x,dto()),null);});
test('Account normal intersecta cartera y respeta fila missing',()=>{const x=ctx();x.real=x.persona={...x.datos.personas[1]};x.carteraPorSilla.account=new Set(['a']);const d=dto();assert.equal(get(x,d),null);d.filas=[d.filas[0]];assert.equal(cell(x,get(x,d),['a']).total,4);assert.equal(cell(x,get(x,d),['b']).total,null);});
test('proyección no recicla respuesta tras cambio de actor/source assignment',()=>{const x=ctx(),before=scope(x);x.datos.asignaciones=[{cliente_id:'a',persona_id:'acc',silla:'account'}];assert.equal(project(x,dto(),before),null);});
test('modelo/celda no acepta tampering mes/hash ni scope posterior',()=>{const x=ctx(),mod=get(x,dto()),cel=cell(x,mod,['a']);assert.equal(alive(x,mod,cel),true);mod.periodo='2026-10';assert.equal(cell(x,mod,['a']).total,null);assert.equal(alive(x,mod,cel),false);mod.periodo='2026-09';mod.hash='0'.repeat(64);assert.equal(cell(x,mod,['a']).total,null);});
test('privacidad DTOextra ni persona financiera entra allowlist',()=>{const x=ctx();x.datos.personas[0].salario=987654;x.clientesVisibles[0].equipo.account[0].secreto=456789;const d=dto();d.filas[0].telefono='NO_PRINT';d.importes='NO_PRINT';assert.doesNotMatch(JSON.stringify(get(x,d)),/NO_PRINT|987654|456789/);});
const main=()=>{const b=h('main',{});b.connected=true;return b;};const reads=[],rc=ctx(),box=main();rc.api=async ruta=>{reads.push(ruta);return ruta.startsWith('operaciones/llamadas/historico')?dto():null;};await renderAccounts263(box,rc,'accounts');
test('renderer real columnaSep ytarjeta sin sustituirKPIs7d',()=>{assert.equal(reads.filter(x=>x.startsWith('operaciones/llamadas/historico')).length,1);assert.match(text(box),/Llamadas \(sep2026\)/);assert.match(text(box),/Llamadas · septiembre2026 ≥7 · sep2026/);assert.equal(walk(walk(box).find(x=>x.attrs['data-kpis-proyecto']==='315')).filter(x=>x.tag==='th').length,11);});
const bb=walk(box).find(x=>x.tag==='button'&&x.attrs['aria-label']?.startsWith('Llamadas históricas · cartera actual'));
test('click real describe histórico no actividad account actual',()=>{bb.events.click();assert.match(text(box),/Actor y dirección desconocidos/);assert.match(text(box),/No mide esta semana ni octubre/);});
test('click real tras revocar ACT no mantiene detalle ni cifra',()=>{rc.clientesVisibles[0].activo_confirmado=false;bb.events.click();assert.doesNotMatch(text(box),/≥7 · sep2026|Actor y dirección desconocidos/);});
let finish;const late=ctx(),lb=main();late.api=async ruta=>ruta.startsWith('operaciones/llamadas/historico')?new Promise(r=>finish=r):null;const wait=renderAccounts263(lb,late,'clientes');while(!finish)await new Promise(r=>setImmediate(r));late.veModulo=()=>false;finish(dto());await wait;
test('respuesta tardía tras negar módulos no pinta dato histórico',()=>assert.doesNotMatch(text(lb),/≥4 · sep2026/));
const ac=ctx(),ab=main();ac.real=ac.persona={...ac.datos.personas[1]};ac.carteraPorSilla.account=new Set(['a']);ac.api=async ruta=>ruta.startsWith('operaciones/llamadas/historico')?{...dto(),filas:[row('a',4)]}:null;await renderAccounts263(ab,ac,'clientes');
test('renderer Account sólo propia una fila conocida',()=>{assert.match(text(ab),/≥4 · sep2026/);const tbody=walk(ab).find(x=>x.tag==='tbody');assert.equal(tbody.children.length,1);});
const den=ctx();den.veModulo=mod=>mod!=='bandeja';let requests=0;den.api=async ruta=>{if(ruta.startsWith('operaciones/llamadas/historico'))requests++;return null;};await renderAccounts263(main(),den,'clientes');
test('sin Bandeja no consulta histórico y nozero',()=>assert.equal(requests,0));
test('helper sólolectura sin financieros/proveedor/POST',()=>assert.doesNotMatch(fs.readFileSync(path.join(mod,'_llamadas_historicas_353.js'),'utf8'),/fetch\(|ctx\.accion|POST|cuota|salario|ctx\.api/));
console.log(n+' grupos353 PASS · helper y renderer263 actuales sin negocioPOST');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
