const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.events={};this.isConnected=true;}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){this.children.push(x);if(x instanceof N)x.parentNode=this;}}replaceChildren(...xs){this.children=[];this.append(...xs);}setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);}getAttribute(k){return this.attrs[k];}set textContent(v){this.children=[String(v)];}addEventListener(k,f){this.events[k]=f;}}
const b={Date,Intl,Map,Set,Promise,Node:N,document:{createElement:t=>new N(t),createTextNode:t=>String(t)}};vm.createContext(b);const s=fs.readFileSync(__dirname+'/modulos/_badges_operaciones_311.js','utf8').replace(/export /g,'');vm.runInContext(s+';Object.assign(this,{contadoresOperaciones311,ambitoBadges311,iniciarBadges311,CONTADORES_ORIGINALES311});',b);
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function urlSegura('),comp.indexOf('export function h(')).replace('export ',''),b);vm.runInContext(comp.slice(comp.indexOf('export function h('),comp.indexOf('const svgNS =')).replace('export ',''),b);
const ctx=()=>({hoy:'2026-10-03',servidor:true,real:{id:'ops',estado:'activo',puestos:['operaciones']},persona:{id:'ops',estado:'activo',puestos:['operaciones']},clientesVisibles:[{id:'c',activo_confirmado:true,detalle:true,equipo:{account:[{principal:true,confianza:'alta',persona_id:'a'}]}}],datos:{personas:[{id:'a',estado:'activo'}],meta:{construido:'2026-10-03T10:00:00Z'},alarmas:[{id:'r1',cliente_id:'c',gravedad:'rojo'}]},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true});
const docs=()=>({portal:{_meta:{generado:'2026-10-03'},filas:[{cliente_id:'c'},{cliente_id:'ajeno'}]},nuevos:{hoy:'2026-10-03',generado:'2026-10-03T10:00:00Z',altas:[{cliente_id:'c',alta:'2026-09-30'}]},produccion:{hoy:'2026-10-03',fuentes:{tareas:{hora:'2026-10-03T10:00:00Z'}},revisiones:[{id:'r',cliente_id:'c',estado_determinado:true,revisa:'account',mas48:true,dias:3}]}});
const all=(el,p)=>[...(el instanceof N&&p(el)?[el]:[]),...(el instanceof N?el.children.flatMap(x=>all(x,p)):[])];
const ops=fs.readFileSync(__dirname+'/modulos/operaciones.js','utf8').replace(/^import .*;\n/gm,'').replace(/export default /,'this.ops=').replace(/export /g,'').replace(/await import\(/g,'await importar311(');b.plegarConsejo=()=>{};b.vacio=()=>new N('vacio');b.importar311=async()=>({renderBandeja270:async el=>el.append('Contenido principal disponible')});vm.runInContext(ops,b);
let n=0;const test=async(l,f)=>{await f();n++;};
(async()=>{
 await test('13 contadores exactos original,4tabsnoinventado',()=>{const ref=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8');const a=ref.slice(ref.indexOf('const TABS=['),ref.indexOf('const ORD='));for(const key of b.CONTADORES_ORIGINALES311)assert(a.includes("['"+key+"'"));for(const key of ['equipo','cierre','puesto','repartir'])assert(!b.CONTADORES_ORIGINALES311.includes(key));assert.equal(b.CONTADORES_ORIGINALES311.length,13);});
 await test('Valores acreditados neutros source/periodo sinPII',()=>{const x=b.contadoresOperaciones311(ctx(),docs());for(const key of ['clientes','fichas','accounts','nuevos','hoy','produccion']){assert.equal(x[key].valor,1);assert.equal(x[key].estado,'gris');}assert(x.produccion.detalle.includes('+48h'));assert(x.nuevos.detalle.includes('90d'));assert(!JSON.stringify(x).includes('ajeno'));});
 await test('Ausencia/empty/zeroparcial jamás0verde',()=>{for(const d of [{},{portal:{generado:'2026-10-03',filas:[]},nuevos:{hoy:'2026-10-03',generado:'2026-10-03',altas:[]},produccion:{hoy:'2026-10-03',fuentes:{tareas:{hora:'2026-10-03'}},revisiones:[]}}]){const x=b.contadoresOperaciones311(ctx(),d);for(const key of ['fichas','nuevos','produccion']){assert.equal(x[key].valor,null);assert.equal(x[key].texto,'—');}}});
 await test('Future invalid source yalta noentra',()=>{const d=docs();d.portal._meta.generado='2026-10-04';d.nuevos.altas[0].alta='2026-02-30';d.produccion.fuentes.tareas.hora='2026-10-04';const x=b.contadoresOperaciones311(ctx(),d);for(const k of ['fichas','nuevos','produccion'])assert.equal(x[k].valor,null);});
 await test('Duplicados/foreign/ACT/P noúltimagana',()=>{const c=ctx();c.clientesVisibles.push({...c.clientesVisibles[0]});const x=b.contadoresOperaciones311(c,docs());for(const k of ['clientes','fichas','nuevos','hoy','produccion'])assert.equal(x[k].valor,null);const d=docs();d.produccion.revisiones.push({...d.produccion.revisiones[0]});assert.equal(b.contadoresOperaciones311(ctx(),d).produccion.valor,null);const neg=ctx();neg.ver=()=>({ok:false});assert.equal(b.contadoresOperaciones311(neg,docs()).hoy.valor,null);});
 await test('Edad/stock mixtos nofalso48h; owner conflictunknown',()=>{const d=docs();delete d.produccion.revisiones[0].estado_determinado;assert.equal(b.contadoresOperaciones311(ctx(),d).produccion.valor,null);const c=ctx();c.datos.personas.push({id:'b',estado:'activo'});c.clientesVisibles[0].equipo.account.push({persona_id:'b',principal:true,confianza:'confirmada'});assert.equal(b.contadoresOperaciones311(c,docs()).accounts.valor,null);});
 await test('Read no bloquea y máximo2lecturas concurrentes,3fuentes únicas',async()=>{const c=ctx(),pend=[],paints=[];let vivos=0,max=0;c.datosModulo=p=>{vivos++;max=Math.max(max,vivos);return new Promise(r=>pend.push({p,r:d=>{vivos--;r(d);}}));};const h=b.iniciarBadges311(c,{vigente:()=>true,pintar:d=>paints.push(d)});assert.equal(paints.length,1);assert.equal(pend.length,2);assert.equal(max,2);pend[0].r(docs().portal);await new Promise(setImmediate);assert.equal(pend.length,3);pend[1].r(docs().nuevos);pend[2].r(docs().produccion);await h.promesa;assert.equal(new Set(pend.map(x=>x.p)).size,3);assert.equal(max,2);assert.equal(paints.at(-1).produccion.valor,1);});
 await test('Revocación duranteawait/identidad no oldbadge',async()=>{for(const change of [c=>c.real={id:'otro'},c=>c.persona.puestos=['account'],c=>c.ver=()=>({ok:false}),c=>c.veModulo=()=>false,c=>c.clientesVisibles[0].activo_confirmado=false]){const c=ctx(),pend=[],paints=[];c.datosModulo=()=>new Promise(r=>pend.push(r));const h=b.iniciarBadges311(c,{vigente:()=>true,pintar:d=>paints.push(d)});change(c);for(const r of pend)r(docs().portal);await h.promesa;assert.deepEqual(Object.keys(paints.at(-1)),[]);}});
 await test('Revocación posterior reabrir invalida con actualizar',async()=>{const c=ctx(),p=[];c.datosModulo=async()=>null;const h=b.iniciarBadges311(c,{vigente:()=>true,pintar:d=>p.push(d)});await h.promesa;c.persona={id:'otra'};h.actualizar();assert.deepEqual(Object.keys(p.at(-1)),[]);});
 await test('Errores nofake0; offline/inactivo norequest',async()=>{const c=ctx(),p=[];c.datosModulo=async()=>{throw Error('fixture');};const h=b.iniciarBadges311(c,{vigente:()=>true,pintar:d=>p.push(d)});await h.promesa;assert.equal(p.at(-1).fichas.valor,null);for(const how of ['offline','baja']){const c=ctx();if(how==='offline')c.servidor=false;else c.real.estado='baja';let calls=0;c.datosModulo=async()=>{calls++;return docs();};await b.iniciarBadges311(c,{vigente:()=>true,pintar:()=>{}}).promesa;assert.equal(calls,0);}});
 await test('Shell real13badges/main noawaitfuentes ytoggle revoca',async()=>{const c=ctx(),pend=[],cont=new N('main');c.params=['bandeja'];c.titulo=()=>{};c.navegar=()=>{};c.datosModulo=()=>new Promise(r=>pend.push(r));await b.ops.render(cont,c);assert.equal(pend.length,2);assert.equal(all(cont,x=>x.attrs['data-operaciones-apartado']==='bandeja')[0].children[0],'Contenido principal disponible');assert.equal(all(cont,x=>x.attrs['data-ops-contador']).length,13);const badges=all(cont,x=>x.attrs['data-ops-contador']==='clientes');assert.equal(badges[0].children[0],'1');c.ver=()=>({ok:false});all(cont,x=>x.tag==='details')[0].events.toggle();assert.equal(badges[0].children[0],'—');for(const r of pend)r(null);await new Promise(setImmediate);});
 await test('Fuegos no cuenta clientes rojos ni afirma cero actual',async()=>{const c=ctx();c.verdad=()=>({gravedad:'critico'});let r=b.contadoresOperaciones311(c);assert.equal(r.fuegos.valor,null);assert.equal(r.fuegos.estado,'gris');c.verdad=()=>({gravedad:'bien'});assert.equal(b.contadoresOperaciones311(c).fuegos.valor,null);c.verdad=()=>({gravedad:'critico'});c.veModulo=m=>m!=='en-rojo';assert.equal(b.contadoresOperaciones311(c).fuegos.valor,null);});
 console.log(n+' grupos badges311 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
