const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync('pruebas_revision_captacion_415.cjs','utf8').split('\nconst c={')[0];const outer={require,console,process,__dirname:process.cwd()};vm.createContext(outer);vm.runInContext(base+';globalThis.ENV=e;globalThis.NODE=N;globalThis.H=h;',outer);const e=outer.ENV,N=outer.NODE,h=outer.H;
const src=fs.readFileSync('componentes.js','utf8');vm.runInContext(src.slice(src.indexOf('export function tablaApilable('),src.indexOf('// --------------------------------------------------- contacto:')).replace('export ',''),e);
e.vacio=o=>h('p',{},o.titulo);e.chipsFiltro=o=>h('div',{},o.opciones.map(x=>h('button',{on:{click:()=>o.alCambiar(x.valor)}},x.texto)));
const all=(n,f)=>[...(n instanceof N&&f(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,f)):[])];
let n=0;function test(f){f();n++;}
const cell=x=>x.v,valor=x=>x.v,col={clave:'v',titulo:'Coste registrado 7 d · unidad pendiente',num:true,valor,celda:cell,ordenable:true,minAncho:'100px'},before={...col};
test(()=>{const short=e.cabeceraCompacta421(col);assert.equal(short.titulo,'Coste 7d (ref.)');assert.equal(short.tituloCompleto,col.titulo);for(const k of ['clave','num','valor','celda','ordenable','minAncho'])assert.equal(short[k],col[k]);assert.deepEqual(col,before);});
for(const titulo of ['Leads cualificados 7d','Ventas cerradas 30d','Leads Meta · definición pendiente','Orgánico / Maps','Horas / referencia económica','Coste registrado 7 d · unidad pendiente extra'])test(()=>{const c={titulo,clave:'same'};assert.equal(e.cabeceraCompacta421(c),c);});
test(()=>{const c={...col,tituloCompleto:'Definición original · unidad sin confirmar'};assert.equal(e.cabeceraCompacta421(c).tituloCompleto,c.tituloCompleto);});
for(const tipo of ['tablaDensa','tablaApilable'])test(()=>{const root=e[tipo]({columnas:[col],filas:[{v:0}],porPagina:0});const th=all(root,x=>x.tag==='th')[0],td=all(root,x=>x.tag==='td')[0];assert.equal(th.textContent,'Coste 7d (ref.)');assert.equal(th.attrs.title,col.titulo);assert.equal(th.attrs['aria-label'],col.titulo);if(tipo==='tablaDensa'){const b=all(th,x=>x.tag==='button')[0];assert.equal(b.attrs.title,col.titulo);assert.equal(b.attrs['aria-label'],col.titulo);}assert.equal(td.attrs['data-l'],'Coste 7d (ref.)');assert.equal(td.attrs.title,col.titulo);assert.equal(td.textContent,'0');});
test(()=>{const root=e.tablaDensa({columnas:[col],filas:[{v:2},{v:0},{v:1}],porPagina:0});const b=all(root,x=>x.tag==='th')[0].children[0];b.on.click();assert.deepEqual(all(root,x=>x.tag==='td').map(x=>x.textContent),['2','1','0']);b.on.click();assert.deepEqual(all(root,x=>x.tag==='td').map(x=>x.textContent),['0','1','2']);});
test(()=>{const root=e.tablaDensa({columnas:[col],filas:[{v:0,k:'A'},{v:2,k:'B'}],filtros:[{clave:'k',titulo:'Sin cambios',opciones:['A','B']}],porPagina:0});all(root,x=>x.tag==='button'&&x.textContent==='B')[0].on.click();assert.deepEqual(all(root,x=>x.tag==='td').map(x=>x.textContent),['2']);});
test(()=>{const root=e.tablaApilable({columnas:[{clave:'v',titulo:'Leads cualificados 7d'}],filas:[{v:2}],buscar:{campos:['v']},porPagina:0});assert(all(root,x=>x.tag==='input'&&x.attrs.type==='search').length);assert.equal(all(root,x=>x.tag==='th')[0].textContent,'Leads cualificados 7d');});
test(()=>{let clicks=0;const root=e.tablaApilable({columnas:[col],filas:[{v:1}],alPulsar:()=>clicks++,puedePulsar:()=>false,porPagina:0});assert(!all(root,x=>x.tag==='tr').some(x=>x.events?.click));assert.equal(clicks,0);});
for(const tipo of ['tablaDensa','tablaApilable'])test(()=>{const root=e[tipo]({columnas:[{...col,tituloMovil:'Coste ref.'}],filas:[{v:0}],porPagina:0});const td=all(root,x=>x.tag==='td')[0];assert.equal(td.attrs['data-l'],'Coste ref.');assert.equal(td.attrs.title,col.titulo);assert.equal(td.textContent,'0');});
console.log(n+' grupos421 independientes PASS: componentes reales, semántica/callbacks/columnkeys, metadatos completos y filtros/orden intactos.');
