const fsB=require('node:fs');
const baseB=fsB.readFileSync(__dirname+'/pruebas_tablero_mi_trabajo_181.cjs','utf8').split('const a=')[0];
const srcB=fsB.readFileSync(__dirname+'/pruebas_comentario_durable_366.cjs','utf8');
const fixturesB=srcB.slice(srcB.indexOf("const task={"),srcB.indexOf('\n(async()=>{'));
new Function('require','__dirname',baseB+fixturesB+String.raw`
(async()=>{
await test('LostResponseBodyHeldDuringRepaintAndDoubleClick',async()=>{const e=context(),requests=[];let finish;e.ctx.accion=p=>{requests.push(p);return new Promise((res,rej)=>finish=()=>rej(Error('respuesta perdida')));};let root=c.panelComentario366(e,task,h),txt=field(root),b=button(root);txt.value='Nota estable';const p=b.attrs.on.click();await b.attrs.on.click();assert.equal(requests.length,1);finish();await p;assert.equal(txt.value,'Nota estable');root=c.panelComentario366(e,task,h);e.ctx.accion=async p=>{requests.push(p);return ack(p);};await button(root).attrs.on.click();assert.equal(requests.length,2);assert.equal(requests[0],requests[1]);assert.equal(e.local.length,1);assert.equal(e.local[0].estado,'simulado');assert(!text(root).includes('enviado a ClickUp'));});
await test('NackAndWrongIdNeverEmptyOrLocalEvent',async()=>{for(const responder of [p=>({ok:false,error:'denegado'}),p=>({...ack(p),intencion_guardada:{id:otherUid,accion_id:8,repetida:false}})]){const e=context();e.ctx.accion=async p=>responder(p);const root=c.panelComentario366(e,task,h);field(root).value='Texto conservado';await button(root).attrs.on.click();assert.equal(field(root).value,'Texto conservado');assert.equal(e.local.length,0);assert(text(root).includes('Reintentar la misma intención'));}});
await test('ChangedTaskListAndActorDuringWaitNoLocalAck',async()=>{for(const change of [e=>e.D.tareas[0].lista_id='list-other',e=>e.ctx.real.activo=false,e=>e.ctx.datos.personas.push({...e.ctx.real}),e=>e.ctx.persona.puestos=['seo']]){const e=context(),i=c.prepararComentario366(e,task,'Texto conservado',uid);await c.guardarComentario366(e,task,i,async p=>{change(e);return ack(p);});assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');}});
await test('AuthorizedScopeChangeKeepsOriginalBodyAndUuid',async()=>{const e=context(),requests=[];let count=0;c.crypto={randomUUID:()=>++count===1?uid:otherUid};e.ctx.accion=async p=>{requests.push(p);throw Error('commit realizado respuesta perdida');};let root=c.panelComentario366(e,task,h);field(root).value='Texto idéntico';await button(root).attrs.on.click();e.ctx.real.puestos=['operaciones','seo'];e.ctx.persona.puestos=['operaciones','seo'];root=c.panelComentario366(e,task,h);assert(text(root).includes('Reintentar la misma intención'));await button(root).attrs.on.click();assert.equal(requests[0].texto,requests[1].texto);assert.equal(requests[0].intencion_id,requests[1].intencion_id);assert.equal(requests[0],requests[1]);});
await test('ExplicitInternalClientsAllowedMissingAndCrossClientDenied',async()=>{for(const cli of [null,'']){const e=context(),t={...task,cli};e.D.tareas=e.D.tareas.map(r=>({...r,cli}));e.ctx.clientesVisibles=[];e.ctx.ver=()=>({ok:false});assert(c.ambitoComentario366(e,t));const i=c.prepararComentario366(e,t,'Nota interna',uid);assert.equal(i.payload.cliente_id,null);await c.guardarComentario366(e,t,i,async p=>ack(p));assert(i.recibo);}for(const cli of [undefined,'foreign-client']){const e=context(),t={...task,cli};e.D.tareas=e.D.tareas.map(r=>({...r,cli}));assert.equal(c.ambitoComentario366(e,t),null);}const e=context(),t={...task,cli:null};e.D.tareas[0].cli='';assert.equal(c.ambitoComentario366(e,t),null);});
console.log(casos+' grupos revisión independiente366b PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
