const fs=require('node:fs');
const bands=fs.readFileSync(__dirname+'/pruebas_bandas_horas_381.cjs','utf8');
const historyFixture=bands.slice(bands.indexOf('function dto381('),bands.indexOf('(async()=>{',bands.indexOf('function dto381(')));
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];
new Function('require','__dirname',prefix+'\nconst copy=x=>JSON.parse(JSON.stringify(x));\n'+historyFixture+`
const actor={id:'real',estado:'activo',activo:true,puestos:['operaciones']};
const ctx450=()=>({...make(),servidor:true,real:actor,persona:{...actor},datos:{personas:[actor,{id:'p',estado:'activo',puestos:['seo']}]}});
const money={generado:'2026-10-03 02:56',mes_cuota:'2026-10',clientes:[{cliente_id:'c',cuota_horas:{pautadas:20},cuota:99999}]};
const body=n=>all(n,x=>x.tag==='tbody').map(text).join(' ');
(async()=>{
await test('90d actual renderer days preserves n over natural range',async()=>{const n=new N('main');await c.renderEquipo262(n,ctx381(),'horas');all(n,z=>z.tag==='button'&&text(z)==='Semana pasada')[0].events.click();const row=all(n,z=>z.tag==='tbody')[0].children[0];assert.equal(text(row.children[4]),'4/7 días');assert(row.children[4].children[0].attrs['aria-label'].includes('horas positivas'));assert(row.children[4].children[0].attrs.title.includes('5/7 fechas naturales'));});
await test('person percent numeric title aria reference external',async()=>{const n=new N('main');await c.renderEquipo262(n,make(),'horas');const tb=all(n,x=>x.tag==='tbody')[0];assert(!text(tb).includes('ref.'));assert(text(tb).includes('≥'));const pct=all(tb,x=>x.attrs.class?.includes('oe-observado'))[0];assert(pct.attrs.title.includes('no capacidad contractual'));assert(pct.attrs['aria-label'].includes('8h'));assert(text(n).includes('Referencia8h'));assert(text(n).includes('no jornada ni cumplimiento'));});
await test('legacy days observed count not implied denominator',async()=>{const n=new N('main');await c.renderEquipo262(n,make(),'horas');const row=all(n,x=>x.tag==='tbody')[0].children[0];assert.equal(text(row.children[4]),'1 obs.');const span=row.children[4].children[0];assert(span.attrs['aria-label'].includes('no cobertura completa'));assert(!text(row).includes('muestra /'));});
await test('client authorized pauta exact values and reference outside cells',async()=>{const x=ctx450(),n=new N('main');x.datosModulo=async p=>p==='dinero_cliente/dinero_cliente'?money:docs[p];await c.renderEquipo262(n,x,'horas');all(n,z=>z.tag==='button'&&text(z)==='Este mes')[0].events.click();const row=all(n,z=>z.tag==='tbody')[1].children[0];assert.equal(text(row.children[1]),'5');assert.equal(text(row.children[2]),'1,9 h');assert.equal(text(row.children[3]),'≥262,5 %');assert(!text(row).includes('ref.'));assert(row.children[2].children[0].attrs['aria-label'].includes('no presupuesto contractual'));assert(row.children[3].children[0].attrs.title.includes('no acredita consumo total'));assert(text(n).includes('pauta × laborables /21 de referencia, no presupuesto contractual'));assert(!text(n).includes('99999'));});
await test('revoked financial grant still no payout or ratio',async()=>{const x=ctx450(),n=new N('main');x.ver=o=>({ok:o.tipo!=='horas_pautadas'});x.datosModulo=async p=>p==='dinero_cliente/dinero_cliente'?money:docs[p];await c.renderEquipo262(n,x,'horas');all(n,z=>z.tag==='button'&&text(z)==='Este mes')[0].events.click();assert(!body(n).includes('262,5'));assert(!body(n).includes('1,9 h'));});
await test('unknown remains neutral not 0 percent',async()=>{const n=new N('main'),x=make();x.datosModulo=async p=>p==='horas/horas'?{...H,personas:[{persona_id:'p',nombre:'P'}]}:docs[p];await c.renderEquipo262(n,x,'horas');assert(!body(n).includes('0 %'));assert(!body(n).includes('obs.'));});
await test('current month and past-month mismatch no inferred reference ratio',async()=>{const n=new N('main'),x=ctx450();x.datosModulo=async p=>p==='dinero_cliente/dinero_cliente'?{...money,mes_cuota:'2026-09'}:docs[p];await c.renderEquipo262(n,x,'horas');all(n,z=>z.tag==='button'&&text(z)==='Este mes')[0].events.click();assert(!text(all(n,z=>z.tag==='tbody')[1]).includes('%'));});
console.log(checks+' grupos450 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
