const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const box={Date,Intl,Map,Set,Number,Object,fmt:{num:n=>String(n),pct:n=>String(n)+'%'},hoyMadrid:()=> '2026-10-03',REGLAS:{},FECHAS:{}};vm.createContext(box);
for(const [file,names] of [['_meta_semantica_285','semanticaMeta285'],['_paid_mediciones','normalizarPaid,medirCplPaid'],['_crm_mediciones','normalizarFilaCRM,medirEmbudoCRM'],['_resultados_dia_314','clientesDia314,crmDia314'],['_crm_secundario_317','secundariosCRM317,textoConteo317,referenciaAlta317']]){const s=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${names}})})()`,box);}
const fuente=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${fuente};this.BLOQUES=BLOQUES;this.NUMERO=NUMERO;})()`,box);
const ctx=()=>({hoy:'2026-10-03',clientesVisibles:[{id:'c',activo_confirmado:true},{id:'d',activo_confirmado:true}],datos:{personas:[{id:'e',estado:'activo',nombre:'Fixture'}]},ver:()=>({ok:true})});
const crm=()=>({fuentes:{ghl:{hora:'2026-10-03T08:00:00Z',estado:'bien'}},resumen:{asistencia_pct:99,velocidad_pct_1h:100,despachos_cumplen_garantia:99},especialistas:[{id:'other',nombre:'AJENO',rojo:99,verde:0}],subcuentas:[{cliente_id:'c',tipo:'cliente',especialista_id:'e',citas_30d:{agendadas:6,celebradas:2,no_presentadas:2,sin_estado:2},citas_14d:{sin_estado:1},sin_tocar_24h:0,velocidad:{juzgables:4,en_1h:1}}]});
const D=x=>({dato:()=>x,opcional:()=>null});let n=0;function test(l,f){f();n++;}

test('Número principal no aggregate99/null ni objetivosgreen',()=>{const c=crm();c.reglas={verde_crm:'asistencia≥75%'};const r=box.NUMERO.crm_verde.hacer(ctx(),D(c));assert.equal(r.valor,'1');assert.equal(r.estado,'gris');assert(r.unidad.includes('1 autorizadas'));assert(!r.contexto.includes('75'));assert(!JSON.stringify(r).includes('null'));assert(!JSON.stringify(r).includes('99'));});
test('Fuente vieja/vacía no0fake desempeño',()=>{for(const mode of ['old','empty','future','error']){const c=crm();if(mode==='old')c.fuentes.ghl.hora='2026-09-01';if(mode==='empty')c.subcuentas=[];if(mode==='future')c.fuentes.ghl.hora='2026-10-04';if(mode==='error')c.fuentes.ghl.error='fixture';const r=box.NUMERO.crm_verde.hacer(ctx(),D(c));assert.equal(r.valor,null);assert.equal(r.estado,'gris');assert(!r.contexto.includes('en rojo'));}});
test('Scope ACT grant duplicates and foreign withoutglobalfallback',()=>{for(const mode of ['ACT','grant','duplicate','foreign']){const x=ctx(),c=crm();if(mode==='ACT')x.clientesVisibles[0].activo_confirmado=false;if(mode==='grant')x.ver=()=>({ok:false});if(mode==='duplicate')c.subcuentas.push({...c.subcuentas[0]});if(mode==='foreign')c.subcuentas[0].cliente_id='foreign';assert.equal(box.NUMERO.crm_verde.hacer(x,D(c)).valor,null);}});
test('Asistenciamia samebase exactown no 75/60performance',()=>{const x=ctx();x.persona={id:'e'};const c=crm();c.subcuentas.push({...c.subcuentas[0],cliente_id:'d',especialista_id:'other',citas_30d:{celebradas:100,no_presentadas:0}});const r=box.NUMERO.asistencia_mia.hacer(x,D(c));assert.equal(r.valor,'50%');assert.equal(r.estado,'gris');assert(r.unidad.includes('4 citas'));assert(r.contexto.includes('1 autorizadas'));});
test('Asistencia missingcounterpart or zero denominator unknown',()=>{const x=ctx();x.persona={id:'e'};for(const counts of [{celebradas:0,no_presentadas:0},{celebradas:4}]){const c=crm();c.subcuentas[0].citas_30d=counts;const r=box.NUMERO.asistencia_mia.hacer(x,D(c));assert.equal(r.valor,null);assert.equal(r.estado,'gris');assert(!r.contexto.includes('Sin citas'));}});
test('0% observed conserva neutral unlike missing',()=>{const x=ctx();x.persona={id:'e'};const c=crm();c.subcuentas[0].citas_30d={celebradas:0,no_presentadas:2};const r=box.NUMERO.asistencia_mia.hacer(x,D(c));assert.equal(r.valor,'0%');assert.equal(r.estado,'gris');});
console.log(n+' grupos númeroCRM319 PASS');
