const fs368=require('node:fs'),path368=require('node:path');
const b=fs368.readFileSync(path368.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
const src=fs368.readFileSync(path368.join(__dirname,'pruebas_historial_diario_364.cjs'),'utf8');
const f=src.slice(src.indexOf('const copy=x=>'),src.indexOf('\n(async()=>{'));
new Function('require','__dirname',b+f+`
(async()=>{
 await test('Mixed2hZeroSepDaysPositiveOnly',()=>{const s=model().series.get('p'),m=c.horasHistorialRango364(s,{desde:'2026-09-01',hasta:'2026-09-30'});assert.equal(m.valor,2);assert.equal(m.dias,1);assert.equal(m.fechas_con_registros,2);assert.equal(m.ultima,'2026-09-02');assert.equal(m.total_dias,30);assert(m.detalle.includes('2/30 fechas naturales con registros'));});
 await test('All90ZeroStillExplicitObservedNoPositiveDays',()=>{const d=dto364();for(const day of d.personas[0].historial_diario.dias)Object.assign(day,{horas:0,entradas:1,estado:'observado'});const s=model(ctx364(),d).series.get('p'),m=c.horasHistorialRango364(s,{desde:s.desde,hasta:s.hasta});assert.equal(m.valor,0);assert.equal(m.dias,0);assert.equal(m.fechas_con_registros,90);assert.equal(m.total_dias,90);assert.equal(m.ultima,s.hasta);assert.equal(m.parcial,true);});
 await test('TinyPositiveDurationNeverLosesPositiveDay',()=>{const d=dto364(),day=d.personas[0].historial_diario.dias.find(x=>x.fecha==='2026-09-01');day.horas=Number.MIN_VALUE;const s=model(ctx364(),d).series.get('p'),m=c.horasHistorialRango364(s,{desde:day.fecha,hasta:day.fecha});assert.equal(m.valor,Number.MIN_VALUE);assert.equal(m.dias,1);assert.equal(m.fechas_con_registros,1);});
 await test('Outside90dRetainsNaturalCoverageNoInventedZero',()=>{const s=model().series.get('p'),m=c.horasHistorialRango364(s,{desde:'2026-06-01',hasta:'2026-09-30'});assert.equal(m.valor,2);assert.equal(m.dias,1);assert.equal(m.fechas_con_registros,2);assert.equal(m.total_dias,122);assert.equal(m.fuera_ventana,true);const none=c.horasHistorialRango364(s,{desde:'2026-06-01',hasta:'2026-06-30'});assert.equal(none.valor,null);assert.equal(none.dias,null);assert.equal(none.fechas_con_registros,null);assert.equal(none.ultima,null);});
 await test('RealRendererMonthDays1VersusCoverage2NoGreen',async()=>{const ctx=ctx364(),n=new N('main');await c.renderEquipo262(n,ctx,'horas');all(n,x=>x.tag==='button'&&text(x)==='Mes pasado')[0].events.click();const table=all(n,x=>x.tag==='table')[0],cells=all(table,x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(cells[4]),'1/30 días');assert(cells[4].children[0].attrs.title.includes('2/30 fechas naturales con registros'));assert.equal(text(cells[1]),'≥2');assert.equal(text(cells[5]),'2026-09-02');assert.equal(all(table,x=>x.tag==='th').length,6);assert(!all(n,x=>/ref-(verde|rojo)/.test(x.attrs.class||'')).length);});
 await test('RenderAllZerosVersusUnknownBothDifferent',async()=>{for(const observed of [true,false]){const ctx=ctx364(),d=dto364();for(const day of d.personas[0].historial_diario.dias)Object.assign(day,{horas:observed?0:null,entradas:observed?1:null,estado:observed?'observado':'sin_dato'});ctx.api=async()=>d;const n=new N('main');await c.renderEquipo262(n,ctx,'horas');all(n,x=>x.tag==='button'&&text(x)==='Mes pasado')[0].events.click();const cells=all(all(n,x=>x.tag==='table')[0],x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(cells[1]),observed?'≥0':'—');assert.equal(text(cells[4]),observed?'0/30 días':'—');assert.equal(text(cells[5]),observed?'2026-09-30':'—');assert(!all(n,x=>/ref-(verde|rojo)/.test(x.attrs.class||'')).length);}});
 await test('TinyRealFormatRangeAndDailyNeverZero',async()=>{const ctx=ctx364(),d=dto364();for(const day of d.personas[0].historial_diario.dias)Object.assign(day,{horas:null,entradas:null,estado:'sin_dato'});Object.assign(d.personas[0].historial_diario.dias.find(x=>x.fecha==='2026-10-02'),{horas:0.0005,entradas:1,estado:'observado'});ctx.api=async()=>d;let n=new N('main');await c.renderEquipo262(n,ctx,'horas');const cells=all(all(n,x=>x.tag==='table')[0],x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(cells[1]),'<0,1');assert(cells[1].children[0].attrs.title.includes('Suma observada 0.0005 h'));assert.equal(text(cells[4]),'1/6 días');n=new N('main');await c.renderEquipo262(n,ctx,'equipo-dia');const td=all(all(n,x=>x.tag==='table')[0],x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(td[6]),'<0,1');assert(!text(td[6]).includes('≥0'));});
 console.log(checks+' grupos independientes368 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
