const fs=require('fs');const base=fs.readFileSync(__dirname+'/pruebas_urgencias_406.cjs','utf8').split('let n=0;')[0];
const extra=String.raw`
(async()=>{
let groups=0;const check=async(name,fn)=>{await fn();groups++;console.log('PASS '+name);};
function pair(a,b){const d=dto();d.filas=[{...row,titulo:'Título primero',titulo_estado:'observado_saneado',titulo_fuente:'clickup_cache_local',titulo_leido_utc:a,estado_leido_utc:a},{...row,tarea_id:'t2',titulo:'Título segundo',titulo_estado:'observado_saneado',titulo_fuente:'clickup_cache_local',titulo_leido_utc:b,estado_leido_utc:b}];d.abiertas_en_copia=2;d.observaciones=2;d.lectura_desde_utc=a;d.lectura_hasta_utc=b;return d;}
async function mount(d){const c=ctx(),root=new N('main');let calls=0;c.api=async()=>{calls++;return d;};await box.renderUrgencias406(root,c);all(root,x=>x.tag==='button')[0]?.events.click();return {c,root,calls,detail:all(root,x=>x.attrs['aria-label']==='Urgencias del cliente')[0]};}
await check('Sello común íntegro y ambos títulos/IDs/enlaces',async()=>{const a='2026-10-03T13:00:00.123456Z',m=await mount(pair(a,a));assert.equal(all(m.detail,x=>x.tag==='th').length,3);assert.equal(all(m.detail,x=>x.tag==='tr').length,3);assert(all(m.detail,x=>x.tag==='p'&&x.attrs.title?.includes(a)).length===1);for(const t of ['Título primero','Título segundo','t1','t2','Madrid'])assert(m.detail.textContent.includes(t));assert.deepEqual(all(m.detail,x=>x.tag==='a').map(x=>x.attrs.href),['https://app.clickup.com/t/t1','https://app.clickup.com/t/t2']);assert.equal(m.calls,1);assert(m.root.textContent.includes('Fuegos actuales: por confirmar'));});
await check('Instantes distintos visibles sin perder fulltimestamp',async()=>{const a='2026-10-03T13:00:00Z',b='2026-10-03T13:00:01Z',m=await mount(pair(a,b));assert.equal(all(m.detail,x=>x.tag==='th').length,4);assert.deepEqual(all(m.detail,x=>x.tag==='td'&&x.attrs.title).map(x=>x.attrs.title),[a,b]);});
await check('Fechas inválidas/lectura posterior al corte rechazan sin datos',async()=>{for(const t of ['2026-02-30T13:00:00Z','2026-10-03T13:00:00+02:99','2026-10-05T00:00:00Z']){const m=await mount(pair(t,t));assert.equal(m.detail,undefined);assert(m.root.textContent.includes('Falta una lectura válida'));assert(!m.root.textContent.includes('Título primero'));}});
await check('Fuente inválida no revive filas',async()=>{const d=pair(row.estado_leido_utc,row.estado_leido_utc);d.fuente='otra';const m=await mount(d);assert(!m.detail);assert(!m.root.textContent.includes('Título primero'));});
await check('Scope revocado en filtro/detalle/enlace cancela y limpia',async()=>{for(const mode of ['filter','detail','link']){const m=await mount(pair(row.estado_leido_utc,row.estado_leido_utc));m.c.clientes[0].activo_confirmado=false;if(mode==='filter')all(m.root,x=>x.tag==='input')[0].events.input();if(mode==='detail')all(m.root,x=>x.tag==='button')[0].events.click();if(mode==='link'){let prevented=false;all(m.detail,x=>x.tag==='a')[0].events.click({preventDefault(){prevented=true;}});assert(prevented);}assert.equal(m.root.textContent,'');}});
await check('FIX P2: microsegundos distintos conservan ambos sellos',async()=>{const a='2026-10-03T13:00:00.000001Z',b='2026-10-03T13:00:00.000002Z',m=await mount(pair(a,b));assert.equal(all(m.detail,x=>x.tag==='th').length,4);assert.equal(all(m.detail,x=>x.attrs.title===a).length,1);assert.equal(all(m.detail,x=>x.attrs.title===b).length,1);assert.equal(all(m.detail,x=>x.tag==='a').length,2);});
await check('UTC sin fracción equivale a fracción cero sin duplicar sello',async()=>{const m=await mount(pair('2026-10-03T13:00:00Z','2026-10-03T13:00:00.000000Z'));assert.equal(all(m.detail,x=>x.tag==='th').length,3);assert.equal(all(m.detail,x=>x.tag==='a').length,2);});
console.log(groups+' grupos505 PASS · incluye corrección P2 independiente');
})().catch(e=>{console.error(e);process.exitCode=1;});`;
new Function('require','__dirname',base+extra)(require,__dirname);
