const fs=require('fs'),vm=require('vm'),assert=require('assert');
class N {constructor(tag,attrs={},children=[]){this.tag=tag;this.attrs=attrs;this.children=[];this.isConnected=true;this.append(...children);}append(...xs){for(const x of xs.flat(Infinity))if(x!==null&&x!==undefined&&x!==false)this.children.push(x);}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}addEventListener(){}replaceChildren(...xs){this.children=[];this.append(...xs);}get lastElementChild(){return this.children.filter(x=>x instanceof N).at(-1);}}
const h=(tag,attrs={},...children)=>new N(tag,attrs,children);
const box={Node:N,h,console,Date,Number,Map,Set,MutationObserver:class{observe(){}},fmt:{num:String},limpiaTexto:x=>x,icono:()=>h('i'),infoCompacta:o=>h('details',{},o.contexto),frescura:()=>h('small'),selloMedible:()=>h('small'),tiles:a=>h('div',{class:'tiles'},a),panel:(o,...xs)=>h('section',{},o.titulo,...xs),listaLoPrimero:(rows,o)=>h('div',{},rows.length?rows.map(x=>x.motivo):[o.vacio.titulo,o.vacio.porque]),filasFlexibles:x=>x,vacio:o=>h('div',{},o.titulo,o.texto),selectorCliente:()=>h('select'),chipEstado:(c,t)=>h('span',{class:c},t),logoCliente:()=>h('img'),iniciales:()=>'',panelPlanFuego255:()=>h('aside'),consejoCompacto:()=>{},lineaTiempo:()=>h('div'),botonDeshacer:()=>h('button'),barraEtapas:()=>h('div')};
const comps=fs.readFileSync('componentes.js','utf8');const tile=comps.slice(comps.indexOf('export function tile('),comps.indexOf('/** tiles([...])')).replace('export function','function');
vm.createContext(box);vm.runInContext(tile,box);
const src=fs.readFileSync('modulos/en_rojo.js','utf8').replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"];?/gm,'').replace('export default {','globalThis.modulo={').replace(/export function /g,'function ');
vm.runInContext(src,box);
let passed=0;const check=(f)=>{f();passed++;};
const meta={version:'290.1',estado:'medido',fecha_evaluacion:'2026-10-03',desde:'2026-09-26',hasta:'2026-10-02',tipo_evento:'lead',eventos_lead:0,fuente:'meta_insights',cohorte_crm_confirmada:false};
for(const value of [null,0,false,'0',NaN,-1])check(()=>{const a=box.contadoresMetaCrm290({leads_meta_7d:value,leads_ghl_7d:value},'2026-10-03');for(const t of a){assert(t.textContent.includes('Sin dato'));assert(t.attrs.class.includes('gris'));assert(!/verde|rojo/.test(t.attrs.class));}});
check(()=>{const a=box.contadoresMetaCrm290({leads_meta_7d:203,leads_ghl_7d:2},'2026-10-03');assert(a[0].textContent.includes('203'));assert(a[1].textContent.includes('2'));assert(a[0].textContent.includes('unidad y periodo pendientes'));assert(!a.some(t=>t.attrs.class.includes('verde')));assert(!a.some(t=>t.textContent.includes('GHL de Meta')));});
check(()=>{const a=box.contadoresMetaCrm290({meta_medicion_290:meta,leads_ghl_7d:0},'2026-10-03');assert(a[0].textContent.includes('Eventos lead Meta'));assert(!a[0].textContent.includes('Sin dato'));assert(a[0].textContent.includes('0'));assert(a[1].textContent.includes('Sin dato'));assert(!a[0].attrs.class.includes('verde'));});
for(const patch of [{fecha_evaluacion:'2026-10-04'},{hasta:'2026-09-30'},{tipo_evento:'purchase'},{eventos_lead:false},{fuente:'legacy'},{cohorte_crm_confirmada:true},{desde:'2026-02-30'}])check(()=>{assert(box.contadoresMetaCrm290({meta_medicion_290:{...meta,...patch}},'2026-10-03')[0].textContent.includes('Sin dato'));});
const ctxFor=(v,detail=true)=>({hoy:'2026-10-03',real:{id:'actor'},persona:{id:'actor'},vigente:()=>true,clientes:[{id:'fixture',nombre:'Cliente sintético',detalle:detail}],clientesVisibles:[],params:['fixture'],datos:{meta:{fuentes:[]}},datosModulo:async()=>({filas:[]}),verdad:()=>v,titulo:()=>{},nombre:()=>'',veModulo:()=>false,soloLectura:false});
(async()=>{
 const base={gravedad:'sin_dato',motivos:[],leads_meta_7d:0,leads_ghl_7d:0,salud:null};
 const cont=new N('main');await box.pintarDetalle(cont,ctxFor(base),'fixture');const text=cont.textContent;assert(text.includes('Resultados Meta · 7 días'));assert(text.includes('Contador CRM · 7 días'));assert(!text.includes('GHL de Meta'));assert(text.includes('Sin puntuación acreditada'));assert(text.includes('Sin señales acreditadas en esta copia'));assert(!text.includes('Este cliente está bien'));passed++;
 const legacy=new N('main');await box.pintarDetalle(legacy,ctxFor({...base,salud:100}),'fixture');assert(legacy.textContent.includes('Referencia provisional de una copia anterior'));passed++;
 const denied=new N('main');await box.pintarDetalle(denied,ctxFor({...base,leads_meta_7d:321},false),'fixture');assert(denied.textContent.includes('El detalle de este cliente no es de tu puesto'));assert(!denied.textContent.includes('321'));passed++;
 const stale=new N('main'),ctx=ctxFor(base);ctx.vigente=()=>false;await box.pintarDetalle(stale,ctx,'fixture');assert.equal(stale.children.length,0);passed++;
 const list=new N('main'),lc=ctxFor(base);let title='';lc.persona.puestos=['direccion'];lc.carteraIds=new Set();lc.verdadComun=()=>[{id:'fixture',nombre:'Cliente sintético',gravedad:'sin_dato',n_motivos:0}];lc.datos.alarmas=[];lc.titulo=(_,s)=>title=s;box.chipsFiltro=o=>{const n=h('nav',{},o.opciones.map(x=>x.texto));n.valor=()=>'';return n;};box.tablaDensa=o=>h('table',{},o.filas.map(f=>o.columnas.map(c=>c.celda(f))));box.candado=()=>h('span');await box.pintarLista(list,lc);assert(title.includes('1 por confirmar'));assert(list.textContent.includes('Por confirmar'));assert(list.textContent.includes('Sin dato'));assert(list.textContent.includes('Sin señales críticas en esta copia'));passed++;
 console.log(`${passed} grupos PASS: funciones y detalle reales, componente tile real; DOM sintético, sin proveedor.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
