const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');let n=0;const check=(t,f)=>{f();n++;console.log('PASS',t)};
const node=(tag,attrs={},...children)=>({tag,attrs,style:{},children:children.flat(Infinity).filter(x=>x!=null),append(...xs){this.children.push(...xs.flat(Infinity))},replaceChildren(...xs){this.children=xs.flat(Infinity)},querySelectorAll(){return[]},addEventListener(){}});const walk=x=>x&&typeof x==='object'?[x,...(x.children||[]).flatMap(walk)]:[];const text=x=>typeof x==='object'?(x.children||[]).map(text).join(' '):String(x??'');
function load(name,symbol){const source=fs.readFileSync(path.join(__dirname,'modulos',name+'.js'),'utf8');const context={Set,Map,Date,Math,Intl,document:{getElementById:()=>null},h:node,fmt:{num:n=>n==null?'—':String(n),pct:n=>n==null?'—':n+'%',plural:(n,a,b)=>`${n} ${n===1?a:b}`,hace:()=>''},panel:(cfg,...xs)=>node('panel',{cfg},xs),vacio:cfg=>node('vacio',{cfg},cfg.titulo,cfg.texto),vacioLinea:(t,cfg)=>node('vaciolinea',{cfg},t),listaLoPrimero:(rows,cfg)=>node('primero',{rows,cfg}),filasFlexibles:x=>x,tiles:xs=>node('tiles',{},xs),tile:cfg=>node('tile',{cfg}),rejillaTarjetas:xs=>node('tiles',{},xs),chipsFiltro:cfg=>({...node('chips',{cfg}),valor:()=>''}),tablaDensa:cfg=>node('tabla',{cfg}),pantallaAncha:cfg=>node('pantalla',{},cfg.lista,...cfg.contexto),franjaCifras:rows=>node('franja',{rows}),franjaEnLinea:x=>x,semaforo:n=>n==null?'gris':n>=100?'verde':'rojo',chipEstado:(e,t)=>node('chip',{estado:e},t),botonConfirmar:cfg=>node('boton',{cfg})};for(const m of source.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"][^'"]+['"];?/g))for(const name of m[1].split(',').map(x=>x.trim()).filter(Boolean))if(!(name in context))context[name]=()=>null;let code=source.replace(/import\s*\{[^}]+\}\s*from\s*['"][^'"]+['"];?/g,'').replace(/export default/g,'const moduloEvaluado =').replace(/export (?:async )?function/g,m=>m.includes('async')?'async function':'function').replace(/export const/g,'const');vm.runInNewContext(code+`;globalThis.run=${symbol};`,context);return context.run}
const inc=load('incidencias','pintarIncongruencias');const S=D=>({ctx:{nivel:'suyo',soloLectura:true,persona:{puestos:['account']}},D,porObjeto:new Map(),nom:id=>id,cli:new Map()});let root=node('main');inc(root,S({incongruencias:[],accesos:[]}));
check('render vacío incongruencias no concordancia falsa',()=>{assert.match(text(root),/No confirma/);assert.doesNotMatch(text(root),/dicen lo mismo|cuadran con la tabla|Nadie que se haya ido conserva acceso/);assert.ok(walk(root).filter(x=>x.tag==='vacio').every(x=>x.attrs.cfg.tono==='neutro'))});
check('render accesos vacío no inventario completo',()=>assert.match(text(root),/No acredita inventario completo/));
root=node('main');inc(root,S({incongruencias:[],accesos:[{id:'a',persona:'Fixture',herramienta:'ClickUp',estado_herramienta:'activo',que_hacer:'Revisar',ok:false}]}));check('observación acceso activo mantiene rojo',()=>assert.equal(walk(root).find(x=>x.tag==='primero').attrs.rows[0].estado,'rojo'));
root=node('main');inc(root,S({incongruencias:[{id:'i',tipo:'Tipo fixture',cliente:'Fixture',detalle:'Observación'}],accesos:[]}));check('filas incongruencia reales conservadas',()=>assert.equal(walk(root).find(x=>x.tag==='tabla').attrs.cfg.filas.length,1));
const redes=load('redes','pintarPortada'),ctx={persona:{id:'p',puestos:['direccion']},nivel:'todo',soloLectura:true,clientes:[],hoy:'2026-10-03',titulo:()=>{},nombre:id=>id};const data=clientes=>({_meta:{ventana:['2026-10-03','2026-10-16'],leido_metricool:'2026-10-03',medicion:{}},clientes,sin_metricool:[],por_persona:[]});root=node('main');redes(root,ctx,data([]));
check('render Redes vacío no todos cubiertos',()=>{const p=walk(root).find(x=>x.tag==='primero');assert.equal(p.attrs.cfg.vacio.celebrar,false);assert.match(p.attrs.cfg.vacio.porque,/no acredita/)});
check('Redes sin inventario tarjetas unknown no verdes',()=>{const ts=walk(root).filter(x=>x.tag==='tile');for(const label of ['Hueco en 7 días','Fallidas · 7 días','Por aprobar']){const t=ts.find(x=>x.attrs.cfg.etiqueta===label);assert.equal(t.attrs.cfg.valor,null);assert.equal(t.attrs.cfg.estado,'gris')}});
const row={cliente_id:'c',cliente:'Fixture',redes_id:'p',estado_14:'verde',huecos:[],fallidas:[],calendario:[],por_red:{},fallidas_7:0,borradores:0,programadas_14:2,publicadas_30:1,pasadas_30:1};root=node('main');redes(root,ctx,data([row]));check('Redes observaciones positivas mantienen semáforo',()=>{const ts=walk(root).filter(x=>x.tag==='tile');assert.equal(ts.find(x=>x.attrs.cfg.etiqueta==='14 días cubiertos').attrs.cfg.estado,'verde');assert.equal(ts.find(x=>x.attrs.cfg.etiqueta==='Hueco en 7 días').attrs.cfg.valor,0)});
root=node('main');redes(root,ctx,data([{...row,estado_14:'rojo',huecos:[{en_7:true,desde:'2026-10-03',hasta:'2026-10-05',dias:3}]}]));check('Redes hueco observado mantiene señal roja',()=>assert.equal(walk(root).find(x=>x.tag==='tile'&&x.attrs.cfg.etiqueta==='Hueco en 7 días').attrs.cfg.estado,'rojo'));
console.log(n+' grupos PASS, renderizadores reales sin proveedor ni acciones.');
