const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(tag){this.tag=tag;this.children=[];this.style={};this.isConnected=true;}append(...x){this.children.push(...x.filter(v=>v!=null));}replaceChildren(...x){this.children=x;}setAttribute(){}addEventListener(){}}
const b={Date,Intl,Map,Set,WeakSet,Node:N,document:{createElement:t=>new N(t),createTextNode:t=>t},ID:'reuniones',vigilarCortes:()=>{},vacio:()=>new N('vacio')};vm.createContext(b);
for(const file of ['_metodo_cohorte_305.js','_cadencia_metodo.js']){const s=fs.readFileSync(__dirname+'/modulos/'+file,'utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${file.startsWith('_metodo')?'proyectarMetodo305':'separarCadencias,textoCadencia,estadoCadencia,ambitoCadencia307'}})})()`,b);}
const helper453=fs.readFileSync(__dirname+'/modulos/_seguimiento_metodo_453.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${helper453};Object.assign(this,{ambitoSeguimiento453,pintarSeguimiento453})})()`,b);
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function h('),comp.indexOf('const svgNS =')).replace('export ',''),b);
const src=fs.readFileSync(__dirname+'/modulos/reuniones.js','utf8');vm.runInContext(src.slice(src.indexOf('function juntar('),src.indexOf('// ===================================================================== render')),b);vm.runInContext(src.slice(src.indexOf('export default {'),src.indexOf('// ===================================================================== pantalla')).replace('export default','this.modulo='),b);
const row=()=>({cliente_id:'c',regla_id:'seguimiento_quincenal_especialista',cadencia_dias:15,responsable_role:'trafficker',estado:'en_cadencia',incumplimiento:null,responsables_ids:['t'],responsable_id:'t',ultima_confirmada:'2026-09-25',proxima_revision:'2026-10-10',fuentes_operativas:[{tipo:'reunion_celebrada',fecha:'2026-09-25'}]});
const doc=()=>({hoy:'2026-10-03',sugerencias:[row()],cobertura_reuniones:{completa:false}});
const ctx=()=>({hoy:'2026-10-03',real:{id:'real',estado:'activo',puestos:['operaciones']},persona:{id:'real',estado:'activo',puestos:['operaciones']},servidor:true,clientes:[{id:'c',activo_confirmado:true,detalle:true}],clientesVisibles:[{id:'c',activo_confirmado:true,detalle:true}],datos:{personas:[{id:'t',estado:'activo',puestos:['trafficker']},{id:'real',estado:'activo',puestos:['operaciones']}]},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,datosModulo:async()=>({asistencias:[],clientes:[{cliente_id:'c',estado:'sin_reunion'}]}),api:async p=>p==='metodo/sugerencias'?doc():{acciones:[]}});
let paints=[],checks=0;b.pintar=(n,c,s)=>paints.push(b.separarCadencias(s.D.clientes,s.firmaMetodo307===b.ambitoCadencia307(c).firma?s.metodo:null,b.ambitoCadencia307(c)));
const test=async(label,fn)=>{paints=[];await fn();checks++;};
(async()=>{
 await test('Actual reconocido verde validado no fuente mutable',async()=>{const c=ctx();await b.modulo.render(new N('main'),c);assert.equal(paints.length,1);assert.equal(paints[0].historicos.length,0);assert.equal(b.estadoCadencia(paints[0].seguimiento[0]),'verde');assert(b.textoCadencia(paints[0].seguimiento[0]).includes('no es una cita agendada'));assert.equal(b.estadoCadencia(row()),'gris');});
 await test('Viejo/futuro/wrong/duplicado preserva registro histórico',async()=>{for(const d of [{...doc(),hoy:'2026-10-02'},{...doc(),hoy:'2026-10-04'},{...doc(),sugerencias:[{...row(),cadencia_dias:30}]},{...doc(),sugerencias:[row(),row()]},{...doc(),sugerencias:'malformado'}]){paints=[];const c=ctx();c.api=async p=>p==='metodo/sugerencias'?d:{acciones:[]};await b.modulo.render(new N('main'),c);assert.equal(paints[0].seguimiento.length,0);assert.equal(paints[0].historicos.length,1);}});
 await test('Fecha imposible/no actor activo/planificada jamáscumplida',async()=>{for(const patch of [{ultima_confirmada:'2026-02-30'},{fuentes_operativas:[{tipo:'agendada',fecha:'2026-09-25'}]},{proxima_revision:'2026-10-11'}]){const x=b.separarCadencias([{cliente_id:'c'}],{...doc(),sugerencias:[{...row(),...patch}]},b.ambitoCadencia307(ctx()));assert.equal(b.estadoCadencia(x.seguimiento[0]),'gris');}const c=ctx();c.datos.personas[0].estado='baja';const x=b.separarCadencias([{cliente_id:'c'}],doc(),b.ambitoCadencia307(c));assert.equal(b.estadoCadencia(x.seguimiento[0]),'gris');});
 await test('Scope ACT permiso duplicado noforeign',()=>{for(const modify of [c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false}),c=>c.clientes.push({...c.clientes[0]})]){const c=ctx();modify(c);const x=b.separarCadencias([{cliente_id:'c'},{cliente_id:'ajeno'}],doc(),b.ambitoCadencia307(c));assert.equal(x.seguimiento.length,0);assert.equal(x.historicos.length,0);}});
 await test('Revocación identidad durante await no pintura',async()=>{for(const route of ['reuniones/reuniones','metodo/sugerencias']){const c=ctx();if(route==='reuniones/reuniones')c.datosModulo=async()=>{c.persona={id:'otra'};return {asistencias:[]};};else c.api=async p=>{if(p===route)c.persona={id:'otra'};return p===route?doc():{acciones:[]};};await b.modulo.render(new N('main'),c);assert.equal(paints.length,0);}});
 await test('Revocación módulo/ACT/rol mientras overlay vuelve',async()=>{for(const how of ['module','ACT','role']){paints=[];const c=ctx();c.api=async p=>{if(p==='metodo/sugerencias'){if(how==='module')c.veModulo=()=>false;else if(how==='ACT')c.clientes[0].activo_confirmado=false;else c.persona.puestos=['seo'];return doc();}return {acciones:[]};};await b.modulo.render(new N('main'),c);if(how==='module')assert.equal(paints.length,0);else{assert.equal(paints[0].seguimiento.length,0);assert.equal(paints[0].historicos.length,0);}}});
 await test('Callback periodo después revocación no repinta',async()=>{const c=ctx();let cb;c.alCambiarPeriodo=f=>cb=f;await b.modulo.render(new N('main'),c);assert.equal(paints.length,1);c.persona={id:'otra'};cb({id:'mes_ant'});assert.equal(paints.length,1);});
 await test('API error preserva histórico sin incumplimiento',async()=>{const c=ctx();c.api=async p=>{if(p==='metodo/sugerencias')throw Error('fixture');return {acciones:[]};};await b.modulo.render(new N('main'),c);assert.equal(paints[0].seguimiento.length,0);assert.equal(paints[0].historicos.length,1);});
 await test('Caller dosargs falta personas noverde y nodato no muta snapshot',()=>{const d=doc(),antes=JSON.stringify(d);const x=b.separarCadencias([{cliente_id:'c'}],d,{hoy:'2026-10-03'});assert.equal(b.estadoCadencia(x.seguimiento[0]),'gris');assert.equal(JSON.stringify(d),antes);});
 await test('Estado validado inmutable noverde por mutación accidental',()=>{const x=b.separarCadencias([{cliente_id:'c'}],{...doc(),sugerencias:[{...row(),estado:'sin_dato',ultima_confirmada:null,proxima_revision:null}]},b.ambitoCadencia307(ctx()));assert(Object.isFrozen(x.seguimiento[0]));x.seguimiento[0].estado='en_cadencia';assert.equal(b.estadoCadencia(x.seguimiento[0]),'gris');});
 console.log(checks+' grupos Reuniones307 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
