const fs=require('node:fs'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.open=false;this.append(...xs)}get isConnected(){return this.connected===true||!!this.parent?.isConnected}append(...xs){if(xs.some(Array.isArray))throw Error('arrays no DOM');for(const x of xs){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x)}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}addEventListener(k,f){this.events[k]=f}}
const h=(t,a,...xs)=>new N(t,a,xs),all=(n,t)=>[...(n.tag===t?[n]:[]),...n.children.filter(x=>x instanceof N).flatMap(x=>all(x,t))];let tests=0;const check=f=>{f();tests++};
(async()=>{const M=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_embudo_observado_469.js')).toString('base64'));
// DTO real emitido por whitelist467 a partir de adaptador466 sintético.
const dto=JSON.parse(execFileSync('python3',['-c',`import json
from ghl_embudo_observado_466 import preparar
from crm_embudo_api_467 import _medicion
v={'leads':[{'contacto':'contactA','creado':1790812800000,'es_lead':True}], 'citas':[{'id':'apptA','contacto':'contactA','creada':1790899200000}]}
a='2026-10-01T00:00:00Z';b='2026-10-03T23:59:59Z';c='2026-10-04T12:00:00Z'
r=preparar(v,'cliente','subCuentaA',a,b,c)
print(json.dumps({'version':'467.1','estado':'copia_observada','cliente_id':'cliente','medicion':_medicion(r['agregado'],'cliente',a,b,c),'diagnosticos':r['diagnosticos'],'hora_fuente':c,'desde':a,'hasta':b,'corte':c}))`],{cwd:__dirname,encoding:'utf8'}));
const fixture=()=>{const p={id:'operador',estado:'activo',puestos:['operaciones']},c={id:'cliente',activo_confirmado:true,detalle:true};return {servidor:true,hoy:'2026-10-04',real:structuredClone(p),persona:structuredClone(p),datos:{personas:[structuredClone(p)]},clientes:[structuredClone(c)],clientesVisibles:[structuredClone(c)],veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,api:async()=>structuredClone(dto)}};
const mount=ctx=>{const p=M.panelEmbudo469(ctx,'cliente',{h});const host=h('main',{});host.connected=true;host.append(p);return p;};
check(()=>{const c=fixture(),p=M.panelEmbudo469(c,'cliente',{h});assert.equal(p.isConnected,false);assert.match(p.textContent,/Embudo observado/);assert.equal(p.open,false)});
check(()=>{const m=M.modeloEmbudo469(dto,'cliente','2026-10-04');assert(m);assert.equal(m.vals.recibido,1);assert.equal(m.vals.cita,1);assert.equal(m.vals.venta,null)});
let c=fixture(),calls=0;c.api=async()=>{calls++;return structuredClone(dto)};let p=mount(c);check(()=>assert.equal(calls,0));p.open=true;await p.events.toggle();check(()=>{assert.equal(calls,1);const th=all(p,'th');assert.equal(th.length,7);assert.deepEqual(th.map(n=>n.textContent),['Rec.','Cual.','Cont.','Resp.','Citas','Asist.','Ventas']);assert(th.every(n=>n.attrs.title&&n.attrs['aria-label']));assert.equal(all(p,'td').filter(n=>n.textContent==='—').length,5);assert.match(p.textContent,/incluidas canceladas/);assert.match(p.textContent,/2026-10-01/);assert(!p.textContent.includes('subCuentaA'));assert(!p.textContent.includes('lead_id'));assert(!all(p,'button').length)});
p.open=false;await p.events.toggle();p.open=true;await p.events.toggle();check(()=>assert.equal(calls,1));
for(const mutate of [d=>d.extra='secret',d=>d.cliente_id='ajeno',d=>d.version='466.1',d=>d.diagnosticos.token=1,d=>d.diagnosticos.cita_replay=NaN,d=>d.medicion.cohorte.etapas.venta.observados=1,d=>d.medicion.eventos_periodo.contacto.eventos_observados=1,d=>d.medicion.cohorte.etapas.cita.observados=2,d=>d.medicion.cohorte.etapas.recibido.estado='completo',d=>d.medicion.source='privado',d=>d.medicion.limites.push('secret'),d=>d.hasta='2026-02-30T00:00:00Z',d=>d.corte='2026-10-04T12:00:00+02:99',d=>d.hora_fuente='2026-10-05T00:00:00Z',d=>d.corte='2026-10-05T00:00:00Z']){const d=structuredClone(dto);mutate(d);check(()=>assert.equal(M.modeloEmbudo469(d,'cliente','2026-10-04'),null))}
const zero=structuredClone(dto);zero.medicion.cohorte.recibidos_observados=0;zero.medicion.cohorte.estado='desconocido';for(const v of Object.values(zero.medicion.cohorte.etapas)){v.observados=0;v.estado='desconocido'}for(const v of Object.values(zero.medicion.eventos_periodo)){v.eventos_observados=0;v.leads_unicos_observados=0;v.estado='desconocido'}c=fixture();c.api=async()=>zero;p=mount(c);p.open=true;await p.events.toggle();check(()=>assert.equal(all(p,'td').filter(n=>n.textContent==='—').length,7));
for(const mutate of [c=>c.servidor=false,c=>c.ver=()=>({ok:false}),c=>c.veModulo=()=>false,c=>c.real.estado='baja',c=>c.datos.personas.push({...c.datos.personas[0]}),c=>c.persona.puestos.push('seo'),c=>c.datos.personas[0].puestos.push('operaciones'),c=>c.clientes.push({...c.clientes[0]}),c=>c.clientes[0].activo_confirmado=false,c=>c.clientes[0].activo=false,c=>c.clientesVisibles[0].detalle=false]){c=fixture();calls=0;c.api=async()=>{calls++;return dto};mutate(c);p=mount(c);p.open=true;if(p.events.toggle)await p.events.toggle();check(()=>{assert.equal(calls,0);assert.equal(p.textContent,'')})}
c=fixture();let finish;c.api=()=>new Promise(r=>finish=r);p=mount(c);p.open=true;const pending=p.events.toggle();c.clientes[0].activo_confirmado=false;finish(dto);await pending;check(()=>assert.equal(p.textContent,''));
c=fixture();p=mount(c);p.open=true;await p.events.toggle();const detail=all(p,'details')[1];c.ver=()=>({ok:false});await detail.events.toggle();check(()=>assert.equal(p.textContent,''));
c=fixture();p=mount(c);p.open=true;await p.events.toggle();c.datos.personas[0].estado='baja';p.open=false;await p.events.toggle();check(()=>assert.equal(p.textContent,''));
c=fixture();c.api=async()=>{throw Error('network')};p=mount(c);p.open=true;await p.events.toggle();check(()=>{assert.match(p.textContent,/no disponibles/);assert(!all(p,'td').length)});
c=fixture();const un={version:'467.1',estado:'sin_configurar',cliente_id:'cliente',medicion:null,diagnosticos:null,hora_fuente:null,desde:null,hasta:null,corte:null};c.api=async()=>un;p=mount(c);p.open=true;await p.events.toggle();check(()=>{assert.match(p.textContent,/Sin una copia/);assert(!all(p,'td').length);assert(M.modeloEmbudo469(un,'cliente',c.hoy))});
check(()=>assert.equal(M.modeloEmbudo469(dto,'cliente','2026-02-30'),null));
c=fixture();calls=0;let resolve;c.api=()=>{calls++;return new Promise(r=>resolve=r)};p=mount(c);p.open=true;const first=p.events.toggle();await p.events.toggle();check(()=>assert.equal(calls,1));resolve(dto);await first;
c=fixture();const viewed={id:'account',estado:'activo',puestos:['account']};c.persona=structuredClone(viewed);c.datos.personas.push(viewed);check(()=>assert(M.ambitoEmbudo469(c,'cliente')));c.persona.activo=false;check(()=>assert.equal(M.ambitoEmbudo469(c,'cliente'),null));
console.log(tests+' grupos469 PASS: DTO467 real sintético, ciclo DOM, lazy, unknown y revocación');})().catch(e=>{console.error(e);process.exitCode=1});
