const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(__dirname+'/probar_operaciones_265.cjs','utf8').split('(async()=>{')[0];
const E=new Function('require','__dirname',base+';return {s,El,ctx,text};')(require,__dirname),{s,El,ctx,text}=E;
// h auténtico: eventos sólo on:{toggle}, atributos accesibles y textos sin HTML.
El.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(El.prototype,'className',{set(v){this.attrs.class=v;}});
s.Node=El;s.document={createElement:t=>{const n=new El(t,{});n.style={};return n;},createTextNode:t=>String(t)};
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function urlSegura('),comp.indexOf('const svgNS =')).replace(/export /g,''),s);
const all=n=>n instanceof El?[n,...n.children.flat(Infinity).flatMap(all)]:[],pick=(n,tag)=>all(n).filter(x=>x.tag===tag),copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
async function test(l,f){await f();checks++;}
const sample=[{etiqueta:'Altas en plazo',valor:'3/4 · 75 %',referencia:'Día 12, referencia original por confirmar',detalle:'Copia parcial · período septiembre · corte2026-10-01'},
 {etiqueta:'Compromisos vencidos sin aviso',valor:0,referencia:'48 h; no medir con stock parcial',detalle:'Referencia histórica de la fuente disponible'},
 {etiqueta:'Horas por cuenta nueva',valor:'25,4 h/mes',referencia:'45 h/mes, referencia original por confirmar',detalle:'Fuente histórica; corte2026-10-01'}];
const render=(rs=sample,vigente=()=>true)=>s.pintarNumerosSemanales449(s.h,rs,{vigente,semana:'28sep→4oct2026'});
(async()=>{
 await test('three compact full headers',()=>{const n=render();assert.deepEqual(pick(n,'th').map(text),['Indicador','Valor','Detalle']);assert.equal(pick(n,'tr').length,4);assert.equal(pick(n,'details').length,3);assert(pick(n,'details').every(x=>!x.open));});
 await test('qualified values and units unchanged, actual zero retained',()=>{const n=render();assert.deepEqual(pick(n,'tr').slice(1).map(x=>text(x.children[1])),['3/4 · 75 %','0','25,4 h/mes']);assert(text(n).includes('Referencia histórica; no acredita cumplimiento'));assert(!all(n).some(x=>/verde|rojo|ambar/.test(x.attrs.class||'')));});
 await test('criterion/source not repeated before disclosure, week remains',()=>{const n=render();assert(text(n).includes('28sep→4oct2026'));assert(!text(n).includes('Día 12'));assert(!text(n).includes('Fuente histórica; corte2026'));for(const d of pick(n,'details')){assert(d.events.toggle);assert.equal(pick(d,'summary')[0].style.minHeight,'44px');assert(pick(d,'summary')[0].attrs['aria-label'].startsWith('Fuente y criterio de '));}});
 await test('real events preserve full source and criterion at mobile',()=>{const n=render(),d=pick(n,'details')[0];d.open=true;d.events.toggle();assert(text(d).includes(sample[0].detalle));assert(text(d).includes(sample[0].referencia));assert.equal(pick(d,'p').length,2);d.open=false;d.events.toggle();assert(!text(d).includes(sample[0].detalle));});
 await test('missing source metadata is honest and not zero',()=>{const n=render([{etiqueta:'Sin medición',valor:null}]),d=pick(n,'details')[0];assert.equal(text(pick(n,'tr')[1].children[1]),'—');assert(pick(n,'tr')[1].children[1].attrs.title.includes('no equivale a cero'));d.open=true;d.events.toggle();assert(text(d).includes('Sin criterio confirmado'));assert(text(d).includes('Sin ventana y evidencia suficiente'));});
 await test('NaN infinity objects are unknown not literal objects',()=>{for(const v of [NaN,Infinity,undefined,{},false,''])assert.equal(text(pick(render([{etiqueta:'X',valor:v}]),'tr')[1].children[1]),'—');});
 await test('text import cannot execute HTML or add private field',()=>{const n=render([{...sample[0],valor:'<img onerror=boom>',raw:'PRIVATE_UNAUTHORIZED'}]);assert(text(n).includes('<img onerror=boom>'));assert.equal(pick(n,'img').length,0);assert(!text(n).includes('PRIVATE_UNAUTHORIZED'));});
 await test('revocation opening closed disclosure clears full block',()=>{let allowed=true;const n=render(sample,()=>allowed),d=pick(n,'details')[0];allowed=false;d.open=true;d.events.toggle();assert.equal(n.children.length,0);});
 await test('revocation closing previously open disclosure clears source',()=>{let allowed=true;const n=render(sample,()=>allowed),d=pick(n,'details')[0];d.open=true;d.events.toggle();allowed=false;d.open=false;d.events.toggle();assert.equal(n.children.length,0);});
 await test('denied or disconnected never publishes source',()=>{assert.equal(render(sample,()=>false).children.length,0);const n=render(),d=pick(n,'details')[0];n.isConnected=false;d.open=true;d.events.toggle();assert.equal(n.children.length,0);});
 async function mounted(change=null){const x=ctx();x.datosModulo=async path=>{if(change)change(x);return path==='decisiones/direccion'?{informe_semanal:{corte:'2026-10-01',semana:'28sep→4oct2026',numeros:sample.map((r,i)=>({nombre:['Altas en plazo (encendidas el día 10, límite 12)','Compromisos vencidos sin aviso','Horas por cuenta nueva (media al mes)'][i],valor:r.valor,detalle:r.detalle})).concat([{nombre:'PRIVATE_EXTRA',valor:999,detalle:'PRIVATE_EXTRA'}])}}:{};};const n=s.h('main',{});await s.renderDiaDireccion265(n,x,'dia');return {n,x,block:all(n).find(t=>t.attrs['data-numeros-semanales-449'])};}
 await test('real parent maps exactly3 canonical indicators no extra source rows',async()=>{const {n,block}=await mounted();assert(block);assert.equal(pick(block,'tr').length,4);assert(text(block).includes('3/4 · 75 %'));assert(!text(n).includes('PRIVATE_EXTRA'));const d=pick(block,'details')[0];d.open=true;d.events.toggle();assert(text(d).includes('fuente histórica2026-10-01')||text(d).includes('fuente histórica 2026-10-01'));});
 await test('real parent scope source grant revoked during await prevents old values',async()=>{const {block}=await mounted(x=>{x.veModulo=id=>id!=='decisiones';});assert(block);assert.equal(block.children.length,0);});
 await test('real parent canonical scope changed on disclosure clears only block',async()=>{const {block,x}=await mounted(),d=pick(block,'details')[0];x.datos.personas.push(copy(x.datos.personas[0]));d.open=true;d.events.toggle();assert.equal(block.children.length,0);});
 await test('real parent ACT catalogue changed after read denies disclosure',async()=>{const {block,x}=await mounted(),d=pick(block,'details')[0];x.clientes.push({id:'ok',activo_confirmado:false});d.open=true;d.events.toggle();assert.equal(block.children.length,0);});
 console.log(checks+' grupos449 PASS · componente h y renderer265 reales, sin POST');
})().catch(e=>{console.error(e);process.exitCode=1;});
