const fs364=require('node:fs'),path364=require('node:path');
const base364=fs364.readFileSync(path364.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
new Function('require','__dirname',base364+`
const copy=x=>JSON.parse(JSON.stringify(x));
function dto364(){const cut='2026-10-03',days=Array.from({length:90},(_,i)=>({fecha:new Date(Date.parse(cut+'T00:00Z')-(90-i)*864e5).toISOString().slice(0,10),horas:null,entradas:null,estado:'sin_dato'}));
 for(const [f,v] of [['2026-09-01',2],['2026-09-02',0],['2026-10-02',1.5]])Object.assign(days.find(d=>d.fecha===f),{horas:v,entradas:1,estado:'observado'});
 return {version:'362.1',estado:'copia_observada',generado:'2026-10-03T19:00:00+00:00',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',unidad:'h',cumplimiento:null,capacidad_contractual:null,personas:[{persona_id:'p',historial_diario:{version:'359.1',fuente:'ClickUp entradas',fecha_fuente_utc:'2026-10-03T00:56:00+00:00',cobertura:'parcial',unidad:'h',zona:'Europe/Madrid',zona_confirmada:true,desde:days[0].fecha,hasta:days.at(-1).fecha,corte_fecha:cut,atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,dias:days}}]};}
function ctx364(){const ctx=make(),actor={id:'real',estado:'activo',activo:true,puestos:['operaciones']};ctx.servidor=true;ctx.real=actor;ctx.persona={...actor};ctx.datos={personas:[actor,{id:'p',nombre:'Persona fixture',estado:'activo',activo:true,puestos:['seo']}]};ctx.api=async p=>{assert.equal(p,'horas/historial-diario');return dto364();};return ctx;}
const model=(ctx=ctx364(),doc=dto364())=>c.modeloHistorial364(ctx,doc,H,c.ambitoHistorial364(ctx,H));
(async()=>{
 await test('Valid36290datesandpartialunit',()=>{const m=model();assert(m);assert.equal(m.series.get('p').dias.length,90);assert.equal(m.series.get('p').dias.find(d=>d.fecha==='2026-09-02').horas,0);assert.equal(m.series.get('p').dias[0].horas,null);});
 await test('Allprotocoltamperdeny',()=>{for(const change of [d=>d.version='359.1',d=>d.sha256_candidato='a'.repeat(64),d=>d.unidad='m',d=>d.cumplimiento=true,d=>d.cobertura='completa',d=>d.generado='2026-10-04T00:00:00Z',d=>d.personas[0].persona_id='ajeno',d=>d.personas.push(copy(d.personas[0])),d=>d.personas[0].historial_diario.fecha_fuente_utc='2026-10-03 00:56',d=>d.personas[0].historial_diario.fecha_fuente_utc='2026-10-04T00:56:00Z',d=>d.personas[0].historial_diario.zona_confirmada=false,d=>d.personas[0].historial_diario.zona='BAD',d=>d.personas[0].historial_diario.dias.pop(),d=>d.personas[0].historial_diario.dias[1].fecha=d.personas[0].historial_diario.dias[0].fecha,d=>d.personas[0].historial_diario.dias[0].horas=0,d=>d.personas[0].historial_diario.duracion_cerrada_confirmada=true]){const d=dto364();change(d);assert.equal(model(ctx364(),d),null);}});
 await test('Canonicalactorgrantrevocation',()=>{for(const change of [x=>x.real.estado='baja',x=>x.datos.personas.push(copy(x.datos.personas[0])),x=>x.real.puestos=['seo'],x=>x.datos.personas[1].activo=false,x=>x.ver=()=>({ok:false}),x=>x.veModulo=()=>false]){const ctx=ctx364();change(ctx);assert.equal(model(ctx),null);}});
 await test('Oldscopechangedstillcanonicaldeny',()=>{const ctx=ctx364(),scope=c.ambitoHistorial364(ctx,H);ctx.persona={...ctx.persona,id:'other'};assert.equal(c.modeloHistorial364(ctx,dto364(),H,scope),null);});
 await test('RangeSeptember2notmonthlylegacy14NoSum',()=>{const s=model().series.get('p'),r={desde:'2026-09-01',hasta:'2026-09-30'},m=c.horasRango262(H.personas[0],H,r,s);assert.equal(m.valor,2);assert.equal(m.dias,1);assert.equal(m.fechas_con_registros,2);assert.equal(m.total_dias,30);assert.equal(m.ultima,'2026-09-02');assert.equal(m.tipo,'observado_historial_90d');assert(m.detalle.includes('2/30'));assert(m.detalle.includes('fuente UTC'));});
 await test('AllunknowninWindowNoMonthlyRevival',()=>{const s=model().series.get('p'),m=c.horasRango262(H.personas[0],H,{desde:'2026-08-01',hasta:'2026-08-31'},s);assert.equal(m.valor,null);assert.equal(m.ultima,null);assert.equal(m.dias,null);assert.equal(m.total_dias,31);});
 await test('RangeOutside90dNoExtrapolate',()=>{const s=model().series.get('p'),m=c.horasRango262(H.personas[0],H,{desde:'2026-06-01',hasta:'2026-09-30'},s);assert.equal(m.valor,2);assert.equal(m.fuera_ventana,true);assert(m.detalle.includes('fuera de los 90 días'));assert.equal(m.total_dias,122);});
 await test('ZeroExplicitRealVersusUnknown',()=>{const s=model().series.get('p');assert.equal(c.horasHistorialRango364(s,{desde:'2026-09-02',hasta:'2026-09-02'}).valor,0);assert.equal(c.horasHistorialRango364(s,{desde:'2026-09-03',hasta:'2026-09-03'}).valor,null);});
 await test('LegacyWhenNoTypedClearlyReference',()=>{const m=c.horasRango262(H.personas[0],H,{desde:'2026-09-01',hasta:'2026-09-30'});assert.equal(m.valor,14);assert.equal(m.tipo,'referencia_mensual');assert(m.detalle.includes('sin descriptor'));});
 await test('RenderMonthlyRealhPreserveSixAndFourColumnsOneGet',async()=>{const ctx=ctx364(),n=new N('main');let gets=0;ctx.api=async()=>{gets++;return dto364();};await c.renderEquipo262(n,ctx,'horas');const btn=all(n,x=>x.tag==='button'&&text(x)==='Mes pasado')[0];btn.events.click();const t=all(n,x=>x.tag==='table');assert.equal(t.length,2);assert.equal(all(t[0],x=>x.tag==='th').length,6);assert.equal(all(t[1],x=>x.tag==='th').length,4);const td=all(t[0],x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(td[1]),'≥2');assert.equal(text(td[4]),'1/30 días');assert.equal(text(td[5]),'2026-09-02');assert.equal(gets,1);assert(text(n).includes('Historial90d'));assert(!all(n,x=>/ref-(verde|rojo)/.test(x.attrs.class||'')).length);});
 await test('DateFreeControlsUse90d',async()=>{const ctx=ctx364(),n=new N('main');await c.renderEquipo262(n,ctx,'horas');const from=all(n,x=>x.tag==='input'&&x.attrs['aria-label']==='Desde')[0];from.events.change({target:{value:'2026-09-01'}});const to=all(n,x=>x.tag==='input'&&x.attrs['aria-label']==='Hasta')[0];to.events.change({target:{value:'2026-09-02'}});const row=all(n,x=>x.tag==='table')[0];assert(text(row).includes('1/2 días'));assert(text(row).includes('≥2'));});
 await test('Monday5LaborablesIncludesTypedEarlierDate11Cols',async()=>{const ctx=ctx364(),n=new N('main');ctx.hoy='2026-10-05';await c.renderEquipo262(n,ctx,'equipo-dia');const t=all(n,x=>x.tag==='table')[0];assert.equal(all(t,x=>x.tag==='th').length,11);assert(text(t).includes('09-28'));assert(text(t).includes('10-02'));assert(text(t).includes('1,5'));assert(!all(n,x=>/ref-(verde|rojo)/.test(x.attrs.class||'')).length);});
 await test('TypedNoObservedDoesNotFallBackShort14',async()=>{const ctx=ctx364(),d=dto364();d.personas[0].historial_diario.dias.forEach(x=>Object.assign(x,{estado:'sin_dato',horas:null,entradas:null}));ctx.api=async()=>d;const n=new N('main');await c.renderEquipo262(n,ctx,'equipo-dia');assert.equal(all(n,x=>x.attrs.class?.includes('oe-observado')).length,0);});
 await test('UnavailableSourceLegacyVisibleNotFresh',async()=>{const ctx=ctx364(),n=new N('main');ctx.api=async()=>{throw Error();};await c.renderEquipo262(n,ctx,'horas');assert(text(n).includes('Historial90d no disponible'));assert(text(n).includes('referencia mensual heredada'));});
 await test('LateApiIdentityChangedNoPaint',async()=>{const ctx=ctx364(),n=new N('main');ctx.api=async()=>{ctx.persona={id:'other'};return dto364();};assert.equal(await c.renderEquipo262(n,ctx,'horas'),false);assert.equal(n.children.length,0);});
 await test('GrantRevokedWhileApiNoPaint',async()=>{const ctx=ctx364(),n=new N('main');ctx.api=async()=>{ctx.ver=()=>({ok:false});return dto364();};assert.equal(await c.renderEquipo262(n,ctx,'horas'),false);assert.equal(n.children.length,0);});
 await test('AfterPaintCallbackRevokedClearsOldPrivateData',async()=>{const ctx=ctx364(),n=new N('main');await c.renderEquipo262(n,ctx,'horas');assert(text(n).includes('Persona fixture'));const button=all(n,x=>x.tag==='button'&&text(x)==='Mes pasado')[0];ctx.datos.personas[1].activo=false;button.events.click();assert(!text(n).includes('Persona fixture'));assert(!text(n).includes('1,5'));});
 await test('NoHoursGrantNoProductionFallbackLeak',async()=>{const ctx=ctx364(),n=new N('main');ctx.ver=()=>({ok:false});ctx.api=async()=>({...dto364(),personas:[]});await c.renderEquipo262(n,ctx,'equipo-dia');assert(!text(n).includes('Persona fixture'));assert.equal(all(n,x=>x.tag==='th').length,11);});
 await test('NoCanonicalNoNewApi',async()=>{const ctx=make(),n=new N('main');let calls=0;ctx.api=async()=>{calls++;return dto364();};await c.renderEquipo262(n,ctx,'horas');assert.equal(calls,0);});
 await test('InvalidCanonicalServerNeverLegacyFallback',async()=>{for(const route of ['horas','equipo-dia'])for(const change of [x=>x.real.estado='baja',x=>x.datos.personas.push(copy(x.datos.personas[0])),x=>x.real.puestos=['seo']]){const ctx=ctx364(),n=new N('main');change(ctx);let gets=0;ctx.api=async()=>{gets++;return dto364();};assert.equal(await c.renderEquipo262(n,ctx,route),false);assert.equal(gets,0);assert(!text(n).includes('Persona fixture'));assert(!text(n).includes('14'));assert.equal(all(n,x=>x.tag==='table').length,0);assert(text(n).includes('permisos actuales'));}});
 await test('ExplicitServerDeniedNeverLegacyFallback',async()=>{for(const status of [401,403])for(const route of ['horas','equipo-dia']){const ctx=ctx364(),n=new N('main');ctx.api=async()=>{throw Object.assign(Error('denied'),{status});};assert.equal(await c.renderEquipo262(n,ctx,route),false);assert(!text(n).includes('Persona fixture'));assert(!text(n).includes('14'));assert.equal(all(n,x=>x.tag==='table').length,0);assert(text(n).includes('permisos actuales'));}});
 await test('368ExplicitZeroIsObservedButNotPositiveDay',()=>{const s=model().series.get('p'),m=c.horasHistorialRango364(s,{desde:'2026-09-02',hasta:'2026-09-02'});assert.equal(m.valor,0);assert.equal(m.dias,0);assert.equal(m.fechas_con_registros,1);assert.equal(m.ultima,'2026-09-02');assert(m.detalle.includes('1/1 fechas naturales con registros'));assert(m.detalle.includes('0 días con horas positivas'));});
 await test('368NoRecordNeverZeroPositiveDays',()=>{const s=model().series.get('p'),m=c.horasHistorialRango364(s,{desde:'2026-09-03',hasta:'2026-09-03'});assert.equal(m.valor,null);assert.equal(m.dias,null);assert.equal(m.fechas_con_registros,null);assert.equal(m.ultima,null);});
 await test('368TinyDurationRendererNeverZeroHour',async()=>{const ctx=ctx364(),d=dto364(),entry=d.personas[0].historial_diario.dias.find(x=>x.fecha==='2026-10-02');entry.horas=0.0005;ctx.api=async()=>d;const n=new N('main');await c.renderEquipo262(n,ctx,'horas');all(n,x=>x.tag==='button'&&text(x)==='Este mes')[0].events.click();const row=all(n,x=>x.tag==='table')[0],cells=all(row,x=>x.tag==='tbody')[0].children[0].children;assert.equal(text(cells[1]),'<0,1');assert.equal(text(cells[2].children[0].children[0]),'<0,1 %');assert(cells[2].children[0].attrs.title.includes('Simulación referencia8h por laborable'));assert(cells[2].children[0].attrs['aria-label'].includes('no capacidad contractual'));assert(!text(cells[2]).includes('Ref. baja'));assert(cells[2].children[0].attrs.class.includes('rojo'));assert(cells[1].children[0].attrs.title.includes('0.0005 h'));assert.equal(text(cells[4]),'1/3 días');const day=new N('main');await c.renderEquipo262(day,ctx,'equipo-dia');assert(text(day).includes('<0,1'));});
 console.log(checks+' grupos364 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
