const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const base=fs.readFileSync(__dirname+'/pruebas_resumen_274.cjs','utf8').split('(async()=>{')[0];const {tmp,walk}=new Function('require','__dirname',base+';return {tmp,walk};')(require,__dirname);
(async()=>{try{const M=await import('file://'+path.join(tmp,'_operaciones_resumen_274.mjs'));const U=await import('file://'+path.join(tmp,'_operaciones_urgencias_406.mjs'));const {h}=await import('file://'+path.join(tmp,'componentes.mjs'));let n=0;const test=async(name,f)=>{await f();n++;console.log('PASS '+name);};
const actor={id:'ops',estado:'activo',puestos:['operaciones']},client={id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true};
function ctx(){return {servidor:true,hoy:'2026-10-04',real:{...actor},persona:{...actor},datos:{personas:[{...actor}]},clientes:[{...client}],clientesVisibles:[{...client}],veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,nombre:id=>id,verdad:()=>null,api:async()=>dto()};}
const row={tarea_id:'t1',cliente_id:'c',lista_id:'l',prioridad:'urgent',estado:'en curso',tipo_estado:'custom',clasificacion:'abierta_en_copia_por_contrastar',final_flujo_en_copia:false,estado_fuente:'clickup',estado_leido_utc:'2026-10-03T13:00:00Z',prioridad_fuente:'clickup_cache_literal',prioridad_leida_utc:null,medicion_urgencia:null,es_fuego_actual:null,verificacion_conjunta:false,ejecucion_verificada:false,aceptacion_verificada:false};
function dto(){return {version:'402.1',grupo:'abiertas',urgencias_actuales:null,verificacion_conjunta:false,cumplimiento:null,cliente_ids:['c'],filas:[{...row}],estado:'copia_observada',fuente_version:'398.1',fuente:'clickup_cache_local',cobertura:'parcial',corte_preparacion_utc:'2026-10-04T00:00:00Z',generado:'2026-10-04T01:00:00Z',lectura_desde_utc:row.estado_leido_utc,lectura_hasta_utc:row.estado_leido_utc,abiertas_en_copia:1,observaciones:1};}
const main=()=>{const x=h('main',{});x.connected=true;return x;},fuego=root=>walk(root).find(x=>x.tag==='a'&&x.attrs.href==='#/operaciones/fuegos');
await test('Una lectura406 real, grisN y fecha/unidad accesible, sinIDsprivados',async()=>{const c=ctx(),root=main();let calls=[];c.api=async p=>{calls.push(p);return dto();};const verified=U.proyectarUrgencias406(c,dto(),U.ambitoUrgencias406(c));await M.renderResumen274(root,c,{fuentes:{}});assert.deepEqual(calls,['produccion/urgencias-observadas']);const a=fuego(root);assert(a.textContent.includes('Fuegos · copia'));assert.equal(a.children.at(-1).textContent,String(verified.filas.length));assert(a.attrs.title.includes(row.estado_leido_utc));assert(a.attrs['aria-label'].includes('sin verificación conjunta'));assert(a.children.at(-1).attrs.class.includes('gris'));assert(!root.textContent.includes('t1'));assert(!root.textContent.includes('en curso'));});
await test('Macroprimero ruta239; carteraabierta;11indicadores y7pasos intactos',async()=>{const c=ctx(),root=main();await M.renderResumen274(root,c,{fuentes:{}});const r=root.children[0];assert.equal(r.children[1].attrs.href,'#/mi-dia/control-cartera/operaciones');const groups=walk(root).filter(x=>x.attrs.class==='tiles274');assert.deepEqual(groups.map(x=>x.children.length),[6,5]);assert.equal(walk(root).find(x=>x.attrs.class==='pasos274').children.length,7);assert.equal(walk(root).find(x=>x.tag==='details'&&x.children[0]?.textContent==='Accounts de un vistazo').attrs.open,true);});
await test('Accountpropia rutaaccount sinforzarOps',async()=>{const c=ctx(),p={...actor,id:'acc',puestos:['account']};c.real=p;c.persona={...p};c.datos.personas=[p];const root=main();await M.renderResumen274(root,c,{fuentes:{}});assert(walk(root).some(x=>x.attrs.href==='#/mi-dia/control-cartera/account'));assert(!walk(root).some(x=>x.attrs.href==='#/mi-dia/control-cartera/operaciones'));});
await test('Empty/ausencia/403/503 nozero ni bloquear11indicadores',async()=>{for(const mode of ['empty','missing',403,503]){const c=ctx(),root=main();c.api=async()=>{if(typeof mode==='number')throw {status:mode};if(mode==='missing')return null;const d=dto();Object.assign(d,{filas:[],observaciones:null,abiertas_en_copia:null,lectura_desde_utc:null,lectura_hasta_utc:null});return d;};await M.renderResumen274(root,c,{fuentes:{}});assert.equal(fuego(root).children.at(-1).textContent,'—');assert.equal(walk(root).filter(x=>x.attrs.class==='tiles274').length,2);}});
await test('Clasificación ajena/final/duplicate/cliente noautorizado no badge',async()=>{for(const mode of ['final','duplicate','outside','current']){const c=ctx(),d=dto(),root=main();if(mode==='final')d.filas[0].tipo_estado='done';if(mode==='duplicate')d.filas.push({...row});if(mode==='outside')d.filas[0].cliente_id='x';if(mode==='current')d.urgencias_actuales=1;c.api=async()=>d;await M.renderResumen274(root,c,{fuentes:{}});assert.equal(fuego(root).children.at(-1).textContent,'—');}});
await test('NoesperalaAPI para mostrar matriz/indicadores;awaitrevocado limpia',async()=>{for(const mutate of [c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false}),c=>c.datos.personas.push({...actor}),c=>c.persona.puestos=['seo']]){const c=ctx(),root=main();let resolve;c.api=()=>new Promise(r=>resolve=r);const run=M.renderResumen274(root,c,{fuentes:{}});await new Promise(r=>setImmediate(r));assert(walk(root).some(x=>x.attrs.class==='tiles274'));mutate(c);resolve(dto());await run;assert.equal(root.children[0].children.length,0);}});
await test('ClickFuegos ymacro despuésrevocación niegan/limpian',async()=>{for(const isMacro of [false,true]){const c=ctx(),root=main();await M.renderResumen274(root,c,{fuentes:{}});const a=isMacro?walk(root).find(x=>x.attrs.href==='#/mi-dia/control-cartera/operaciones'):fuego(root);c.ver=()=>({ok:false});let prevented=false;a.attrs.on.click({preventDefault:()=>prevented=true});assert(prevented);assert.equal(root.children[0].children.length,0);}});
await test('Scopeinexistente noGET402/no macro; rojo no urge',async()=>{const c=ctx(),root=main();c.clientes[0].activo_confirmado=false;let calls=0;c.api=async()=>{calls++;return dto();};await M.renderResumen274(root,c,{fuentes:{}});assert.equal(calls,0);assert(!walk(root).some(x=>x.attrs.href?.includes('control-cartera')));assert.equal(fuego(root).children.at(-1).textContent,'—');});
console.log(n+' grupos530 PASS · renderer274 y modelo406 reales sin POST');}finally{fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
