const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const b={Date,Intl,Map,Set,WeakSet,Promise,CACHE:new Map(),CONFIG:{},VIDA_CACHE_MS:300000,MODULOS:[],motivoDe:(status,error,modulo)=>({ok:false,status,error,modulo}),scopeDia:c=>JSON.stringify([c.real?.id,c.persona?.id]),yo:c=>c.persona.id,verdad:()=>null,nomCli:(c,id)=>id,diaCorto:v=>v,hrefCliente:(c,id)=>'#/ficha/'+id,plural:(n)=>String(n),fresco:()=>({}),alcance:(b,d)=>b?.alcance||d};vm.createContext(b);
for(const file of ['_metodo_cohorte_305.js','_cadencia_metodo.js']){const s=fs.readFileSync(__dirname+'/modulos/'+file,'utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${file.startsWith('_metodo')?'proyectarMetodo305':'separarCadencias,textoCadencia,estadoCadencia,ambitoCadencia307'}})})()`,b);}
const funciones={},src=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8');b.def=(id,usa,fn)=>funciones[id]=fn;vm.runInContext(src.slice(src.indexOf('function reunionesCartera('),src.indexOf("def('trabajo_account'"))+';this.cartera=reunionesCartera;',b);
const md=fs.readFileSync(__dirname+'/modulos/mi_dia.js','utf8');vm.runInContext(md.slice(md.indexOf('function cargador('),md.indexOf('\nasync function cargarConfig'))+';this.loader=cargador;',b);
const feed=()=>({hoy:'2026-10-03',sugerencias:[{cliente_id:'c',regla_id:'seguimiento_quincenal_especialista',cadencia_dias:15,responsable_role:'trafficker',estado:'en_cadencia',incumplimiento:null,responsables_ids:['t'],responsable_id:'t',ultima_confirmada:'2026-09-25',proxima_revision:'2026-10-10',fuentes_operativas:[{tipo:'reunion_celebrada',fecha:'2026-09-25'}]}]});
const reuniones={_meta:{generado:'2026-10-03',mes_pasado:'2026-09'},clientes:[{cliente_id:'c',account_id:'a',estado:'sin_reunion',cliente:'Fixture'}]};
const ctx=()=>({hoy:'2026-10-03',real:{id:'t',estado:'activo',puestos:['trafficker']},persona:{id:'t',estado:'activo',puestos:['trafficker']},servidor:true,clientes:[{id:'c',activo_confirmado:true}],carteraIds:new Set(),datos:{personas:[{id:'t',estado:'activo'}]},veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,api:async()=>feed(),datosModulo:async()=>reuniones});
let n=0;const test=async(label,fn)=>{await fn();n++;};
const d=r=>({dato:()=>reuniones,opcional:()=>r});
(async()=>{
 await test('Trafficker propio validado aparece sin carteraAccount ni responsables_ids',()=>{const r=b.cartera(ctx(),d(feed()));assert.equal(r.actuales.length,1);assert.equal(r.actuales[0].responsable_id,'t');assert.equal(b.estadoCadencia(r.actuales[0]),'verde');assert.equal(r.sin.length,0);const bloque=funciones.reuniones_ciclo(ctx(),d(feed()),{});assert.equal(bloque.estado,'verde');assert.equal(bloque.filas.length,1);assert(bloque.filas[0].extra.includes('no es una cita agendada'));});
 await test('Otra persona no hereda silla; cuentaAccount sólocarteraactual',()=>{const c=ctx();c.persona={id:'otro'};assert.equal(b.cartera(c,d(feed())).actuales.length,0);c.carteraIds.add('c');assert.equal(b.cartera(c,d(feed())).actuales.length,1);});
 await test('Unknown propietario jamás verde',()=>{const c=ctx();c.carteraIds.add('c');c.datos.personas[0].estado='baja';const r=funciones.reuniones_ciclo(c,d(feed()),{});assert.equal(r.estado,'gris');assert.equal(r.filas[0].estado,'gris');});
 await test('Feed viejo/futuro conserva histórico gris autorizado',()=>{const c=ctx();c.persona.id='a';for(const fecha of ['2026-10-02','2026-10-04']){const f={...feed(),hoy:fecha};const r=b.cartera(c,d(f));assert.equal(r.actuales.length,0);assert.equal(r.sin.length,1);assert.equal(funciones.reuniones_ciclo(c,d(f),{}).estado,'gris');}});
 await test('ACT/cliente permiso revocado corta historia y overlay',()=>{for(const change of [c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false}),c=>c.clientes.push({...c.clientes[0]})]){const c=ctx();change(c);const r=b.cartera(c,d(feed()),'todo');assert.equal(r.l.length,0);assert.equal(r.actuales.length,0);}});
 await test('Loader unaAPI sincache/paquete y dato/opcional actuales',async()=>{const c=ctx();let calls=0;c.api=async p=>{assert.equal(p,'metodo/sugerencias');calls++;return feed();};const D=b.loader(c,{fuentes:{'metodo/sugerencias':{hoy:'viejo'}}});await D.precargar(['metodo/sugerencias','metodo/sugerencias']);assert.equal(calls,1);assert.equal(D.opcional('metodo/sugerencias').hoy,c.hoy);assert.equal(D.dato('metodo/sugerencias').hoy,c.hoy);assert.equal(b.CACHE.size,0);assert.equal(D.sueltos.length,0);});
 await test('Permiso negado antes noAPI',async()=>{const c=ctx();let calls=0;c.veModulo=()=>false;c.api=async()=>{calls++;return feed();};const D=b.loader(c);await D.precargar(['metodo/sugerencias']);assert.equal(calls,0);assert.equal(D.opcional('metodo/sugerencias'),null);});
 await test('Cambios duranteawait norespuesta antigua',async()=>{for(const change of [c=>c.persona={id:'otro'},c=>c.real={id:'otro'},c=>c.veModulo=()=>false,c=>c.clientes=[],c=>c.persona.puestos=['seo'],c=>c.hoy='2026-10-04',c=>c.vigente=()=>false]){const c=ctx();let finish;c.api=()=>new Promise(r=>finish=r);const D=b.loader(c),wait=D.precargar(['metodo/sugerencias']);change(c);finish(feed());await wait;assert.equal(D.opcional('metodo/sugerencias'),null);assert.throws(()=>D.dato('metodo/sugerencias'));}});
 await test('Cambios después de lectura invalidan ambos lectores/callback',async()=>{for(const change of [c=>c.persona={id:'otro'},c=>c.ver=()=>({ok:false}),c=>c.clientes[0].activo_confirmado=false,c=>c.veModulo=()=>false,c=>c.vigente=()=>false]){const c=ctx(),D=b.loader(c);await D.precargar(['metodo/sugerencias']);assert(D.opcional('metodo/sugerencias'));change(c);assert.equal(D.opcional('metodo/sugerencias'),null);assert.throws(()=>D.dato('metodo/sugerencias'));}});
 await test('Error fuente nofallbackni0cumplimiento',async()=>{const c=ctx();c.api=async()=>{throw Error('fixture');};const D=b.loader(c);await D.precargar(['metodo/sugerencias']);assert.equal(D.opcional('metodo/sugerencias'),null);assert.equal(b.CACHE.size,0);});
 console.log(n+' grupos MiDía309 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
