const fs=require('fs'),vm=require('vm'),assert=require('assert');
const b={};vm.createContext(b);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_cierre_artifact_253.js','utf8').replace(/export /g,''),b);
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
function h(tag,attrs,...kids){return{tag,attrs,kids:kids.flat(Infinity),append(...xs){this.kids.push(...xs.flat(Infinity))}}}
const walk=x=>!x||typeof x!=='object'?[]:[x,...(x.kids||[]).flatMap(walk)];
const text=x=>typeof x==='string'?x:(x?.kids||[]).map(text).join(' ');
const hist={version:'267.1',periodo:'2026-09',cobertura:'parcial',verificacion_externa:false,cumplimiento:null,no_evalua_garantia:true,sha256_candidato:'4afc61a142faadf9631141c3a33109712cfd9ecfdf832a99e469731e970f5bc2',fuente_llamadas:'zadarma_cache_historica',fuente_reuniones:'verificacion_manual_anterior_ID_exacto',llamadas30:2,reuniones_verificadas_historicas:1};
function render(row={},v=null,extra=[]){return b.pintarCierre253({h,d:{mes_horas:'2026-09',mes_cuota:'2026-09',clientes:[{cliente_id:'a',nombre:'A',account_id:'ops',...row},...extra]},clientes:[{id:'a',activo_confirmado:true}],verdad:()=>v})}
const cells=tree=>walk(tree).filter(x=>x.tag==='td');
test('desconocidos sólo raya visible y semántica accesible',()=>{const t=render(),cs=cells(t);assert.equal(cs.length,7);for(const c of cs.slice(1))assert.equal(text(c),'—');for(const c of [cs[1],cs[2],cs[3],cs[5],cs[6]]){assert(c.attrs.title);assert(c.attrs['aria-label'])}const sem=walk(cs[4]).find(x=>x.tag==='span');assert(sem.attrs.title.includes('por confirmar'));assert(sem.attrs['aria-label']);assert.equal(sem.attrs.class,'sem253 gris');assert(text(t).includes('no cumplimiento'));assert(text(t).includes('— indica dato sin acreditar'))});
test('cifras históricas mantienen mínimos sin repetir unidad',()=>{const cs=cells(render({historico_267:hist}));assert.equal(text(cs[5]),'≥1');assert.equal(text(cs[6]),'≥2');assert(cs[5].attrs.title.includes('Asistencia'));assert(cs[6].attrs.title.includes('Cobertura parcial'));assert(!text(cs[5]).includes('registros'))});
test('porcentaje compacto conserva referencia fuera tabla y mínimo553',()=>{const t=render({coste_horas:{sep:130.06},cuota_horas:{pautadas:100}}),cs=cells(t);assert.equal(text(cs[3]),'≥130 %');const p=walk(cs[3]).find(x=>x.tag==='span');assert.equal(p.attrs.class,'ratio361 rojo');assert(p.attrs.title.includes('no acredita déficit'));assert(!text(cs[3]).includes('ref.'));assert(text(t).includes('ref.'))});
test('semáforo actual mantiene colores sólo con cliente exacto',()=>{for(const [gravedad,color,label] of [['critico','rojo','Crítico'],['atencion','ambar','Vigilar'],['bien','verde','Bien']]){const c=cells(render({}, {id:'a',gravedad}))[4];assert.equal(text(c),label);assert(walk(c).some(x=>x.attrs?.class==='sem253 '+color))}assert.equal(text(cells(render({}, {id:'otro',gravedad:'bien'}))[4]),'—')});
test('siete columnas todas filas autorizadas sin clientes extra',()=>{const t=render({},null,[{cliente_id:'ajeno',nombre:'NO_MOSTRAR',coste_horas:{sep:9}}]);assert.equal(walk(t).filter(x=>x.tag==='th').length,7);assert.equal(cells(t).length,7);assert(!text(t).includes('NO_MOSTRAR'))});
console.log(n+' grupos compacto556 PASS');
