const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const box={Date,Intl,Map,Set,Number,Object,fmt:{num:n=>String(n),pct:n=>String(n)+'%'},hoyMadrid:()=> '2026-10-03',REGLAS:{},FECHAS:{}};vm.createContext(box);
for(const [file,names] of [['_meta_semantica_285','semanticaMeta285'],['_paid_mediciones','normalizarPaid,medirCplPaid'],['_crm_mediciones','normalizarFilaCRM,medirEmbudoCRM'],['_resultados_dia_314','clientesDia314,crmDia314'],['_crm_secundario_317','secundariosCRM317,textoConteo317,referenciaAlta317']]){const s=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${names}})})()`,box);}
const fuente=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${fuente};this.BLOQUES=BLOQUES;})()`,box);
const ctx=()=>({hoy:'2026-10-03',clientesVisibles:[{id:'c',activo_confirmado:true},{id:'d',activo_confirmado:true}],datos:{personas:[{id:'e',estado:'activo',nombre:'Fixture'}]},ver:()=>({ok:true})});
const crm=()=>({fuentes:{ghl:{hora:'2026-10-03T08:00:00Z',estado:'bien'}},resumen:{asistencia_pct:99,velocidad_pct_1h:100,despachos_cumplen_garantia:99},especialistas:[{id:'other',nombre:'AJENO',rojo:99,verde:0}],subcuentas:[{cliente_id:'c',tipo:'cliente',especialista_id:'e',citas_30d:{agendadas:6,celebradas:2,no_presentadas:2,sin_estado:2},citas_14d:{sin_estado:1},sin_tocar_24h:0,velocidad:{juzgables:4,en_1h:1}}]});
const D=x=>({dato:()=>x,opcional:()=>null});let n=0;function test(l,f){f();n++;}
test('Real blocks scoped pair ratio not globalstock or threshold',()=>{const r=box.BLOQUES.asistencia_velocidad.hacer(ctx(),D(crm()));assert.equal(r.valor,'50%');assert.equal(r.estado,'gris');assert(r.filas[0].extra.includes('25%'));assert(!JSON.stringify(r).includes('99'));assert(!JSON.stringify(r).includes('70'));assert(!JSON.stringify(r).includes('garantia'));});
test('No current data null instead0/green aggregate',()=>{const c=crm();c.subcuentas=[];for(const id of ['asistencia_velocidad','tabla_especialista']){const r=box.BLOQUES[id].hacer(ctx(),D(c));assert.equal(r.valor,null);assert.equal(r.estado,'gris');}assert.equal(box.secundariosCRM317(ctx(),c).citas.agendadas.valor,null);});
test('Observedzero preserved counts but denominator0ratio unknown',()=>{const c=crm();c.subcuentas[0].citas_30d={agendadas:0,celebradas:0,no_presentadas:0,sin_estado:0};c.subcuentas[0].velocidad={juzgables:0,en_1h:0};const r=box.secundariosCRM317(ctx(),c);assert.equal(r.citas.agendadas.valor,0);assert.equal(r.asistencia,null);assert.equal(r.velocidad,null);});
test('Missing counterpartexcluded notdifferentdenominator',()=>{const c=crm();c.subcuentas.push({cliente_id:'d',tipo:'cliente',especialista_id:'e',citas_30d:{celebradas:100},velocidad:{juzgables:100}});const r=box.secundariosCRM317(ctx(),c);assert.equal(r.asistencia,50);assert.equal(r.asistencia_subcuentas,1);assert.equal(r.velocidad,25);assert.equal(r.velocidad_subcuentas,1);});
for(const mode of ['old','future','error','fraction','negative','wrongtotal'])test('Invalid '+mode,()=>{const c=crm();if(mode==='old')c.fuentes.ghl.hora='2026-09-01';if(mode==='future')c.fuentes.ghl.hora='2026-10-04';if(mode==='error')c.fuentes.ghl.error='fixture';if(mode==='fraction')c.subcuentas[0].citas_30d.celebradas=.5;if(mode==='negative')c.subcuentas[0].citas_30d.celebradas=-1;if(mode==='wrongtotal'){c.subcuentas[0].citas_30d.con_fecha_en_ventana=1;}const r=box.secundariosCRM317(ctx(),c);assert.equal(r.asistencia,null);});
test('ScopeACTgrantduplicatesotherID nootherglobalemployee',()=>{for(const mode of ['ACT','grant','duplicate','other']){const x=ctx(),c=crm();if(mode==='ACT')x.clientesVisibles[0].activo_confirmado=false;if(mode==='grant')x.ver=()=>({ok:false});if(mode==='duplicate')c.subcuentas.push({...c.subcuentas[0]});if(mode==='other')c.subcuentas[0].cliente_id='foreign';const r=box.BLOQUES.tabla_especialista.hacer(x,D(c));assert.equal(r.filas.length,0);assert(!JSON.stringify(r).includes('AJENO'));}});
test('Canonicalactive employee only, no names/fuzzy grants',()=>{for(const mode of ['duplicate','inactive','unmapped']){const x=ctx(),c=crm();if(mode==='duplicate')x.datos.personas.push({...x.datos.personas[0]});if(mode==='inactive')x.datos.personas[0].estado='baja';if(mode==='unmapped')c.subcuentas[0].especialista_id='unknown';assert.equal(box.secundariosCRM317(x,c).especialistas.length,0);}});
test('Alta legacy mediana conservar pero noleadcalificado/sourceperiod green',()=>{const r=box.BLOQUES.carga_altas.hacer(ctx(),D({resumen:{carga_semana:0,carga_tope:6,primer_lead_mediana_dias:2.5}}));assert.equal(r.valor,'0');assert.equal(r.estado,'gris');assert(r.motivo.includes('2.5'));assert(r.motivo.includes('evento y cohorte no acreditados'));assert.equal(r.barras.length,0);const m=box.BLOQUES.carga_altas.hacer(ctx(),D({resumen:{}}));assert.equal(m.valor,null);assert(m.motivo.includes('Sin dato'));});
test('No mutation real DTO',()=>{const c=crm(),s=JSON.stringify(c);box.secundariosCRM317(ctx(),c);assert.equal(JSON.stringify(c),s);});
console.log(n+' grupos CRMsecundario317 PASS');
