const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.attrs=a;this.hidden=!!a.hidden;this.style=a.style||{};this.children=[];this.on=a.on||{};this.append(...kids)}append(...kids){this.children.push(...kids.flat(Infinity).filter(x=>x!=null))}replaceChildren(...kids){this.children=[];this.append(...kids)}get childNodes(){return this.children}get lastElementChild(){return this.children.filter(x=>x instanceof N).at(-1)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}set textContent(x){this.replaceChildren(x)}setAttribute(k,v){this.attrs[k]=v}querySelectorAll(){return []}querySelector(){return null}desc(){return this.children.filter(x=>x instanceof N).flatMap(x=>[x,...x.desc()])}}
const h=(t,a,...kids)=>new N(t,a,kids);let options;let nav=0;let valid=true;let stopped=0;
const e={h,ID:'salud-crm',EST:{gris:{o:3,t:'Sin dato'},verde:{o:2,t:'Bien'},ambar:{o:1,t:'Vigilar'},rojo:{o:0,t:'Crítico'}},fmt:{num:x=>x==null?'Sin dato':String(x)},pc:x=>x+'%',logoCliente:()=>null,chipsFiltro:o=>Object.assign(h('div',{}),{valor:()=>''}),cuentagotas:()=>f=>f.estado,pesoSub:()=>0,tablaDensa:o=>{options=o;return h('table',{})},puntoEstado:(_,t)=>h('span',{},t),numFuerte:x=>x==null?h('span',{},'Sin dato'):String(x),abrirGHL:link=>link?h('a',{href:link},'GHL'):null,MOVIL:()=>false,panel:(o,...kids)=>h('section',{},...kids)};vm.createContext(e);
const s=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');vm.runInContext(s.slice(s.indexOf('function pintarSubcuentas('),s.indexOf('// ------------------------------------------------------------------ pestaña: leads sin tocar')),e);
const row={sub_id:'s',nombre:'Cliente fixture',estado:'gris',tipo:'cliente',enlaces:{ghl:'https://app.gohighlevel.com/fixture'},especialista:'Persona',mot1:{texto:'Motivo operativo completo'},leads_30d:null,leads_meta_7d:null,citas_14d:{sin_estado:null},citas_30d:{asistencia_pct:null},velocidad:{juzgables:0}};
const d={subcuentas:[row,{...row,sub_id:'foreign'}],fuentes:{ghl:{hora:'2026-10-03'},captacion:{hora:'2026-10-02'}}};const ctx={nivel:'suyo',soloLectura:true,navegar:()=>nav++,vigente:()=>valid};const zone=h('main',{});
e.pintarSubcuentas(zone,ctx,d,{jefatura:false,base:[row],mias:[row]});assert.equal(options.columnas.length,8);assert.equal(options.filas.length,1);assert(zone.textContent.includes('min-width:900px'));assert(zone.textContent.includes('th button{padding:0}'));assert(zone.textContent.includes('font-size:13px'));assert(zone.textContent.includes('th:first-child{width:18%}'));assert(zone.textContent.includes('th:last-child{width:14%}'));assert(options.columnas.find(x=>x.clave==='v1h').titulo==='Intento <1h');
const lead=options.columnas.find(x=>x.clave==='leads_30d').celda(row);assert(lead.attrs['aria-label'].includes('GHL30d: Sin dato'));assert(lead.attrs['aria-label'].includes('Meta7d: Sin dato'));assert(!/GHL30d:\s+0/.test(lead.textContent));
const observed=options.columnas.find(x=>x.clave==='leads_30d').celda({...row,leads_30d:0,leads_meta_7d:2});assert(observed.attrs['aria-label'].includes('GHL30d: 0'));assert(observed.attrs['aria-label'].includes('Meta7d: 2'));
const appt=options.columnas.find(x=>x.clave==='se').celda(row);assert(appt.textContent.includes('—'));assert(appt.attrs['aria-label'].includes('Sin dato'));assert(!appt.textContent.includes('0%'));const measured=options.columnas.find(x=>x.clave==='se').celda({...row,citas_14d:{sin_estado:0},citas_30d:{asistencia_pct:75}});assert(measured.attrs['aria-label'].includes('Citas sin estado14d: 0'));assert(measured.textContent.includes('75%'));
const node=options.columnas.find(x=>x.clave==='ir').celda(row);const b=node.desc().find(x=>x.tag==='button');const detail=node.desc().find(x=>x.hidden);assert.equal(detail.childNodes.length,0);b.on.click({stopPropagation:()=>stopped++});assert.equal(stopped,1);assert.equal(nav,0);assert.equal(b.attrs['aria-expanded'],'true');assert(detail.textContent.includes('Motivo operativo completo'));assert(detail.textContent.includes('2026-10-03'));assert(detail.textContent.includes('no constituye una cohorte'));assert(detail.desc().some(x=>x.attrs.href==='#/salud-crm/s'));assert(node.desc().some(x=>x.attrs.href==='https://app.gohighlevel.com/fixture'));
b.on.click({stopPropagation(){}});assert.equal(detail.hidden,true);valid=false;b.on.click({stopPropagation(){}});assert.equal(detail.hidden,true);valid=true;options.alPulsar(row);assert.equal(nav,1);
console.log('7 grupos245 PASS: tabla real8columnas/scopedcartera, unknown!=0, recuentos independientes, citasobservadas, detallelazy/fechas, enlaceGHL, stale y rowclick.');
