const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(t,a={}){this.tag=t;this.attrs=a;this.children=[];this.events=a.on||{};this.isConnected=true;this.style={};this.value='';}append(...xs){this.children.push(...xs.flat(Infinity).filter(x=>x!==null&&x!==undefined));}replaceChildren(...xs){this.children=[];this.append(...xs);}addEventListener(k,v){this.events[k]=v;}setAttribute(k,v){this.attrs[k]=v;}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}}
const h=(t,a,...xs)=>{const n=new N(t,a);n.append(...xs);return n;},box={h,Date,Intl,Map,Set,Number};vm.createContext(box);vm.runInContext(fs.readFileSync('modulos/_operaciones_urgencias_406.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,''),box);
const row={tarea_id:'t1',cliente_id:'c',lista_id:'l',prioridad:'urgent',estado:'en curso',tipo_estado:'custom',clasificacion:'abierta_en_copia_por_contrastar',final_flujo_en_copia:false,estado_fuente:'clickup',estado_leido_utc:'2026-10-03T13:00:00Z',prioridad_fuente:'clickup_cache_literal',prioridad_leida_utc:null,medicion_urgencia:null,es_fuego_actual:null,verificacion_conjunta:false,ejecucion_verificada:false,aceptacion_verificada:false};
const dto=()=>({version:'402.1',grupo:'abiertas',urgencias_actuales:null,verificacion_conjunta:false,cumplimiento:null,cliente_ids:['c'],filas:[{...row}],estado:'copia_observada',fuente_version:'398.1',fuente:'clickup_cache_local',cobertura:'parcial',corte_preparacion_utc:'2026-10-04T00:00:00Z',generado:'2026-10-04T01:00:00Z',lectura_desde_utc:row.estado_leido_utc,lectura_hasta_utc:row.estado_leido_utc,abiertas_en_copia:1,observaciones:1});
const ctx=()=>{const p={id:'ops',estado:'activo',puestos:['operaciones']},c={id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true};return {servidor:true,hoy:'2026-10-04',real:p,persona:p,datos:{personas:[p]},clientes:[{...c}],clientesVisibles:[c],veModulo:()=>true,ver:()=>({ok:true}),api:async()=>dto(),vigente:()=>true};};
const all=(n,p)=>[...(n instanceof N&&p(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,p)):[])];
let n=0;const test=async f=>{await f();n++;};
(async()=>{
await test(()=>{const c=ctx(),m=box.proyectarUrgencias406(c,dto(),box.ambitoUrgencias406(c));assert.equal(m.filas.length,1);assert(!JSON.stringify(m).includes('es_fuego_actual'));});
await test(()=>{for(const patch of [{prioridad:'high'},{final_flujo_en_copia:true},{tipo_estado:'done'},{es_fuego_actual:true},{verificacion_conjunta:true},{cliente_id:'fuera'},{estado_leido_utc:'2026-02-30T12:00:00Z'}]){const c=ctx(),d=dto();Object.assign(d.filas[0],patch);assert.equal(box.proyectarUrgencias406(c,d,box.ambitoUrgencias406(c)),null);}});
await test(()=>{const c=ctx(),d=dto();d.filas.push({...row});assert.equal(box.proyectarUrgencias406(c,d,box.ambitoUrgencias406(c)),null);});
await test(()=>{const c=ctx(),d=dto();d.abiertas_en_copia=10;assert.equal(box.proyectarUrgencias406(c,d,box.ambitoUrgencias406(c)),null);});
await test(async()=>{let reads=0;const c=ctx();c.clientes[0].activo_confirmado=false;c.api=async()=>{reads++;return dto();};const root=new N('main');await box.renderUrgencias406(root,c);assert.equal(reads,0);});
await test(async()=>{for(const mutate of [c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false}),c=>c.veModulo=()=>false,c=>c.clientes.push({...c.clientes[0]})]){const c=ctx(),root=new N('main');let resolve;c.api=()=>new Promise(r=>resolve=r);const pending=box.renderUrgencias406(root,c);mutate(c);resolve(dto());await pending;assert.equal(root.textContent,'');}});
await test(async()=>{const c=ctx(),root=new N('main');await box.renderUrgencias406(root,c);assert(root.textContent.includes('Cliente fixture'));assert(root.textContent.includes('pendientes de contraste'));const b=all(root,x=>x.tag==='button')[0];b.events.click();assert(root.textContent.includes('t1'));assert(all(root,x=>x.tag==='a')[0].attrs.href.endsWith('/t1'));c.clientes[0].activo_confirmado=false;b.events.click();assert.equal(root.textContent,'');});
await test(async()=>{const c=ctx(),root=new N('main');c.api=async()=>{throw Error('503');};await box.renderUrgencias406(root,c);assert(root.textContent.includes('Falta una lectura'));assert(!root.textContent.includes('0'));});
await test(async()=>{const c=ctx(),root=new N('main'),d=dto();d.filas=[];d.observaciones=null;d.abiertas_en_copia=null;d.lectura_desde_utc=null;d.lectura_hasta_utc=null;c.api=async()=>d;await box.renderUrgencias406(root,c);assert(root.textContent.includes('por confirmar'));assert(!root.textContent.includes('no hay fuegos'));});
await test(()=>{const c=ctx(),antes=box.ambitoUrgencias406(c);c.persona={...c.persona,id:'otro'};assert.equal(box.proyectarUrgencias406(c,dto(),antes),null);});
console.log(n+' grupos406 PASS: urgencias separadas, snapshot desconocido, scopes actuales, fechas/partición, revocación y detalle local sin POST.');
})().catch(e=>{console.error(e);process.exitCode=1;});
