// Renderer263 y lectores364/390 reales, ESM temporal y DOM sintético; sin HTTP.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_accounts_263.cjs','utf8').split('(async()=>{try{')[0];
const {dir}=new Function('require','__dirname',prefix+';return {dir};')(require,__dirname);
const clone=x=>JSON.parse(JSON.stringify(x)),walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
function dto(){const cut='2026-10-05',dias=Array.from({length:90},(_,i)=>{const fecha=new Date(Date.parse(cut+'T00:00:00Z')-(90-i)*864e5).toISOString().slice(0,10),known=fecha==='2026-10-03';return {fecha,estado:known?'observado':'sin_dato',horas:known?38.37:null,entradas:known?1:null};});return {version:'362.1',estado:'copia_observada',generado:'2026-10-05T01:00:00Z',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',unidad:'h',cumplimiento:null,capacidad_contractual:null,personas:[{persona_id:'acc',historial_diario:{version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona:'Europe/Madrid',zona_confirmada:true,desde:dias[0].fecha,hasta:dias.at(-1).fecha,corte_fecha:cut,fecha_fuente_utc:'2026-10-05T00:30:00Z',atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,dias}}]};}
function ctx(){const ps=[{id:'ops',estado:'activo',puestos:['operaciones']},{id:'acc',estado:'activo',puestos:['account']}],cs=[{id:'ok',nombre:'Cliente sintético',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}];return {servidor:true,hoy:'2026-10-05',real:clone(ps[0]),persona:clone(ps[0]),datos:{personas:clone(ps),asignaciones:[]},clientes:clone(cs),clientesVisibles:clone(cs),veModulo:()=>true,ver:()=>({ok:true}),nombre:x=>x,vigente:()=>true,api:async r=>r==='horas/historial-diario'?dto():null,datosModulo:async()=>null};}
let passed=0;async function test(name,f){try{await f();passed++;}catch(e){throw Error(name+': '+e.message)}}
(async()=>{try{
 const {h,N}=await import('file://'+path.join(dir,'componentes.mjs'));N.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(N.prototype,'className',{get(){return this.attrs.class||'';},set(v){this.attrs.class=v;}});
 const {renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 const mount=async(c,r='accounts')=>{const root=h('main',{});root.connected=true;await renderAccounts263(root,c,r);return root;};const hours=root=>walk(root).find(x=>x.tag==='button'&&x.attrs['aria-label']?.startsWith('acc · Imputa'));
 await test('correct complete typed series and exactly oneGET',async()=>{const c=ctx();let n=0;c.api=async r=>{if(r==='horas/historial-diario'){n++;return dto();}return null;};const root=await mount(c);assert.equal(n,1);assert.equal(text(hours(root)),'38,4');assert(hours(root).attrs.class.includes('ref390-verde'));assert(!text(hours(root)).includes('≥'));});
 await test('source unavailable no238orweekfallback',async()=>{const c=ctx();c.api=async r=>{if(r==='horas/historial-diario')throw {status:503};return null;};c.datosModulo=async r=>r==='horas/horas'?{personas:[{persona_id:'acc',semana:999}]}:null;const root=await mount(c);assert.equal(text(hours(root)),'—');});
 await test('only accounts/control subroutes read personal history',async()=>{for(const ruta of ['clientes','hoy']){const c=ctx();let n=0;c.api=async r=>{if(r==='horas/historial-diario')n++;return null;};await mount(c,ruta);assert.equal(n,0);}});
 await test('revoked source/grants late await no value publication',async()=>{for(const change of [c=>c.veModulo=m=>m!=='horas',c=>c.ver=()=>({ok:false}),c=>c.datos.personas[1].estado='baja',c=>c.persona.id='acc']){const c=ctx();let resolve,started;const entered=new Promise(r=>started=r),deferred=new Promise(r=>resolve=r);c.api=async r=>{if(r==='horas/historial-diario'){started();return deferred;}return null;};const root=h('main',{});root.connected=true;const pending=renderAccounts263(root,c,'accounts');await entered;change(c);resolve(dto());await pending;assert(!text(root).includes('38,4'));}});
 await test('detached old frame cannot open source after async repaint',async()=>{const c=ctx();let resolve,entered;const start=new Promise(r=>entered=r),p=new Promise(r=>resolve=r);c.api=async r=>{if(r==='horas/historial-diario'){entered();return p;}return null;};const root=h('main',{});root.connected=true;const pending=renderAccounts263(root,c,'accounts');await start;const old=hours(root);assert(old);resolve(dto());await pending;assert(!old.isConnected);old.events.click();assert(!walk(root).some(x=>x.attrs.class==='detalle250'));});
 await test('preopened details cleared after revocation',async()=>{const c=ctx(),root=await mount(c),b=hours(root);b.events.click();assert(text(root).includes('38,4 h personales observadas'));c.veModulo=m=>m!=='horas';b.events.click();assert(!text(root).includes('38,4 h personales observadas'));assert(!text(root).includes('38,4'));});
 await test('navigation during late history cannot repaint detached root',async()=>{const c=ctx();let resolve,entered;const start=new Promise(r=>entered=r),p=new Promise(r=>resolve=r);c.api=async r=>{if(r==='horas/historial-diario'){entered();return p;}return null;};const root=h('main',{});root.connected=true;const pending=renderAccounts263(root,c,'control');await start;root.replaceChildren();resolve(dto());await pending;assert(!text(root).includes('38,4'));});
 console.log(passed+' grupos393B independientes PASS · render263+364+390 reales/asíncronos.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e.message);process.exitCode=1});
