const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.attrs=a;this.hidden=!!a.hidden;this.style=a.style||{};this.children=[];this.on=a.on||{};this.append(...kids)}append(...kids){this.children.push(...kids.flat(Infinity).filter(x=>x!=null))}replaceChildren(...kids){this.children=[];this.append(...kids)}get childNodes(){return this.children}get lastElementChild(){return this.children.filter(x=>x instanceof N).at(-1)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}set textContent(x){this.replaceChildren(x)}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,fn){this.events??={};this.events[k]=fn}querySelectorAll(){return []}querySelector(){return null}desc(){return this.children.filter(x=>x instanceof N).flatMap(x=>[x,...x.desc()])}}
const h=(t,a,...kids)=>new N(t,a,kids);let options;let saved=0;let edits=0;let stopped=0;
const e={h,S:['0','2px','4px','6px','8px'],NOWRAP:{whiteSpace:'nowrap'},GRAV:{dato:{o:3,t:'Sin dato'}},GRAV_CLI:{critico:{t:'Crítico'},atencion:{t:'Vigilar'},bien:{t:'Bien'}},CUELLO:{paid:{t:'Paid'},seguimiento:{t:'CRM'},integracion:{t:'Conexión'}},filtroPendiente:()=>null,
 chipsFiltro:o=>Object.assign(h('div',{}),{valor:()=>o.multiple?[]:''}),panelPaid:c=>c.panelEspecialista,medirCplPaid:()=>({real:null}),hoyMadrid:()=> '2026-10-03',gc:()=>({o:1,t:'Vigilar'}),nombre:(_,id)=>id,textoMot:x=>x.texto,tablaDensa:o=>{options=o;return h('table',{})},logoCliente:()=>null,esTienda:()=>false,chipEstado:(_,t)=>h('span',{},t),chipCli:()=>h('span',{},'Vigilar'),chipPub:()=>h('span',{},'Sin dato'),chipCuello:k=>h('span',{},k),icono:()=>null,num:x=>String(x),eur:x=>x==null?'Sin dato':x+'€',deltaMini:()=>null,candado:t=>h('span',{},t),fDiaRO:x=>x,avisoParcial:x=>h('span',{},x),hoyBit:()=>null,diaDe:x=>x.fecha,cuandoBit:()=> 'ayer',editorBitacora:()=>{edits++;return h('input',{})}};vm.createContext(e);
vm.runInContext(fs.readFileSync(__dirname+'/modulos/_matriz_paid_508.js','utf8').replace(/export /g,''),e);
const s=fs.readFileSync(__dirname+'/modulos/captacion.js','utf8');vm.runInContext(s.slice(s.indexOf('function pCuentas('),s.indexOf('function deltaMini(')),e);
const c={cliente_id:'fixture',nombre:'Cliente fixture',gravedad:'atencion',severidad:'dato',equipo:{trafficker:'persona'},meta_activa:true,dinero:true,leads:{'7d':0},gasto:{'7d':2},motivos:[{texto:'Motivo completo privado operativo'}],cpl_resumen:{ref:12,ref_base:'7d'},panelEspecialista:{real:12,objetivo:null,hasta:null,datoVigente:false,racha:null,creativos:null,fechaCreativos:null,accion:'Revisar datos antes de evaluar objetivo'}};
const d={parametros:{},bitacora:new Map()},ctx={nivel:'todo',soloLectura:false,navegar:()=>saved++,fechas:{esHoy:()=>false}};
const out=h('div',{});e.pCuentas(out,ctx,d,[c],{},{});assert.equal(options.columnas.length,9); // same trafficker: column intentionally hidden
assert(!options.columnas.some(x=>['hoy','motivo'].includes(x.clave)));assert(out.textContent.includes('min-width:900px'));assert(out.textContent.includes('font-size:13px'));
const mapped=options.filas[0];const action=options.columnas.find(x=>x.clave==='pendiente').celda(mapped);const button=action.desc().find(x=>x.tag==='button');const pane=out.desc().find(x=>x.attrs['aria-label']==='Detalle de la cuenta Paid');assert(pane);assert.equal(pane.childNodes.length,0);assert(!action.desc().some(x=>x.hidden));let detail;assert(button.textContent==='Ver');
button.on.click({stopPropagation:()=>stopped++});assert.equal(stopped,1);assert.equal(saved,0);assert.equal(button.attrs['aria-expanded'],'true');detail=pane.desc().find(x=>x.tag==='div'&&x.style.marginTop==='6px');assert(detail);assert(!action.desc().includes(detail));assert(detail.textContent.includes('Motivo completo'));assert(detail.textContent.includes('sin fecha'));assert(detail.textContent.includes('Objetivo sin confirmar')||detail.textContent.includes('Objetivo sin confirmar'.toLowerCase()));assert(detail.desc().some(x=>x.tag==='a'&&x.attrs.href==='#/captacion/fixture'));
const apuntar=detail.desc().find(x=>x.tag==='button'&&x.textContent.includes('Apuntar'));assert(apuntar);apuntar.on.click();assert.equal(edits,1);button.on.click({stopPropagation:()=>stopped++});assert.equal(detail.hidden,true);assert.equal(pane.childNodes.length,0);assert.equal(saved,0);
for(const readonly of [true,false]){const n=e.celdaRevisionCompacta243({...ctx,soloLectura:readonly,nivel:readonly?'todo':'resumen'},d,mapped);const b=n.desc().find(x=>x.tag==='button');b.on.click({stopPropagation(){}});assert(!n.desc().some(x=>x.tag==='button'&&x.textContent==='Apuntar'));}
const cell=options.columnas.find(x=>x.clave==='cplref').celda(mapped);assert(cell.textContent==='—');assert(cell.attrs.title.includes('— Sin dato'));assert(!cell.attrs.class.includes('verde'));const privateCell=options.columnas.find(x=>x.clave==='cplref').celda({...mapped,dinero:false});assert(!privateCell.textContent.includes('12€'));
assert.equal(options.columnas.find(x=>x.clave==='sinleads').celda(mapped).textContent,'—');const creative=options.columnas.find(x=>x.clave==='creativos').celda(mapped);assert.equal(creative.textContent,'—');assert(creative.attrs.title.includes('no confirma fatiga'));assert(out.textContent.includes('white-space:normal;overflow-wrap:normal'));const streak=options.columnas.find(x=>x.clave==='sinleads').celda({...mapped,panelEspecialista:{...mapped.panelEspecialista,racha:{dias:12,completa:true,hasta:'2026-10-02'}}});assert.equal(streak.textContent,'12');assert(streak.attrs.title.includes('2026-10-02'));options.alPulsar(mapped);assert.equal(saved,1);
console.log('8 grupos243 PASS: columnas/celdas reales compactas, detalles lazy, no navegación involuntaria, editor conservado, readonly/resumen, CPL desconocido y reservado, racha/creativos sin dato, navegación fila.');
