const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ro388-'));fs.chmodSync(dir,0o700);
const harness=fs.readFileSync(path.join(__dirname,'pruebas_operaciones_accounts_263.cjs'),'utf8');
const stub=harness.match(/fs.writeFileSync\(path.join\(dir,'componentes.mjs'\),`([\s\S]*?)`\);/)[1];fs.writeFileSync(path.join(dir,'componentes.mjs'),stub);
for(const name of ['_mensaje_alarma_345','_alarmas_operaciones_342','_top_alarmas_388']){let s=fs.readFileSync(path.join(__dirname,'modulos',name+'.js'),'utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'").replace("from '../componentes.js'","from './componentes.mjs'");fs.writeFileSync(path.join(dir,name+'.mjs'),s);}
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
let groups=0;const test=(label,f)=>{f();groups++;};
(async()=>{try{
const {h}=await import('file://'+path.join(dir,'componentes.mjs')),{seleccionarTop388,modeloTop388,pintarTop388,ambitoTop388}=await import('file://'+path.join(dir,'_top_alarmas_388.mjs')),{proyectarAlarmas342}=await import('file://'+path.join(dir,'_alarmas_operaciones_342.mjs'));
const copy=x=>JSON.parse(JSON.stringify(x));
function ctx(){const p={id:'ops',estado:'activo',puestos:['operaciones']},cs=Array.from({length:8},(_,i)=>({id:'c'+i,nombre:'Cliente '+i,activo_confirmado:true,detalle:true}));return {real:copy(p),persona:copy(p),servidor:true,hoy:'2026-10-04',vigente:()=>true,veModulo:()=>true,ver:()=>({ok:true}),datos:{personas:[copy(p),{id:'account',estado:'activo',puestos:['account']}],asignaciones:[]},clientes:copy(cs),clientesVisibles:copy(cs),carteraPorSilla:{account:cs.map(x=>x.id)}};}
const alarm=(id,cid,tipo='acc_critico',extra={})=>({id,cliente_id:cid,tipo,titulo:'Título '+id,motivo:'Evidencia '+id,gravedad:'alta',ir:'#/en-rojo',...extra});
const doc=rows=>({generado:'2026-10-03T12:00:00Z',alertas:rows}),row=(id,cid,tipo,extra={})=>({id,cliente_id:cid,tipo,gravedad:'rojo',...extra});
const sample=[alarm('a0','c0'),alarm('a1','c0','acc_correos'),alarm('a2','c0','web_caida'),alarm('a3','c1'),alarm('a4','c2','alta_fuera_plazo'),alarm('a5','c3','acc_correos'),alarm('a6','c4','web_caida'),alarm('a7','c5','web_caida'),alarm('a8','c6')];
test('original independently executes round robin for matching exact categories',()=>{const src=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8'),start=src.indexOf('function vHoy(){'),slice=src.slice(start,src.indexOf('  const k=',start)),run=new Function('D','MES',slice.replace('function vHoy(){','')+';return top;');const rs=[row('a','c0','Semáforo en rojo'),row('b','c1','Semáforo en rojo'),row('c','c2','Cliente nuevo fuera de plazo'),row('d','c3','Sin responder'),row('e','c4','Revisión del account >48 h'),row('f','c5','Semáforo sin rellenar')],old=run({alarmas:rs.map(x=>({...x,cliente:x.cliente_id}))},'Octubre');assert.deepEqual(seleccionarTop388(rs).map(x=>x.id),old.map(x=>x.id));assert.equal(old.length,6);});
test('actual collection six slots do not duplicate a client',()=>{const c=ctx(),d=doc(sample),full=proyectarAlarmas342(c,d),m=modeloTop388(c,d);assert.equal(full.filas.length,9);assert.equal(m.top.length,6);assert.equal(new Set(m.top.map(x=>x.cliente_id)).size,6);assert.deepEqual(m.top.slice(0,3).map(x=>x.tipo),['acc_critico','alta_fuera_plazo','acc_correos']);assert.equal(d.alertas.length,9);});
test('343 source-shaped projected records preserve full list and rotated Top6',()=>{const types=['web_caida','acc_sin_agente','acc_critico','alta_fuera_plazo','acc_correos','crm_sin_tocar','gbp_perfil'],alerts=Array.from({length:343},(_,i)=>alarm(types[i%types.length]+':fixture-'+i,'c'+(i%8),types[i%types.length],{gravedad:i%3?'alta':'media'})),c=ctx(),d=doc(alerts),full=proyectarAlarmas342(c,d),m=modeloTop388(c,d);assert.equal(full.filas.length,343);assert.equal(m.registros,343);assert.equal(m.top.length,6);assert.equal(new Set(m.top.map(x=>x.cliente_id)).size,6);assert(m.top.every(x=>x.id.includes(':')));const main=h('main',{});main.connected=true;const root=pintarTop388(main,c,d);assert.equal(walk(root).filter(x=>x.tag==='article').length,6);assert.equal(d.alertas.length,343);});
test('model never fabricates red or selects persons/internal-only alerts',()=>{const c=ctx(),m=modeloTop388(c,doc([alarm('a','c0',undefined,{gravedad:'media'}),alarm('b',null),alarm('c','c1')]));assert.equal(m.top.length,1);assert.equal(m.top[0].cliente_id,'c1');});
test('duplicate alarm ID rejected rather than pick first',()=>assert.equal(seleccionarTop388([row('same','c0','acc_critico'),row('same','c1','acc_critico')]).length,0));
test('provider source-shaped colon alarm IDs remain typed and distinct',()=>{const c=ctx(),d=doc([alarm('web_caida:c0','c0','web_caida'),alarm('acc_sin_agente:i-9ae93bbbf9','c1','acc_sin_agente')]);const m=modeloTop388(c,d);assert.equal(m.top.length,2);assert.deepEqual(m.top.map(x=>x.id).sort(),['acc_sin_agente:i-9ae93bbbf9','web_caida:c0']);assert.equal(seleccionarTop388([row('web_caida:c0','c0','web_caida'),row('web_caida:c0','c1','web_caida')]).length,0);assert.equal(seleccionarTop388([row('web_caida:c0','client:invalid','web_caida')]).length,0);});
test('typed IDs and malformed severity no selection',()=>assert.equal(seleccionarTop388([row('a',{},'acc_critico'),row('b','c0','acc_critico',{gravedad:'alta'}),{id:[],cliente_id:'c1',tipo:'acc_critico',gravedad:'rojo'}]).length,0));
test('ACT current not stale visible grants either catalogue',()=>{for(const f of [c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push(copy(c.clientes[0])),c=>c.clientes=[],c=>c.clientesVisibles.push(copy(c.clientesVisibles[0]))]){const c=ctx();f(c);assert.equal(modeloTop388(c,doc([alarm('a','c0')])).top.length,0);}});
test('scope rejects canonical actor role mismatch and duplicate',()=>{const c=ctx();c.persona.puestos=['seo'];assert.equal(ambitoTop388(c),null);const d=ctx();d.datos.personas.push(copy(d.real));assert.equal(ambitoTop388(d),null);});
test('Account uses own canonical scope and intersect granted clients',()=>{const c=ctx();c.real=c.persona={id:'account',estado:'activo',puestos:['account']};c.carteraPorSilla.account=['c1'];assert.deepEqual(modeloTop388(c,doc(sample)).top.map(x=>x.cliente_id),['c1']);c.ver=x=>({ok:x.cliente_id!=='c1'});assert.equal(modeloTop388(c,doc(sample)).top.length,0);});
test('filters account client type severity preserve collection',()=>{const c=ctx(),rs=[{cliente_id:'c0',account_id:'account'},{cliente_id:'c1',account_id:'account'}];assert.equal(modeloTop388(c,doc(sample),rs,{cliente:'c0'}).top.length,1);assert.equal(modeloTop388(c,doc(sample),rs,{tipo:'web_caida'}).top.length,3);assert.equal(modeloTop388(c,doc(sample),rs,{gravedad:'ambar'}).top.length,0);assert.equal(modeloTop388(c,doc(sample),rs,{account:'account'}).top.length,2);assert.equal(modeloTop388(c,doc(sample),rs,{account:'foreign'}).top.length,0);});
test('future absent source and no rows never green claims',()=>{const c=ctx();assert.equal(modeloTop388(c,null),null);assert.equal(modeloTop388(c,{...doc([]),generado:'2026-10-05T12:00:00Z'}),null);const n=h('main',{});n.connected=true;const r=pintarTop388(n,c,doc([]));assert.match(text(r),/No acredita ausencia/);assert.equal(walk(r).filter(x=>x.tag==='article').length,0);});
test('real render compact six distinct native closed details and source',()=>{const n=h('main',{});n.connected=true;const r=pintarTop388(n,ctx(),doc(sample));assert.equal(walk(r).filter(x=>x.tag==='article').length,6);assert.equal(walk(r).filter(x=>x.tag==='details'&&x.attrs.open).length,0);assert.match(text(r),/corte 2026-10-03/);assert.match(text(r),/cobertura parcial/);assert.equal(new Set(walk(r).filter(x=>x.tag==='article').map(x=>x.attrs['data-cliente-top'])).size,6);});
for(const [name,change] of [['ACT',c=>c.clientes[0].activo_confirmado=false],['details grant',c=>c.ver=x=>({ok:x.tipo!=='alarma_detalle'})],['roles',c=>c.persona.puestos=['seo']],['scope epoch',c=>c.vigente=()=>false]])test('real details revocation '+name,()=>{const c=ctx(),n=h('main',{});n.connected=true;const r=pintarTop388(n,c,doc(sample));change(c);walk(r).find(x=>x.tag==='details').events.toggle({});assert.equal(walk(r).filter(x=>x.tag==='article').length,0);assert.doesNotMatch(text(r),/Evidencia a/);});
test('real origin click revoked prevents navigation and clears',()=>{const c=ctx(),n=h('main',{});n.connected=true;const r=pintarTop388(n,c,doc(sample));c.veModulo=()=>false;let stopped=false;walk(r).find(x=>x.tag==='a').events.click({preventDefault:()=>stopped=true});assert(stopped);assert.equal(walk(r).filter(x=>x.tag==='article').length,0);});
test('input snapshots remain unchanged',()=>{const c=ctx(),d=doc(sample),before=JSON.stringify(d);modeloTop388(c,d);assert.equal(JSON.stringify(d),before);});
console.log(groups+' grupos388 PASS · selección original y renderer real342/388');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
