const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
class N{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.events={};this.style={};this.isConnected=true;}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){this.children.push(x);if(x instanceof N)x.parent=this;}}replaceChildren(...xs){this.children=[];this.append(...xs);}setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}set className(v){this.attrs.class=v;}addEventListener(k,fn){this.events[k]=fn;}focus(){}querySelectorAll(){return[];}}
const c={Date,Intl,Number,Map,Set,Promise,Node:N,document:{createElement:t=>new N(t),createTextNode:s=>String(s)}};vm.createContext(c);
const component=fs.readFileSync(path.join(__dirname,'componentes.js'),'utf8');vm.runInContext(component.slice(component.indexOf('export function urlSegura('),component.indexOf('export function h(')).replace('export ',''),c);vm.runInContext(component.slice(component.indexOf('export function h('),component.indexOf('const svgNS =')).replace('export ',''),c);
function load(file,exports){const s=fs.readFileSync(path.join(__dirname,'modulos',file),'utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');Object.assign(c,vm.runInContext(`(()=>{${s}\nreturn {${exports.join(',')}}})()`,c));}
load('_cabeceras_operaciones_423.js',['cabeceraOperaciones423']);load('_pauta_proporcional_306.js',['pautaProporcional306']);load('control_cartera.js',['pautaHorasControl','prepararControlCartera']);load('_operaciones_registros_269.js',['filaAvisado269']);load('_operaciones_anomalias_276.js',['controlAnomalia276']);load('_horas_diarias_238.js',['serieHorasDiaria238']);load('_operaciones_notas_equipo_281.js',['panelEquipoNotas281','observacionesSemana281']);load('_produccion_baseline.js',['planificacionBaseline']);load('_produccion_creadas_287.js',['creadasSemana287','panelComparacionSemanal296','modeloComparacionSemanal296']);load('_planning_comparacion_320.js',['comparacionCreadores320']);load('_account_fuegos_346.js',['accountFuego346']);load('_planning_observado_360.js',['ambitoPlanning360','proyectarPlanning360','panelPlanningObservado360']);load('_bandas_horas_381.js',['bandaHoras381','formatearBanda381','cssBandas381','leyendaHoras381']);load('_ejemplos_creador_438.js',['ambitoEjemplos438','modeloEjemplos438','panelEjemplosCreador438']);load('_operaciones_equipo_262.js',['renderEquipo262','INVENTARIO_EQUIPO_262','diasLaborables262','horasRango262','referenciaHoras262','horasProyectoRango262','pautaProyectoRango262']);
const all=(n,p)=>[...(n instanceof N&&p(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,p)):[])],text=n=>n instanceof N?n.children.map(text).join(' '):String(n??'');
const cp=require('child_process');
const dto=JSON.parse(cp.execFileSync('python3',['-c',"import json;import probar_integracion_comparacion_296 as F;import evidencia_produccion_287 as M;print(json.dumps(M.aplicar296({'proyectos':[{'cliente_id':'a','cliente':'Cliente fixture'}],'personas':[{'persona_id':'p','nombre':'Persona fixture'}]},F.fixture(),{'a'},{'p'},M.SHA296,M.SHA296)))"],{encoding:'utf8'}));
const clone=x=>JSON.parse(JSON.stringify(x));
const ctx=()=>({hoy:'2026-10-03',real:{id:'ops'},persona:{id:'ops'},clientes:[{id:'a',activo_confirmado:true,detalle:true}],clientesVisibles:[{id:'a',activo_confirmado:true,detalle:true}],datos:{personas:[{id:'p',estado:'activo',nombre:'Persona fixture'}]},ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,datosModulo:async()=>clone(dto)});

let n=0;const test=async(l,f)=>{await f();n++;console.log('PASS '+l);};
const make491=()=>{const d=clone(dto);d.personas.push({persona_id:'q',nombre:'Pendiente fixture',creadas:0},{persona_id:'r',nombre:'Otra fixture'});const x=ctx();const actor={id:'ops',nombre:'Operaciones fixture',estado:'activo',puestos:['operaciones']};Object.assign(x,{servidor:true,real:clone(actor),persona:clone(actor),datos:{personas:[actor,{id:'p',nombre:'Persona fixture',estado:'activo',puestos:['account']},{id:'q',nombre:'Pendiente fixture',estado:'activo',puestos:['account']},{id:'r',nombre:'Otra fixture',estado:'activo',puestos:['account']}]},api:async()=>{throw Error('Fuente opcional ausente fixture');},datosModulo:async()=>clone(d)});return {x,d};};
const select491=root=>all(root,q=>q.tag==='select'&&q.attrs['aria-label']==='Cobertura de creadores')[0];
const input491=root=>all(root,q=>q.tag==='input'&&q.attrs['aria-label']==='Buscar creador')[0];
const matrix491=root=>all(root,q=>q.attrs['data-planning-creadores491']!==undefined)[0];
const rows491=root=>all(matrix491(root),q=>q.tag==='tbody')[0].children;
(async()=>{
await test('Default sólo observaciones tipadas; referencia0 no observada',async()=>{const {x}=make491(),root=new N('main');await c.renderEquipo262(root,x,'planificacion');assert.equal(select491(root).value,'observados');assert.equal(rows491(root).length,1);assert(text(rows491(root)[0]).includes('Persona fixture'));assert(!text(matrix491(root)).includes('Pendiente fixture'));assert(text(root).includes('1/3 creadores'));assert.equal(all(matrix491(root),q=>q.tag==='th').length,8);});
await test('Todos y pendientes preservan creadores/7KPI originales',async()=>{const {x}=make491(),root=new N('main');await c.renderEquipo262(root,x,'planificacion');const s=select491(root);s.value='todos';s.events.change();assert.equal(rows491(root).length,3);assert(text(matrix491(root)).includes('Pendiente fixture'));s.value='pendientes';s.events.change();assert.equal(rows491(root).length,2);assert(!text(matrix491(root)).includes('Persona fixture'));assert(all(matrix491(root),q=>q.tag==='th')[5].attrs.title==='Semana pasada');});
await test('Búsqueda combina cobertura y puede restablecerse sin POST',async()=>{const {x}=make491(),root=new N('main');let posts=0;x.accion=()=>{posts++;throw Error('POST prohibido');};await c.renderEquipo262(root,x,'planificacion');const s=select491(root),b=input491(root);s.value='todos';s.events.change();b.value='PENDIENTE';b.events.input();assert.equal(rows491(root).length,1);assert(text(rows491(root)[0]).includes('Pendiente fixture'));b.value='no existe';b.events.input();assert(text(matrix491(root)).includes('Sin filas disponibles'));b.value='';b.events.input();assert.equal(rows491(root).length,3);assert.equal(posts,0);});
await test('Inventario360 aparece antes de Disciplina y se conserva comparación',async()=>{const {x}=make491(),root=new N('main');await c.renderEquipo262(root,x,'planificacion');const content=text(root);assert(content.indexOf('Inventario de planificación')>=0);assert(content.indexOf('Inventario de planificación')<content.indexOf('Disciplina de planificación'));assert(content.includes('Creaciones y cierres')||content.includes('Comparación')||content.includes('comparación'));});
for(const mode of ['roles','grant','ACT','identity','module'])await test('Callback revocado '+mode,async()=>{const {x}=make491(),root=new N('main');await c.renderEquipo262(root,x,'planificacion');const s=select491(root);if(mode==='roles')x.persona.puestos=['operaciones','seo'];if(mode==='grant')x.ver=()=>({ok:false});if(mode==='ACT')x.clientes[0].activo_confirmado=false;if(mode==='identity')x.persona.id='other';if(mode==='module')x.veModulo=()=>false;s.value='todos';s.events.change();assert.equal(all(root,q=>q.tag==='table').length,0);});
await test('Cambio catálogo durante GETproducción no publica fuente antigua',async()=>{const {x,d}=make491(),root=new N('main');x.datosModulo=async()=>{x.datos.personas.push(clone(x.datos.personas[0]));return d;};assert.equal(await c.renderEquipo262(root,x,'planificacion'),false);assert.equal(root.children.length,0);});
await test('Cambio ACT durante fuente360 limpia antes de matriz',async()=>{const {x}=make491(),root=new N('main');x.api=async()=>{x.clientes[0].activo_confirmado=false;throw Error('revocación fixture');};assert.equal(await c.renderEquipo262(root,x,'planificacion'),false);assert.equal(all(root,q=>q.tag==='table').length,0);});
await test('Actor canónico duplicado/inactivo no permite nuevo control',async()=>{for(const mode of ['duplicate','inactive']){const {x}=make491(),root=new N('main');if(mode==='duplicate')x.datos.personas.push(clone(x.datos.personas[0]));else x.datos.personas[0].estado='baja';assert.equal(await c.renderEquipo262(root,x,'planificacion'),false);assert.equal(all(root,q=>q.tag==='table').length,0);}});
await test('Predicado real admite0 sólo si valor acreditado; no null/bool/infinity',()=>{const match=fs.readFileSync(path.join(__dirname,'modulos/_operaciones_equipo_262.js'),'utf8').match(/observado:\[actual\?\.valor,anterior\?\.valor\]\.some\((v=>[^}]+)\)\}/);assert(match);const pred=vm.runInContext('('+match[1]+')',c);assert.equal(pred(0),true);for(const v of [null,undefined,false,Infinity,NaN,-1])assert.equal(pred(v),false);});
await test('ACT/grant cliente inicialmente revocado no expone matriz',async()=>{for(const mode of ['ACT','grant']){const {x}=make491(),root=new N('main');if(mode==='ACT')x.clientes[0].activo_confirmado=false;else x.ver=q=>({ok:q.tipo!=='cliente_detalle'});assert.equal(await c.renderEquipo262(root,x,'planificacion'),false);assert.equal(all(root,q=>q.tag==='table').length,0);}});
await test('Todos no recupera persona baja/duplicada/sin permiso personal',async()=>{for(const mode of ['baja','duplicate','grant']){const {x}=make491(),root=new N('main');if(mode==='baja')x.datos.personas.find(p=>p.id==='q').estado='baja';if(mode==='duplicate')x.datos.personas.push(clone(x.datos.personas.find(p=>p.id==='q')));if(mode==='grant')x.ver=q=>({ok:q.persona_id!=='q'});await c.renderEquipo262(root,x,'planificacion');const sel=select491(root);sel.value='todos';sel.events.change();assert.equal(rows491(root).length,2);assert(!text(matrix491(root)).includes('Pendiente fixture'));}});
console.log(n+' grupos planificación491 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
