const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class N{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.style={};this.events={};this.isConnected=false;}append(...xs){for(const x of xs){assert(!Array.isArray(x),'nativeappend must not receive arrays');this.children.push(x);if(x instanceof N){x.parent=this;attach(x,this.isConnected);}}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)attach(x,false);this.children=[];this.append(...xs);}setAttribute(k,v){this.attrs[k]=String(v);}set className(v){this.attrs.class=v;}addEventListener(k,f){this.events[k]=f;}querySelectorAll(){return [];}closest(){return null;}}
function attach(n,on=true){n.isConnected=on;for(const x of n.children)if(x instanceof N)attach(x,on);}
const b={Date,Intl,Map,Set,WeakSet,Promise,JSON,Number,Node:N,document:{createElement:t=>new N(t),createTextNode:t=>String(t)},matchMedia:()=>({matches:false}),MutationObserver:class{observe(){}},PUESTO:{}};vm.createContext(b);
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function urlSegura('),comp.indexOf('const svgNS =')).replace(/export /g,''),b);
function load(file,keys){const s=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');Object.assign(b,vm.runInContext('(()=>{'+s+';return {'+keys.join(',')+'};})();',b));}
load('_metodo_cohorte_305',['proyectarMetodo305']);load('_cadencia_metodo',['separarCadencias','estadoCadencia','textoCadencia','ambitoCadencia307']);load('_seguimiento_metodo_453',['ambitoSeguimiento453','evidenciaSeguimiento453','pintarSeguimiento453']);
const src=fs.readFileSync(__dirname+'/modulos/reuniones.js','utf8'),imports=[...src.matchAll(/import\s*{([^}]+)}\s*from\s*['"][^'"]+['"];?/g)];for(const m of imports)for(const key of m[1].split(',').map(x=>x.trim()).filter(Boolean))if(!(key in b))b[key]=()=>new N('auxiliar');
b.panel=(o,...xs)=>b.h('section',{},b.h('h2',{},o.titulo),o.sub,...xs);b.fmt={num:x=>x==null?'—':String(x),plural:(n,a,z)=>n+' '+(n===1?a:z),hace:()=>''};b.tiles=x=>b.h('div',{},x);b.tile=()=>null;b.pestanas=()=>new N('pestanas');b.plegarConsejo=()=>{};
vm.runInContext(src.replace(/^import[^;]+;\s*/gm,'').replace(/export default/,'const modulo453=').replace(/export /g,'')+';this.modulo453=modulo453;',b);
const all=n=>n instanceof N?[n,...n.children.flatMap(all)]:[],text=n=>n instanceof N?n.children.map(text).join(' '):String(n??''),pick=(n,t)=>all(n).filter(x=>x.tag===t),copy=x=>JSON.parse(JSON.stringify(x));
const actor={id:'ops',estado:'activo',activo:true,puestos:['operaciones'],nombre:'Operaciones fixture'},trafficker={id:'t',estado:'activo',activo:true,puestos:['publicidad'],nombre:'Trafficker fixture'};
function ctx(){const c={id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true};return {hoy:'2026-10-04',nivel:'todo',real:{...actor},persona:{...actor},datos:{personas:[copy(actor),copy(trafficker)]},clientes:[c],clientesVisibles:[{...c}],veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,titulo:()=>{},servidor:true,periodo:null};}
const evidence=(n=2)=>({version:'452.1',estado_fuente:'disponible',cobertura:'parcial',importado_el:'2026-10-03',registros_historicos_observados:n,ultimo_registro_historico:n?'2026-10-02':null,responsable_historico:null,celebracion_confirmada:null,participacion_trafficker_confirmada:null,faltantes:['celebracion','participacion_trafficker','responsable_en_fecha','cobertura_intervalo']});
const row=()=>({cliente_id:'c',regla_id:'seguimiento_quincenal_especialista',cadencia_dias:15,responsable_role:'trafficker',estado:'en_cadencia',incumplimiento:null,responsables_ids:['t'],responsable_id:'t',ultima_confirmada:'2026-09-25',proxima_revision:'2026-10-10',fuentes_operativas:[{tipo:'reunion_celebrada',fecha:'2026-09-25'}],evidencia_por_revisar:evidence()});
const doc=()=>({hoy:'2026-10-04',sugerencias:[row()],cobertura_reuniones:{completa:false}}),rows=(c,d)=>b.separarCadencias([{cliente_id:'c'}],d,b.ambitoCadencia307(c)).seguimiento;
function render(c=ctx(),d=doc()){return b.pintarSeguimiento453(b.h,c,rows(c,d),d,{ambitoInicial:b.ambitoSeguimiento453(c),vigente:()=>c.vigente()});}
function mount(n){const host=new N('main');attach(host);host.append(n);return host;}
function open(n){const d=pick(n,'details')[0];d.open=true;d.events.toggle();return d;}
let checks=0;async function test(l,f){await f();checks++;}
(async()=>{
 await test('available count retains partial nonverification contract',()=>{const m=b.evidenciaSeguimiento453(evidence(),'2026-10-04');assert.equal(m.registros,2);assert(m.detalle.includes('No confirma celebración'));});
 await test('zero only explicit available corpus, not zero meetings',()=>{const m=b.evidenciaSeguimiento453(evidence(0),'2026-10-04');assert.equal(m.registros,0);assert.equal(m.ultima,null);assert(m.detalle.includes('cobertura parcial'));});
 await test('malformed flags/version/date/unit cannot become measured',()=>{for(const mut of [e=>e.version='446.1',e=>e.celebracion_confirmada=true,e=>e.responsable_historico='t',e=>e.participacion_trafficker_confirmada=true,e=>e.registros_historicos_observados=true,e=>e.registros_historicos_observados=1.5,e=>e.registros_historicos_observados=-1,e=>e.registros_historicos_observados=Infinity,e=>e.importado_el='2026-10-05',e=>e.importado_el='2026-02-30',e=>e.ultimo_registro_historico='2026-10-04',e=>e.faltantes.pop(),e=>e.faltantes[0]='token',e=>e.cobertura='completa']){const e=evidence();mut(e);assert.equal(b.evidenciaSeguimiento453(e,'2026-10-04').registros,null);}});
 await test('unavailable/config/unauthorized unknown no IO',()=>{for(const state of ['sin_configurar','no_autorizado','no_disponible']){const e={...evidence(),estado_fuente:state,cobertura:'desconocida',registros_historicos_observados:null,ultimo_registro_historico:null,importado_el:null},m=b.evidenciaSeguimiento453(e,'2026-10-04');assert.equal(m.estado,state);assert.equal(m.registros,null);}});
 await test('new disconnected node builds, mounted disclosure paints seven cols',()=>{const n=render();assert.equal(n.isConnected,false);assert.equal(pick(n,'details').length,1);assert.equal(pick(n,'table').length,0);mount(n);open(n);assert.equal(pick(n,'th').length,7);const cells=pick(n,'tbody')[0].children[0].children;assert.equal(text(cells[0]),'Cliente fixture');assert.equal(text(cells[1]),'Trafficker fixture');assert.equal(text(cells[4]),'2');assert.equal(text(cells[5]),'02-oct');assert.equal(pick(n,'a')[0].attrs.href,'#/ficha/c/reunion');});
 await test('unmounted callbacks never expose table',()=>{const n=render();open(n);assert.equal(n.children.length,0);});
 await test('confirmed dates remain305, history cannot recolor',()=>{const c=ctx(),d=doc(),before=JSON.stringify(d),n=render(c,d);mount(n);open(n);const cells=pick(n,'tbody')[0].children[0].children;assert.equal(text(cells[2]),'25-sep');assert.equal(text(cells[3]),'10-oct');assert(pick(cells[3],'span')[0].attrs.class.includes('verde'));assert(!all(cells[4]).some(x=>/verde|rojo|ambar/.test(x.attrs.class||'')));assert(cells[3].attrs.title.includes('no es una cita agendada'));assert.equal(JSON.stringify(d),before);});
 await test('history with unknown confirmed date does not invent celebration',()=>{const c=ctx(),d=doc();Object.assign(d.sugerencias[0],{estado:'sin_dato',ultima_confirmada:null,proxima_revision:null,fuentes_operativas:[]});const n=render(c,d);mount(n);open(n);const cells=pick(n,'tbody')[0].children[0].children;assert.equal(text(cells[2]),'—');assert.equal(text(cells[3]),'—');assert.equal(text(cells[4]),'2');assert(!all(n).some(x=>/chip verde|chip ambar/.test(x.attrs.class||'')));});
 await test('null/source withheld does not show zero or link',()=>{const c=ctx(),d=doc();delete d.sugerencias[0].evidencia_por_revisar;const n=render(c,d);mount(n);open(n);const cells=pick(n,'tbody')[0].children[0].children;assert.equal(text(cells[4]),'—');assert.equal(text(cells[5]),'—');assert.equal(pick(n,'a').length,0);});
 await test('source cannot append raw secrets or rows from other clients',()=>{const c=ctx(),d=doc();d.sugerencias[0].evidencia_por_revisar.raw='SECRET_FIXTURE';d.sugerencias.push({...row(),cliente_id:'other'});const n=render(c,d);mount(n);open(n);assert.equal(pick(n,'tbody')[0].children.length,1);assert(!text(n).includes('SECRET_FIXTURE'));assert(!text(n).includes('other'));});
 await test('sidecar denial while regular suggestion still accessible',()=>{const c=ctx();for(const p of [c.real,c.persona,c.datos.personas[0]])p.puestos=['seo'];const n=render(c);mount(n);open(n);const cells=pick(n,'tbody')[0].children[0].children;assert.equal(text(cells[4]),'—');assert.equal(pick(n,'a').length,0);assert.equal(text(cells[2]),'25-sep');});
 await test('canonical actors duplicates/revoked/wrongroles denied initial',()=>{for(const mut of [c=>c.datos.personas.push(copy(c.real)),c=>c.real.activo=false,c=>c.persona.puestos=['account'],c=>c.real.puestos=['operaciones','operaciones'],c=>c.datos.personas[0].estado='baja']){const c=ctx();mut(c);assert.equal(b.ambitoSeguimiento453(c),null);assert.equal(render(c).children.length,0);}});
 await test('ACT/client detail exact scope no others or duplicate',()=>{for(const mut of [c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push(copy(c.clientes[0])),c=>c.clientesVisibles[0].detalle=false,c=>c.ver=()=>({ok:false})]){const c=ctx();mut(c);const n=render(c);mount(n);open(n);assert.equal(pick(n,'tbody')[0].children.length,0);}});
 await test('module/grant/hoy/identity/roles changed opening clears all',()=>{for(const mut of [c=>c.veModulo=()=>false,c=>c.ver=()=>({ok:false}),c=>c.hoy='2026-10-05',c=>c.persona.id='other',c=>c.datos.personas[0].puestos=['seo'],c=>c.clientes[0].activo_confirmado=false]){const c=ctx(),n=render(c);mount(n);mut(c);open(n);assert.equal(n.children.length,0);}});
 await test('link after revoke cancels browser navigation and cleans',()=>{const c=ctx(),n=render(c);mount(n);open(n);const link=pick(n,'a')[0];c.veModulo=()=>false;let blocked=false;link.events.click({preventDefault(){blocked=true;}});assert(blocked);assert.equal(n.children.length,0);});
 await test('no ficha grant no link but observed historical metadata remains',()=>{const c=ctx();c.veModulo=id=>id!=='ficha';const n=render(c);mount(n);open(n);assert.equal(pick(n,'a').length,0);assert(text(n).includes('2'));});
 await test('real reuniones renderer mounts453 while scope is unchanged',async()=>{const c=ctx();c.datosModulo=async()=>({asistencias:[],clientes:[{cliente_id:'c',estado:'sin_reunion'}],_meta:{meses:['2026-10']}});c.api=async p=>p==='metodo/sugerencias'?doc():{acciones:[]};const main=new N('main');attach(main);await b.modulo453.render(main,c);const n=all(main).find(x=>x.attrs['data-seguimiento-453']);assert(n);assert.equal(n.isConnected,true);open(n);assert.equal(pick(n,'th').length,7);assert.equal(text(pick(n,'tbody')[0].children[0].children[4]),'2');});
 await test('real source returned after canonical scope revoke paints no metadata',async()=>{const c=ctx();c.datosModulo=async()=>({asistencias:[],clientes:[{cliente_id:'c',estado:'sin_reunion'}]});c.api=async p=>{if(p==='metodo/sugerencias'){c.datos.personas.push(copy(c.real));return doc();}return {acciones:[]};};const main=new N('main');attach(main);await b.modulo453.render(main,c);const n=all(main).find(x=>x.attrs['data-seguimiento-453']);assert(n);assert.equal(n.children.length,0);assert(!text(n).includes('02-oct'));});
 await test('actual Ficha routing and PINTAR contract history only in reunion, not resumen',()=>{const source=fs.readFileSync(__dirname+'/modulos/ficha.js','utf8');assert(source.includes('const [idParam, tabParam] = ctx.params'));assert(source.includes('orden.includes(tabParam) ? tabParam'));const start=source.indexOf('const PINTAR = {'),parts={};for(const match of source.slice(start).matchAll(/^  (\w+)\([^\n]*\) \{/gm)){const i=start+match.index,end=source.indexOf('\n  },',i);parts[match[1]]=source.slice(i,end);}assert(parts.reunion.includes('pintarHistorialReuniones(z, ctx, F)'));assert(parts.resumen);assert(!parts.resumen.includes('pintarHistorialReuniones'));assert(!parts.comunicacion.includes('pintarHistorialReuniones'));const n=render();mount(n);open(n);const a=pick(n,'a')[0],tab=a.attrs.href.split('/').at(-1);assert.equal(tab,'reunion');assert(parts[tab].includes('pintarHistorialReuniones'));assert(a.attrs.title.startsWith('Abrir reunión'));assert(a.attrs['aria-label'].startsWith('Abrir reunión'));assert.notEqual(a.attrs.href,'#/ficha/c');});
 console.log(checks+' grupos453 PASS · DOM inicialmente desconectado, componentes/305/307/Reuniones reales, sin POST');
})().catch(e=>{console.error(e);process.exitCode=1;});
