const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ro390-'));fs.chmodSync(dir,0o700);
for(const n of ['_historial_diario_364','_bandas_horas_381','_imputa_personal_390'])fs.writeFileSync(path.join(dir,n+'.mjs'),fs.readFileSync(path.join(__dirname,'modulos',n+'.js'),'utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'"));
const copy=x=>JSON.parse(JSON.stringify(x));let checks=0;async function test(n,f){await f();checks++;}
(async()=>{try{
const {ambitoImputa390,cargarImputa390,celdaImputa390,imputaVigente390}=await import('file://'+path.join(dir,'_imputa_personal_390.mjs'));
const pid='acc',cut='2026-10-05';
function dto(values={'2026-10-01':4,'2026-10-02':0},zone='Europe/Madrid',stamp='2026-10-05T00:30:00Z'){
 const dates=Array.from({length:90},(_,i)=>{const f=new Date(Date.parse(cut+'T00:00Z')-(90-i)*864e5).toISOString().slice(0,10),known=Object.hasOwn(values,f);return {fecha:f,horas:known?values[f]:null,entradas:known?1:null,estado:known?'observado':'sin_dato'};});
 const serie={version:'359.1',fuente:'ClickUp entradas',cobertura:'parcial',unidad:'h',zona:zone,zona_confirmada:true,desde:dates[0].fecha,hasta:dates.at(-1).fecha,corte_fecha:cut,fecha_fuente_utc:stamp,atribucion:'inicio',duracion_cerrada_confirmada:false,sin_registros_no_equivale_a_cero:true,dias:dates};
 return {version:'362.1',estado:'copia_observada',generado:'2026-10-05T01:00:00Z',fuente:'ClickUp entradas',fuente_version:'359.1',sha256_candidato:'21abf5db866bfd0ed9805b61bf686a625f613d37d21ce80095ef998f209f6280',cobertura:'parcial',unidad:'h',cumplimiento:null,capacidad_contractual:null,personas:[{persona_id:pid,historial_diario:serie}]};
}
function ctx(d=dto()) {const ops={id:'ops',estado:'activo',puestos:['operaciones']},acc={id:pid,estado:'activo',puestos:['account']},seo={id:'seo',estado:'activo',puestos:['seo']};return {servidor:true,hoy:cut,vigente:()=>true,veModulo:m=>m==='horas',real:copy(ops),persona:copy(ops),datos:{personas:[copy(ops),copy(acc),copy(seo)]},ver:()=>({ok:true}),api:async p=>{assert.equal(p,'horas/historial-diario');return d;}};}
await test('real364 loader measures personal not project hours',async()=>{const c=ctx();c.produccion={proyectos:[{horas_mes:99999}]};const m=await cargarImputa390(c,[pid]),cell=celdaImputa390(c,m,pid);assert.equal(cell.total,4);assert.equal(cell.observadas,2);assert.equal(cell.valor,4);assert.equal(cell.estado,'gris');assert.equal(cell.referencia_horas,40);assert(cell.detalle.includes('2/7'));assert(cell.detalle.includes('no calendario laboral confirmado'));assert(!JSON.stringify(cell).includes('99999'));});
await test('absence never zero and explicit0 with entry retained',async()=>{for(const [values,want]of [[{},null],[{'2026-10-02':0},0]]){const c=ctx(dto(values)),m=await cargarImputa390(c,[pid]),cell=celdaImputa390(c,m,pid);assert.equal(cell.total,want);assert.equal(cell.valor,want===null?'—':0);assert.equal(cell.estado,'gris');}});
await test('last7 not calendar week no currentday sample',async()=>{const c=ctx(dto({'2026-09-27':100,'2026-09-28':1,'2026-10-04':3})),m=await cargarImputa390(c,[pid]);assert.equal(m.desde,'2026-09-28');assert.equal(m.hasta,'2026-10-04');assert.equal(celdaImputa390(c,m,pid).total,4);});
await test('zone excludes day of reading not assumed complete',async()=>{const c=ctx(dto({'2026-10-03':2,'2026-10-04':100},'America/Argentina/Buenos_Aires'));const m=await cargarImputa390(c,[pid]);assert.equal(celdaImputa390(c,m,pid).total,2);assert(celdaImputa390(c,m,pid).detalle.includes('2026-10-04'));});
await test('all currentpeople H allows real API source beyond account rows',async()=>{const d=dto();d.personas.push({persona_id:'seo',historial_diario:copy(d.personas[0].historial_diario)});const m=await cargarImputa390(ctx(d),[pid]);assert.equal(m.celdas.size,1);assert(!m.celdas.has('seo'));});
await test('own account no grants to others',async()=>{const c=ctx();c.real=c.persona=copy(c.datos.personas[1]);c.ver=x=>({ok:x.tipo==='horas_persona'&&x.persona_id===pid});const m=await cargarImputa390(c,[pid,'seo']);assert.equal(m.celdas.size,1);assert.equal(celdaImputa390(c,m,'seo').total,null);});
await test('duplicateinvalid target or canonical actor deny beforeGET',async()=>{for(const change of [c=>c.datos.personas.push(copy(c.real)),c=>c.real.puestos=['account'],c=>c.veModulo=()=>false,c=>c.vigente=()=>false]){const c=ctx();let n=0;c.api=async()=>{n++;return dto()};change(c);assert.equal(await cargarImputa390(c,[pid]),null);assert.equal(n,0);}assert.equal(ambitoImputa390(ctx(),[pid,pid]),null);assert.equal(ambitoImputa390(ctx(),[{}]),null);});
await test('canonical inactive no permissions inferred from data',async()=>{for(const change of [c=>c.datos.personas[1].estado='baja',c=>c.datos.personas.push(copy(c.datos.personas[1])),c=>c.datos.personas[1].puestos=['seo'],c=>c.ver=()=>({ok:false})]){const c=ctx();change(c);let n=0;c.api=async()=>{n++;return dto()};assert.equal(await cargarImputa390(c,[pid]),null);assert.equal(n,0);}});
await test('revocation during await cannot publish result',async()=>{for(const f of [c=>c.datos.personas[1].activo=false,c=>c.ver=()=>({ok:false}),c=>c.persona.puestos=['seo'],c=>c.vigente=()=>false]){const c=ctx();c.api=async()=>{f(c);return dto()};assert.equal(await cargarImputa390(c,[pid]),null);}});
await test('live callbacks deny after changes',async()=>{const c=ctx(),m=await cargarImputa390(c,[pid]);assert(imputaVigente390(c,m));c.datos.personas[1].puestos=['seo'];assert(!imputaVigente390(c,m));assert.equal(celdaImputa390(c,m,pid).valor,'—');});
await test('sum overflow unknown not infinity',async()=>{const c=ctx(dto({'2026-10-01':1e308,'2026-10-02':1e308})),m=await cargarImputa390(c,[pid]);assert.equal(celdaImputa390(c,m,pid).total,null);assert(!JSON.stringify(celdaImputa390(c,m,pid)).includes('Infinity'));});
await test('future source bad sequence missingentry fail closed actual364',async()=>{for(const f of [d=>d.personas[0].historial_diario.fecha_fuente_utc='2026-10-06T00:00:00Z',d=>d.personas[0].historial_diario.dias.pop(),d=>d.personas[0].historial_diario.dias.find(x=>x.estado==='observado').entradas=0]){const d=dto();f(d);assert.equal(await cargarImputa390(ctx(d),[pid]),null);}});
await test('403 and unavailable source no legacy fallback',async()=>{for(const status of [403,503]){const c=ctx();c.api=async()=>{throw {status}};c.horas={personas:[{persona_id:pid,semana:40}]};assert.equal(await cargarImputa390(c,[pid]),null);}});
await test('input sources unchanged',async()=>{const d=dto(),raw=JSON.stringify(d);await cargarImputa390(ctx(d),[pid]);assert.equal(JSON.stringify(d),raw);});
console.log(checks+' grupos390 PASS · lector364/modelo/celdas reales, sólo fixtures');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
