const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ro344-'));fs.chmodSync(dir,0o700);
const mod=path.join(__dirname,'modulos'),harness=fs.readFileSync(path.join(__dirname,'pruebas_operaciones_accounts_263.cjs'),'utf8');
fs.writeFileSync(path.join(dir,'componentes.mjs'),harness.match(/fs.writeFileSync\(path.join\(dir,'componentes.mjs'\),`([\s\S]*?)`\);/)[1].replace('replaceChildren(...xs){', 'replaceChildren(...xs){if(xs.some(Array.isArray))throw Error("replaceChildren nativo no aplana arrays");'));
for(const name of ['_llamadas_historicas_353','_pedidos_macro_344','_mensaje_alarma_345','_alarmas_operaciones_342','_top_alarmas_388','_orden_clientes_348','_horas_cartera_349','_operaciones_accounts_263','control_cartera','_control_artifact_250','_control_cartera_ruta_239','_imputa_personal_390','_historial_diario_364','_bandas_horas_381','_horas_diarias_238','_evidencias_resumen'])fs.writeFileSync(path.join(dir,name+'.mjs'),fs.readFileSync(path.join(mod,name+'.js'),'utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'").replace("from '../componentes.js'","from './componentes.mjs'"));
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
let n=0;const test=(label,f)=>{f();n++;console.log('PASS',label);};
(async()=>{try{
 const {h}=await import('file://'+path.join(dir,'componentes.mjs')),{ambitoPedidos344,proyectarPedidos344,celdaPedidos344,semanaPedidos344}=await import('file://'+path.join(dir,'_pedidos_macro_344.mjs')),{renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 const ctx=()=>{const ops={id:'ops',estado:'activo',puestos:['operaciones']};return {real:{...ops},persona:{...ops},hoy:'2026-10-03',servidor:true,veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,nombre:x=>x,clientesVisibles:[{id:'c1',nombre:'Cliente fixture',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'a1',principal:true,confianza:'confirmada'}]}}],carteraPorSilla:{account:new Set(['c1'])},datos:{personas:[{...ops},{id:'mili',estado:'activo',puestos:['operaciones']},{id:'a1',estado:'activo',puestos:['account']},{id:'a2',estado:'activo',puestos:['account']}],asignaciones:[{cliente_id:'c1',silla:'account',principal:true,persona_id:'a1'}]},verdad:cid=>({cliente_id:cid,gravedad:'atencion'}),api:async()=>null,datosModulo:async()=>null};};
 const fila=(extra={})=>({receptor_id:'a1',cliente_ids:['c1'],pedidos_semana:2,pendientes:5,ultima_declaracion:'2026-10-02T12:00:00Z',receptores_historicos:true,asignacion_actual_confirmada:true,...extra});
 const doc=(extra={})=>({version:'343.1',generado:'2026-10-03T12:01:00Z',corte_utc:'2026-10-03T12:00:00Z',hoy:'2026-10-03',desde:'2026-09-28',hasta:'2026-10-03',zona:'Europe/Madrid',estado:'medido',origen:'ledger_pedidos_account_294',autor_id:'mili',declarado:true,envio_realizado:false,llamada_realizada:false,ejecucion_verificada:false,cobertura:{ambito:'real_interseccion_vista_ACT',completa_ledger:true,semana_en_curso:true,truncado:false},cliente_ids_autorizados:['c1'],receptor_ids_autorizados:['a1','a2'],filas:[fila()],...extra});
 const model=(c,d)=>proyectarPedidos344(c,d,ambitoPedidos344(c));
 test('semana lunes natural exacta y calendario inválido',()=>{assert.equal(semanaPedidos344('2026-10-03'),'2026-09-28');assert.equal(semanaPedidos344('2026-02-30'),null);});
 test('observado declarado gris y pendientes pueden superar semana',()=>{const c=ctx(),v=celdaPedidos344(c,model(c,doc()),'a1');assert.equal(v.valor,'2 semana · 5 pendientes');assert.equal(v.estado,'gris');assert.match(v.detalle,/semanas anteriores/);assert.match(v.detalle,/No acredita contacto, envío, llamada ni ejecución/);});
 test('cero semana con pendientes antiguos acepta fecha anterior',()=>{const c=ctx(),m=model(c,doc({filas:[fila({pedidos_semana:0,pendientes:3,ultima_declaracion:'2026-09-20T12:00:00Z'})]}));assert.equal(celdaPedidos344(c,m,'a1').valor,'0 semana · 3 pendientes');});
 test('cero explícito sólo ledger completo y fila medido',()=>{const c=ctx(),m=model(c,doc({filas:[fila({pedidos_semana:0,pendientes:0,ultima_declaracion:null})]}));assert.equal(celdaPedidos344(c,m,'a1').valor,'0 semana · 0 pendientes');assert.match(celdaPedidos344(c,m,'a1').detalle,/no ausencia de acciones externas/);});
 test('ledger vacío y receptor ausente nunca crea cero',()=>{const c=ctx(),m=model(c,doc({filas:[]}));assert.equal(celdaPedidos344(c,m,'a1').valor,'—');assert.equal(celdaPedidos344(c,model(c,doc()),'a2').valor,'—');});
 test('receptor histórico no se reasigna al owner actual',()=>{const c=ctx(),m=model(c,doc({filas:[fila({receptor_id:'a2',asignacion_actual_confirmada:false})]}));assert.equal(celdaPedidos344(c,m,'a1').valor,'—');assert.equal(celdaPedidos344(c,m,'a2').valor,'2 semana · 5 pendientes');assert.match(celdaPedidos344(c,m,'a2').detalle,/asignación actual no confirmada/);});
 for(const [label,patch] of [['truncado',{cobertura:{...doc().cobertura,truncado:true}}],['ledger parcial',{cobertura:{...doc().cobertura,completa_ledger:false}}],['sin dato',{estado:'sin_dato'}],['otro origen',{origen:'proveedor'}],['ejecución',{ejecucion_verificada:true}],['autor ausente',{autor_id:null}],['otra semana',{desde:'2026-09-21'}],['corte futuro',{corte_utc:'2026-10-04T00:00:00Z'}],['ISO sin zona',{generado:'2026-10-03T12:01:00'}],['zona falsa',{zona:'UTC'}]])test('rechaza '+label,()=>assert.equal(model(ctx(),doc(patch)),null));
 for(const [label,f] of [['fracción',fila({pedidos_semana:1.5})],['negativo',fila({pendientes:-1})],['cliente ajeno',fila({cliente_ids:['otro']})],['cliente duplicado',fila({cliente_ids:['c1','c1']})],['receptor ajeno',fila({receptor_id:'otro'})],['fecha futura',fila({ultima_declaracion:'2026-10-03T13:00:00Z'})],['fecha ausente con pedidos',fila({ultima_declaracion:null})],['última anterior con pedidos semanales',fila({ultima_declaracion:'2026-09-20T12:00:00Z'})]])test('fila inválida '+label,()=>assert.equal(model(ctx(),doc({filas:[f]})),null));
 test('filas duplicadas no elige última',()=>assert.equal(model(ctx(),doc({filas:[fila(),fila()]})),null));
 test('receptor activo pero no Account no es elegible',()=>assert.equal(model(ctx(),doc({receptor_ids_autorizados:['ops'],filas:[fila({receptor_id:'ops'})]})),null));
 for(const [label,revoca] of [['roles',c=>c.persona.puestos=['seo']],['duplicado',c=>c.datos.personas.push({...c.real})],['baja',c=>c.datos.personas[0].activo=false],['ACT',c=>c.clientesVisibles[0].activo_confirmado=false],['detalle',c=>c.ver=()=>({ok:false})],['bandeja',c=>c.veModulo=m=>m!=='bandeja']])test('ámbito '+label+' revocado no reutiliza modelo',()=>{const c=ctx(),s=ambitoPedidos344(c),m=model(c,doc());revoca(c);assert.equal(proyectarPedidos344(c,doc(),s),null);assert.equal(celdaPedidos344(c,m,'a1').valor,'—');});
 test('Account sólo propia cartera y receptor exacto',()=>{const c=ctx();c.real=c.persona={id:'a1',estado:'activo',puestos:['account']};assert.ok(model(c,doc()));assert.equal(model(c,doc({filas:[fila({receptor_id:'a2'})]})),null);c.carteraPorSilla.account.clear();assert.equal(model(c,doc()),null);});
 for(const [label,revoca] of [['ausente',c=>c.datos.personas=c.datos.personas.filter(p=>p.id!=='mili')],['duplicada',c=>c.datos.personas.push({id:'mili',estado:'activo',puestos:['operaciones']})],['inactiva',c=>c.datos.personas.find(p=>p.id==='mili').activo=false],['rol distinto',c=>c.datos.personas.find(p=>p.id==='mili').puestos=['seo']]])test('Mili autora '+label+' no autoriza cifras',()=>{const c=ctx();revoca(c);assert.equal(model(c,doc()),null);});
 const {spawnSync}=require('child_process');
 const py=spawnSync('python3',['-c',`import json
from probar_resumen_pedidos_account_343 import Test343
t=Test343();t.setUp()
try:
 empty=t.summary();t.event(fecha='2026-09-20T12:00:00Z');old=t.summary();t.owner='b';t.raw['asignaciones'][0]['persona_id']='b';historical=t.summary();print(json.dumps({'empty':empty,'old':old,'historical':historical,'raw':t.raw}))
finally:t.tearDown()`],{cwd:__dirname,encoding:'utf8',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});assert.equal(py.status,0,py.stderr);const round=JSON.parse(py.stdout),realctx=ctx();realctx.real=realctx.persona={...round.raw.personas[0]};realctx.datos=round.raw;realctx.clientesVisibles=[{id:'c',activo_confirmado:true,detalle:true}];realctx.carteraPorSilla.account=new Set(['c']);
 test('DTO real343 tabla vacía tiene cero explícito compatible',()=>assert.equal(celdaPedidos344(realctx,model(realctx,round.empty),'a').valor,'0 semana · 0 pendientes'));
 test('DTO real343 pending antiguo acepta semana0 y fecha anterior',()=>assert.equal(celdaPedidos344(realctx,model(realctx,round.old),'a').valor,'0 semana · 1 pendientes'));
 test('DTO real343 receptor histórico conserva contador y actual0',()=>{const m=model(realctx,round.historical);assert.equal(celdaPedidos344(realctx,m,'a').valor,'0 semana · 1 pendientes');assert.match(celdaPedidos344(realctx,m,'a').detalle,/asignación actual no confirmada/);assert.equal(celdaPedidos344(realctx,m,'b').valor,'0 semana · 0 pendientes');});
 const main=()=>{const x=h('main',{});x.connected=true;return x;};
 for(const sub of ['accounts','control']){const c=ctx(),box=main(),calls=[];c.api=async ruta=>{calls.push(ruta);if(ruta==='operaciones/pedidos-account/resumen')return doc();throw Error('otra fuente');};await renderAccounts263(box,c,sub);test('render '+sub+' independiente301 e incluye celda gris',()=>{assert.equal(calls.filter(x=>x==='operaciones/pedidos-account/resumen').length,1);assert.match(text(box),/2 semana · 5 pendientes/);assert.equal(walk(box).find(x=>x.attrs['data-estado']==='gris'&&text(x)==='2 semana · 5 pendientes')?.tag,'span');const score=walk(box).find(x=>x.tag==='table'&&text(x).includes('Empujes de Mili'));assert.equal(walk(score).filter(x=>x.tag==='th').length,11);});}
 for(const sub of ['hoy','clientes']){const c=ctx(),box=main(),calls=[];c.api=async ruta=>{calls.push(ruta);return doc();};await renderAccounts263(box,c,sub);test('no GET pedidos en '+sub,()=>assert.ok(!calls.includes('operaciones/pedidos-account/resumen')));}
 for(const [label,revoca] of [['ACT',c=>c.clientesVisibles[0].activo_confirmado=false],['actor',c=>c.datos.personas[0].activo=false],['permiso',c=>c.veModulo=m=>m!=='bandeja']]){let fin;const c=ctx(),box=main();c.api=async ruta=>ruta==='operaciones/pedidos-account/resumen'?new Promise(r=>fin=r):null;const p=renderAccounts263(box,c,'accounts');while(!fin)await new Promise(r=>setImmediate(r));revoca(c);fin(doc());await p;test('respuesta tardía '+label+' no se pinta',()=>assert.doesNotMatch(text(box),/2 semana · 5 pendientes/));}
 const c=ctx(),box=main();c.api=async ruta=>ruta==='operaciones/pedidos-account/resumen'?doc():null;await renderAccounts263(box,c,'accounts');test('click detalle después revocar no filtra contador antiguo',()=>{const b=walk(box).find(x=>x.attrs['aria-label']?.startsWith('Empujes de Mili · pedidos locales: 2'));assert.ok(b);c.ver=()=>({ok:false});b.events.click();assert.doesNotMatch(text(box),/2 semana · 5 pendientes/);});
 const lateCtx=ctx(),lateBox=main();let resolver;lateCtx.clientesVisibles.push({id:'c2',nombre:'Segundo fixture',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'a2',principal:true,confianza:'confirmada'}]}});lateCtx.datos.asignaciones.push({cliente_id:'c2',persona_id:'a2',silla:'account',principal:true});lateCtx.api=async ruta=>ruta==='operaciones/pedidos-account/resumen'?new Promise(r=>resolver=r):null;
 const late=renderAccounts263(lateBox,lateCtx,'accounts');while(!resolver)await new Promise(r=>setImmediate(r));const selector=walk(lateBox).find(x=>x.attrs['aria-label']==='Account');selector.value='a1';selector.events.change();resolver(doc());await late;
 test('respuesta tardía preserva filtro account y KPI original',()=>{assert.equal(selector.value,'a1');const score=walk(lateBox).find(x=>x.tag==='table'&&text(x).includes('Empujes de Mili'));assert.match(text(score),/2 semana · 5 pendientes/);assert.doesNotMatch(text(score),/a2/);assert.equal(walk(score).filter(x=>x.tag==='th').length,11);});
 test('campos desconocidos fuente no entran en proyección',()=>{const c=ctx(),m=model(c,doc({filas:[fila({texto_privado:'No transmitir'})]}));assert.doesNotMatch(JSON.stringify([...m.filas.values()]),/No transmitir|texto_privado/);});
 const historicoCtx={...realctx,api:async ruta=>ruta==='operaciones/pedidos-account/resumen'?round.historical:null,datosModulo:async()=>null},historicoBox=main();await renderAccounts263(historicoBox,historicoCtx,'accounts');
 const histTable=()=>walk(historicoBox).find(x=>x.tag==='section'&&x.attrs['data-pedidos-historicos']==='344');
 test('DTO real343 render conserva receptor A fuera de cartera sin reasignar a B',()=>{assert.ok(histTable());assert.match(text(histTable()),/Pedidos a receptores sin cartera actual visible/);const hs=walk(histTable()).filter(x=>x.tag==='th').map(text);assert.deepEqual(hs,['Receptor','Pedidos semana','Pendientes','Última declaración','Evidencia']);assert.ok(walk(histTable()).some(x=>x.attrs['aria-label']==='a · Pendientes al corte: 1'));const score=walk(historicoBox).find(x=>x.tag==='table'&&text(x).includes('Empujes de Mili'));assert.match(text(score),/b.*0 semana · 0 pendientes/);assert.doesNotMatch(text(score),/0 semana · 1 pendientes/);});
 const historicoSelector=walk(historicoBox).find(x=>x.attrs['aria-label']==='Account');
 test('selector incorpora receptor histórico sin clonar grupo ni proyectos',()=>{assert.ok(walk(historicoSelector).find(x=>x.tag==='option'&&x.attrs.value==='a'));historicoSelector.value='a';historicoSelector.events.change();assert.ok(histTable());assert.match(text(histTable()),/1/);const score=walk(historicoBox).find(x=>x.tag==='table'&&text(x).includes('Empujes de Mili'));assert.match(text(score),/Sin filas autorizadas/);assert.doesNotMatch(text(score),/0 semana · 1 pendientes/);});
 test('filtro B no confunde gs filtrados con cartera completa',()=>{historicoSelector.value='b';historicoSelector.events.change();assert.equal(histTable(),undefined);assert.ok(walk(historicoSelector).find(x=>x.tag==='option'&&x.attrs.value==='a'));});
 test('reset conserva opción histórica y recupera bloque aparte',()=>{walk(historicoBox).find(x=>x.tag==='button'&&text(x)==='Restablecer filtros').events.click();assert.ok(histTable());assert.equal(historicoSelector.value,'');assert.ok(walk(historicoSelector).find(x=>x.tag==='option'&&x.attrs.value==='a'));});
 test('detalle de receptor histórico usa guard344 tras revocación',()=>{const b=walk(histTable()).find(x=>x.attrs['aria-label']==='a · Pendientes al corte: 1');historicoCtx.ver=()=>({ok:false});b.events.click();assert.equal(histTable(),undefined);assert.doesNotMatch(text(historicoBox),/0 semana · 1 pendientes|Receptor histórico/);});
 for(const [label,cambia] of [['receptor duplicado',c=>c.datos.personas.push({...c.datos.personas.find(p=>p.id==='a')})],['receptor inactivo',c=>c.datos.personas.find(p=>p.id==='a').activo=false]]){
  const c=structuredClone(round.raw),x=ctx();x.real=x.persona={...c.personas[0]};x.datos=c;x.clientesVisibles=[{id:'c',activo_confirmado:true,detalle:true}];x.api=async ruta=>ruta==='operaciones/pedidos-account/resumen'?round.historical:null;cambia(x);const box=main();await renderAccounts263(box,x,'accounts');test('histórico '+label+' no publica bloque',()=>assert.equal(walk(box).find(n=>n.attrs['data-pedidos-historicos']==='344'),undefined));
 }
 test('fuente344 sin POST ni proveedores y matriz KPI intacta',()=>{const source=fs.readFileSync(path.join(mod,'_pedidos_macro_344.js'),'utf8');assert.doesNotMatch(source,/fetch\(|ctx\.accion|method\s*:\s*['"]POST/);assert.equal(walk(box).filter(x=>x.tag==='th'&&text(x)==='Empujes de Mili').length<=1,true);});
 console.log(n+' grupos344 PASS · contrato y render263 reales, sin negocioPOST');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
