const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('modulos/_informes_declarados_612.js','utf8').replace(/export /g,'');
const box={};vm.createContext(box);vm.runInContext(code+'\nthis.ambito=ambitoResumenInformes612;this.proyectar=proyectarResumenInformes612;this.celda=celdaInformeDeclarado612;',box);
const row=(n=2,cid='cliente')=>({cliente_id:cid,informes_declarados:n,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null});
const dto=(rows=[row()])=>({nota:'Declaraciones activas por mes del informe, no por fecha de envío. Cero no acredita ausencia de envío ni cumplimiento; no hay verificación externa.',version:'611.1',periodo_informe:'2026-09',clientes:rows,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null,cobertura:'parcial'});
function fixture(){const p={id:'actor',nombre:'Actor fixture',estado:'activo',activo:true,puestos:['operaciones']};const c={id:'cliente',activo_confirmado:true,detalle:true};const ctx={real:p,persona:p,servidor:true,hoy:'2026-10-04',datos:{personas:[p]},clientes:[c],clientesVisibles:[c],vigente:()=>true,veModulo:()=>true,ver:()=>({ok:true})};let epoch=true;const scope={...box.ambito(ctx,'2026-09'),vigente:()=>epoch};return {ctx,scope,p,c,revoke:()=>epoch=false};}
let count=0;function test(name,f){f();count++;console.log('PASS',name)}
function model(q,D=dto()){return box.proyectar(q.ctx,D,q.scope)}
test('observado declarado2 gris sin envio/score',()=>{const q=fixture(),m=model(q),c=box.celda(m,'cliente');assert.equal(c.valor,'2 decl.');assert.equal(c.estado,'gris');assert.equal(c.informes_declarados,2);assert(c.detalle.includes('mes del informe, no mes de envío'));assert(c.detalle.includes('no verifica envío'));assert(c.vigente());assert(!JSON.stringify(m).includes('Actor fixture'))});
test('0 explícito válido no ausencia de actividad',()=>{const q=fixture();assert.equal(box.celda(model(q,dto([row(0)])),'cliente').valor,'0 decl.')});
test('missing null/schema inválido unknown no0',()=>{const q=fixture();assert.equal(box.celda(model(q,dto([])),'cliente').valor,'—');for(const d of [null,dto([row(null)]),dto([row(false)]),dto([row('0')]),dto([row(1.5)]),dto([row(-1)]),dto([row(Infinity)]),dto([row(Number.MAX_SAFE_INTEGER+1)])]){assert.equal(model(q,d),null);assert.equal(box.celda(null,'cliente').valor,'—')}});
test('sin callbackvigencia obligado',()=>{const q=fixture();delete q.scope.vigente;assert.equal(model(q),null)});
test('callback época revoca antes/después',()=>{const q=fixture(),m=model(q),old=box.celda(m,'cliente');q.revoke();assert.equal(model(q),null);assert.equal(box.celda(m,'cliente').valor,'—');assert.equal(old.vigente(),false)});
test('periodo exacto no mes envío',()=>{const q=fixture();assert.equal(model(q,{...dto(),periodo_informe:'2026-10'}),null);q.scope.periodo='2026-10';assert.equal(model(q),null);for(const month of ['2026-00','2026-13','2026-9',null])assert.equal(box.ambito(q.ctx,month),null)});
test('duplicado toda colecciónunknown',()=>{const q=fixture();assert.equal(model(q,dto([row(),row(1)])),null)});
test('ajeno no aparece y no datosfinancieros',()=>{const q=fixture();assert.equal(model(q,dto([row(2,'ajeno')])),null);assert.equal(model(q,dto([{...row(),cuota:999,token:'PRIVATE'}])),null);assert.equal(model(q,{...dto(),dinero_empresa:999}),null);assert(!JSON.stringify(box.celda(null,'cliente')).includes('PRIVATE'))});
test('nota exacta no HTML/textolibre',()=>{const q=fixture();for(const nota of ['<script>PRIVATE</script>','PRIVATE',null,undefined])assert.equal(model(q,{...dto(),nota}),null)});
test('contrato source/cobertura no supuestos',()=>{const q=fixture();for(const [k,v] of [['version','151.1'],['source_kind','desk'],['verificacion_externa',true],['cumplimiento',true],['cobertura','completa']])assert.equal(model(q,{...dto(),[k]:v}),null);for(const k of ['source_kind','verificacion_externa','cumplimiento']){const d=dto();delete d[k];assert.equal(model(q,d),null)};assert.equal(model(q,dto([{...row(),cobertura:'parcial'}])),null)});
for(const [name,mut] of Object.entries({actorBaja:q=>q.p.estado='baja',actorInactivo:q=>q.p.activo=false,actorDuplicado:q=>q.ctx.datos.personas.push({...q.p}),rolesDuplicados:q=>q.p.puestos.push('operaciones'),catalogRoles:q=>q.ctx.datos.personas=[{...q.p,puestos:['seo']}],ACT:q=>q.c.activo_confirmado=false,clienteBaja:q=>q.c.estado='baja',clienteInactivo:q=>q.c.activo=false,clienteDup:q=>q.ctx.clientes.push({...q.c}),visDup:q=>q.ctx.clientesVisibles.push({...q.c}),sinDetalle:q=>q.c.detalle=false,grant:q=>q.ctx.ver=()=>({ok:false}),modulo:q=>q.ctx.veModulo=()=>false,vigencia:q=>q.ctx.vigente=()=>false,static:q=>q.ctx.servidor=false,hoyEpoch:q=>q.ctx.hoy='2026-10-05'}))test('revocación '+name,()=>{const q=fixture(),m=model(q);mut(q);assert.equal(model(q),null);assert.equal(box.celda(m,'cliente').valor,'—')});
test('cliente contradictorio inicialmente inelegible',()=>{for(const mut of [q=>q.c.activo=false,q=>q.c.estado='baja',q=>q.ctx.clientesVisibles=[{...q.c,activo:false}],q=>q.ctx.clientesVisibles=[{...q.c,estado:'baja'}]]){const q=fixture();mut(q);const a=box.ambito(q.ctx,'2026-09');assert.equal(a.ids.length,0);assert.equal(model(q),null)}});
test('vercomo legítimo no obliga rolAccount ni escritura',()=>{const q=fixture(),v={id:'vista',nombre:'Vista fixture',estado:'activo',activo:true,puestos:['account']};q.ctx.persona=v;q.ctx.datos.personas.push(v);q.ctx.soloLectura=true;q.scope={...box.ambito(q.ctx,'2026-09'),vigente:()=>true};assert.equal(box.celda(model(q),'cliente').valor,'2 decl.');v.estado='baja';assert.equal(box.celda(model(q),'cliente').valor,'—')});
test('scope mutado y cliente fuera selección unknown',()=>{const q=fixture(),m=model(q);assert.equal(box.celda(m,'ajeno').valor,'—');q.scope.ids.push('ajeno');assert.equal(model(q),null)});
test('modelo no recibe spread ni mutación DTO posterior',()=>{const q=fixture(),D=dto(),m=model(q,D);D.clientes[0].informes_declarados=90;m.periodo_informe='PRIVATE';const c=box.celda(m,'cliente');assert.equal(c.valor,'2 decl.');assert(!c.detalle.includes('PRIVATE'));assert.equal(Object.hasOwn(m,'clientes'),false)});
test('doble chequeo proyectando responde a cambio concurrente síncrono',()=>{const q=fixture();let calls=0;const D=dto();Object.defineProperty(D,'clientes',{enumerable:true,get(){calls++;if(calls===2)q.c.activo_confirmado=false;return[row()]}});assert.equal(model(q,D),null)});
console.log(count+' grupos PASS612; no IO/API/POST');
