const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.append(...xs)}get isConnected(){return this.connected===true||!!this.parent?.isConnected}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x)}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs)}set textContent(x){this.replaceChildren(x)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}addEventListener(k,f){this.events[k]=f}}
const h=(t,a,...xs)=>new N(t,a,xs);let n=0,k=0;const check=f=>{f();n++};
(async()=>{const M=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(__dirname+'/modulos/_revision_leads_369.js','utf8')).toString('base64'));
const fixture=()=>{const ref='r'+(++k),x={ref,cliente_id:'c',sub_id:'s',subcuenta:'Fixture',creado:'2026-10-01T10:00Z',horas:50};const p={id:'o',estado:'activo',puestos:['operaciones']};return {x,c:{real:structuredClone(p),persona:structuredClone(p),datos:{personas:[structuredClone(p)]},servidor:true,soloLectura:false,clientesVisibles:[{id:'c',activo_confirmado:true,detalle:true}],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true},d:{leads_sin_tocar:[x],subcuentas:[{sub_id:'s',cliente_id:'c'}],revisados:new Map()}}};
const mount=f=>{const root=h('main',{});root.connected=true;const badge=M.estadoRevisionLead369(h,f.x,f.d),w=M.crearRevisionLead369(h,f.c,f.x,f.d,['El despacho lo llamó desde su móvil','Duplicado']);root.append(badge,w);return {root,w,badge,b:w.children.find(x=>x.tag==='button')}};
const ack=(b,id=2)=>({ok:true,id,estado:'simulada',texto:b.texto,vista_previa:b.vista_previa,intencion_guardada:{id:b.intencion_id,accion_id:id,repetida:false}});
let f=fixture();const old={tipo:'revisado_lead',objeto:'lead '+f.x.ref,cliente_id:'c',id:1,texto:'El despacho lo llamó desde su móvil'};f.d.revisados.set(old.objeto,old);
check(()=>{assert.equal(M.leadsPendientes369(f.d.leads_sin_tocar,f.d.subcuentas).length,1);const r=M.revisionLead369(f.x,f.d.revisados);assert(r.registrada);assert(!r.contacto_verificado);assert(!r.resuelto_en_ghl)});
check(()=>{assert.equal(M.leadsPendientes369([f.x,f.x],f.d.subcuentas).length,0);assert.equal(M.leadsPendientes369([f.x],[...f.d.subcuentas,...f.d.subcuentas]).length,0);assert.equal(M.leadsPendientes369([{...f.x,cliente_id:'other'}],f.d.subcuentas).length,0);assert.equal(M.leadsPendientes369([f.x],[...f.d.subcuentas,{sub_id:'s',cliente_id:'other'}]).length,0)});
f=fixture();let calls=[],fail=true;f.c.accion=async b=>{calls.push(b);if(fail){fail=false;throw Error('lost')}return ack(b)};let u=mount(f);await u.b.events.click();check(()=>{assert.equal(f.d.revisados.size,0);assert.match(u.w.textContent,/sin confirmar/);assert(!u.root.hidden)});
await u.w.children.filter(x=>x.tag==='button')[1].events.click();check(()=>assert.equal(calls.length,1));
u=mount(f);await u.b.events.click();check(()=>{assert.equal(calls[0],calls[1]);assert.equal(calls[0].intencion_id,calls[1].intencion_id);assert.equal(f.d.revisados.size,1);assert.match(u.badge.textContent,/pendiente en GHL/);assert(!u.root.hidden)});
f=fixture();calls=[];f.c.accion=async b=>{calls.push(b);if(calls.length===1)throw Error('lost');return ack(b)};u=mount(f);await u.b.events.click();f.c.real.puestos.push('seo');f.c.persona.puestos.push('seo');f.c.datos.personas[0].puestos.push('seo');u=mount(f);await u.b.events.click();check(()=>{assert.equal(calls.length,2);assert.equal(calls[0],calls[1]);assert.equal(calls[0].intencion_id,calls[1].intencion_id)});
f=fixture();let done,count=0;f.c.accion=b=>{count++;return new Promise(r=>done=()=>r(ack(b)))};u=mount(f);let pending=u.b.events.click();await u.b.events.click();check(()=>assert.equal(count,1));done();await pending;
for(const alter of [f=>f.c.soloLectura=true,f=>f.c.pilotoLectura=true,f=>f.c.persona.id='other',f=>f.c.real.estado='baja',f=>f.c.datos.personas.push({...f.c.datos.personas[0]}),f=>f.c.persona.puestos=['seo'],f=>f.c.veModulo=()=>false,f=>f.c.ver=()=>({ok:false}),f=>f.c.clientesVisibles[0].activo_confirmado=false,f=>f.d.subcuentas.push({...f.d.subcuentas[0]}),f=>f.d.leads_sin_tocar.push({...f.x,sub_id:'other'})]){f=fixture();count=0;f.c.accion=async()=>count++;alter(f);u=mount(f);if(u.b)await u.b.events.click();check(()=>assert.equal(count,0))}
f=fixture();f.c.accion=b=>new Promise(r=>done=()=>r(ack(b)));u=mount(f);pending=u.b.events.click();f.c.ver=()=>({ok:false});done();await pending;check(()=>{assert.equal(f.d.revisados.size,0);assert.match(u.w.textContent,/permisos actuales/)});
f=fixture();count=0;f.c.accion=async()=>count++;u=mount(f);f.c.datos.personas[0].estado='baja';await u.b.events.click();check(()=>{assert.equal(count,0);assert.match(u.w.textContent,/permisos actuales/)});
for(const bad of [b=>({...ack(b),texto:'other'}),b=>({...ack(b),intencion_guardada:{id:b.intencion_id,accion_id:99,repetida:false}}),b=>({...ack(b),estado:'confirmado'}),b=>({...ack(b),vista_previa:'forged'})]){f=fixture();f.c.accion=async b=>bad(b);u=mount(f);await u.b.events.click();check(()=>{assert.equal(f.d.revisados.size,0);assert.match(u.w.textContent,/sin confirmar/)})}
// La colección real de pestañas también conserva revisiones anteriores.
const crmSource=fs.readFileSync(__dirname+'/modulos/crm.js','utf8');f=fixture();f.d.revisados.set('lead '+f.x.ref,{...old,objeto:'lead '+f.x.ref});
const collection=crmSource.split('\n').find(line=>line.trim().startsWith('const leads = leadsPendientes369('));
const collectionEnv={...M,d:f.d,vis:{base:f.d.subcuentas}};vm.createContext(collectionEnv);vm.runInContext(collection+'\nglobalThis.resultado=leads;',collectionEnv);check(()=>assert.equal(collectionEnv.resultado.length,1));
// El pintor real conserva overlays antiguos, columnas, fuente y acciones; no espejo.
const src=fs.readFileSync(__dirname+'/modulos/crm.js','utf8'),start=src.indexOf('function pintarLeads('),end=src.indexOf('// ------------------------------------------------------------------',start+1);let options;
const env={h,...M,MOVIL:()=>false,cuentagotas:()=>()=> 'gris',panel:(o,...xs)=>h('section',{},o.sub,...xs),tablaDensa:o=>{options=o;return h('table',{})},botonRevisado:()=>null,logoCliente:()=>null,fDiaRO:x=>x,puntoEstado:()=>null,horasTxt:x=>x,masAcciones:()=>null,accionSim:()=>null,botonVerDatos:()=>null,abrirGHL:()=>null,tareaAccount:()=>null};vm.createContext(env);vm.runInContext(src.slice(start,end),env);f=fixture();f.d.revisados.set('lead '+f.x.ref,{...old,objeto:'lead '+f.x.ref});const zone=h('main',{});env.pintarLeads(zone,f.c,f.d,{base:f.d.subcuentas},[f.x]);check(()=>{assert.equal(options.filas.length,1);assert(options.columnas.some(c=>c.clave==='revision_ro'));assert.match(zone.textContent,/no elimina el pendiente/);assert(!src.includes("!rev.has(claveRev('lead', x))"));assert(!src.includes("!d.revisados?.has(claveRev('lead', x))"))});
console.log(n+' grupos369 PASS: renderer, overlays, recibo, UUID y permisos');})().catch(e=>{console.error(e);process.exitCode=1});
