const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=__dirname;
const s=fs.readFileSync(path.join(root,'modulos/operaciones.js'),'utf8');
const box={};vm.createContext(box);vm.runInContext(s.replace(/^import .*;\n/gm,'').replace(/export default /,'const modulo=').replace(/export /g,'')+'\nglobalThis.apartados=APARTADOS_OPERACIONES;',box);
const ref=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8');
const orden=JSON.parse(ref.match(/const ORD=(\[[^;]+\]);/)[1].replace(/'/g,'"'));
assert.deepEqual(Array.from(box.apartados.filter(a=>a[0]!=='rojos'),a=>a[0]),orden);assert.equal(box.apartados.length,18);
for(const a of box.apartados)assert(fs.existsSync(path.join(root,'modulos',a[3]+'.js')));
const ctx=(puestos,allowed)=>({persona:{puestos},veModulo:id=>allowed.includes(id)});
const all=Array.from(box.apartados,a=>a[2]);
assert.equal(box.apartadosAutorizados(ctx(['operaciones'],all)).length,18);
assert.equal(box.apartadosAutorizados(ctx(['seo'],all)).length,0);
assert.equal(box.apartadosAutorizados(ctx(['account'],['en-rojo'])).length,1);
assert.equal(box.apartadosAutorizados(ctx(['operaciones'],[])).length,0);
const b={h:()=>{},chipEstado:()=>{}};vm.createContext(b);const r=fs.readFileSync(path.join(root,'modulos/_operaciones_rituales_264.js'),'utf8');vm.runInContext(r.replace(/^import .*;\n/gm,'').replace(/export /g,''),b);
const c={clientesVisibles:[{id:'a',activo_confirmado:true,nombre:'A',responsable_id:'owner'},{id:'b',activo_confirmado:false}]};
const P={revisiones:[{id:'1',cliente_id:'a',revisa:'account',dias:31},{id:'2',cliente_id:'a',revisa:'cliente'},{id:'3',cliente_id:'b',revisa:'account'},{id:'4',cliente_id:'ajeno',revisa:'account'}],cola:[{id:'5',cli:'a',grupo:'bloqueada',estado:'bloqueado',estado_determinado:true,dias_estado:40},{id:'6',cli:'a',grupo:'bloqueada',estado:'bloqueado',estado_determinado:false}]};
const B={correos:[{id:'7',cliente_id:'a',horas:800},{id:'8',cliente_id:'a',horas:800,auto:true},{id:'9',cliente_id:'b',horas:900}]};
const f=b.filasSaneamiento264(c,P,B);assert.equal(f.tareas.length,1);assert.equal(f.tickets.length,1);assert.equal(f.bloqueadas.length,1);assert.equal(f.tareas[0].account_id,'owner');
assert.equal(b.filasSaneamiento264({...c,clientesVisibles:[c.clientesVisibles[0],c.clientesVisibles[0]]},P,B).tareas.length,0);
assert.equal(b.filasSaneamiento264(c,{revisiones:[P.revisiones[0],P.revisiones[0]]},B).tareas.length,0);
console.log('266 PASS: 17 apartados originales preservados + En rojo separado de Fuegos, dependencias existentes, rutas por rol failclosed, saneamiento ACT/cartera/identidad única/taxonomía y dueño canónico. No certifica equivalencia completa de las vistas aún en integración.');
