const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const setup=fs.readFileSync('pruebas_captacion_compacta_243.cjs','utf8').split('const c={')[0],outer={require,console,__dirname:process.cwd()};vm.createContext(outer);vm.runInContext(setup+';globalThis.E=e;globalThis.H=h;globalThis.NODO=N;',outer);const e=outer.E,h=outer.H,N=outer.NODO;
N.prototype.isConnected=true;e.panel=(o,...kids)=>h('section',{},o.titulo,...kids);e.vacio=o=>h('p',{},o.titulo,o.texto);e.chipsFiltro=o=>{let v='seguro';return Object.assign(h('div',{},o.opciones.map(x=>h('button',{on:{click:()=>{v=x.valor;o.alCambiar();}}},x.texto))),{valor:()=>v});};e.botonConfirmar=o=>Object.assign(h('button',{on:{click:()=>o.alConfirmar()}},o.texto),{config:o});
const storage=new Map();e.location={origin:'http://127.0.0.1:8771'};e.localStorage={getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,v)};
let uid=0;e.crypto={randomUUID:()=>`00000000-0000-4000-8000-${String(++uid).padStart(12,'0')}`};vm.runInContext(fs.readFileSync('modulos/_triaje_durable_432.js','utf8').replaceAll('export ',''),e);vm.runInContext('(function(){'+fs.readFileSync('modulos/_triaje_lectura_exacta_440.js','utf8').replace(/^import .*;$/m,'').replaceAll('export ','')+';globalThis.consultarTriaje440=consultarTriaje440;globalThis.validarLecturaTriaje440=validarLecturaTriaje440;})();',e);const b=fs.readFileSync('modulos/bandeja.js','utf8');vm.runInContext(b.slice(b.indexOf('function pintarTriaje(')),e);
const all=(n,f)=>[...(n instanceof N&&f(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,f)):[])];
function fixture(reset=true){if(reset)storage.clear();const p={id:'ops',estado:'activo',puestos:['operaciones']},receiver={id:'account',estado:'activo',puestos:['account']},c={id:'cid',activo_confirmado:true,detalle:true},t={id:'desk1',numero:'RO123',cliente_id:'cid',propuesta:'seguro',agente_propuesto_id:'account',asunto:'Ticket fixture',motivo:'Propuesta fixture'};return {ctx:{real:p,persona:p,servidor:true,datos:{personas:[p,receiver]},clientes:[c],clientesVisibles:[{...c}],veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,api:async()=>({version:'437.1',ticket_id:'desk1',cliente_id:'cid',objeto:'RO123',origen:'ledger_local',lectura_exacta:true,confirmacion_desk:false,tipos:{asignar:{cantidad:0,ultima:null},cerrar:{cantidad:0,ultima:null}}}),nombre:id=>id},S:{triaje:[t],porObjeto:new Map(),accionesTriajeLeidas432:true},t};}
const ack=p=>({ok:true,id:7,estado:'simulada',texto:p.texto,vista_previa:p.vista_previa,intencion_guardada:{id:p.intencion_id,accion_id:7,repetida:false}});
let count=0;async function test(f){await f();count++;}
(async()=>{
await test(()=>{const {ctx,S,t}=fixture();S.porObjeto.set(t.numero,[{tipo:'cerrar'}]);assert.equal(e.filasTriaje432(ctx,S).length,1);const root=h('main',{});e.pintarTriaje(root,ctx,S);assert(root.textContent.includes(t.asunto));assert(root.textContent.includes('Registro local previo'));});
await test(async()=>{const {ctx,S,t}=fixture();let payload;ctx.accion=async p=>(payload=p,ack(p));const root=h('main',{});e.pintarTriaje(root,ctx,S);await all(root,x=>x.config&&x.textContent.startsWith('Solicitar asignación'))[0].on.click();assert(root.textContent.includes(t.asunto));assert(root.textContent.includes('Intención local guardada'));assert(!S.porObjeto.has(t.numero));assert.equal(payload.vista_previa.a,'account');assert.equal(payload.modulo,'bandeja');assert.equal(e.filasTriaje432(ctx,S).length,1);});
await test(async()=>{const {ctx,S,t}=fixture();const sent=[];ctx.accion=async p=>{sent.push(p);if(sent.length===1)throw Error('Ack perdido');return {...ack(p),intencion_guardada:{id:p.intencion_id,accion_id:7,repetida:true}};};let root=h('main',{});e.pintarTriaje(root,ctx,S);await assert.rejects(all(root,x=>x.config&&x.textContent.startsWith('Solicitar asignación'))[0].on.click());assert(root.textContent.includes('Resultado sin confirmar'));ctx.persona.puestos.push('seo');root=h('main',{});e.pintarTriaje(root,ctx,S);await all(root,x=>x.config&&x.textContent==='Reintentar misma intención')[0].on.click();assert.equal(sent[0],sent[1]);assert.equal(sent[0].intencion_id,sent[1].intencion_id);assert(root.textContent.includes(t.asunto));});
for(const response of [null,{ok:true}, {ok:true,id:7,estado:'simulada',intencion_guardada:{id:'wrong',accion_id:7,repetida:false}}])await test(async()=>{const {ctx,S,t}=fixture();ctx.accion=async()=>response;const i=e.intencionTriaje432(ctx,S,t,'cerrar');await e.guardarTriaje432(ctx,S,t,i);assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');assert.equal(e.filasTriaje432(ctx,S).length,1);});
await test(async()=>{const {ctx,S,t}=fixture();ctx.accion=async p=>{ctx.clientes[0].activo_confirmado=false;return ack(p);};const root=h('main',{});e.pintarTriaje(root,ctx,S);await assert.rejects(all(root,x=>x.config&&x.textContent==='Solicitar cierre')[0].on.click());assert.equal(root.children.length,0);});
await test(async()=>{const {ctx,S,t}=fixture();ctx.accion=async()=>{throw Error('Lost');};const i=e.intencionTriaje432(ctx,S,t,'asignar');await e.guardarTriaje432(ctx,S,t,i);t.agente_propuesto_id='ops';assert.throws(()=>e.intencionTriaje432(ctx,S,t,'asignar'));assert.equal(e.previaTriaje432(ctx,S,t,'asignar'),i);assert(e.estadoTriaje432(ctx,S,t).includes('Propuesta cambiada'));});
await test(()=>{const {ctx,S,t}=fixture();ctx.datos.personas[1].estado='baja';assert.equal(e.ambitoTriaje432(ctx,S,t,'asignar'),null);assert(e.ambitoTriaje432(ctx,S,t,'cerrar'));});
await test(()=>{const {ctx,S,t}=fixture();S.triaje.push({...t,id:'other'});assert.equal(e.filasTriaje432(ctx,S).length,0);});
await test(()=>{const {ctx,S,t}=fixture();ctx.soloLectura=true;assert.equal(e.ambitoTriaje432(ctx,S,t,'asignar'),null);assert.equal(e.filasTriaje432(ctx,S).length,1);const root=h('main',{});e.pintarTriaje(root,ctx,S);assert(!all(root,x=>x.config).length);});
await test(()=>{const {ctx,S,t}=fixture();ctx.real={...ctx.real,id:'other'};ctx.datos.personas.push(ctx.real);assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);});
await test(()=>{const {ctx,S,t}=fixture();t.cliente_id=null;assert.equal(e.filasTriaje432(ctx,S).length,1);assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);});
await test(()=>{const {ctx,S}=fixture();S.triaje=[];assert.equal(e.filasTriaje432(ctx,S).length,0);S.triaje=null;assert.equal(e.filasTriaje432(ctx,S),null);});
await test(()=>{const {ctx,S,t}=fixture();ctx.clientes[0].activo_confirmado=false;assert.equal(e.filasTriaje432(ctx,S).length,0);assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);});
await test(()=>{const {ctx,S}=fixture();const root=h('main',{});e.pintarTriaje(root,ctx,S);ctx.vigente=()=>false;all(root,x=>x.tag==='button'&&x.textContent==='Dudoso')[0].on.click();assert.equal(root.children.length,0);});
await test(()=>{const {ctx,S,t}=fixture();ctx.datos.personas.push({...ctx.real});assert.equal(e.filasTriaje432(ctx,S),null);assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);});

await test(async()=>{const {ctx,S,t}=fixture();let resolve,calls=0;ctx.accion=p=>(calls++,new Promise(r=>resolve=()=>r(ack(p))));const i=e.intencionTriaje432(ctx,S,t,'asignar'),pending=e.guardarTriaje432(ctx,S,t,i);assert.equal(await e.guardarTriaje432(ctx,S,t,i),false);assert.equal(calls,1);resolve();await pending;assert(i.recibo);});
await test(async()=>{const {ctx,S,t}=fixture();ctx.accion=async()=>{throw Error('lost');};const old=e.intencionTriaje432(ctx,S,t,'asignar');await e.guardarTriaje432(ctx,S,t,old);const reload=fixture(false);reload.S.porObjeto.set(t.numero,[{tipo:'asignar'}]);const restored=e.intencionTriaje432(reload.ctx,reload.S,reload.t,'asignar');assert.equal(restored.payload.intencion_id,old.payload.intencion_id);assert.deepEqual(JSON.parse(JSON.stringify(restored.payload)),JSON.parse(JSON.stringify(old.payload)));reload.ctx.accion=async p=>JSON.parse(JSON.stringify({...ack(p),vista_previa:{origen:'triaje',ticket:p.objeto,a:'account'}}));await e.guardarTriaje432(reload.ctx,reload.S,reload.t,restored);assert(restored.recibo);assert.equal(e.filasTriaje432(reload.ctx,reload.S).length,1);});
await test(()=>{const {ctx,S,t}=fixture();S.porObjeto.set(t.numero,[{tipo:'asignar'}]);assert.equal(e.ambitoTriaje432(ctx,S,t,'asignar'),null);assert.throws(()=>e.intencionTriaje432(ctx,S,t,'cerrar'));const root=h('main',{});e.pintarTriaje(root,ctx,S);assert(root.textContent.includes(t.asunto));assert(root.textContent.includes('Registro local previo'));assert(!all(root,x=>x.config).length);});
await test(()=>{const {ctx,S,t}=fixture();S.accionesTriajeLeidas432=false;assert.equal(e.ambitoTriaje432(ctx,S,t,'asignar'),null);const root=h('main',{});e.pintarTriaje(root,ctx,S);assert(root.textContent.includes(t.asunto));assert(root.textContent.includes('No se pudo leer el registro'));assert(!all(root,x=>x.config).length);});
await test(()=>{const {ctx,S,t}=fixture(),original=e.localStorage;e.localStorage={getItem:()=>null,setItem:()=>{throw Error('quota');}};try{assert.throws(()=>e.intencionTriaje432(ctx,S,t,'asignar'));assert.equal(S.intencionesTriaje432.size,0);}finally{e.localStorage=original;}});
await test(()=>{const {ctx,S,t}=fixture();e.intencionTriaje432(ctx,S,t,'asignar');S.intencionesTriaje432=new Map();storage.set([...storage.keys()][0],'{invalid');assert.throws(()=>e.intencionTriaje432(ctx,S,t,'asignar'));});
await test(()=>{const {ctx,S,t}=fixture();e.intencionTriaje432(ctx,S,t,'asignar');S.intencionesTriaje432=new Map();t.fecha='2026-10-04';assert.throws(()=>e.intencionTriaje432(ctx,S,t,'asignar'));});
await test(async()=>{const {ctx,S,t}=fixture();ctx.accion=async p=>{ctx.datos.personas[1].estado='baja';return ack(p);};const i=e.intencionTriaje432(ctx,S,t,'asignar');assert.equal(await e.guardarTriaje432(ctx,S,t,i),false);assert.equal(i.recibo,null);});
await test(()=>{const {ctx,S,t}=fixture();ctx.pilotoLectura=true;assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);ctx.pilotoLectura=false;ctx.servidor=false;assert.equal(e.ambitoTriaje432(ctx,S,t,'cerrar'),null);});
await test(()=>{const {ctx,S,t}=fixture();const i=e.intencionTriaje432(ctx,S,t,'asignar');for(const r of [{...ack(i.payload),estado:'confirmada'},{...ack(i.payload),texto:'changed'},{...ack(i.payload),vista_previa:{...i.payload.vista_previa,extra:'x'}},{...ack(i.payload),vista_previa:{...i.payload.vista_previa,a:'ops'}}])assert.equal(e.reciboTriaje432(r,i),null);assert(Object.isFrozen(i.payload));assert(Object.isFrozen(i.payload.vista_previa));});

await test(()=>{const {ctx,S,t}=fixture();const i=e.intencionTriaje432(ctx,S,t,'asignar');storage.set([...storage.keys()][0],'corrupt');let called=0;ctx.accion=async()=>{called++;};return e.guardarTriaje432(ctx,S,t,i).then(x=>{assert.equal(x,false);assert.equal(called,0);});});
await test(()=>{const {ctx,S,t}=fixture();e.intencionTriaje432(ctx,S,t,'asignar');const reload=fixture(false),root=h('main',{});e.pintarTriaje(root,reload.ctx,reload.S);assert(all(root,x=>x.config&&x.textContent==='Reintentar misma intención').length);const saved=[...storage.values()][0];assert(!saved.includes(t.asunto));assert(!saved.includes(t.motivo));});
await test(async()=>{const original=e.botonConfirmar;N.prototype.focus=()=>{};const comp=fs.readFileSync('componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function botonConfirmar('),comp.indexOf('/** candado(',comp.indexOf('export function botonConfirmar('))).replace('export ',''),e);try{const {ctx,S}=fixture();ctx.accion=async()=>null;const root=h('main',{});e.pintarTriaje(root,ctx,S);const trigger=all(root,x=>x.tag==='button'&&x.textContent==='Solicitar cierre')[0],box=all(root,x=>x.attrs?.class==='confirmar'&&x.children.includes(trigger))[0];trigger.on.click();await all(box,x=>x.tag==='button'&&x.textContent==='Guardar intención')[0].on.click();assert(box.textContent.includes('No se pudo'));assert(!box.textContent.includes('Hecho'));assert(root.textContent.includes('Resultado')||root.textContent.includes('conserva la misma intención'));}finally{e.botonConfirmar=original;}});
await test(()=>{const {ctx,S}=fixture();const m=b.match(/const pendTriaje = (.*);/);e.ctx=ctx;e.S=S;vm.runInContext('globalThis.counter432='+m[1],e);assert.equal(e.counter432,1);S.triaje=[];vm.runInContext('globalThis.counter432='+m[1],e);assert.equal(e.counter432,0);S.triaje=null;vm.runInContext('globalThis.counter432='+m[1],e);assert.equal(e.counter432,undefined);ctx.datos.personas.push({...ctx.real});S.triaje=[];vm.runInContext('globalThis.counter432='+m[1],e);assert.equal(e.counter432,undefined);});

await test(()=>{const {ctx,S,t}=fixture();t.asunto='RV: Empezamos en 15 minutos';t.motivo='Propuesta operativa con explicación completa sin columna de icono';const root=h('main',{});e.pintarTriaje(root,ctx,S);const list=all(root,x=>x.tag==='ul'&&x.attrs.class==='primero triaje432')[0],row=list.children[0];assert.equal(row.children.length,2);assert.equal(row.children[0].attrs.class,'triaje432-texto');assert(row.children[0].textContent.includes(t.asunto));assert(row.children[0].textContent.includes(t.motivo));assert.equal(row.children[1].attrs.class,'acc');assert.equal(all(row,x=>x.config).length,2);const css=all(root,x=>x.tag==='style')[0].textContent;assert(css.includes('.primero.triaje432>li{grid-template-columns:minmax(0,1fr) minmax(160px,34%)'));assert(css.includes('@media(max-width:640px)'));assert(css.includes('.primero.triaje432>li{grid-template-columns:minmax(0,1fr)}'));assert(css.includes('flex-wrap:wrap'));assert(!css.includes('30px'));});
console.log(count+' grupos432 PASS · función/render reales, recibo194, mismoUUID lostresponse/roles, pendientes conservados, permisos/ACT/propuesta/contador y sin POST real.');
})().catch(e=>{console.error(e);process.exitCode=1;});
