const fs=require('fs');
const base=fs.readFileSync(__dirname+'/pruebas_tablero_mi_trabajo_181.cjs','utf8').split('const a=')[0];
new Function('require','__dirname',base+String.raw`
const task={id:'task-a',persona_id:'yo',lista_id:'list-1',cli:'client-1',estado:'open',tarea:'Fixture'};
const uid='11111111-1111-4111-8111-111111111111',otherUid='22222222-2222-4222-8222-222222222222';c.crypto={randomUUID:()=>uid};
function context(){const actor={id:'yo',estado:'activo',puestos:['operaciones']};return {D:{tareas:[{...task}]},V:{personas:[actor]},local:[],vigente:()=>true,ctx:{servidor:true,real:actor,persona:{...actor},datos:{personas:[actor]},clientesVisibles:[{id:'client-1',activo_confirmado:true,detalle:true}],veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true}};}
const ack=(p,id=8)=>({ok:true,id,texto:p.texto,vista_previa:{},estado:'simulada',intencion_guardada:{id:p.intencion_id,accion_id:id,repetida:false}});
const field=root=>buscar(root,x=>x.tag==='textarea')[0],button=root=>buscar(root,x=>x.tag==='button')[0];
const test=async(name,fn)=>{await fn();casos++;};
(async()=>{
await test('PayloadImmutableExactAndLocalReceipt',()=>{const e=context(),i=c.prepararComentario366(e,task,'Nota operativa',uid);assert(Object.isFrozen(i.payload));assert(Object.isFrozen(i.payload.vista_previa));assert.equal(i.payload.objeto,task.id);assert.equal(i.payload.cliente_id,task.cli);const r=c.reciboComentario366(ack(i.payload),i);assert(r.guardado_local);assert.equal(r.confirmacion_remota,false);});
await test('MissingOrForgedAckNeverDurable',()=>{const i=c.prepararComentario366(context(),task,'Nota operativa',uid);for(const mutate of [r=>delete r.intencion_guardada,r=>r.id=0,r=>r.intencion_guardada.id=otherUid,r=>r.intencion_guardada.accion_id=9,r=>r.intencion_guardada.repetida='no',r=>r.texto='otro',r=>r.vista_previa={a:'inventado'},r=>r.ok=false]){const r=ack(i.payload);mutate(r);assert.equal(c.reciboComentario366(r,i),null);}});
await test('LostResponseRetryExactlySameUUIDAndBody',async()=>{const e=context(),i=c.prepararComentario366(e,task,'Nota operativa',uid),sent=[];await c.guardarComentario366(e,task,i,async p=>{sent.push(JSON.stringify(p));throw Error('timeout');});assert.equal(i.estado,'sin_confirmar');assert.equal(i.recibo,null);await c.guardarComentario366(e,task,i,async p=>{sent.push(JSON.stringify(p));return ack(p);});assert.equal(sent[0],sent[1]);assert(i.recibo);assert.equal(i.estado,'guardado');await c.guardarComentario366(e,task,i,()=>{throw Error('must not send');});});
await test('ConcurrentClicksOneTransport',async()=>{const e=context(),i=c.prepararComentario366(e,task,'Nota operativa',uid);let finish,payload,calls=0;const pending=c.guardarComentario366(e,task,i,p=>{calls++;payload=p;return new Promise(r=>finish=r);});assert.equal(await c.guardarComentario366(e,task,i,()=>{calls++;}),false);finish(ack(payload));await pending;assert.equal(calls,1);});
await test('CanonicalReadWriteGuardsAndScope',()=>{for(const mutate of [e=>e.ctx.soloLectura=true,e=>e.ctx.pilotoLectura=true,e=>e.ctx.real.estado='baja',e=>e.ctx.persona.id='other',e=>e.ctx.datos.personas.push({...e.ctx.real}),e=>e.ctx.ver=()=>({ok:false}),e=>e.ctx.veModulo=()=>false,e=>e.ctx.clientesVisibles[0].activo_confirmado=false,e=>e.D.tareas.push({...task,lista_id:'other'}),e=>e.D.tareas.push({...task}),e=>e.ctx.datos.personas[0].puestos=['seo'],e=>e.D.tareas=[]]){const e=context();mutate(e);assert.equal(c.ambitoComentario366(e,task),null);assert.throws(()=>c.prepararComentario366(e,task,'Nota operativa',uid));}});
await test('PostRevocationNoReceipt',async()=>{const e=context(),i=c.prepararComentario366(e,task,'Nota operativa',uid);await c.guardarComentario366(e,task,i,async p=>{e.ctx.ver=()=>({ok:false});return ack(p);});assert.equal(i.recibo,null);assert.equal(i.estado,'sin_confirmar');});
await test('RenderMissingReceiptRetainsTextRetrySameUUID',async()=>{const e=context(),requests=[];e.ctx.accion=async p=>{requests.push(p);return {ok:true,id:3};};const root=c.panelComentario366(e,task,h),txt=field(root),b=button(root);txt.value='Nota operativa';await b.attrs.on.click();assert.equal(txt.value,'Nota operativa');assert.equal(e.local.length,0);assert(text(root).includes('Reintentar la misma intención'));e.ctx.accion=async p=>{requests.push(p);return ack(p);};await b.attrs.on.click();assert.equal(requests[0],requests[1]);assert.equal(txt.value,'');assert.equal(e.local.length,1);assert.equal(e.local[0].estado,'simulado');assert.equal(e.local[0].intencion_id,uid);assert(text(root).includes('llegada a ClickUp sin confirmar'));});
await test('EditCreatesNewIntentWithoutReusingPreviousUUID',async()=>{const e=context(),sent=[];let n=0;c.crypto={randomUUID:()=>++n===1?uid:otherUid};e.ctx.accion=async p=>{sent.push(p);throw Error();};const root=c.panelComentario366(e,task,h),txt=field(root),b=button(root);txt.value='Primera nota';await b.attrs.on.click();txt.value='Segunda nota';txt.attrs.on.input();await b.attrs.on.click();assert.equal(sent[0].intencion_id,uid);assert.equal(sent[1].intencion_id,otherUid);assert.equal(txt.value,'Segunda nota');});
await test('StateStoredAcrossDetailRepaint',async()=>{const e=context();c.crypto={randomUUID:()=>uid};let request;e.ctx.accion=async p=>{request=p;throw Error();};let root=c.panelComentario366(e,task,h);field(root).value='Nota operativa';await button(root).attrs.on.click();root=c.panelComentario366(e,task,h);assert.equal(field(root).value,'Nota operativa');e.ctx.accion=async p=>{assert.equal(p,request);return ack(p);};await button(root).attrs.on.click();assert.equal(field(root).value,'');});
await test('LateRevocationClearsEditorNoPrivateAck',async()=>{const e=context();let finish,payload;e.ctx.accion=p=>{payload=p;return new Promise(r=>finish=r);};const root=c.panelComentario366(e,task,h);field(root).value='Nota operativa';const pending=button(root).attrs.on.click();e.ctx.clientesVisibles=[];finish(ack(payload));await pending;assert.equal(root.children.length,0);assert.equal(e.local.length,0);});
await test('RevokedRenderCannotShowOldDraftText',()=>{const e=context();let root=c.panelComentario366(e,task,h);field(root).value='Nota operativa';field(root).attrs.on.input();e.ctx.ver=()=>({ok:false});root=c.panelComentario366(e,task,h);assert.equal(buscar(root,x=>x.tag==='textarea').length,0);assert(!text(root).includes('Nota operativa'));});
await test('RevokeBeforeClickNoTransport',async()=>{const e=context();let calls=0;e.ctx.accion=async()=>{calls++;};const root=c.panelComentario366(e,task,h);field(root).value='Nota operativa';e.D.tareas=[];await button(root).attrs.on.click();assert.equal(calls,0);assert.equal(root.children.length,0);});
await test('ChangedTextDuringAwaitNotErasedAndNewIntent',async()=>{const e=context();let finish,payload;e.ctx.accion=p=>{payload=p;return new Promise(r=>finish=r);};const root=c.panelComentario366(e,task,h),txt=field(root);txt.value='Primera nota';const pending=button(root).attrs.on.click();txt.value='Otra nota';finish(ack(payload));await pending;assert.equal(txt.value,'Otra nota');assert.equal(e.local.length,1);txt.attrs.on.input();assert.equal(button(root).disabled,false);});
await test('InternalNullAndEmptyOwnUseExactRowsAndNullPayload',async()=>{for(const cid of [null,'']){const e=context(),t={...task,cli:cid};e.D.tareas=[t];e.ctx.real.puestos=['seo'];e.ctx.persona.puestos=['seo'];e.ctx.clientesVisibles=[];e.ctx.ver=()=>({ok:false});assert(c.ambitoComentario366(e,t));const intent=c.prepararComentario366(e,t,'Nota interna',uid);assert.equal(intent.payload.cliente_id,null);await c.guardarComentario366(e,t,intent,async p=>ack(p));assert(intent.recibo);}});
await test('InternalBroadAndCanonicalChiefStillRequireAuthoritativeRow',()=>{for(const kind of ['broad','chief']){const e=context(),t={...task,cli:null,persona_id:'worker'};e.D.tareas=[t];e.ctx.clientesVisibles=[];e.ctx.ver=()=>({ok:false});e.ctx.datos.personas.push({id:'worker',estado:'activo',puestos:['seo'],jefe:'yo'});if(kind==='chief'){e.ctx.real.puestos=['jefa_seo'];e.ctx.persona.puestos=['jefa_seo'];}assert(c.ambitoComentario366(e,t));e.D.tareas=[];assert.equal(c.ambitoComentario366(e,t),null);}});
await test('UndefinedMalformedForeignClientNeverMeansInternal',()=>{for(const cid of [undefined,{},[],false,0,'foreign']){const e=context(),t={...task,cli:cid};e.D.tareas=[t];assert.equal(c.ambitoComentario366(e,t),null);}const e=context(),t={...task,cli:null};e.D.tareas=[{...t,cli:undefined}];assert.equal(c.ambitoComentario366(e,t),null);});
await test('InternalIdentityAndRelationshipRevocationRemainDenied',()=>{const e=context(),t={...task,cli:null,persona_id:'worker'};e.D.tareas=[t];e.ctx.real.puestos=['jefa_seo'];e.ctx.persona.puestos=['jefa_seo'];e.ctx.datos.personas.push({id:'worker',estado:'activo',puestos:['seo'],jefe:'yo'});e.ctx.clientesVisibles=[];assert(c.ambitoComentario366(e,t));e.ctx.datos.personas[1].jefe='other';e.V.personas.push({id:'worker',jefe:'yo'});assert.equal(c.ambitoComentario366(e,t),null);});
await test('ScopeRoleChangeRepaintLostResponseKeepsUUIDAndPayload',async()=>{const e=context(),sent=[];c.crypto={randomUUID:()=>uid};e.ctx.accion=async p=>{sent.push(p);throw Error('response lost');};let root=c.panelComentario366(e,task,h);field(root).value='Nota operativa';await button(root).attrs.on.click();e.ctx.real.puestos=['operaciones','seo'];e.ctx.persona.puestos=['operaciones','seo'];c.crypto={randomUUID:()=>otherUid};root=c.panelComentario366(e,task,h);e.ctx.accion=async p=>{sent.push(p);return ack(p);};await button(root).attrs.on.click();assert.equal(sent[0],sent[1]);assert.equal(sent[1].intencion_id,uid);assert.equal(field(root).value,'');assert.equal(e.local.length,1);});
await test('RebaseCannotTransferBindingToOtherTaskOrListOrClient',async()=>{for(const change of [{id:'other-task'},{lista_id:'other-list'},{cli:'other-client'}]){const e=context(),i=c.prepararComentario366(e,task,'Nota operativa',uid),t={...task,...change};e.D.tareas=[t];e.ctx.clientesVisibles.push({id:'other-client',detalle:true,activo_confirmado:true});let calls=0;assert.equal(await c.guardarComentario366(e,t,i,()=>{calls++;}),false);assert.equal(calls,0);}});
await test('CurrentDetalleUsesActualPanelAndLegacyBypassRejected',()=>{const e=context();e.ctx.hoy='2026-10-03';e.ctx.nombre=x=>x;e.V.yo='yo';e.V.cambios=[];e.V.estados_lista={};e.V.estados_detalle={};e.ctx.pilotoLectura=true;const t={...task,grupoV:'hoy',capa:{cambios:[]}};const root=c.detalle(e,t,()=>{});assert.equal(buscar(root,x=>x.attrs?.['data-comentario-366']===task.id).length,1);assert(source.includes("if(tipo==='comentario')throw"));});
console.log(casos+' grupos366 PASS · renderer real, UUID/recibo194, revocación y retry sin proveedores');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
