const fs376=require('node:fs'),path376=require('node:path');
const base376=fs376.readFileSync(path376.join(__dirname,'pruebas_operaciones_equipo_262.cjs'),'utf8').split('(async()=>{')[0];
new Function('require','__dirname',base376+`
const cp=x=>JSON.parse(JSON.stringify(x));
function dto(){return {version:'376.1',estado:'copia_observada',generado:'2026-10-04T00:00:00Z',sha256_candidato:'1045a53219b967885e5bfe6748327c3ca19a48e71266bd4c522c4e236e833670',fuente:'ClickUp entradas',cobertura:'parcial',ventana:{desde:'2026-08-05',hasta_exclusivo:'2026-10-04',observado_hasta:'2026-10-03T00:56:00Z',zona:'Europe/Madrid',atribucion:'inicio'},fecha_fuente:'2026-10-03T00:56:00Z',unidad:'h',unidad_muestra:'usuario_id+task_id',unidad_maximo:'suma_por_caso',clasificacion:'orientativa_por_titulo',minimo_casos:5,filas:[{grupo:'optimizar seo',casos:5,mediana_h:3,max_h:7,total_h:17,registros_mas10h:0}],duracion_cerrada_confirmada:false,tipo_historico_confirmado:false,tiempo_normativo:null};}
function ctx376(){const a={id:'real',estado:'activo',activo:true,puestos:['operaciones']},ctx=make();Object.assign(ctx,{hoy:'2026-10-04',servidor:true,real:a,persona:{...a},datos:{personas:[a,{id:'p',estado:'activo',puestos:['seo']}]},api:async p=>{assert.equal(p,'horas/agrupaciones-tarea');return dto();}});ctx.clientes=ctx.clientesVisibles.map(c=>({...c}));return ctx;}
(async()=>{
await test('5 metrics same case sum',()=>{const m=c.modeloAgrupaciones376(dto(),ctx376());assert(m);assert.equal(m.filas[0].max_h,7);assert.equal(m.filas[0].total_h,17);});
await test('reject schema units windows future duplicate unknown0',()=>{for(const fn of [d=>d.sha256_candidato='a'.repeat(64),d=>d.unidad='min',d=>d.ventana.desde='2026-08-04',d=>d.ventana.zona='UTC',d=>d.generado='2026-10-05T00:00:00Z',d=>d.fecha_fuente='2026-02-30T00:00:00Z',d=>d.ventana.observado_hasta='2026-10-03T99:00:00Z',d=>d.filas.push(cp(d.filas[0])),d=>d.filas[0].mediana_h=null,d=>d.filas[0].casos=4,d=>d.filas[0].total_h=Infinity,d=>d.filas[0].grupo='password=fixture',d=>d.duracion_cerrada_confirmada=true]){const d=dto();fn(d);assert.equal(c.modeloAgrupaciones376(d,ctx376()),null);}});
await test('observedzero notunknown',()=>{const d=dto();Object.assign(d.filas[0],{mediana_h:0,max_h:0,total_h:0});assert.equal(c.modeloAgrupaciones376(d,ctx376()).filas[0].total_h,0);});
await test('canonical scope modules grants',()=>{for(const fn of [x=>x.real.estado='baja',x=>x.persona.puestos=['seo'],x=>x.datos.personas.push(cp(x.real)),x=>x.veModulo=()=>false,x=>x.servidor=false]){const x=ctx376();fn(x);assert.equal(c.ambitoAgrupaciones376(x),null);}});
await test('real renderer five columns all metrics',async()=>{const x=ctx376(),n=new N('main');await c.renderEquipo262(n,x,'tipos-tarea');const t=all(n,x=>x.tag==='table')[0];assert(t);assert.deepEqual(all(t,x=>x.tag==='th').map(text),['Tipo','Casos','Mediana','Máximo','H. total']);assert.deepEqual(all(t,x=>x.tag==='th').map(x=>x.attrs.title),['Tipo de tarea','Casos','Mediana','Máximo','Horas totales']);assert.deepEqual(all(t,x=>x.tag==='th').map(x=>x.attrs['aria-label']),all(t,x=>x.tag==='th').map(x=>x.attrs.title));assert(text(t).includes('optimizar seo'));assert(text(t).includes('17'));assert(!text(n).includes('Tipo fixture'));assert(text(n).includes('60 días'));assert(!text(n).includes('normal exigible'));});
await test('nocopy no legacy global fallback',async()=>{const x=ctx376();x.api=async()=>({ ...dto(),estado:'sin_dato',sha256_candidato:null,ventana:null,filas:[]});const n=new N('main');await c.renderEquipo262(n,x,'tipos-tarea');assert(!text(n).includes('Tipo fixture'));assert(text(n).includes('Pendiente'));assert.equal(all(n,x=>x.tag==='th').length,5);});
await test('valid scoped no five cases empty honest',async()=>{const x=ctx376();x.api=async()=>({...dto(),filas:[]});const n=new N('main');await c.renderEquipo262(n,x,'tipos-tarea');assert(text(n).includes('cinco casos'));assert(!text(n).includes('Tipo fixture'));});
await test('revoked await no old numbers',async()=>{const x=ctx376();x.api=async()=>{x.ver=()=>({ok:false});return dto();};const n=await c.renderAgrupaciones376(c.h,x);assert(!text(n).includes('optimizar seo'));assert.equal(all(n,x=>x.tag==='table').length,0);});
await test('catalog changed await deny',async()=>{const x=ctx376();x.api=async()=>{x.datos.personas[1].estado='baja';return dto();};const n=await c.renderAgrupaciones376(c.h,x);assert.equal(all(n,x=>x.tag==='table').length,0);});
await test('detached creation can load before parent attaches',async()=>{const x=ctx376(),hh=(...args)=>{const n=c.h(...args);if(n instanceof N)n.isConnected=false;return n;},n=await c.renderAgrupaciones376(hh,x);assert.equal(all(n,x=>x.tag==='table').length,1);assert(text(n).includes('optimizar seo'));});
await test('canonical clients ACT change stale visible denies',async()=>{for(const change of [x=>x.clientes[0].activo_confirmado=false,x=>x.clientes.push(cp(x.clientes[0])),x=>x.clientes=[]]){const x=ctx376();x.api=async()=>{change(x);return dto();};const n=await c.renderAgrupaciones376(c.h,x);assert.equal(all(n,x=>x.tag==='table').length,0);assert(!text(n).includes('optimizar seo'));}});
await test('no canonical client catalog no request',async()=>{const x=ctx376();delete x.clientes;let calls=0;x.api=async()=>{calls++;return dto();};await c.renderAgrupaciones376(c.h,x);assert.equal(calls,0);});
await test('view change await no render',async()=>{const x=ctx376();x.api=async()=>{x.persona.id='other';return dto();};const n=await c.renderAgrupaciones376(c.h,x);assert.equal(all(n,x=>x.tag==='table').length,0);});
await test('details revoke clears metrics',async()=>{const x=ctx376(),n=await c.renderAgrupaciones376(c.h,x),d=all(n,x=>x.tag==='details')[0];x.clientesVisibles[0].activo_confirmado=false;d.events.toggle();assert(!text(n).includes('optimizar seo'));});
await test('API denied source not0',async()=>{const x=ctx376();x.api=async()=>{throw Object.assign(Error(),{status:403});};const n=await c.renderAgrupaciones376(c.h,x);assert(!text(n).includes('Tipo fixture'));assert(text(n).includes('No se pudo'));});
await test('canonical invalid no request',async()=>{const x=ctx376();x.real.estado='baja';let calls=0;x.api=async()=>{calls++;return dto();};const n=await c.renderAgrupaciones376(c.h,x);assert.equal(calls,0);assert.equal(all(n,x=>x.tag==='table').length,0);});
console.log(checks+' grupos376 PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
`)(require,__dirname);
