const fs=require('fs'),path=require('path'),assert=require('assert/strict');const base=fs.readFileSync(__dirname+'/pruebas_resumen_274.cjs','utf8').split('(async()=>{')[0];const {tmp,walk}=new Function('require','__dirname',base+';return {tmp,walk};')(require,__dirname);
(async()=>{try{const M=await import('file://'+path.join(tmp,'_operaciones_resumen_274.mjs'));const {h}=await import('file://'+path.join(tmp,'componentes.mjs'));let n=0;const test=async(name,f)=>{await f();n++;console.log('PASS '+name);};
function ctx(){const ops={id:'ops',estado:'activo',puestos:['operaciones']},acc={id:'acc',estado:'activo',puestos:['account']},clients=['a','b'].map(id=>({id,nombre:id,activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}));return {servidor:true,hoy:'2026-10-04',real:{...ops},persona:{...ops},datos:{personas:[ops,acc],asignaciones:[]},clientes:structuredClone(clients),clientesVisibles:clients,carteraPorSilla:{account:new Set(['a','b'])},ver:()=>({ok:true}),veModulo:()=>true,nombre:id=>id,verdad:()=>null,vigente:()=>true,api:async()=>null};}
const main=()=>{const m=h('main',{});m.connected=true;return m;},cartera=root=>walk(root).find(x=>x.tag==='details'&&x.children[0]?.textContent==='Accounts de un vistazo');
await test('4columnas íntegramente conservadas sin duplicarcartera comoCarga',async()=>{const c=ctx(),model=M.modeloResumen274(c),root=main();assert.equal(model.accounts.length,1);assert.equal(model.accounts[0].clientes,2);assert.equal(model.accounts[0].referenciaCarga.valor,'2');await M.renderResumen274(root,c,{fuentes:{}});const block=cartera(root),table=walk(block).find(x=>x.tag==='table');assert.deepEqual(walk(table).filter(x=>x.tag==='th').map(x=>x.textContent),['Account','Clientes visibles','Nota','Carga']);const row=walk(table).find(x=>x.tag==='tbody').children[0];assert.deepEqual(row.children.map(x=>x.textContent),['acc','2','—','—']);assert(row.children[3].children[0].attrs['aria-label'].includes('desconocida'));assert(row.children[3].textContent!=='2');assert.equal(block.attrs.open,true);});
await test('Referencia íntegra en detailscerrado; no párrafo largo encima',async()=>{const root=main();await M.renderResumen274(root,ctx(),{fuentes:{}});const block=cartera(root),ref=walk(block).find(x=>x.tag==='details'&&x.children[0]?.textContent==='Fuente y referencia');assert(ref);assert.notEqual(ref.attrs.open,true);assert(ref.textContent.includes('Capacidad12'));assert(ref.textContent.includes('referencia histórica0–100'));assert(ref.textContent.includes('no se repite ese número como carga'));assert.equal(block.children[1].tag,'div');assert(!block.children.slice(0,2).some(x=>x.textContent.includes('Capacidad12')));});
await test('Abrirfuente despuésACT/grant revocado elimina contenido',async()=>{for(const mutate of [c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false}),c=>c.datos.personas.push({...c.real})]){const c=ctx(),root=main();await M.renderResumen274(root,c,{fuentes:{}});const ref=walk(cartera(root)).find(x=>x.tag==='details');mutate(c);ref.attrs.on.toggle();assert.equal(root.children[0].children.length,0);}});
await test('Source/modelo no mutados; notas noverde, onceysietes siguen',async()=>{const c=ctx(),before=JSON.stringify(c.clientes),root=main();await M.renderResumen274(root,c,{fuentes:{}});assert.equal(JSON.stringify(c.clientes),before);assert.equal(walk(root).filter(x=>x.attrs.class==='tiles274').reduce((sum,x)=>sum+x.children.length,0),11);assert.equal(walk(root).find(x=>x.attrs.class==='pasos274').children.length,7);const table=walk(cartera(root)).find(x=>x.tag==='table');assert(walk(table).filter(x=>x.attrs['data-estado']).every(x=>x.attrs['data-estado']==='gris'));});
console.log(n+' grupos535 PASS · renderer274/modelo263 reales; sinPOST');}finally{fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
