const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(tag,attrs,...children){this.tag=tag;this.attrs=attrs||{};this.children=children.flat().filter(x=>x!=null);this.style={};this.dataset={};this.isConnected=true;this.events={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x.filter(x=>x!=null);}addEventListener(k,f){this.events[k]=f;}querySelector(){return null;}querySelectorAll(){return [];}setAttribute(k,v){this.attrs[k]=v;}remove(){}focus(){} }
const h=(t,a,...c)=>new El(t,a,...c),txt=n=>n instanceof El?n.children.map(txt).join(' '):String(n??'');
const s={console,Date,Map,Set,JSON,Number,Array,String,Object,Promise,h,icono:()=>'',chipEstado:(c,t)=>h('span',{},t),vacio:o=>h('p',{},o.titulo,o.texto),esqueleto:()=>h('p',{},'Leyendo'),panel:(o,...c)=>h('section',{},o.titulo,...c),logoCliente:()=>'',iniciales:()=>'',fmt:x=>x,fechaCorta:x=>x,diaMes:x=>x,conTickets:x=>x,avisoFlotante:()=>{},copiar:async()=>{},requestAnimationFrame:()=>{},setTimeout,MutationObserver:class{observe(){}},window:{matchMedia:()=>({matches:false})},history:{replaceState(){}},document:{getElementById:()=>null},chipsFiltro:()=>({valor:()=>''})};vm.createContext(s);
function load(file){const raw=fs.readFileSync(__dirname+'/modulos/'+file+'.js','utf8');const names=[...raw.matchAll(/^export (?:async )?(?:function|const) (\w+)/gm)].map(x=>x[1]);const src=raw.replace(/^import .*$/gm,'').replace(/export default /,'const modulo333=').replace(/export /g,'');if(raw.includes('export default'))names.push('modulo333');Object.assign(s,vm.runInContext('(()=>{'+src+'\nreturn {'+names.join(',')+'};})();',s));}
load('_alcance_asistente_333');load('ia_componentes');s.estilosIA=s.estilos;s.pestanas=o=>{const z=h('div',{});o.pintar(o.activa,z);z.elegir=id=>o.pintar(id,z);return z;};load('asistente_ia');
const persona={id:'mili',estado:'activo',puestos:['operaciones']},cliente={id:'c',nombre:'Nombre vigente',activo_confirmado:true,detalle:true};
function ctx(){return {real:{...persona},persona:{...persona},datos:{personas:[{...persona}]},clientesVisibles:[{...cliente}],servidor:true,veModulo:()=>true,ver:()=>({ok:true}),vigente:()=>true,params:[],titulo(){},api:async route=>route==='ia/lista'?{copiloto:[],borradores:[],estado:{conectada:false}}:{ok:false,motivo:'Sin propuesta'}};}
const dto={copiloto:[{cliente_id:'c',nombre:'Nombre viejo',color:'rojo'},{cliente_id:'privado',nombre:'NO_EXPONER'}],borradores:[{cliente_id:'c',ticket:'RO-1',cliente:'Nombre viejo'}],estado:{}};

let count=0;async function test(f){await f();count++;}
async function render(dto){const c=ctx(),root=h('main',{});c.api=async route=>route==='ia/lista'?dto:{ok:false,motivo:'Sin propuesta'};await s.modulo333.render(root,c);return {text:txt(root),root,c};}
const base={copiloto:[],borradores:[],estado:{conectada:false}};
(async()=>{
await test(async()=>{const x=await render(base);assert(x.text.includes('Lista disponible: 0 clientes'));assert(x.text.includes('0 borradores'));assert(x.text.includes('Sin borradores disponibles'));assert(x.text.includes('sin recuento acreditado'));assert(!x.text.includes('0 datos por completar'));assert(!x.text.includes('40 correos'));assert(x.text.includes('sin fecha acreditada'));});
await test(async()=>{const x=await render({...base,borradores:[{cliente_id:'c',ticket:'RO-1',huecos:0},{cliente_id:'privado',ticket:'RO-2',huecos:7}]});assert(x.text.includes('1 borradores'));assert(x.text.includes('0 datos por completar'));assert(!x.text.includes('7 datos'));assert(x.text.includes('no es el total de correos pendientes'));});
await test(async()=>{for(const n of [undefined,null,true,'0',-1,Infinity,2.5]){const x=await render({...base,borradores:[{cliente_id:'c',ticket:'RO-1',huecos:n}]});assert(x.text.includes('sin recuento acreditado'));assert(!x.text.includes('0 datos por completar'));}});
await test(async()=>{for(const conectada of ['false',1,{},null]){const x=await render({...base,estado:{conectada}});assert(x.text.includes('Estado del proveedor sin confirmar'));assert(!x.text.includes('Proveedor disponible'));}});
await test(async()=>{const x=await render({...base,estado:{conectada:true,modelo:'fixture'}});assert(x.text.includes('Proveedor disponible según el servidor'));assert(x.text.includes('Disponibilidad no acredita una llamada nueva'));assert(!x.text.includes('IA conectada'));});
await test(async()=>{const x=await render({...base,generado:'2026-10-03T12:00:00Z'});assert(x.text.includes('3-oct, 14:00 (Madrid)'));assert(!x.text.includes('2-oct'));assert(x.root.children[2].attrs.title==='2026-10-03T12:00:00Z');});
await test(async()=>{const x=await render({...base,generado:'2026-10-02 18:34'});assert(x.text.includes('2-oct, 18:34 (zona no declarada)'));assert(!x.text.includes('(Madrid)'));});
await test(async()=>{for(const generado of ['2026-02-30T12:00:00Z','2026-10-03T24:00:00Z','2026-10-03T12:00:00+02:99','2026-10-03T12:00:00+15:00',{},false]){const x=await render({...base,generado});assert(x.text.includes('sin fecha acreditada'));assert(!x.root.children[2].attrs.title);}});
await test(async()=>{const x=await render({...base,borradores:[{cliente_id:'c',ticket:'RO-1',huecos:Number.MAX_SAFE_INTEGER},{cliente_id:'c',ticket:'RO-2',huecos:1}]});assert(x.text.includes('sin recuento acreditado'));});
await test(async()=>{const c=ctx(),root=h('main',{});let release;c.api=()=>new Promise(r=>release=r);const pending=s.modulo333.render(root,c);c.veModulo=()=>false;release({...base,generado:'2026-10-03T12:00Z'});await pending;assert.equal(txt(root),'');});
console.log(count+' grupos604 PASS: render actual, contrato333 y componentes IA reales, datos ficticios.');
})().catch(e=>{console.error(e);process.exitCode=1;});
