const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const c={Intl,Date,Set,Map,Number};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'modulos/_produccion_baseline.js'),'utf8').replace(/export /g,''),c);
let n=0;const test=(name,fn)=>{fn();n++;};
const snapshot=(v)=>({valor:v||null,observaciones:v,estado:v?'observado_parcial':'sin_observaciones',cobertura:'parcial',tipo:'snapshot',mas48:null});
const evento=(v,desde,campo='date_created')=>({valor:v||null,observaciones:v,estado:v?'observado_parcial':'sin_observaciones',cobertura:'parcial',tipo:'eventos_fechados',desde,hasta:'2026-10-03T13:08:00Z',campo});
const fixture=()=>{const e={version:'256.1',cliente_id:'c',fuente:'clickup_cache_local',corte:'2026-10-03T13:08:00Z',fecha_original:'2026-10-03 15:08',zona:'Europe/Madrid',lunes:'2026-09-28',mes:'2026-10',cobertura:'parcial',sha256_tareas:'a'.repeat(64),sha256_catalogo:'b'.repeat(64),sha256_candidato:'c'.repeat(64),metricas:{account:snapshot(3),tecnica:snapshot(2),bloqueadas:snapshot(0),cliente:snapshot(4),creadas_mes:evento(5,'2026-09-30T22:00:00Z'),creadas_semana:evento(8,'2026-09-27T22:00:00Z'),cerradas_semana:evento(1,'2026-09-27T22:00:00Z','date_done_or_closed+catalogo_actual_terminal')}};const p={cliente_id:'c',creadas_mes:999,bloqueadas:99,_revision_account:{n:123,mas48:120,fecha:'2026-10-02 09:16'},_evidencia_produccion_256:e},d={hoy:'2026-10-03',fuentes:{flujo:{hora:'2026-10-02 09:16'}},proyectos:[p],revisiones:[]};return{p,d,e};};
test('Typed wins counts and preserves unknown age over old120',()=>{const{p,d}=fixture(),x=c.metricasProyectoBaseline(p,d);assert.equal(x.account.valor,3);assert.equal(x.account.mas48,null);assert.equal(x.tecnica.valor,2);assert.equal(x.creadas_mes.valor,5);assert.equal(x.bloqueadas.valor,null);});
test('No zero or noPlanning fallback from typedunknown',()=>{const{p,d}=fixture();p.no_planificadas=999;p.sin_tareas_mes=true;const x=c.metricasProyectoBaseline(p,d);assert.equal(x.no_plan.valor,null);assert.equal(x.sin_mes.valor,null);});
test('Cross-client or duplicate raw descriptor never grants typed data',()=>{let{p,d,e}=fixture();e.cliente_id='ajeno';assert.equal(c.descriptorProduccion256(p,d),null);({p,d}=fixture());d.proyectos.push({...p});assert.equal(c.descriptorProduccion256(p,d),null);});
test('MalformedSHA/zone/cut/period rejects source',()=>{for(const alter of [e=>e.sha256_tareas='bad',e=>e.zona='UTC',e=>e.corte='2026-10-04T13:08:00Z',e=>e.lunes='2026-09-21',e=>e.mes='2026-09',e=>e.fecha_original='2026-10-03 18:08']){const{p,d,e}=fixture();alter(e);assert.equal(c.descriptorProduccion256(p,d),null);}});
test('Invalid date month not revived from ISOoverflow',()=>{const{p,d,e}=fixture();e.corte='2026-02-30T13:08:00Z';assert.equal(c.descriptorProduccion256(p,d),null);});
test('Period exactMadrid-midnight not totalsfromdifferentwindow',()=>{const{p,d,e}=fixture();e.metricas.creadas_mes.desde='2026-10-01T00:00:00Z';assert.equal(c.metricasProyectoBaseline(p,d).creadas_mes.valor,null);});
test('Fractional/colliding count counters unknown',()=>{for(const alter of [m=>m.observaciones=.5,m=>m.valor=999,m=>m.estado='completo',m=>m.cobertura='completa']){const{p,d,e}=fixture();alter(e.metricas.creadas_mes);assert.equal(c.metricasProyectoBaseline(p,d).creadas_mes.valor,null);}});
test('No old/newcohort aggregation even if numberspositive',()=>{const{p,d}=fixture(),t=c.metricasProyectoBaseline(p,d).account;const out=c.sumarMetricaBaseline([t,{valor:7,cohorte:'legacy:2026-10-02:account'}],2);assert.equal(out.valor,null);assert(out.detalle.includes('No')||out.detalle.includes('no se suman'));});
test('Same typedcohort sums partial nofakeknownzero',()=>{const{p,d}=fixture(),t=c.metricasProyectoBaseline(p,d).account;const out=c.sumarMetricaBaseline([t,{...t,valor:null}],2);assert.equal(out.valor,3);assert.equal(out.medidos,1);assert.equal(c.sumarMetricaBaseline([{...t,valor:null}],1).valor,null);});
test('Header newer typeddate and explicit legacydate',()=>{const{p,d}=fixture(),s=c.fuenteProduccionBaseline([p],d);assert(s.includes('2026-10-03 15:08'));assert(s.includes('2026-10-02 09:16'));assert(s.includes('anteriores'));});
// Actual candidate adapter, not an invented schema: no PII printed.
test('Typed candidate49 currentproject fields survive parser',()=>{const f=path.join(__dirname,'../RECUPERACION_CODEX_2026-10-03/staging_produccion_typed_256/produccion.json');const D=JSON.parse(fs.readFileSync(f,'utf8')),ps=D.proyectos.filter(p=>p._evidencia_produccion_256);assert.equal(ps.length,49);for(const p of ps){assert(c.descriptorProduccion256(p,D));const x=c.metricasProyectoBaseline(p,D);assert.equal(x.account.valor,p._evidencia_produccion_256.metricas.account.valor);assert.equal(x.account.mas48,null);assert.equal(x.creadas_semana.valor,p._evidencia_produccion_256.metricas.creadas_semana.valor);}});
console.log(`${n} grupos typed256 PASS`);
