const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(t){this.tag=t;this.children=[];this.style={};this.attrs={};}append(...xs){this.children.push(...xs.flat(Infinity).filter(x=>x!=null));}setAttribute(k,v){this.attrs[k]=String(v);}addEventListener(){}}
const b={Date,Intl,Map,Set,Node:N,document:{createElement:t=>new N(t),createTextNode:t=>String(t)},fmt:{num:(v,n=0)=>Number(v).toLocaleString('es-ES',{maximumFractionDigits:n}),plural:(n,s,p)=>`${n} ${n===1?s:p}`},chipEstado:(e,t)=>{const x=new N('chip');x.estado=e;x.append(t);return x;}};vm.createContext(b);
for(const f of ['_horas_diarias_238.js','_control_equipo_313.js']){const s=fs.readFileSync(__dirname+'/modulos/'+f,'utf8').replace(/^import[^;]+;\s*/gm,'').replace(/export /g,'');vm.runInContext(`(()=>{${s};Object.assign(this,{${f.startsWith('_horas')?'serieHorasDiaria238':'prepararControlEquipo313,celdaControlEquipo313,diaControlEquipo313'}})})()`,b);}
const comp=fs.readFileSync(__dirname+'/componentes.js','utf8');vm.runInContext(comp.slice(comp.indexOf('export function h('),comp.indexOf('const svgNS =')).replace('export ',''),b);
const md=fs.readFileSync(__dirname+'/modulos/mi_dia.js','utf8');vm.runInContext(md.slice(md.indexOf('function mapaControl('),md.indexOf('\n/** Altas en su pista'))+';this.mapa=mapaControl;',b);
const ctx=()=>({hoy:'2026-10-03',datos:{personas:[{id:'a',estado:'activo'},{id:'b',estado:'activo'}]},ver:x=>({ok:x.tipo==='horas_persona'&&['a','b'].includes(x.persona_id)})});
const control=()=>[{persona_id:'a',persona_ref:'a',nombre:'Fixture',imputa:{ayer:0},revisa:{mas48:0},contesta:{mas48:0},reune:{sin_reunion:0,sin_correo_sem:0}}];
const H=()=>({hoy:'2026-10-03',personas:[{persona_id:'a',diario_238:{version:'238.1',fuente:'ClickUp entradas',cobertura:'parcial',zona_confirmada:true,zona:'Europe/Madrid',fecha_fuente:'2026-10-03T08:00:00Z',desde:'2026-09-28',hasta:'2026-10-02',dias:['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'].map((fecha,i)=>({fecha,estado:i===4?'observado':'sin_dato',horas:i===4?14:null,entradas:i===4?2:null}))}}]});
const text=x=>x instanceof N?x.children.map(text).join(' '):String(x??''),all=(x,p)=>[...(x instanceof N&&p(x)?[x]:[]),...(x instanceof N?x.children.flatMap(y=>all(y,p)):[])];
let n=0;const test=(label,f)=>{f();n++;};
test('Fecha L–V explícita noasumefestivos',()=>{assert.equal(b.diaControlEquipo313('2026-10-03'),'2026-10-02');assert.equal(b.diaControlEquipo313('2026-10-05'),'2026-10-02');assert.equal(b.diaControlEquipo313('2026-02-30'),null);});
test('Typedpositivo mismafuentefecha parcial nogreen',()=>{const r=b.prepararControlEquipo313(ctx(),control(),H())[0],d=b.celdaControlEquipo313(r,'imputa');assert.equal(d.valor,14);assert.equal(d.tipo,'observado');assert.equal(d.estado,'gris');assert.equal(d.fecha,'2026-10-02');assert(d.detalle.includes('parcial'));});
test('Cero realentrada observado vsdefault sinDato',()=>{const h=H();h.personas[0].diario_238.dias[4].horas=0;assert.equal(b.celdaControlEquipo313(b.prepararControlEquipo313(ctx(),control(),h)[0],'imputa').valor,0);assert.equal(b.celdaControlEquipo313(b.prepararControlEquipo313(ctx(),control(),null)[0],'imputa').valor,null);});
test('Legacypositivo conservadoref explícita, sinpct/disciplina',()=>{const x=control();x[0].imputa.ayer=3.5;const r=b.prepararControlEquipo313(ctx(),x,null)[0];assert.equal(b.celdaControlEquipo313(r,'imputa').valor,3.5);assert.equal(b.celdaControlEquipo313(r,'imputa').tipo,'referencia');});
test('Source/rango/identidad/día inválidos no vuelven medidos',()=>{for(const change of [h=>h.hoy='2026-10-02',h=>h.personas[0].diario_238.desde='2026-09-01',h=>h.personas[0].diario_238.zona_confirmada=false,h=>h.personas[0].diario_238.dias[4].entradas=0,h=>h.personas.push({...h.personas[0]}),h=>h.personas[0].persona_id='ajeno',h=>h.personas[0].diario_238.fecha_fuente='2026-10-04']){const h=H();change(h);assert.equal(b.celdaControlEquipo313(b.prepararControlEquipo313(ctx(),control(),h)[0],'imputa').valor,null);}});
test('Scopepersonas P/activo/duplicado/nohomónimos',()=>{for(const change of [c=>c.ver=()=>({ok:false}),c=>c.datos.personas[0].estado='baja',c=>c.datos.personas.push({...c.datos.personas[0]})]){const c=ctx();change(c);assert.equal(b.prepararControlEquipo313(c,control(),H()).length,0);}const x=control();x[0].persona_ref='b';assert.equal(b.prepararControlEquipo313(ctx(),x,H()).length,0);assert.equal(b.prepararControlEquipo313(ctx(),[...control(),...control()],H()).length,0);});
test('Otrosceros/ausencia gris, positivos referenciasnoacusación',()=>{const x=control();x[0].revisa.mas48=7;const r=b.prepararControlEquipo313(ctx(),x,H())[0];assert.equal(b.celdaControlEquipo313(r,'revisa').valor,7);assert.equal(b.celdaControlEquipo313(r,'contesta').valor,null);assert.equal(b.celdaControlEquipo313(r,'reunion').valor,null);});
test('Render realtabla6columnas 0legacy no0h/rojo/verde',()=>{const el=b.mapa(b.prepararControlEquipo313(ctx(),control(),null),10);assert.equal(all(el,x=>x.tag==='th'&&x.attrs.scope==='col').length,6);assert(!text(el).includes('0 h'));assert(!text(el).includes('No imputaron'));assert(all(el,x=>x.tag==='chip').every(x=>x.estado==='gris'));assert(text(el).includes('—'));});
test('Render real14h conserva ysource/detailalclictooltip',()=>{const el=b.mapa(b.prepararControlEquipo313(ctx(),control(),H()),10);assert(text(el).includes('14 h'));assert(all(el,x=>x.tag==='td'&&x.attrs.title?.includes('2026-10-02')).length);assert(all(el,x=>x.tag==='chip').every(x=>x.estado==='gris'));});
test('Rawrenderer sinpreparación failclosed sinNum0',()=>{const el=b.mapa(control(),10);assert(!text(el).includes('0 h'));assert(all(el,x=>x.tag==='chip').every(x=>x.estado==='gris'));});
const bloques=fs.readFileSync(__dirname+'/modulos/mi_dia_bloques.js','utf8');
b.def=(id,usa,fn)=>{b.bloque=fn;b.usa=usa;};b.controlPersona=()=>({});b.fresco=()=>({texto:'Fixture'});
vm.runInContext(bloques.slice(bloques.indexOf("def('equipo_control'"),bloques.indexOf("def('para_tomas'")),b);
const ejecutar=(c,rows,h)=>b.bloque(c,{dato:()=>({control:rows}),opcional:k=>k==='horas/horas'?h:{no_imputan_ayer:['a','b']}},{},{});
test('Bloque real ausencia legacy no9/9rojo ni nombres acusatorios',()=>{const r=ejecutar(ctx(),control(),null);assert(b.usa.includes('horas/horas'));assert.equal(r.estado,'gris');assert.equal(r.valor,1);assert.equal(r.filas.length,0);assert(!JSON.stringify(r).includes('No imputaron'));assert.equal(r.mapa[0].imputa.ayer,null);assert(r.motivo.includes('no se evalúa jornada'));});
test('Bloque real conserva typed14 sin juicio y filas scope Ops/propio',()=>{const rows=[...control(),{...control()[0],persona_id:'b',persona_ref:'b',nombre:'Fixture B'}];const ops=ejecutar(ctx(),rows,H());assert.equal(ops.mapa.length,2);assert.equal(ops.mapa[0].imputa.ayer,14);const own=ctx();own.ver=x=>({ok:x.tipo==='horas_persona'&&x.persona_id==='a'});assert.equal(ejecutar(own,rows,H()).mapa.length,1);own.ver=()=>({ok:false});const denied=ejecutar(own,rows,H());assert.equal(denied.mapa.length,0);assert.equal(denied.valor,null);});
console.log(n+' grupos controlEquipo313 PASS');
