const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ro342-'));fs.chmodSync(dir,0o700);
const mod=path.join(__dirname,'modulos');
const harness=fs.readFileSync(path.join(__dirname,'pruebas_operaciones_accounts_263.cjs'),'utf8');
const stub=harness.match(/fs.writeFileSync\(path.join\(dir,'componentes.mjs'\),`([\s\S]*?)`\);/)[1];fs.writeFileSync(path.join(dir,'componentes.mjs'),stub);
for(const name of ['_cabeceras_operaciones_423','_referencia_score_408','_seguimiento_accounts_404','_kpis_compactos_396','_top_alarmas_388','_llamadas_historicas_353','_pedidos_macro_344','_mensaje_alarma_345','_alarmas_operaciones_342','_orden_clientes_348','_horas_cartera_349','_operaciones_accounts_263','control_cartera','_control_artifact_250','_control_cartera_ruta_239','_imputa_personal_390','_historial_diario_364','_bandas_horas_381','_horas_diarias_238','_evidencias_resumen']){let s=fs.readFileSync(path.join(mod,name+'.js'),'utf8').replace(/from '\.\/([^']+)\.js'/g,"from './$1.mjs'").replace("from '../componentes.js'","from './componentes.mjs'");fs.writeFileSync(path.join(dir,name+'.mjs'),s);}
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
let groups=0;const test=(name,f)=>{f();groups++;console.log('PASS',name);};
(async()=>{try{
 const {h}=await import('file://'+path.join(dir,'componentes.mjs')),{ambitoAlarmas342,proyectarAlarmas342,pintarAlarmas342,etiquetaTipoAlarma342}=await import('file://'+path.join(dir,'_alarmas_operaciones_342.mjs')),{renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 function ctx(){const ops={id:'ops',estado:'activo',puestos:['operaciones']};return {real:{...ops},persona:{...ops},hoy:'2026-10-03',servidor:true,vigente:()=>true,veModulo:()=>true,ver:()=>({ok:true}),nombre:id=>id,clientes:[{id:'c1',nombre:'Cliente Uno',activo_confirmado:true,detalle:true}],clientesVisibles:[{id:'c1',nombre:'Cliente Uno',activo_confirmado:true,detalle:true}],datos:{personas:[{...ops},{id:'a1',estado:'activo',puestos:['account']}],asignaciones:[]},carteraPorSilla:{account:new Set(['c1'])},verdad:cid=>({cliente_id:cid,gravedad:'atencion'}),datosModulo:async()=>null,api:async()=>null};}
 const row=(i,extra={})=>({id:'x'+i,cliente_id:'c1',tipo:'web_caida',titulo:'Alarma web '+i,motivo:'Hecho autorizado '+i,gravedad:i%2?'alta':'media',ir:'#/seo-web',...extra});
 const doc=(rows=Array.from({length:8},(_,i)=>row(i)))=>({generado:'2026-10-03T12:00:00Z',alertas:rows});
 const rows=[{cliente_id:'c1',account_id:'a1'}];
 test('tipo fuera siete reglas conservado y orden severity',()=>{const m=proyectarAlarmas342(ctx(),doc(),rows);assert.equal(m.filas.length,8);assert.equal(m.filas[0].gravedad,'rojo');assert.equal(m.filas[0].tipo,'web_caida');});
 test('cliente ajeno, duplicado o inactivo no entra',()=>{const c=ctx();const d=doc([row(0),row(1,{cliente_id:'otro'})]);assert.equal(proyectarAlarmas342(c,d).filas.length,1);c.clientesVisibles.push({...c.clientesVisibles[0]});assert.equal(proyectarAlarmas342(c,d).filas.length,0);});
 test('IDduplicado no se deduplica escogiendo el primero',()=>assert.equal(proyectarAlarmas342(ctx(),doc([row(1),row(1,{titulo:'Distinto'})])).filas.length,0));
 test('persona ajena o actor duplicado/inactivo deniegan',()=>{assert.equal(proyectarAlarmas342(ctx(),doc([row(1,{persona_id:'ajeno'})])).filas.length,0);const c=ctx();c.datos.personas.push({...c.real});assert.equal(ambitoAlarmas342(c),null);c.datos.personas.pop();c.real.activo=false;assert.equal(ambitoAlarmas342(c),null);});
 test('Accountnormal usa fuentepropia y excluye no cliente',()=>{const c=ctx();c.real=c.persona={id:'a1',estado:'activo',puestos:['account']};assert.equal(ambitoAlarmas342(c).ruta,'alertas/p_a1');assert.equal(proyectarAlarmas342(c,doc([row(0),row(1,{cliente_id:null})])).filas.length,1);});
 test('Opsreal/vercomoAccount no elige global',()=>{const c=ctx();c.persona={id:'a1',estado:'activo',puestos:['account']};assert.equal(ambitoAlarmas342(c).ops,false);assert.equal(ambitoAlarmas342(c).ruta,'alertas/p_a1');});
 test('no cliente sólo Opsambas; persona exigegrant',()=>{const c=ctx();assert.equal(proyectarAlarmas342(c,doc([row(1,{cliente_id:null})])).filas.length,1);c.ver=d=>({ok:d.tipo!=='alarma_persona'});assert.equal(proyectarAlarmas342(c,doc([row(1,{cliente_id:null,persona_id:'a1'})])).filas.length,0);});
 test('fuente ausente/futura no lista0certificada',()=>{assert.equal(proyectarAlarmas342(ctx(),null),null);assert.equal(proyectarAlarmas342(ctx(),{...doc(),generado:'2026-10-04T12:00:00Z'}),null);});
 test('permiso detalle cerrado y enlace externo/codetraversal no pasa',()=>{const c=ctx();c.ver=d=>({ok:d.tipo!=='alarma_detalle'});const m=proyectarAlarmas342(c,doc([row(1,{motivo:'No permitido'})]));assert.doesNotMatch(JSON.stringify(m.filas),/No permitido/);for(const ir of ['https://otro.test','#/seo-web/%2e%2e/ficha','#/seo-web/../ficha'])assert.equal(proyectarAlarmas342(ctx(),doc([row(1,{ir})])).filas[0].ruta,null);});
 const main=h('main',{});main.connected=true;const c=ctx();const root=pintarAlarmas342(main,c,doc(),rows);
 test('render real un cliente prioritario y resto7 conserva ocho alarmas',()=>{assert.equal(walk(root).filter(n=>n.tag==='li').length,8);assert.match(text(root),/Resto de la colección · 7/);assert.match(text(root),/copia parcial/);});
 test('filtra tipo/severidad y reset sin afectar inventario',()=>{const sel=walk(root).find(n=>n.attrs['aria-label']==='Severidad de la alarma');sel.events.change({target:{value:'rojo'}});assert.equal(walk(root).filter(n=>n.tag==='li').length,4);walk(root).find(n=>n.tag==='button'&&text(n)==='Restablecer alarmas').events.click();assert.equal(walk(root).filter(n=>n.tag==='li').length,8);});
 test('callback tras grantrevocado limpia textos antiguos',()=>{c.veModulo=()=>false;walk(root).find(n=>n.attrs['aria-label']==='Tipo de alarma').events.change({target:{value:'web_caida'}});assert.equal(walk(root).filter(n=>n.tag==='li').length,0);assert.doesNotMatch(text(root),/Hecho autorizado/);});
 const calls=[],full=h('main',{});full.connected=true;const rctx=ctx();rctx.datosModulo=async ruta=>{calls.push(ruta);return ruta==='alertas/alertas'?doc():null;};await renderAccounts263(full,rctx,'hoy');
 test('integración263 matriz original intacta + colección separada1GET',()=>{assert.equal(calls.filter(x=>x==='alertas/alertas').length,1);assert.match(text(full),/Quién tiene registros en cada regla/);assert.equal(walk(full).filter(n=>n.tag==='li').length,8);});
 let resolve;const stale=h('main',{});stale.connected=true;const staleCtx=ctx();staleCtx.datosModulo=async ruta=>ruta==='alertas/alertas'?new Promise(r=>resolve=r):null;
 const pending=renderAccounts263(stale,staleCtx,'hoy');while(!resolve)await new Promise(r=>setImmediate(r));
 test('matriz ya visible mientras colección aún pendiente',()=>assert.match(text(stale),/Quién tiene registros en cada regla/));staleCtx.clientesVisibles[0].activo_confirmado=false;resolve(doc());await pending;
 test('revocación ACT duranteGET no publica colección tardía',()=>assert.doesNotMatch(text(stale),/Hecho autorizado/));
 const off=h('main',{});off.connected=true;const no=ctx();no.datosModulo=async ruta=>{if(ruta.includes('alertas'))throw Error('403');return null;};await renderAccounts263(off,no,'hoy');
 test('denegaciónfuente conserva matriz y unknown explícito',()=>{assert.match(text(off),/Quién tiene registros en cada regla/);assert.match(text(off),/Fuente no disponible/);assert.doesNotMatch(text(off),/0 registros autorizados/);});
 test('Account con cliente visible pero fuera cartera no publica fila',()=>{const c=ctx();c.real=c.persona={id:'a1',estado:'activo',puestos:['account']};c.carteraPorSilla.account.clear();assert.equal(proyectarAlarmas342(c,doc()).filas.length,0);});
 for(const [nombre,revocar] of [['modulo',c=>c.veModulo=m=>m!=='alertas'],['actor',c=>c.datos.personas[0].activo=false],['detalle',c=>c.ver=d=>({ok:d.tipo!=='cliente_detalle'})]]){
  let fin;const box=h('main',{});box.connected=true;const c=ctx();c.datosModulo=async ruta=>ruta==='alertas/alertas'?new Promise(r=>fin=r):null;
  const request=renderAccounts263(box,c,'hoy');while(!fin)await new Promise(r=>setImmediate(r));revocar(c);fin(doc());await request;
  test('revocación '+nombre+' duranteGET no datos tardíos',()=>assert.doesNotMatch(text(box),/Hecho autorizado/));
 }
 test('etiquetas coinciden con catálogo local sin importar productor ni sus umbrales',()=>{const source=fs.readFileSync(path.join(__dirname,'fuentes_alertas/generar_alertas.py'),'utf8'),catalog=source.slice(source.indexOf('REGLAS = ['),source.indexOf('REGLA = {'));const matches=[...catalog.matchAll(/\{"id": "([^"]+)", "dep": "[^"]+", "titulo": "([^"]+)"/g)];assert.ok(matches.length>30);for(const [,id,titulo] of matches)assert.equal(etiquetaTipoAlarma342(id),titulo);assert.equal(etiquetaTipoAlarma342('tipo_sin_catalogo'),'Otro tipo de alarma');});
 test('roles contextuales deben coincidir exactamente con catálogo canónico',()=>{for(const quien of ['real','persona']){const c=ctx();c[quien]={...c[quien],puestos:['seo']};assert.equal(ambitoAlarmas342(c),null);}const c=ctx();c.real.puestos=['operaciones','operaciones'];assert.equal(ambitoAlarmas342(c),null);const d=ctx();d.datos.personas[0].puestos=['operaciones','seo'];d.real.puestos=['seo','operaciones'];d.persona.puestos=['operaciones','seo'];assert.ok(ambitoAlarmas342(d));});
 test('tipos humanos en filtro y chips conservan ID de selección',()=>{const box=h('main',{});box.connected=true;const c=ctx();const root=pintarAlarmas342(box,c,doc([row(0),row(1,{tipo:'acc_critico'})]),rows);assert.match(text(root),/Web caída/);assert.match(text(root),/Cliente en crítico/);assert.doesNotMatch(text(root),/web_caida|acc_critico/);const opt=walk(root).find(n=>n.tag==='option'&&n.attrs.value==='web_caida');assert.equal(text(opt),'Web caída');walk(root).find(n=>n.attrs['aria-label']==='Tipo de alarma').events.change({target:{value:'acc_critico'}});assert.equal(walk(root).filter(n=>n.tag==='li').length,1);});
 for(const [nombre,revocar] of [['detalle',c=>c.ver=d=>({ok:d.tipo!=='alarma_detalle'})],['rol contextual',c=>c.persona.puestos=['seo']],['actor canónico',c=>c.datos.personas[0].activo=false]]){
  test('abrir Resto tras revocar '+nombre+' limpia contenido antiguo',()=>{const box=h('main',{});box.connected=true;const c=ctx(),root=pintarAlarmas342(box,c,doc(),rows),resto=walk(root).find(n=>n.tag==='details'&&text(n).includes('Resto de la colección'));assert.ok(resto.events.toggle);revocar(c);resto.open=true;resto.events.toggle({target:resto});assert.doesNotMatch(text(root),/Hecho autorizado|Alarma web/);assert.equal(walk(root).filter(n=>n.tag==='li').length,0);assert.match(text(root),/no está disponible/);});
 }
 for(const caso of ['APIdeclaraciones rechaza','sin permiso mi-trabajo']){
  const box=h('main',{});box.connected=true;const c=ctx(),calls=[];let apiCalls=0;
  if(caso==='sin permiso mi-trabajo')c.veModulo=m=>m!=='mi-trabajo';
  c.api=async ruta=>{if(ruta.startsWith('clientes/evidencias_kpi/resumen'))apiCalls++;throw Error('Declaraciones no disponibles');};
  c.datosModulo=async ruta=>{calls.push(ruta);return ruta==='alertas/alertas'?doc():null;};
  await renderAccounts263(box,c,'hoy');
  test('colección se resuelve independientemente: '+caso,()=>{assert.equal(apiCalls,caso==='sin permiso mi-trabajo'?0:1);assert.equal(calls.filter(x=>x==='alertas/alertas').length,1);assert.equal(walk(box).filter(n=>n.tag==='li').length,8);assert.doesNotMatch(text(box),/Leyendo colección/);assert.match(text(box),/Quién tiene registros en cada regla/);});
 }
 console.log(groups+' grupos PASS · helpers y render263 reales sin negocioPOST');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
