const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/carcasa.js','utf8'),start=source.indexOf('function iniciarMenuEscritorio418()'),end=source.indexOf('// ------------------------------------------------------------------ N12',start),fn=source.slice(start,end);
let groups=0;const test=(name,f)=>{f();groups++;};
function fixture({wide=true,pref=null,storageError=false,existingId='',legacy=false}={}){
 let env,writes=[],changes=[];
 class N{constructor(tag,attrs={},kids=[]){this.tag=tag;this.attrs=attrs;this.id=attrs.id||'';this.children=[];this.events={};this.hidden=false;const cs=new Set((attrs.class||'').split(' ').filter(Boolean));this.classList={toggle:(c,on)=>{changes.push(c);if(on)cs.add(c);else cs.delete(c);},contains:c=>cs.has(c),add:c=>cs.add(c)};this.append(...kids);}append(...xs){this.children.push(...xs.flat(Infinity).filter(x=>x!=null));}prepend(x){this.children.unshift(x);}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}addEventListener(k,f){this.events[k]=f;}contains(n){return this===n||this.children.some(c=>c instanceof N&&c.contains(n));}focus(){env.document.activeElement=this;}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}set textContent(v){this.children=[v];}}
 const h=(t,a,...kids)=>new N(t,a,kids),navLink=h('a',{href:'#/fixture'},'Acceso autorizado'),side=h('nav',{id:existingId,class:'side'},navLink),mobile=h('button',{id:'menu-btn'},'Menú móvil'),bar=h('div',{class:'topbar-in'},mobile),app=h('div',{class:'app'},side,h('div',{class:'content'},bar));
 const walk=n=>[n,...n.children.filter(c=>c instanceof N).flatMap(walk)],media={matches:wide};
 if(legacy)media.addListener=f=>media.change=f;else media.addEventListener=(_,f)=>media.change=f;
 env={h,icono:()=>h('svg',{'aria-hidden':'true'}),matchMedia:q=>{assert.equal(q,'(min-width: 901px)');return media;},localStorage:{getItem:k=>{assert.equal(k,'ro.menu.escritorio.plegado');if(storageError)throw Error('denied');return pref;},setItem:(k,v)=>{if(storageError)throw Error('denied');writes.push([k,v]);pref=v;}},document:{activeElement:null,querySelector:s=>({'.app':app,'.app > .side':side,'.topbar-in':bar})[s],getElementById:id=>walk(app).find(n=>n.id===id)||null}};
 vm.createContext(env);vm.runInContext(fn,env);const init=()=>env.iniciarMenuEscritorio418();return {env,app,side,mobile,bar,navLink,media,writes,changes,init};
}
test('botón nativo accesible controla nav completo y no menú móvil',()=>{const f=fixture(),b=f.init();assert.equal(b.tag,'button');assert.equal(b.attrs.type,'button');assert.equal(b.attrs['aria-controls'],f.side.id);assert.equal(b.attrs['aria-expanded'],'true');assert.equal(b.attrs['aria-label'],'Contraer menú');assert.equal(b.title,'Contraer menú');assert.equal(f.bar.children[0],b);assert.equal(f.mobile.textContent,'Menú móvil');});
test('contraer y expandir no destruye entradas ni cambia rutas',()=>{const f=fixture(),b=f.init(),link=f.navLink;b.events.click();assert(f.app.classList.contains('menu-contraido'));assert(f.side.inert);assert.equal(f.side.attrs['aria-hidden'],'true');assert.equal(b.attrs['aria-expanded'],'false');assert.equal(b.attrs['aria-label'],'Expandir menú');b.events.click();assert(!f.app.classList.contains('menu-contraido'));assert.equal(f.side.inert,false);assert(!Object.hasOwn(f.side.attrs,'aria-hidden'));assert.equal(f.side.children[0],link);assert.equal(link.attrs.href,'#/fixture');assert.deepEqual(f.writes.map(x=>x[1]),['1','0']);});
test('foco sale de navegación antes de esconderla',()=>{const f=fixture(),b=f.init();f.env.document.activeElement=f.navLink;b.events.click();assert.equal(f.env.document.activeElement,b);});
test('restaura sólo preferencia1, claves privadas o JSON ignorados',()=>{for(const p of ['0','true','{"id":"persona"}',null]){const f=fixture({pref:p});f.init();assert(!f.app.classList.contains('menu-contraido'));}const f=fixture({pref:'1'}),b=f.init();assert(f.app.classList.contains('menu-contraido'));assert.equal(b.attrs['aria-expanded'],'false');assert.equal(f.writes.length,0);});
test('fallo de almacenamiento no impide reversibilidad',()=>{const f=fixture({storageError:true}),b=f.init();b.events.click();assert(f.side.inert);b.events.click();assert.equal(f.side.inert,false);});
test('móvil no aplica preferencia de escritorio ni responde a clic programado',()=>{const f=fixture({wide:false,pref:'1'}),b=f.init();assert(b.hidden);assert.equal(f.side.inert,false);assert(!f.app.classList.contains('menu-contraido'));f.app.classList.add('menu-abierto');b.events.click();assert(f.app.classList.contains('menu-abierto'));assert.equal(f.writes.length,0);assert(!f.app.classList.contains('menu-contraido'));});
test('cambio a móvil libera inert y mueve foco al control móvil',()=>{const f=fixture({pref:'1'}),b=f.init();b.focus();f.media.matches=false;f.media.change();assert.equal(f.env.document.activeElement,f.mobile);assert(b.hidden);assert.equal(f.side.inert,false);assert(!Object.hasOwn(f.side.attrs,'aria-hidden'));f.media.matches=true;f.media.change();assert(f.side.inert);assert(!b.hidden);assert.equal(b.attrs['aria-expanded'],'false');});
test('al regresar a escritorio el control está visible antes de recibir foco',()=>{const f=fixture({wide:false,pref:'1'}),b=f.init();b.focus=()=>{assert.equal(b.hidden,false);f.env.document.activeElement=b;};f.env.document.activeElement=f.navLink;f.media.matches=true;f.media.change();assert.equal(f.env.document.activeElement,b);assert(f.side.inert);});
test('inicio duplicado no duplica controles ni listeners',()=>{const f=fixture({existingId:'menu-actual'}),b=f.init();assert.equal(f.init(),b);assert.equal(f.bar.children.filter(x=>x.id==='menu-escritorio-btn').length,1);assert.equal(b.attrs['aria-controls'],'menu-actual');});
test('media legacy funciona y falta de DOM o media es inocua',()=>{const f=fixture({legacy:true}),b=f.init();f.media.matches=false;f.media.change();assert(b.hidden);f.env.document.querySelector=()=>null;assert.equal(f.init(),null);const g=fixture();g.env.matchMedia=undefined;assert.equal(g.init(),null);});
test('CSS oculta nav sólodesktop y elimina columna/fondo vacíos',()=>{const css=fs.readFileSync(__dirname+'/estilos.css','utf8'),a=css.indexOf('/*418'),chunk=css.slice(a,css.indexOf('/* K4',a));assert.match(chunk,/@media \(min-width: 901px\)/);assert.match(chunk,/grid-template-columns: minmax\(0, 1fr\)/);assert.match(chunk,/\.app\.menu-contraido > \.side \{ display: none/);assert.match(chunk,/background: none/);assert.match(chunk,/min-height: 44px/);assert(!chunk.includes('.menu-abierto'));});
console.log(groups+' grupos418 PASS · control real: reversibilidad, accesibilidad, foco, almacenamiento y móvil sin cambios.');
