const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const harness=fs.readFileSync('pruebas_captacion_compacta_243.cjs','utf8').split('const c={')[0];const outer={require,console,__dirname:process.cwd()};vm.createContext(outer);vm.runInContext(harness+';globalThis.E=e;globalThis.Nodo=N;globalThis.H=h;',outer);const e=outer.E,N=outer.Nodo,h=outer.H;
const append=N.prototype.append;N.prototype.append=function(...kids){append.apply(this,kids);for(const x of this.children)if(x instanceof N)x.parentNode=this;};
Object.defineProperty(N.prototype,'classList',{get(){this._classes??=new Set();return {add:x=>this._classes.add(x),contains:x=>this._classes.has(x),toggle:(x,v)=>v?this._classes.add(x):this._classes.delete(x)};}});
Object.defineProperty(N.prototype,'childElementCount',{get(){return this.children.filter(x=>x instanceof N).length;}});
N.prototype.closest=function(q){const classes=q.split(',').map(x=>x.trim());for(let n=this;n;n=n.parentNode)if(classes.some(x=>x==='thead'?n.tag==='thead':String(n.attrs.class||'').split(' ').includes(x.slice(1))))return n;return null;};
let uid=0;e.uid=()=>String(++uid);e.fmt={num:String};e.poner=(n,x)=>n.replaceChildren(x);e.celdaPorDefecto=String;e.estadoVacio=()=>h('div',{},'Vacío');e.menuElegir=o=>h('div',{},o.opciones.map(p=>h('button',{on:{click:()=>o.alCambiar(p.valor)}},p.texto)));
const source=fs.readFileSync('componentes.js','utf8');vm.runInContext(source.slice(source.indexOf('export function tablaDensa('),source.indexOf('// ------------------------------------------------------------ capas flotantes')).replace('export ',''),e);
const all=(n,f)=>[...(n instanceof N&&f(n)?[n]:[]),...(n instanceof N?n.children.flatMap(x=>all(x,f)):[])];
vm.runInContext(fs.readFileSync('modulos/_serie_paid_549.js','utf8').replaceAll('export ',''),e);
const c={cliente_id:'c1',nombre:'Cuenta uno',gravedad:'atencion',severidad:'dato',equipo:{trafficker:'p1'},meta_activa:true,dinero:false,leads:{},gasto:{},motivos:[],panelEspecialista:{real:null,objetivo:null,hasta:null,racha:null,creativos:null,accion:'Contrastar'}};
const d={parametros:{},bitacora:new Map()},ctx={nivel:'todo',soloLectura:true,navegar(){},fechas:{esHoy:()=>false},vigente:()=>true};
const out=h('main',{});e.pCuentas(out,ctx,d,[c,{...c,cliente_id:'c2',nombre:'Cuenta dos',equipo:{trafficker:'p2'}}],{},{});const pane=all(out,n=>n.attrs['aria-label']==='Detalle de la cuenta Paid')[0];
const detailButtons=()=>all(out,n=>n.tag==='button'&&n.textContent==='Ver');
function dispatch(n,type){const ev={target:n,stopPropagation(){},preventDefault(){}};n.on[type]?.(ev);for(let p=n;p;p=p.parentNode)p.events?.[type]?.(ev);}
let count=0;const test=fn=>{fn();count++;};
test(()=>{dispatch(detailButtons()[0],'click');assert(pane.textContent.includes('Cuenta uno'));dispatch(detailButtons()[1],'click');assert(pane.textContent.includes('Cuenta dos'));assert(!pane.textContent.includes('Cuenta uno'));});
test(()=>{dispatch(all(pane,n=>n.tag==='button'&&n.textContent==='Cerrar detalle')[0],'click');assert.equal(pane.children.length,0);dispatch(detailButtons()[0],'click');assert(pane.textContent.includes('Cuenta uno'));});
test(()=>{const input=all(out,n=>n.tag==='input'&&n.attrs.type==='search')[0];input.value='Cuenta dos';dispatch(input,'input');assert.equal(pane.children.length,0);assert.equal(detailButtons().length,1);dispatch(detailButtons()[0],'click');assert(pane.textContent.includes('Cuenta dos'));});
test(()=>{const th=all(out,n=>n.tag==='th')[0],sort=all(th,n=>n.tag==='button')[0];dispatch(sort,'click');assert.equal(pane.children.length,0);});
test(()=>{const cell=e.celdaRevisionCompacta243({...ctx,servidor:true},d,c,pane);dispatch(all(cell,n=>n.tag==='button')[0],'click');assert.equal(pane.children.length,0);});
// Ámbito Paid actual: no exige fuente Meta ni permiso de inversión.
const actor={id:'actor',estado:'activo',puestos:['trafficker']},client={id:'c1',activo_confirmado:true,detalle:true};const server={...ctx,servidor:true,real:actor,persona:actor,datos:{personas:[actor]},clientes:[client],clientesVisibles:[{...client}],veModulo:()=>true,ver:()=>({ok:true})};
test(()=>{const cell=e.celdaRevisionCompacta243(server,d,c,pane);dispatch(all(cell,n=>n.tag==='button')[0],'click');assert(pane.textContent.includes('Cuenta uno'));server.clientes[0].activo_confirmado=false;const anchor=all(pane,n=>n.tag==='a')[0];let blocked=false;all(pane,n=>n.events?.click)[0].events.click({preventDefault(){blocked=true;},stopPropagation(){}});assert(blocked);assert.equal(pane.children.length,0);});
test(()=>{const many=h('main',{});e.pCuentas(many,ctx,d,Array.from({length:15},(_,i)=>({...c,cliente_id:'x'+i,nombre:'Cuenta '+i})),{},{});const dest=all(many,n=>n.attrs['aria-label']==='Detalle de la cuenta Paid')[0];dispatch(all(many,n=>n.tag==='button'&&n.textContent==='Ver')[0],'click');assert(dest.children.length);const more=all(many,n=>n.tag==='button'&&n.textContent.startsWith('Ver 3 más'))[0];assert(more);dispatch(more,'click');assert.equal(dest.children.length,0);assert.equal(all(many,n=>n.tag==='button'&&n.textContent==='Ver').length,15);});
test(()=>{const original=e.chipsFiltro;e.chipsFiltro=o=>Object.assign(h('div',{},o.opciones.map(p=>h('button',{on:{click:()=>o.alCambiar?.(p.valor)}},p.texto))),{valor:()=>o.multiple?[]:''});const filtered=h('main',{});e.pCuentas(filtered,ctx,d,[c,{...c,cliente_id:'c2',nombre:'Cuenta dos',equipo:{trafficker:'p2'}}],{},{});const dest=all(filtered,n=>n.attrs['aria-label']==='Detalle de la cuenta Paid')[0];dispatch(all(filtered,n=>n.tag==='button'&&n.textContent==='Ver')[0],'click');dispatch(all(filtered,n=>n.tag==='button'&&n.textContent==='p2')[0],'click');assert.equal(dest.children.length,0);assert.equal(all(filtered,n=>n.tag==='button'&&n.textContent==='Ver').length,1);e.chipsFiltro=original;});
test(()=>{const account={id:'carla',estado:'activo',puestos:['account']},a={...server,real:account,persona:account,datos:{personas:[account]},clientes:[{...client,activo_confirmado:true}],clientesVisibles:[{...client,activo_confirmado:true}],soloLectura:true,ver:o=>({ok:o.tipo!=='inversion'})};const cell=e.celdaRevisionCompacta243(a,d,{...c,meta_activa:false},pane);dispatch(all(cell,n=>n.tag==='button')[0],'click');assert(pane.textContent.includes('Cuenta uno'));assert(!all(pane,n=>n.tag==='button'&&n.textContent==='Apuntar').length);});
test(()=>{let money=true;const a={...server,clientes:[{...client,activo_confirmado:true}],clientesVisibles:[{...client,activo_confirmado:true}],ver:o=>({ok:o.tipo!=='inversion'||money})};const cell=e.celdaRevisionCompacta243(a,d,c,pane);dispatch(all(cell,n=>n.tag==='button')[0],'click');assert(pane.children.length);money=false;all(pane,n=>n.events?.click)[0].events.click({preventDefault(){},stopPropagation(){}});assert.equal(pane.children.length,0);});
console.log(count+' grupos415 PASS: tablaDensa real, cambio cuenta/cierre/reapertura/búsqueda/orden, sin privilegio nuevo y revocación con ámbito Paid real.');
