const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const e={};vm.createContext(e);for(const name of ['_tendencias_operaciones_329','_miniserie_operaciones_439'])vm.runInContext('(()=>{'+fs.readFileSync(__dirname+'/modulos/'+name+'.js','utf8').replaceAll('export ','')+';Object.assign(globalThis,{'+(name.includes('329')?'compararMediciones329,tendenciasFotos329,METRICAS329':'modeloMiniserie439,pintarMiniserie439')+'});})();',e);
const scope='a'.repeat(64),ahora='2026-10-04T12:00:00Z',opts={scopeHash:scope,actorId:'ops',ahora};
const med=(valor,corte)=>({version:'329.1',id:'rojas',valor,validado_servidor:true,origen:'medicion_copia',scope_hash:scope,cohorte_hash:'b'.repeat(64),definicion_hash:'c'.repeat(64),unidad:'alarmas',completa:false,corte,leido:ahora,periodo:{tipo:'stock'}});
const foto=(key,m,typed=true)=>({tipo:'foto',objeto:key,registrado_por:'ops',registrado_en:ahora,scope_hash:scope,cumplimiento:null,exhaustiva:false,metricas:e.METRICAS329.map(([id,etiqueta])=>({id,etiqueta,valor:id==='rojas'?m.valor:null,fecha_fuente:id==='rojas'?m.corte:null,estado:id==='rojas'?'observado_copia':'desconocido'})),mediciones_329:typed?[m]:[]});
const a=med(5,'2026-10-02T08:00:00Z'),b=med(3,'2026-10-03T08:00:00Z'),c=med(4,'2026-10-04T08:00:00Z');let n=0;
const read=regs=>e.tendenciasFotos329({version:'272.1',registros:regs},opts)[1];
let r=read([foto('a',a),foto('b',b),foto('c',c)]),g=e.modeloMiniserie439(r);assert(g);assert.equal(g.puntos.length,3);assert.equal(g.segmentos.length,2);assert.match(g.detalle,/alarmas.*parcial/);assert.match(g.detalle,/Variación última \+1/);n++;
assert.equal(e.modeloMiniserie439(read([foto('a',a,false),foto('b',b,false)])),null);assert.equal(e.modeloMiniserie439(read([foto('a',a)])),null);n++;
for(const change of [{cohorte_hash:'d'.repeat(64)},{definicion_hash:'d'.repeat(64)},{unidad:'clientes'},{completa:true},{scope_hash:'d'.repeat(64)},{periodo:{tipo:'mes'}}])assert.equal(e.modeloMiniserie439(read([foto('a',a),foto('b',{...b,...change})])),null);n++;
for(const cut of ['2026-10-03T24:00:00Z','2026-10-03T08:00:00+14:30','2026-10-03T08:00:00+02:99','2026-02-30T08:00:00Z'])assert.equal(e.modeloMiniserie439(read([foto('a',a),foto('b',{...b,corte:cut})])),null);n++;
assert.equal(e.modeloMiniserie439(read([foto('a',a),foto('b',b),foto('dup',b)])),null);n++;
r=read([foto('a',{...a,valor:0}),foto('b',{...b,valor:0})]);g=e.modeloMiniserie439(r);assert(g.puntos.every(p=>p.y===13));assert.match(g.detalle,/Variación última 0/);n++;
const h=(tag,attrs,...kids)=>({tag,attrs,kids});assert.equal(e.pintarMiniserie439(h,r,()=>false),null);const node=e.pintarMiniserie439(h,r,()=>true);assert.equal(node.attrs.role,'img');assert.equal(node.attrs.title,node.attrs['aria-label']);assert(!node.attrs.title.includes('cumplido'));n++;
// Renderer265 real + dependencias reales, con regresiones intactas y capturas de las celdas.
let harness=fs.readFileSync(__dirname+'/probar_operaciones_265.cjs','utf8');
harness=harness.replace("if(mode==='legacy')assert(tt.includes('Referencia de copia: 11'));",`const walk439=n=>n&&typeof n==='object'?[n,...(n.children||[]).flat(Infinity).flatMap(walk439)]:[];const charts439=walk439(root).filter(n=>n.attrs?.['data-miniserie-439']);assert.equal(charts439.length,mode==='typed'?1:0);if(mode==='typed'){assert.match(charts439[0].attrs['aria-label'],/2 cortes compatibles/);const fuente439=walk439(root).find(n=>n.tag==='details'&&walk439(n).some(x=>x.tag==='summary'&&text(x)==='Fuentes y cortes'));assert(fuente439);c.clientes.push({id:'revocado',activo_confirmado:false});fuente439.attrs.on.toggle();assert.equal(root.children[0].children.length,0);}if(mode==='legacy')assert(tt.includes('Referencia de copia: 11'));`);
const run=require('node:child_process').spawnSync(process.execPath,['-e',harness],{cwd:__dirname,encoding:'utf8'});process.stdout.write(run.stdout||'');process.stderr.write(run.stderr||'');assert.equal(run.status,0);console.log(n+' grupos439 puros + renderer26522reg PASS; fuentes/pares/flat0/legacy/revocación, sin red ni POST real.');
