const fs=require('fs'),assert=require('assert/strict');const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_equipo_262.cjs','utf8').split('(async()=>{')[0];const {c,N,all,text,H,docs,make}=new Function('require','__dirname',prefix+';return {c,N,all,text,H,docs,make};')(require,__dirname);const copy=x=>JSON.parse(JSON.stringify(x));let n=0;const test=async(label,f)=>{await f();n++;console.log('PASS '+label);};const days=['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'];
const row=(id,vs=[1,1,1,1,1])=>({persona:{persona_id:id},serie:{zona:'Europe/Madrid',fecha_fuente:'2026-10-03T00:56:00Z',dias:days.map((fecha,i)=>({fecha,estado:vs[i]===null?'sin_dato':'observado',horas:vs[i],entradas:vs[i]===null?null:1}))}});const order=rs=>Array.from(c.ordenarEquipoDia539(rs,days,'2026-10-03'),r=>r.persona.persona_id);
(async()=>{
await test('Últimafecha ascendente, no total ni8h',()=>assert.deepEqual(order([row('a',[0,0,0,0,4]),row('b',[8,8,8,8,0]),row('c',[1,1,1,1,2])]),['b','c','a']));
await test('Suma5sóloobservaciones completas desempata',()=>assert.deepEqual(order([row('high',[4,4,4,4,2]),row('partial',[null,0,0,0,2]),row('low',[0,0,0,0,2])]),['low','high','partial']));
await test('Últimafechaunknown alfinal sin ausencia0; cero explícito primero',()=>assert.deepEqual(order([row('unknown',[1,1,1,1,null]),row('one'),row('zero',[0,0,0,0,0])]),['zero','one','unknown']));
await test('Overflowtotal unknown sinromper últimaobservación',()=>assert.deepEqual(order([row('overflow',[1e308,1e308,0,0,2]),row('finite',[1,1,1,1,2])]),['finite','overflow']));
await test('Tiposinvalidos/duplicadofecha noautoridad',()=>{const a=row('a');a.serie.dias.push({...a.serie.dias.at(-1)});const b=row('b');b.serie.dias.at(-1).horas=true;assert.deepEqual(order([a,b,row('zero',[0,0,0,0,0])]),['zero','a','b']);});
await test('Zonadistinta/cortedíaincompleto alfinal',()=>{const a=row('a');a.serie.zona='UTC';const b=row('b');b.serie.fecha_fuente='2026-10-02T00:00Z';assert.deepEqual(order([a,b,row('ok')]),['ok','a','b']);});
await test('Cortesincompatibles noreordena como rankingúnico',()=>{const a=row('a',[2,2,2,2,2]),b=row('b',[1,1,1,1,1]);b.serie.fecha_fuente='2026-10-03T01:56:00Z';assert.deepEqual(order([a,b]),['a','b']);});
await test('Ventana inválida/identidadduplicada estableysinmutar',()=>{const rs=[row('a'),row('a'),row('b')],before=JSON.stringify(rs);assert.deepEqual(order(rs),['b','a','a']);assert.equal(JSON.stringify(rs),before);assert.deepEqual(Array.from(c.ordenarEquipoDia539(rs,days.slice(1),'2026-10-03'),x=>x.persona.persona_id),['a','a','b']);});
await test('Empatesexactos estables yDSTfechasciviles',()=>{assert.deepEqual(order([row('z'),row('a')]),['z','a']);const dates=Array.from(c.diasLaborables262('2026-03-30'));assert.equal(dates.at(-1),'2026-03-27');});
await test('Rendererreal11cols conserva valores/unknown/orden yfilas',async()=>{const data=copy(H);data.personas=[row('high',[4,4,4,4,2]),row('partial',[null,0,0,0,2]),row('low',[0,0,0,0,2]),row('zero',[0,0,0,0,0])].map(({persona,serie})=>({...persona,nombre:persona.persona_id,diario_238:{...copy(H.personas[0].diario_238),dias:serie.dias}}));const ctx=make();ctx.datosModulo=async p=>p==='horas/horas'?data:docs[p];const root=new N('main');await c.renderEquipo262(root,ctx,'equipo-dia');const table=all(root,x=>x.tag==='table')[0],body=all(table,x=>x.tag==='tbody')[0];assert.equal(all(table,x=>x.tag==='th').length,11);assert.deepEqual(body.children.map(r=>text(r.children[1])),['zero','low','high','partial']);assert.equal(body.children.length,4);assert.equal(text(body.children[3].children[2]),'—');assert.equal(text(body.children[0].children[6]),'0');});
await test('Rendererpermiso revocado durantelectura no publicaorden/filas',async()=>{let active=true;const ctx=make();ctx.vigente=()=>active;ctx.datosModulo=async p=>{active=false;return docs[p];};const root=new N('main');await c.renderEquipo262(root,ctx,'equipo-dia');assert.equal(all(root,x=>x.tag==='table').length,0);});
await test('Denegación362 no rescata238 ni personaslegacy',async()=>{const ctx=make(),actor={id:'ops',estado:'activo',puestos:['operaciones']};ctx.real=ctx.persona=actor;ctx.servidor=true;ctx.datos={personas:[actor,{id:'p',estado:'activo',puestos:['account']}]};ctx.api=async()=>{throw {status:403};};const root=new N('main');await c.renderEquipo262(root,ctx,'equipo-dia');assert.equal(all(root,x=>x.tag==='table').length,0);assert(!text(root).includes('Persona fixture'));});
console.log(n+' grupos539 PASS · ordenpuro/renderer262 real, sinPOST');})().catch(e=>{console.error(e);process.exitCode=1;});
