//400B caracterización independiente. Actual263+396+control138; sin HTTP/DB.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_accounts_263.cjs','utf8').split('(async()=>{try{')[0];
const {dir}=new Function('require','__dirname',prefix+';return {dir};')(require,__dirname);
const clone=x=>JSON.parse(JSON.stringify(x)),walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
function ctx(){const ps=[{id:'ops',estado:'activo',puestos:['operaciones']},{id:'acc',estado:'activo',puestos:['account']}],cs=[{id:'ok',nombre:'Cliente sintético',activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}];return {servidor:true,hoy:'2026-10-05',real:clone(ps[0]),persona:clone(ps[0]),datos:{personas:clone(ps),asignaciones:[]},clientes:clone(cs),clientesVisibles:clone(cs),carteraPorSilla:{account:new Set(['ok'])},veModulo:()=>true,ver:()=>({ok:true}),nombre:x=>x,vigente:()=>true,api:async()=>null,datosModulo:async()=>null};}
const production={hoy:'2026-09-30',fuentes:{horas:{hora:'2026-10-02 05:00'}},proyectos:[{cliente_id:'ok',horas_mes:7,horas_medicion:{estado:'medido',fuente:'horas',periodo:'2026-09',fecha:'2026-10-02 05:00'}}]};
const reference={generado:'2026-10-02 05:00',mes_cuota:'2026-10',clientes:[{cliente_id:'ok',cuota_horas:{pautadas:20},cuota:987654}]};
let passed=0;const bugs=[];async function test(name,f){try{await f();passed++;}catch(e){bugs.push({name,error:e.message});}}
(async()=>{try{
 const {h,N}=await import('file://'+path.join(dir,'componentes.mjs'));N.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(N.prototype,'className',{get(){return this.attrs.class||'';},set(v){this.attrs.class=v;}});
 const {renderAccounts263,prepararAccounts263,ambitoAccounts316}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 const {celdaKpiCompacta396}=await import('file://'+path.join(dir,'_kpis_compactos_396.mjs'));
 await test('compact396 preserves count/state/evidence and does not inventpercent',async()=>{const cell={valor:'1/2 registros',estado:'ambar',detalle:'Una observación, no cumplimiento',medicion:{total:3}};const z=celdaKpiCompacta396(cell,{tabla:'account',indice:4});assert.equal(z.valor,'1/2');assert.equal(z.estado,'ambar');assert.equal(z.medicion,cell.medicion);assert(z.detalle.includes('1/2 registros'));assert(!z.valor.includes('%'));});
 await test('view-as account scope own and no finance GET',async()=>{const c=ctx();c.persona=clone(c.datos.personas[1]);let calls=[];c.datosModulo=async r=>{calls.push(r);return null;};const root=h('main',{});root.connected=true;await renderAccounts263(root,c,'accounts');assert(!calls.some(r=>r.includes('dinero')));assert.equal(prepararAccounts263(c).groups.length,1);c.carteraPorSilla.account=new Set();assert.equal(prepararAccounts263(c).rows.length,0);});
 await test('missing semantic sources never compliance score or zero',async()=>{const d=prepararAccounts263(ctx());assert.equal(d.groups[0].nota.valor,'—');assert.equal(d.groups[0].celdas.planifica.valor,'—');assert.equal(d.groups[0].celdas.reune.valor,'—');assert.equal(d.groups[0].kpis[7].valor,'—');});
 await test('canonical ACT revocation during await must prevent late row',async()=>{const c=ctx();let finish,entered;const pending=new Promise(r=>finish=r),started=new Promise(r=>entered=r);c.datosModulo=async()=>{entered();return pending;};const root=h('main',{});root.connected=true;const req=renderAccounts263(root,c,'accounts');await started;c.clientes[0].activo_confirmado=false;finish(null);await req;assert(!text(root).includes('Cliente sintético'),'Fila obsoleta publicada aunque catálogo actual revocó ACT');});
 await test('canonical client duplicate after load must clear cached row',async()=>{const c=ctx(),root=h('main',{});root.connected=true;await renderAccounts263(root,c,'clientes');c.clientes.push(clone(c.clientes[0]));const reset=walk(root).find(n=>n.tag==='button'&&text(n)==='Restablecer filtros');reset.events.click();assert(!text(root).includes('Cliente sintético'),'Catálogo canónico duplicado no invalida matriz cached');});
 await test('different-month observation and reference cannot form visible pair',async()=>{const d=prepararAccounts263(ctx(),{produccion:production,dinero_cliente:reference});assert.equal(d.rows[0].horas.medicion.periodo,'2026-09');assert.equal(d.rows[0].pauta_horas.periodo,'2026-10');assert(!d.rows[0].horasPauta.valor.includes('/ 20'),'La celda empareja septiembre observado con pauta octubre');assert(!JSON.stringify(d).includes('987654'));});

 await test('missing canonical catalogue fails closed before source requests',async()=>{const c=ctx();delete c.clientes;let calls=0;c.datosModulo=async()=>{calls++;return null;};const root=h('main',{});root.connected=true;await renderAccounts263(root,c,'accounts');assert.equal(calls,0);assert.equal(prepararAccounts263(c).rows.length,0);});
 await test('current canonical missing/detailrevoked/inactive/duplicate denies initialrow',async()=>{for(const mutate of [c=>c.clientes=[],c=>c.clientes[0].detalle=false,c=>c.clientes[0].activo_confirmado=false,c=>c.clientes.push(clone(c.clientes[0]))]){const c=ctx();mutate(c);assert.equal(prepararAccounts263(c).rows.length,0);}});
 await test('same month pair labels reference no budget no finance',async()=>{const ref={...reference,mes_cuota:'2026-09'},d=prepararAccounts263(ctx(),{produccion:production,dinero_cliente:ref}),cell=d.rows[0].horasPauta;assert(cell.valor.includes('/ 20 h ref.'));assert(cell.valor.includes('sept'));assert.equal(cell.estado,'gris');assert(cell.detalle.includes('no objetivo ni presupuesto confirmado'));assert(!JSON.stringify(d).includes('987654'));});

 await test('revisa matches original reference boundaries only typed measured rows',async()=>{for(const [n,state] of [[0,'gris'],[1,'ambar'],[5,'ambar'],[6,'rojo'],[7,'rojo']]){const doc={fuentes:{flujo:{hora:'2026-10-04T10:00:00Z'}},proyectos:[{cliente_id:'ok',rev_account:n,rev_account_48:n,revisiones_account:{estado:'medido',fuente:'flujo',fecha:'2026-10-04T10:00:00Z'}}]},d=prepararAccounts263(ctx(),{produccion:doc});assert.equal(d.groups[0].celdas.revisa.valor,String(n));assert.equal(d.groups[0].celdas.revisa.estado,state);delete doc.proyectos[0].revisiones_account;const missing=prepararAccounts263(ctx(),{produccion:doc});assert.equal(missing.groups[0].celdas.revisa.valor,'—');assert.equal(missing.groups[0].celdas.revisa.estado,'gris');}});
 console.log(JSON.stringify({version:'400B.1',passed,defectos_reproducidos:bugs},null,2));if(bugs.length)process.exitCode=1;
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
