// Reference408 + matrices263 actuales; fixtures/DOM ESM aislados, sin HTTP/DB.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(__dirname+'/pruebas_operaciones_accounts_263.cjs','utf8').split('(async()=>{try{')[0];
const {dir}=new Function('require','__dirname',prefix+';return {dir};')(require,__dirname);
const clone=x=>JSON.parse(JSON.stringify(x)),walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[],text=n=>n&&typeof n==='object'?n.children.map(text).join(' '):String(n??'');
function ctx(){const ps=[{id:'ops',estado:'activo',puestos:['operaciones']},{id:'acc',estado:'activo',puestos:['account']}],cs=['ok','partial'].map(id=>({id,nombre:id,activo_confirmado:true,detalle:true,equipo:{account:[{persona_id:'acc',principal:true,confianza:'confirmada'}]}}));return {servidor:true,hoy:'2026-10-05',real:clone(ps[0]),persona:clone(ps[0]),datos:{personas:clone(ps),asignaciones:[]},clientes:clone(cs),clientesVisibles:clone(cs),carteraPorSilla:{account:new Set(['ok','partial'])},veModulo:()=>true,ver:()=>({ok:true}),nombre:x=>x,vigente:()=>true,api:async()=>null,datosModulo:async r=>r==='produccion/produccion'?production():null};}
function production(){return {fuentes:{flujo:{hora:'2026-10-05T10:00:00Z'}},proyectos:[{cliente_id:'ok',rev_account:7,rev_account_48:7,revisiones_account:{estado:'medido',fuente:'flujo',fecha:'2026-10-05T10:00:00Z'}}]};}
let groups=0;async function test(name,f){try{await f();groups++;}catch(e){throw Error(name+': '+e.message)}}
(async()=>{try{
 const R=await import('file://'+path.join(dir,'_referencia_score_408.mjs')),{h,N}=await import('file://'+path.join(dir,'componentes.mjs')),{prepararAccounts263,renderAccounts263}=await import('file://'+path.join(dir,'_operaciones_accounts_263.mjs'));
 N.prototype.setAttribute=function(k,v){this.attrs[k]=String(v);};Object.defineProperty(N.prototype,'className',{get(){return this.attrs.class||'';},set(v){this.attrs.class=v;}});
 const mount=async c=>{const root=h('main',{});root.connected=true;await renderAccounts263(root,c,'accounts');return root;};
 const score=root=>walk(root).find(n=>n.tag==='section'&&walk(n).some(x=>x.tag==='h2'&&text(x)==='KPIs por account'));
 await test('exact literal weights same original criterion order',async()=>{assert.deepEqual(R.CRITERIOS_SCORE_408.map(c=>c.peso),[15,20,10,20,10,10,5,10]);const source=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/build/build.py','utf8'),line=source.split('\n').find(s=>s.startsWith('CRIT = ')),tuples=[...line.matchAll(/\('([^']+)', (\d+)\)/g)].map(m=>[m[1].replace(/\s/g,''),+m[2]]);assert.deepEqual(R.CRITERIOS_SCORE_408.map(c=>[c.criterio.replace(/\s/g,''),c.peso]),tuples);});
 await test('metadata immutable bands disabled not calculator',async()=>{assert(Object.isFrozen(R.CRITERIOS_SCORE_408));assert(R.CRITERIOS_SCORE_408.every(Object.isFrozen));assert.deepEqual(R.BANDAS_SCORE_408,{verde_desde:80,ambar_desde:60,referencia:true,calculo_habilitado:false});assert.throws(()=>Object.assign(R.CRITERIOS_SCORE_408[0],{peso:100}));});
 await test('reference closed outside rows readable fullweightsbands no data',async()=>{const d=R.renderReferenciaScore408(h);assert.equal(d.tag,'details');assert.equal(d.attrs.open,undefined);assert(text(d).includes('verde desde 80'));assert(text(d).includes('amarillo de 60 a 79'));assert(text(d).includes('Informe mensual: 15'));assert(text(d).includes('no es porcentaje'));assert(text(d).includes('No se recalculan pesos'));});
 await test('headers onlyeight shortlabels fullcriteria title',async()=>{const hs=R.cabecerasScore408();assert.deepEqual(hs.map(x=>x.elemento),['Informe','Reunión','Correo','Respuesta','Revisión','Semáforo','Horas','Nuevos']);assert.deepEqual(hs.map(x=>x.attrs.title),R.CRITERIOS_SCORE_408.map(c=>c.criterio));});
 await test('live matrices preserve nN and Nota unknown no falsepercentage/colors',async()=>{const c=ctx(),before=prepararAccounts263(c,{produccion:production()}),root=await mount(c),s=score(root),tbody=walk(s).find(n=>n.tag==='tbody');assert(text(tbody).includes('1/2'));assert(!text(tbody).includes('%'));assert(!text(tbody).includes('registros'));assert(!text(tbody).includes('80'));assert(!text(tbody).includes('15'));const note=walk(s).find(n=>n.attrs['aria-label']==='Nota de cumplimiento: —');assert(note);assert.equal(note.children[0].attrs['data-estado'],'gris');assert.equal(before.groups[0].nota.valor,'—');assert.equal(before.groups[0].celdas.revisa.estado,'rojo');assert.equal(prepararAccounts263(c,{produccion:production()}).groups[0].celdas.revisa.estado,'rojo');assert.equal(walk(root).filter(n=>n.attrs['data-referencia-score']==='408').length,1);});
 await test('matrix header compact order and full existing details remain',async()=>{const root=await mount(ctx()),s=score(root),headers=walk(s).filter(n=>n.tag==='th');assert.deepEqual(headers.map(text),['Account','Nota',...R.CABECERAS_SCORE_408.map(x=>x==='Semáforo'?'Estado':x),'Emp. Mili']);assert.equal(headers[2].attrs.title,'Informe mensual');assert.equal(headers[7].attrs.title,'Semáforo al día');assert.equal(headers[7].attrs['aria-label'],'Semáforo al día');walk(s).find(n=>n.attrs['aria-label']==='Revisión <48h: 1/2').events.click();assert(text(root).includes('No se calcula porcentaje de cumplimiento'));});
 await test('own account scoped rows no otheraccount grants or extraAPI',async()=>{const c=ctx();c.real=clone(c.datos.personas[1]);c.persona=clone(c.real);c.carteraPorSilla.account=new Set(['ok']);c.ver=d=>({ok:d.cliente_id==='ok'});let calls=[];const api=c.api;c.api=async r=>{calls.push(r);return api(r);};const root=await mount(c);assert(!text(score(root)).includes('partial'));assert.equal(prepararAccounts263(c).rows.length,1);assert(!calls.some(r=>r.includes('score')||r.includes('peso')));});
 await test('legend toggle follows existing scope guard and detached callback inert',async()=>{const c=ctx(),root=await mount(c),fold=walk(root).find(n=>n.attrs['data-referencia-score']==='408');fold.open=true;fold.events.toggle();assert(text(root).includes('ok'));c.clientes[0].activo_confirmado=false;fold.events.toggle();assert(!text(root).includes('ok'));const after=text(root);fold.events.toggle();assert.equal(text(root),after);});
 console.log(groups+' grupos408 PASS · referencia literal fuera de filas, sin nota calculada.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e.message);process.exitCode=1});
