const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class E{constructor(id){this.id=id;this.children=[];this.dataset={};this.style={};this.isConnected=true;this.hidden=false;this.attrs={};}append(n){if(n.parent)n.parent.children=n.parent.children.filter(x=>x!==n);n.parent=this;this.children.push(n);}querySelector(s){return this.select?.[s]||null;}setAttribute(k,v){this.attrs[k]=v;}replaceChildren(...n){this.children=n;}get lastElementChild(){return this.children.at(-1);}}
let observers=[],tasks=[];class O{constructor(f){this.f=f;this.off=false;observers.push(this);}observe(n,opts){this.target=n;this.options=opts;}disconnect(){this.off=true;}}
let main;const box={document:{getElementById:id=>id==='main'?main:null},MutationObserver:O,queueMicrotask:f=>tasks.push(f),icono:()=>new E('icon')};vm.createContext(box);vm.runInContext(fs.readFileSync(__dirname+'/modulos/_plegar_consejo.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),box);
const advice=()=>{const c=new E('advice'),list=new E('list'),res=new E('res'),b=new E('button');c.select={'ol.ia-acciones':list,':scope > .ia-sub':res,'.ia-cab button[aria-controls]':b};return {c,list,res,b};};
let n=0;const check=(label,f)=>{f();n++;console.log('PASS '+label);};
const setup=()=>{observers=[];tasks=[];main=new E('main');const root=new E('ficha'),a=advice();main.append(a.c);main.append(root);main.querySelector=sel=>sel===':scope > [data-ia="consejo"]'?main.children.find(x=>x.id==='advice'):null;return {root,...a};};
check('Caller real sólo cambia ubicación del consejo general',()=>{const source=fs.readFileSync(__dirname+'/modulos/ficha.js','utf8');assert(source.includes('plegarConsejo(cont, { despues: true });'));assert(source.includes("panelCopiloto(ctx, c.id"));assert(source.includes("const med = bloqueMedicion(ctx, F, k)"));assert(source.indexOf('repintar();\n    plegarConsejo')>0);});
check('Montaje inicial y append asíncrono conservan consejo último y único',()=>{const {root,c,list,b}=setup();box.plegarConsejo(root,{despues:true});tasks.shift()();assert.equal(main.lastElementChild,c);assert.equal(list.hidden,true);assert.equal(b.attrs['aria-expanded'],'false');main.append(new E('async'));observers[0].f();assert.equal(main.lastElementChild,c);assert.equal(main.children.filter(x=>x===c).length,1);assert(main.children.includes(root));});
check('Consejo añadido después de iniciar observer se coloca al pie',()=>{const {root,c}=setup();main.children=main.children.filter(x=>x!==c);box.plegarConsejo(root,{despues:true});tasks.shift()();main.append(c);main.append(new E('late'));observers[0].f();assert.equal(main.lastElementChild,c);});
check('Callback no duplica ni vuelve a plegar una preferencia abierta',()=>{const {root,c,list}=setup();box.plegarConsejo(root,{despues:true});tasks.shift()();list.hidden=false;observers[0].f();assert.equal(list.hidden,false);assert.equal(main.children.filter(x=>x===c).length,1);});
check('Salida de ruta desconecta y no desplaza nueva vista',()=>{const {root}=setup();box.plegarConsejo(root,{despues:true});tasks.shift()();root.isConnected=false;const next=new E('newroute');main.append(next);observers[0].f();assert(observers[0].off);assert.equal(main.lastElementChild,next);});
check('Destructor explícito y main ausente son seguros',()=>{const {root}=setup();const dispose=box.plegarConsejo(root,{despues:true});dispose();assert(observers[0].off);main=null;assert.doesNotThrow(()=>box.plegarConsejo(root,{despues:true})());});
console.log(n+' grupos506 PASS · helper real/caller real, sin API ni POST');
