const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ro273-'));let n=0;const check=(t,f)=>{f();n++;console.log('PASS',t);};
fs.writeFileSync(path.join(tmp,'componentes.mjs'),`export class N{constructor(t,a={},xs=[]){this.tag=t;this.attrs=a;this.events=a.on||{};this.children=[];this.disabled=!!a.disabled;this.value=a.value||'';this.append(...xs);}get isConnected(){return this.connected===true||!!this.parent?.isConnected;}append(...xs){for(const x of xs.flat(Infinity)){if(x==null)continue;if(x instanceof N)x.parent=this;this.children.push(x);}}replaceChildren(...xs){for(const x of this.children)if(x instanceof N)x.parent=null;this.children=[];this.append(...xs);}set textContent(v){this.replaceChildren(v);}get textContent(){return this.children.map(x=>typeof x==='object'?x.textContent:String(x)).join(' ');}addEventListener(t,f){this.events[t]=f;}}export const h=(t,a,...xs)=>new N(t,a,xs);export const chipEstado=(e,v)=>h('span',{'data-estado':e},v);`);
fs.writeFileSync(path.join(tmp,'modulo.mjs'),fs.readFileSync(path.join(__dirname,'modulos/_operaciones_feedback_273.js'),'utf8').replace("'../componentes.js'","'./componentes.mjs'"));
const walk=n=>n&&typeof n==='object'?[n,...n.children.flatMap(walk)]:[];
(async()=>{try{const{h}=await import('file://'+path.join(tmp,'componentes.mjs'));const M=await import('file://'+path.join(tmp,'modulo.mjs'));
 const ctx=(api,extra={})=>({hoy:'2026-10-03',servidor:true,real:{id:'a',estado:'activo'},persona:{id:'a',estado:'activo'},clientesVisibles:[{id:'c',nombre:'Cliente fixture',activo_confirmado:true,detalle:true}],veModulo:()=>true,vigente:()=>true,api,...extra});
 const read=(extra={})=>({version:'273.1',cliente_id:'c',semana:'2026-09-28',revision:0,actual:null,historial:[],historial_truncado:false,capacidades:{puede_registrar:true,solo_lectura:false},...extra});
 const receipt=b=>({intencion_id:b.intencion_id,cliente_id:b.cliente_id,semana:b.semana,revision:b.revision+1,autor:'a',registrado_en:'2026-10-03T10:00:00Z',estado:b.estado,nota:b.nota,origen:'local',declarado:true,envio_realizado:false,respuesta_verificada:false});
 function cont(){const c=h('main',{});c.connected=true;return c;}
 const filas=[{cliente_id:'c',muestra:{valor:5,desde:'2026-09-03',hasta:'2026-10-02',dias:2}}];
 let calls=[];const c=cont();await M.renderFeedback273(c,ctx(async(p,o)=>{calls.push([p,o]);if(!o)return read();return {version:'273.1',cliente_id:'c',semana:'2026-09-28',intencion_id:o.cuerpo.intencion_id,resultado:'guardado',recibo:receipt(o.cuerpo)};}),filas);
 check('cuatro cabeceras extraídas del original',()=>{const s=fs.readFileSync('/Users/tomassala/Downloads/PANEL_OPERACIONES_2026-10-01/plantilla.html','utf8'),f=s.slice(s.indexOf('function vLeadsFb()'),s.indexOf('/* ===== Tickets sin asignar'));const hs=[...f.matchAll(/<th(?:\s[^>]*)?>([^<]*)<\/th>/g)].map(x=>x[1]);assert.deepEqual(M.COLUMNAS_FEEDBACK273,hs);assert.equal(walk(c).filter(x=>x.tag==='th').length,4);});
 const guardar=walk(c).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO'),estado=walk(c).find(x=>x.tag==='select'),nota=walk(c).find(x=>x.tag==='textarea');
 check('edición cerrada mantiene tabla compacta',()=>{const editor=walk(c).find(x=>x.tag==='details'&&x.children[0]?.textContent==='Editar registro');assert.ok(editor);assert.ok(!editor.attrs.open);assert.ok(walk(editor).some(x=>x.tag==='textarea'));const first=walk(c).find(x=>x.tag==='tbody').children[0].children[0];assert.ok(!walk(first).some(x=>x.tag==='select'));});
 check('sin registro no conseguido',()=>{assert.equal(estado.value,'sin_opinion');assert.ok(!guardar.disabled);assert.match(c.textContent,/Sin declaración/);});
 estado.value='pedida';nota.value='Opinión solicitada';await guardar.events.click();
 check('pedido local distinto conseguido y recibo guardado',()=>{assert.equal(calls[1][1].cuerpo.estado,'pedida');assert.match(c.textContent,/Guardado en RO/);assert.match(c.textContent,/no envío ni recepción automática/);});
 estado.value='conseguida';nota.value='El cliente declaró calidad adecuada';await guardar.events.click();
 check('segunda intención conserva revisión y UUID nuevo',()=>{assert.equal(calls[2][1].cuerpo.revision,1);assert.notEqual(calls[1][1].cuerpo.intencion_id,calls[2][1].cuerpo.intencion_id);assert.equal(calls[2][1].cuerpo.estado,'conseguida');});
 let ps=[];const retry=cont();await M.renderFeedback273(retry,ctx(async(p,o)=>{if(!o)return read();ps.push(o.cuerpo);if(ps.length===1)throw Error('Respuesta perdida');return {version:'273.1',cliente_id:'c',semana:'2026-09-28',intencion_id:o.cuerpo.intencion_id,resultado:'duplicado',recibo:receipt(o.cuerpo)};}),filas);
 const rb=walk(retry).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO');await rb.events.click();await rb.events.click();
 check('reintento lostresponse mismo payload UUID',()=>{assert.equal(ps.length,2);assert.deepEqual(ps[0],ps[1]);assert.match(retry.textContent,/Guardado en RO/);});
 const bad=cont();await M.renderFeedback273(bad,ctx(async()=>read({cliente_id:'extranjero'})),filas);
 check('GET ajeno no habilita ni muestra opinión',()=>{assert.ok(walk(bad).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO').disabled);assert.match(bad.textContent,/No se pudo leer/);});
 let writes=0;const vista=cont();await M.renderFeedback273(vista,ctx(async(p,o)=>{if(o)writes++;return read();},{persona:{id:'b',estado:'activo'}}),filas);const vb=walk(vista).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO');await vb.events.click();
 check('vercomo noPOST aunque caps equivocadas permitan',()=>{assert.ok(vb.disabled);assert.equal(writes,0);});
 const piloto=cont();await M.renderFeedback273(piloto,ctx(async()=>read(),{soloLectura:true}),filas);
 check('piloto no edición',()=>assert.ok(walk(piloto).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO').disabled));
 let foreignCalls=0;const no=cont();await M.renderFeedback273(no,ctx(async()=>{foreignCalls++;return read();},{clientesVisibles:[{id:'c',activo_confirmado:false,detalle:true}]}),filas);
 check('ACTinactivo sinlectura fuente',()=>assert.equal(foreignCalls,0));
 let viva=true,resolve;const prom=new Promise(r=>resolve=r),stale=cont();const running=M.renderFeedback273(stale,ctx(()=>prom,{vigente:()=>viva}),filas);viva=false;resolve(read());await running;
 check('stale no habilita guardado',()=>assert.ok(walk(stale).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO').disabled));
 let posts=0;const conflict=cont();await M.renderFeedback273(conflict,ctx(async(p,o)=>{if(!o)return read({revision:posts?1:0,actual:posts?receipt({...filas[0],semana:'2026-09-28',revision:0,estado:'pedida',nota:'Otro',intencion_id:crypto.randomUUID()}):null});posts++;const e=Error('CAS');e.status=409;throw e;}),filas);
 const cb=walk(conflict).find(x=>x.tag==='button'&&x.textContent==='Guardar en RO'),cn=walk(conflict).find(x=>x.tag==='textarea');cn.value='Conservar nota';await cb.events.click();
 check('409 bloquea reenvío hasta lectura',()=>{assert.ok(cb.disabled);assert.match(conflict.textContent,/Cambió el registro/);});await walk(conflict).find(x=>x.tag==='button'&&x.textContent==='Recargar versión').events.click();
 check('recargar conserva borrador y vuelvehabilitar',()=>{assert.equal(cn.value,'Conservar nota');assert.equal(cb.disabled,false);});
 console.log(n+' grupos PASS · renderer real y respuestas sintéticas, no servidor ni negocio');
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
