// Auditoría394B de la tabla inferior real, sin requests reales ni datos privados.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const B={Intl,Number,Date,Map,Set,JSON,Object,Array,String,encodeURIComponent};vm.createContext(B);
function load(name){const s=fs.readFileSync(__dirname+'/modulos/'+name+'.js','utf8'),exports=[...s.matchAll(/export (?:async )?function (\w+)/g)].map(x=>x[1]);vm.runInContext('Object.assign(globalThis,(()=>{'+s.replace(/^import .*;$/gm,'').replace(/export /g,'')+';return {'+exports.join(',')+(name==='_control_artifact_250'?',COLUMNAS_CONTROL_250':'')+'};})())',B);}
load('control_cartera');load('_evidencias_resumen');load('_control_artifact_250');
class N{constructor(t,a={},...xs){this.tag=t;this.attrs=a;this.children=[];this.events=a.on||{};this.value=a.value||'';this.checked=false;this.isConnected=true;this.append(...xs);}append(...xs){for(const x of xs.flat(Infinity).filter(x=>x!=null)){this.children.push(x);if(x instanceof N)x.parent=this;}}replaceChildren(...xs){this.children=[];this.append(...xs);}addEventListener(e,f){this.events[e]=f;}setAttribute(k,v){this.attrs[k]=String(v);}set className(v){this.attrs.class=v;}focus(){}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.isConnected=false;}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ');}set textContent(x){this.replaceChildren(x);}}
const h=(t,a,...xs)=>new N(t,a,...xs),all=n=>[n,...n.children.filter(x=>x instanceof N).flatMap(all)],text=n=>n.textContent,visible=n=>n instanceof N?(n.tag==='details'?n.children.filter(x=>x instanceof N&&x.tag==='summary').map(visible).join(''):n.children.map(visible).join('')):String(n??'');
Object.assign(B,{h,chipEstado:(estado,v)=>h('span',{'data-estado':estado},v),vacioLinea:x=>h('p',{},x),hoyMadrid:()=> '2026-10-05',celdaImputa390:()=>({valor:'—',estado:'gris'}),imputaVigente390:()=>false});
const src=fs.readFileSync(__dirname+'/modulos/mi_dia.js','utf8');vm.runInContext(src.slice(src.indexOf('function semanaDeclaracionesControl'),src.indexOf('// ================================================================== el número que manda')),B);
function ctx(){const p={id:'ops',estado:'activo',activo:true,puestos:['operaciones']},c={id:'ok',nombre:'Cliente fixture',activo_confirmado:true,detalle:true,servicios:{seo:'sí'}};return {servidor:true,hoy:'2026-10-05',real:{...p,puestos:[...p.puestos]},persona:{...p,puestos:[...p.puestos]},datos:{personas:[{...p,puestos:[...p.puestos]}],asignaciones:[]},clientes:[{...c}],clientesVisibles:[{...c}],ver:()=>({ok:true}),veModulo:()=>true,vigente:()=>true,nombre:x=>x,verdad:id=>({cliente_id:id,gravedad:'atencion'}),api:async()=>null};}
function docs(month='2026-09'){const stamp='2026-10-02 05:00',p={cliente_id:'ok',horas_mes:7,horas_medicion:{estado:'medido',fuente:'horas',periodo:month,fecha:stamp},rev_account:3,rev_account_48:2,revisiones_account:{estado:'medido',fuente:'flujo',fecha:stamp}};return {'produccion/produccion':{hoy:month+'-01',fuentes:{horas:{hora:stamp},flujo:{hora:stamp},tareas:{hora:stamp}},cola:[],proyectos:[p]},'dinero_cliente/dinero_cliente':{generado:stamp,mes_cuota:'2026-10',clientes:[{cliente_id:'ok',cuota:987654,cuota_horas:{pautadas:20}}]},'bandeja/por_cliente':{generado:stamp,fuentes:{desk:{hora:stamp,estado:'bien'}},clientes:[{cliente_id:'ok',sin_contestar:4,mas_48:1,entre_24_48:2}]},'metodo/sugerencias':{hoy:'2026-10-05',sugerencias:[{cliente_id:'ok',regla_id:'seguimiento_quincenal_especialista',cadencia_dias:15,responsable_role:'trafficker',estado:'pendiente_confirmacion'}]}};}
const render=(c,d)=>B.panelControlCartera(c,{opcional:k=>d[k]||null},'operaciones',()=>true);
const bottom=root=>all(root).filter(n=>n.tag==='table').at(-1),heads=t=>all(t).filter(n=>n.tag==='th'&&n.attrs.scope==='col').map(text),rows=t=>all(t).find(n=>n.tag==='tbody').children;
let n=0;const test=(name,f)=>{try{f();n++;}catch(e){throw Error(name+': '+e.message)}};
// Ejecutar después de RELEASE394; no modifica source.
test('ten compact columns Services last',()=>{const r=render(ctx(),docs()),t=bottom(r);assert.equal(heads(t).length,10);assert.equal(heads(t).at(-1),'Serv.');assert(visible(t).includes('SEO'));assert(!text(r).includes('987654'));});
test('incompatible periods no hours/target ratio',()=>{const r=render(ctx(),docs()),t=bottom(r),v=visible(t);assert(!/7\s*\/\s*20/.test(v));assert(!/35\s*%/.test(v));assert(text(r).includes('Referencia mensual')||text(r).includes('referencia'));});
test('no grant no reference and no viewas financial read',()=>{for(const change of [c=>c.ver=q=>({ok:q.tipo!=='horas_pautadas'}),c=>{c.persona={...c.persona,id:'vista'};c.datos.personas.push({...c.persona});}]){const c=ctx();change(c);const r=render(c,docs());assert(!text(r).includes('20 h'));assert(!/7\s*\/\s*20/.test(visible(bottom(r))));}});
test('15d cadence never meeting count',()=>{const r=render(ctx(),docs()),t=bottom(r),hs=heads(t),i=hs.findIndex(x=>/^Reu\./.test(x)),row=rows(t)[0];assert(i>=0);assert(!visible(row.children[i]).includes('15'));assert(text(r).includes('15'));});
test('same month reference pair stays gray and explicitly economic',()=>{const r=render(ctx(),docs('2026-10')),t=bottom(r),hs=heads(t),i=hs.findIndex(x=>x==='h / ref.'),cell=rows(t)[0].children[i];assert(/7\s*\/\s*20/.test(visible(cell)));assert(!all(cell).some(x=>x.attrs['data-estado']==='verde'));assert(cell.attrs['aria-label'].includes('Pauta económica'));assert(text(r).includes('no presupuesto ni objetivo contractual confirmado'));});
test('measured totals and color grounded in48h not total',()=>{const r=render(ctx(),docs()),t=bottom(r),hs=heads(t),row=rows(t)[0],rv=row.children[hs.indexOf('Rev.')],tk=row.children[hs.indexOf('Tk.')];assert.equal(visible(rv),'3');assert.equal(visible(tk),'4');assert(rv.attrs['aria-label'].includes('2 >48h'));assert(tk.attrs['aria-label'].includes('1 >48h'));assert(all(rv).some(x=>x.attrs['data-estado']==='ambar'));assert(all(tk).some(x=>x.attrs['data-estado']==='rojo'));});
test('uncertified zero not measured or green',()=>{const d=docs();delete d['produccion/produccion'].proyectos[0].revisiones_account;d['produccion/produccion'].proyectos[0].rev_account=0;delete d['bandeja/por_cliente'].fuentes;const t=bottom(render(ctx(),d)),hs=heads(t),row=rows(t)[0];for(const key of ['Rev.','Tk.']){const cell=row.children[hs.indexOf(key)];assert.equal(visible(cell),'—');assert(!all(cell).some(x=>x.attrs['data-estado']==='verde'));}});
for(const [name,change]of [['actor',c=>c.datos.personas[0].estado='baja'],['ACT',c=>c.clientes[0].activo_confirmado=false],['duplicate',c=>c.clientes.push({...c.clientes[0]})],['grant',c=>c.ver=()=>({ok:false})]])test('detail/filter revocation '+name,()=>{const c=ctx(),r=render(c,docs('2026-10')),t=bottom(r),detail=all(t).find(x=>x.tag==='details');assert(text(detail).includes('20 h'));change(c);detail.events.toggle();assert(!text(detail).includes('20 h'));const search=all(r).find(x=>x.attrs['aria-label']==='Buscar cliente en la matriz');search.events.input();assert(!all(r).some(x=>x.tag==='table'&&heads(x).includes('Serv.')));});
(async()=>{
 for(const count of [0,2]){const c=ctx();c.api=async()=>({semana_inicio:'2026-10-05',cobertura:'parcial',verificacion_externa:false,cumplimiento:null,clientes:[{cliente_id:'ok',contactos_declarados:count,reuniones_declaradas:count,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null}]});const r=render(c,docs());await new Promise(resolve=>setImmediate(resolve));const t=bottom(r),hs=heads(t),row=rows(t)[0];for(const key of ['Cont./sem.','Reu./sem.']){const cell=row.children[hs.indexOf(key)];assert.equal(visible(cell),String(count));assert(all(cell).some(x=>x.attrs['data-estado']==='gris'));assert(cell.attrs['aria-label'].includes('declarad'));}assert(text(r).includes('Cero declaraciones no significa ausencia'));n++;}
 for(const change of [c=>c.datos.personas[0].estado='baja',c=>c.clientes[0].activo_confirmado=false,c=>c.ver=()=>({ok:false})]){const c=ctx();let done,start;const entered=new Promise(r=>start=r);c.api=async()=>{start();return new Promise(r=>done=r);};const r=render(c,docs());await entered;change(c);done({semana_inicio:'2026-10-05',cobertura:'parcial',verificacion_externa:false,cumplimiento:null,clientes:[{cliente_id:'ok',contactos_declarados:9,reuniones_declaradas:9,source_kind:'registro_equipo',verificacion_externa:false,cumplimiento:null}]});await new Promise(resolve=>setImmediate(resolve));assert(!all(r).some(x=>x.tag==='table'&&heads(x).includes('Serv.')));n++;}
 console.log(n+' grupos independientes394B PASS · modelo/tabla/declaraciones/roles/ACT/grants reales.');
})().catch(e=>{console.error(e.message);process.exitCode=1;});
