const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class N{constructor(tag,a={},kids=[]){this.tag=tag;this.attrs=a;this.on=a.on||{};this.children=[];this.isConnected=true;this.append(...kids)}append(...kids){this.children.push(...kids.flat(Infinity).filter(x=>x!=null))}replaceChildren(...kids){this.children=[];this.append(...kids)}get textContent(){return this.children.map(x=>x instanceof N?x.textContent:String(x)).join(' ')}set textContent(x){this.replaceChildren(x)}desc(){return this.children.filter(x=>x instanceof N).flatMap(x=>[x,...x.desc()])}}
const h=(t,a,...kids)=>new N(t,a,kids),source=fs.readFileSync(__dirname+'/modulos/_plan_fuego_255.js','utf8').replace(/^import .*;$/m,'').replace('export function','function');
const env={h,chipEstado:(color,text)=>h('span',{color},text),panel:(o,...kids)=>h('section',{},h('h2',{},o.titulo),...kids),crypto:{randomUUID:()=>`fixture-${++serial}`},Promise,JSON,encodeURIComponent};let serial=0;vm.createContext(env);vm.runInContext(source,env);
const dto=()=>({cliente_id:'c',version:0,plan:null,revision:null,historial:[],origen:'local',confirmado_proveedor:false,capacidades:{editar:true,revisar:false,responsables:[{id:'p'}]}});
const flush=()=>new Promise(r=>setImmediate(r));
const find=(root,f)=>root.desc().find(f),button=(root,text)=>find(root,x=>x.tag==='button'&&x.textContent===text);
function context(api,extra={}){let active=true;return {ctx:{nombre:id=>'Persona fixture',vigente:()=>active,soloLectura:false,api,...extra},stale:()=>active=false}}
(async()=>{
 let writes=[],fail=true;const a=context(async(r,o)=>{if(!o)return dto();writes.push(o.cuerpo);if(fail){fail=false;throw Error('Respuesta perdida')}return {...dto(),version:1,plan:{version:1,que:o.cuerpo.que,responsable_id:'p',plazo:'2026-10-09'},ok:true,recibo:{accion_id:o.cuerpo.accion_id}}});
 const root=env.panelPlanFuego255(a.ctx,'c');await flush();assert(root.textContent.includes('Sin plan registrado'));assert(root.textContent.includes('no acredita ejecución'));
 find(root,x=>x.attrs['aria-label']==='Qué se hará').value='Acción verificable';find(root,x=>x.attrs['aria-label']==='Responsable del plan').value='p';find(root,x=>x.attrs['aria-label']==='Plazo del plan').value='2026-10-09';
 await button(root,'Guardar plan en RO').on.click();assert(root.textContent.includes('Respuesta perdida'));assert.equal(writes.length,1);
 await button(root,'Guardar plan en RO').on.click();assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);assert(root.textContent.includes('Pendiente de revisión'));assert(!root.textContent.includes('Visto · versión'));
 const readonly=context(async()=>dto(),{soloLectura:true});const r=env.panelPlanFuego255(readonly.ctx,'c');await flush();assert(!button(r,'Guardar plan en RO'));
 const cap=context(async()=>({...dto(),capacidades:{editar:false,revisar:false,responsables:[]}}));const c=env.panelPlanFuego255(cap.ctx,'c');await flush();assert(!button(c,'Guardar plan en RO'));
 let resolve;const stale=context(()=>new Promise(r=>resolve=r));const s=env.panelPlanFuego255(stale.ctx,'c');await flush();stale.stale();resolve(dto());await flush();assert.equal(s.textContent,'Leyendo el plan local…');
 let touched=0;const before=context(async(r,o)=>{if(o)touched++;return dto()});const b=env.panelPlanFuego255(before.ctx,'c');await flush();before.stale();await button(b,'Guardar plan en RO').on.click();assert.equal(touched,0);
 const detached=context(()=>new Promise(r=>resolve=r));const d=env.panelPlanFuego255(detached.ctx,'c');await flush();d.isConnected=false;resolve(dto());await flush();assert.equal(d.textContent,'Leyendo el plan local…');
 const review=context(async()=>({...dto(),version:2,plan:{version:1,que:'Acción',responsable_id:'p',plazo:'2026-10-09'},revision:{estado:'visto',plan_version:1},capacidades:{editar:false,revisar:true,responsables:[]}}));const v=env.panelPlanFuego255(review.ctx,'c');await flush();assert(v.textContent.includes('Visto · versión 1'));assert(button(v,'Dar visto a esta versión'));assert(button(v,'Pedir cambios'));assert(!button(v,'Guardar plan en RO'));
 let postedResolve;const pending=context((r,o)=>o?new Promise(res=>postedResolve=res):Promise.resolve(dto()));const p=env.panelPlanFuego255(pending.ctx,'c');await flush();const save=button(p,'Guardar plan en RO');const saving=save.on.click();assert.equal(save.disabled,true);pending.stale();postedResolve({...dto(),ok:true,recibo:{accion_id:'fixture'}});await saving;assert(!p.textContent.includes('Visto · versión'));
 const foreign=context(async()=>({...dto(),cliente_id:'foreign',plan:{que:'No exponer respuesta incompatible'}}));const f=env.panelPlanFuego255(foreign.ctx,'c');await flush();assert(f.textContent.includes('respuesta incompatible'));assert(!f.textContent.includes('No exponer respuesta incompatible'));
 let reads=0;const conflict=context(async(r,o)=>{if(o){const e=Error('Conflicto de versión');e.status=409;throw e;}return {...dto(),version:++reads}});const co=env.panelPlanFuego255(conflict.ctx,'c');await flush();find(co,x=>x.attrs['aria-label']==='Qué se hará').value='Mi borrador conservado';await button(co,'Guardar plan en RO').on.click();const reload=button(co,'Leer versión actual sin perder mi borrador');assert.equal(reload.hidden,false);await reload.on.click();assert.equal(find(co,x=>x.attrs['aria-label']==='Qué se hará').value,'Mi borrador conservado');assert.equal(reads,2);
 const rojo=fs.readFileSync(__dirname+'/modulos/en_rojo.js','utf8');const cache={Map};vm.createContext(cache);vm.runInContext(rojo.slice(rojo.indexOf('let ATAJOS = null'),rojo.indexOf('/** «Abrir en X'))+'\nglobalThis.cacheKey=()=>ATAJOS_DE;',cache);
 let fetches=0;const actor=id=>({real:{id},persona:{id:'vista'},soloLectura:true,vigente:()=>true,datosModulo:async()=>{fetches++;return {filas:[{cliente_id:'c',fixture_actor:id}]}}});
 const m1=await cache.cargarAtajos(actor('uno')),m2=await cache.cargarAtajos(actor('dos'));assert.equal(fetches,2);assert.equal(m1.get('c').fixture_actor,'uno');assert.equal(m2.get('c').fixture_actor,'dos');
 let resolveOld;const old={...actor('viejo'),vigente:()=>false,datosModulo:()=>new Promise(r=>resolveOld=r)};const lost=cache.cargarAtajos(old);await cache.cargarAtajos(actor('nuevo'));resolveOld({filas:[]});await lost;assert.equal(cache.cacheKey(),'nuevo|vista|lectura');
 console.log('13 grupos255 UI PASS: render real, capacidades/read-only, reintento UUID, revisión versionada, guards GET/POST/respuesta, DTO ajeno rechazado, conflicto conserva borrador y caché real/vista/stale.');
})().catch(e=>{console.error(e);process.exitCode=1});
