// Las rutas que YA atiende Nest. Todo lo demás pasa tal cual a la app de hoy (servir.py) por el proxy de legado.
// Regla de la noche: una ruta entra en esta lista SOLO cuando su controlador está hecho y `contrato.py comparar`
// da 0 diferencias para ella (y, si es POST, `contrato_escritura.py` también). Así la app está completa a cada momento.
export type Metodo = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/** F5.3: ficheros de datos_de_modulo que atiende Nest (el resto sigue por el proxy). */
export const MODULOS_EN_NEST: readonly string[] = [
  'ajustes/conexiones',
  'agus/agus',
  'agus/licencias_coste',
  'alertas/alertas',
  'bandeja/bandeja',
  'bandeja/hilos',
  'bandeja/por_cliente',
  'captacion/captacion',
  'conexiones/salud',
  'contexto/contexto_clientes',
  'crm/crm',
  'decisiones/direccion',
  'decisiones/firmadas',
  'decisiones/reloj',
  'dinero_cliente/cohortes',
  'dinero_cliente/dinero_cliente',
  'dinero_cliente/rentabilidad',
  'en_rojo/atajos',
  'equipo/salida_accesos',
  'ficha/basica',
  'ficha/correos',
  'ficha/informes',
  'ficha/portal',
  'ficha/web',
  'finanzas/cuadre',
  'finanzas/cuadre_facturacion',
  'finanzas/direccion',
  'finanzas/finanzas',
  'finanzas/impagos',
  'finanzas/impagos_clientes',
  'fuentes/hallazgos_medicion',
  'gbp/gbp',
  'horas/horas',
  'hostinger/cuenta',
  'hostinger/hostinger',
  'incidencias/incidencias',
  'informe/comun',
  'informe/p_2026-06',
  'informe/p_2026-07',
  'informe/p_2026-08',
  'informe/p_2026-09',
  'informe/p_trim',
  'informe/p_u30',
  'informe/paridad',
  'informes/informes',
  'mi_dia/cambios',
  'mi_dia/config',
  'mi_dia/ronda_mili',
  'mi_trabajo/mi_trabajo',
  'modular/tablero',
  'modular/webs',
  'nuevos/nuevos',
  'objetivos/objetivos',
  'paneles/empresa/desk',
  'paneles/empresa/zadarma',
  'paneles/indice',
  'personas_m20/contratacion',
  'personas_m20/equipo',
  'primera_semana/guias',
  'produccion/marca',
  'redes/redes',
  'reuniones/reuniones',
  'riesgo/riesgo_baja',
  'seo/seo',
  'seo/webs',
  'telefonos/dudosos',
  'ventas_ro/meta',
  'ventas_ro_extra/anuncios',
  'verdad/bajas_tareas',
  'verdad/clientes',
  'verdad/equipo',
  'verdad/estado_clientes',
  'verdad/objetivos_clientes',
  'whatsapp/whatsapp',
];

const MODULOS_RE = MODULOS_EN_NEST.length
  ? new RegExp(`^/api/modulo/(${MODULOS_EN_NEST.map((r) => r.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})$`)
  : /^(?!)$/;

export const RUTAS_EN_NEST: ReadonlyArray<readonly [Metodo, RegExp]> = [
  ['GET', /^\/vivo$/],
  ['GET', /^\/api\/sesion$/],
  ['GET', /^\/api\/rastro\/verificar$/],
  ['POST', /^\/api\/rastro$/],
  ['GET', /^\/api\/rastro$/],
  ['GET', MODULOS_RE],
  ['GET', /^\/api\/cliente\/[\w-]+$/],
  ['GET', /^\/api\/indicadores$/],
  ['GET', /^\/api\/preferencias$/],
  ['POST', /^\/api\/preferencias$/],
  ['GET', /^\/logos\/[\w-]+\.(?:jpg|png|webp|gif)$/],
  ['GET', /^\/api\/respuestas_mili$/],
  ['GET', /^\/api\/decisiones$/],
  ['POST', /^\/api\/decisiones$/],
  ['GET', /^\/api\/opiniones$/],
  ['GET', /^\/api\/opiniones\/captura$/],
  ['POST', /^\/api\/opiniones\/estado$/],
  ['POST', /^\/api\/opinion$/],
];

export function atiendeNest(metodo: string, ruta: string): boolean {
  return RUTAS_EN_NEST.some(([m, patron]) => m === metodo && patron.test(ruta));
}
