import {h} from '../componentes.js';
import {ambitoPlanning360} from './_planning_observado_360.js';
const PIN='23ace1eb937926c13c18a05c6ac0e42e4b2a7b40585de0be606f19efa474696d';
const id=x=>typeof x==='string'&&/^[A-Za-z0-9_-]{1,150}$/.test(x);
function instante(x){if(typeof x!=='string')return null;const m=/^(\d{4}-\d{2}-\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(Z|[+-](\d{2}):(\d{2}))$/.exec(x);if(!m||+m[2]>23||+m[3]>59||+m[4]>59||(m[5]!=='Z'&&(+m[6]>14||+m[7]>59||(+m[6]===14&&+m[7]!==0))))return null;const n=Date.parse(x);return Number.isFinite(n)&&new Date(m[1]+'T00:00Z').toISOString().slice(0,10)===m[1]?n:null;}
const fecha=x=>new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(x));
export function ambitoEjemplos438(ctx){try{const base=ambitoPlanning360(ctx);if(!base||!ctx.veModulo?.('horas'))return null;const ps=base.personas.filter(p=>Array.isArray(p.puestos)&&p.puestos.length>0&&p.puestos.every(id)&&new Set(p.puestos).size===p.puestos.length&&ctx.ver({tipo:'horas_persona',persona_id:p.id})?.ok===true),pids=ps.map(p=>p.id).sort();if(!pids.length||!base.ids.length)return null;return {...base,ps,pids,firma:JSON.stringify([base.firma,pids])};}catch{return null;}}
export function modeloEjemplos438(ctx,d,antes){try{const now=ambitoEjemplos438(ctx),gen=instante(d?.generado),cut=instante(d?.corte_preparacion_utc);if(!now||now.firma!==antes?.firma||d?.version!=='438.1'||d.estado!=='copia_observada'||d.sha256_candidato!==PIN||d.fuente!=='clickup_cache_local'||d.cobertura!=='parcial'||d.atribucion!=='creador_ID_exacto'||d.creacion_no_es_planificacion!==true||d.cumplimiento!==null||gen===null||cut===null||cut>gen||new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(gen))>ctx.hoy||!Array.isArray(d.filas))return null;
 for(const [xs,allowed] of [[d.cliente_ids,now.ids],[d.persona_ids,now.pids]])if(!Array.isArray(xs)||!xs.every(id)||new Set(xs).size!==xs.length||!xs.every(x=>allowed.includes(x)))return null;
 const seen=new Set(),rows=[];
 for(const r of d.filas){const created=instante(r?.creada_utc),read=instante(r?.estado_leido_utc);if(!r||!['tarea_id','cliente_id','lista_id','persona_id'].every(k=>id(r[k]))||seen.has(r.tarea_id)||!d.cliente_ids.includes(r.cliente_id)||!d.persona_ids.includes(r.persona_id)||created===null||read===null||created>read||read>cut||!['backlog','planning mensual','planning semanal','diario','en curso'].includes(r.estado_observado)||!['open','custom','unstarted'].includes(r.tipo_estado)||typeof r.titulo_saneado!=='string'||r.titulo_saneado.length>240||/[<>]|https?:\/\/|(?:password|pwd|pass|clave|token)\s*[:=]/i.test(r.titulo_saneado)||Object.keys(r).some(k=>!['tarea_id','cliente_id','lista_id','persona_id','creada_utc','estado_observado','tipo_estado','estado_leido_utc','titulo_saneado'].includes(k)))return null;seen.add(r.tarea_id);rows.push({...r});}
 return {filas:rows,firma:now.firma,corte:d.corte_preparacion_utc};}catch{return null;}}
export async function panelEjemplosCreador438(cont,ctx){
 const before=ambitoEjemplos438(ctx);if(!before)return;const root=h('section',{class:'oe-panel','data-ejemplos-creador':'438'});cont.append(root);
 const vigente=()=>root.isConnected&&ctx.vigente?.()!==false&&ambitoEjemplos438(ctx)?.firma===before.firma;
 root.append(h('header',{},h('h2',{},'Ejemplos por creador')),h('p',{class:'oe-note'},'Lectura pendiente. Creación no equivale a entrada en planificación.'));
 let d;try{d=await ctx.api('produccion/ejemplos-creador');}catch{if(vigente())root.replaceChildren(h('header',{},h('h2',{},'Ejemplos por creador')),h('p',{class:'oe-note'},'Fuente no habilitada o no disponible; no acredita ausencia de ejemplos.'));else root.replaceChildren();return;}
 if(!vigente()){root.replaceChildren();return;}const model=modeloEjemplos438(ctx,d,before);if(!model){root.replaceChildren(h('p',{class:'oe-note'},'La copia no supera la validación de ámbito y fuente.'));return;}
 const body=h('div',{});root.replaceChildren(h('header',{},h('h2',{},'Ejemplos por creador')),h('p',{class:'oe-note'},'Copia parcial · fecha de creación, no quién planificó ni entrada a planning. No mide rendimiento ni cumplimiento.'),body);
 const groups=new Map();for(const r of model.filas){if(!groups.has(r.persona_id))groups.set(r.persona_id,[]);groups.get(r.persona_id).push(r);}
 if(!groups.size)body.append(h('p',{class:'oe-note'},'Sin ejemplos autorizados en esta copia parcial; no equivale a cero tareas.'));
 for(const [pid,rows] of groups){let page=0;const holder=h('div',{}),persona=before.ps.find(p=>p.id===pid),fold=h('details',{on:{toggle:()=>{if(!vigente()){root.replaceChildren();return;}if(fold.open)paint();}}},h('summary',{style:{minHeight:'44px',padding:'12px 18px',boxSizing:'border-box',cursor:'pointer'}},persona?.alias||persona?.nombre||pid,` · ${rows.length} ${rows.length===1?'ejemplo':'ejemplos'}`),holder);
 const paint=()=>{if(!vigente()){root.replaceChildren();return;}const sorted=[...rows].sort((a,b)=>instante(b.creada_utc)-instante(a.creada_utc)||a.tarea_id.localeCompare(b.tarea_id));holder.replaceChildren(h('div',{class:'oe-scroll'},h('table',{class:'densa'},h('thead',{},h('tr',{},['Tarea','Cliente','Creada','Estado leído','Lectura'].map(x=>h('th',{scope:'col'},x)))),h('tbody',{},sorted.slice(page*5,page*5+5).map(r=>h('tr',{},h('td',{},h('a',{href:`https://app.clickup.com/t/${encodeURIComponent(r.tarea_id)}`,target:'_blank',rel:'noopener noreferrer',on:{click:e=>{if(!vigente()){e.preventDefault();root.replaceChildren();}}}},r.titulo_saneado||'Tarea identificada')),h('td',{},before.clientes.find(c=>c.id===r.cliente_id)?.nombre||r.cliente_id),h('td',{title:r.creada_utc},fecha(r.creada_utc)),h('td',{},r.estado_observado),h('td',{title:r.estado_leido_utc},fecha(r.estado_leido_utc))))))),h('div',{class:'oe-range'},h('button',{type:'button',disabled:page===0,on:{click:()=>{if(!vigente()){root.replaceChildren();return;}page--;paint();}}},'Anterior'),h('span',{},`${page+1}/${Math.ceil(rows.length/5)}`),h('button',{type:'button',disabled:(page+1)*5>=rows.length,on:{click:()=>{if(!vigente()){root.replaceChildren();return;}page++;paint();}}},'Siguiente')));};body.append(fold);}
}
